// SPDX-License-Identifier: Apache-2.0
package heteronpu.continuous
import chisel3._
import circt.stage.ChiselStage
import java.nio.file.{Files,Paths}
import gemmini.{HeteroBF16FmaPre,HeteroBF16FmaMul,HeteroBF16FmaPost,HeteroBF16FmaRound}

/** Emit unchanged arithmetic leaf names jointly with the new Chisel integration.
  * No generated SV is postprocessed. The retained external RTL is linked by the
  * runner from a source manifest, never injected as simulation-only arithmetic.
  */
class ProductionBlockCollection(s:QwenBlockShape) extends Module {
  val block=Module(new Qwen2IdmaBlockTop(s));val port=IO(chiselTypeOf(block.io));port<>block.io;dontTouch(port)
  val pre=Module(new HeteroBF16FmaPre);val a=IO(chiselTypeOf(pre.io));a<>pre.io;dontTouch(a)
  val mul=Module(new HeteroBF16FmaMul);val b=IO(chiselTypeOf(mul.io));b<>mul.io;dontTouch(b)
  val post=Module(new HeteroBF16FmaPost);val c=IO(chiselTypeOf(post.io));c<>post.io;dontTouch(c)
  val round=Module(new HeteroBF16FmaRound);val d=IO(chiselTypeOf(round.io));d<>round.io;dontTouch(d)
}
object EmitProductionGate extends App {
  require(args.length==2 && Set("transport","tiny","real").contains(args(1)),"OUT transport|tiny|real")
  val out=Paths.get(args(0));require(!Files.exists(out),"preserve previous outputs");Files.createDirectories(out)
  val opts=Array("--preserve-values=all","-disable-all-randomization")
  if(args(1)=="transport"){
    Files.writeString(out.resolve("RetainedIdmaMemoryAdapter.sv"),ChiselStage.emitSystemVerilog(new RetainedIdmaMemoryAdapter,firtoolOpts=opts))
  }else{
    val s=(if(args(1)=="tiny")QwenBlockShape(hidden=64,ffn=128,heads=2,kvHeads=1,headDim=32)else QwenBlockShape()).copy(retainedMatrix=true)
    Files.writeString(out.resolve("Qwen2IdmaBlockTop.sv"),ChiselStage.emitSystemVerilog(new ProductionBlockCollection(s),firtoolOpts=opts))
    val l=new QwenBlockLayout(s)
    val h=new StringBuilder("// Generated by Chisel; do not edit.\n#pragma once\n#include <cstdint>\n")
    for((n,v)<-Seq("H"->s.hidden,"F"->s.ffn,"HEADS"->s.heads,"KVHEADS"->s.kvHeads,"HD"->s.headDim,"MAX_TOKENS"->s.maxTokens))h.append(s"static constexpr int $n=$v;\n")
    h.append(s"static constexpr int PHYSICAL_MAC_LANES=512;\nstatic constexpr uint64_t ARENA_BYTES=${l.total}ULL, WRITABLE_START=${l.writableStart}ULL;\n")
    for(r<-l.regions)h.append(s"static constexpr uint64_t OFF_${r.name.toUpperCase}=${r.offset}ULL;\n")
    Files.writeString(out.resolve("block_layout.h"),h.toString)
    Files.writeString(out.resolve("production_scope.json"),s"""{"hidden":${s.hidden},"ffn":${s.ffn},"max_tokens":${s.maxTokens},"physical_lanes":512,"dense_rows":16,"dense_columns":32,"transport":"pinned_idma_mailbox","host_command128_frontend":false,"original_graph_descriptor_fetch":false,"timing_signed_off":false}\n""")
  }
}
