// SPDX-License-Identifier: Apache-2.0
package heteronpu.continuous
import chisel3._
import chisel3.util._
import _root_.circt.stage.ChiselStage
import java.nio.file.{Files,Paths}
import gemmini.{HeteroBF16FmaPre,HeteroBF16FmaMul,HeteroBF16FmaPost,HeteroBF16FmaRound}

/** Only Host tables launch this root. No legacy block launch, phase permit,
  * payload injection, or second iDMA exists. Metadata and owner traffic share
  * the same arbiter, mailbox adapter, original upstream backend and AXI port.
  */
class HostBlockTop(s:QwenBlockShape) extends Module {
  require(s.retainedMatrix)
  val io=IO(new Bundle {
    val launch=Flipped(Decoupled(new HostCommandLaunch));val result=Decoupled(new HostCommandResult)
    val completion=Decoupled(UInt(56.W));val axi=new BlockAxiMaster
    val resetRequired=Output(Bool());val idmaTransfers=Output(UInt(64.W))
    val pc=Output(UInt(16.W));val issuedJobs=Output(UInt(16.W))
    val usefulMacs=Output(UInt(64.W));val executedMacs=Output(UInt(64.W));val writeBytes=Output(UInt(64.W))
    val memoryAccepted=Output(Vec(2,UInt(64.W)));val memoryReturned=Output(Vec(2,UInt(64.W)))
  })
  dontTouch(io)
  val cmd=Module(new HostBlockCommands(s));val owner=Module(new QwenOwnerKernel(s))
  val hub=Module(new SharedMemoryArbiter(2));val dma=Module(new RetainedIdmaMemoryAdapter)
  cmd.io.launch<>io.launch;io.result<>cmd.io.result;io.completion<>cmd.io.completion
  owner.io.job<>cmd.io.job;cmd.io.done<>owner.io.done
  hub.io.requests(0)<>cmd.io.memory;cmd.io.response<>hub.io.responses(0)
  hub.io.requests(1)<>owner.io.memory;owner.io.response<>hub.io.responses(1)
  dma.io.request<>hub.io.memory;hub.io.response<>dma.io.response;io.axi<>dma.io.axi
  io.resetRequired:=cmd.io.resetRequired||owner.io.resetRequired||hub.io.resetRequired||dma.io.resetRequired
  io.idmaTransfers:=dma.io.transfers;io.pc:=cmd.io.pc;io.issuedJobs:=cmd.io.issuedJobs
  io.usefulMacs:=cmd.io.usefulMacs;io.executedMacs:=cmd.io.executedMacs;io.writeBytes:=cmd.io.writeBytes
  io.memoryAccepted:=hub.io.accepted;io.memoryReturned:=hub.io.returned
}
class HostBlockCollection(s:QwenBlockShape) extends Module {
  val top=Module(new HostBlockTop(s));val port=IO(chiselTypeOf(top.io));port<>top.io;dontTouch(port)
  val pre=Module(new HeteroBF16FmaPre);val a=IO(chiselTypeOf(pre.io));a<>pre.io;dontTouch(a)
  val mul=Module(new HeteroBF16FmaMul);val b=IO(chiselTypeOf(mul.io));b<>mul.io;dontTouch(b)
  val post=Module(new HeteroBF16FmaPost);val c=IO(chiselTypeOf(post.io));c<>post.io;dontTouch(c)
  val round=Module(new HeteroBF16FmaRound);val d=IO(chiselTypeOf(round.io));d<>round.io;dontTouch(d)
}
object EmitHostBlock extends App {
  require((args.length==2||args.length==3) && Set("tiny","real").contains(args(1)),"OUT tiny|real [512|4096]")
  val matrixMacs=if(args.length==3)args(2).toInt else 4096
  require(Set(512,4096).contains(matrixMacs),"supported Matrix geometry")
  val out=Paths.get(args(0));require(!Files.exists(out),"preserve old outputs");Files.createDirectories(out)
  val s=(if(args(1)=="tiny")QwenBlockShape(hidden=64,ffn=128,heads=2,kvHeads=1,headDim=32)else QwenBlockShape()).copy(retainedMatrix=true,matrixColumns=matrixMacs/16)
  Files.writeString(out.resolve("HostBlockTop.sv"),ChiselStage.emitSystemVerilog(new HostBlockCollection(s),firtoolOpts=Array("--preserve-values=all","-disable-all-randomization")))
  Files.writeString(out.resolve("owner_shape.h"),s"""// Generated by Chisel. Do not edit.
#pragma once
#define OWNER_MATRIX_MACS ${matrixMacs}
static constexpr unsigned H=${s.hidden},F=${s.ffn},HEADS=${s.heads},KVHEADS=${s.kvHeads},HD=${s.headDim},MAX_TOKENS=${s.maxTokens};
""")
  Files.writeString(out.resolve("SCOPE.json"),s"""{"host_commands":true,"block_launch":false,"hidden":${s.hidden},"ffn":${s.ffn},"retained_matrix":true,"matrix_macs":${matrixMacs},"matrix_columns":${s.matrixColumns},"matrix_rows":16,"logical_matrix_engines":1,"physical_matrix_slices":${matrixMacs/512},"peak_requires_context_interleaving":true,"pinned_idma":true,"attention_fusion":"checked QK/SOFTMAX/PV; no DDR scores","official_weights":false,"timing_signoff":false}\n""")
}
