// SPDX-License-Identifier: Apache-2.0
// Canonical production L3 top: command/event/L2 fabric plus direct-stream complex.
`timescale 1ns/1ps
module hetero_l3_production_top #(
  parameter integer ADDR_W = 15,
  parameter integer DATA_W = 512,
  parameter bit WATCHDOG_ENABLE = 1'b1,
  parameter integer WATCHDOG_CYCLES = 4096
) (
  input logic clk_i,input logic rst_ni,
  input logic host_cmd_valid_i,output logic host_cmd_ready_o,input logic[127:0]host_cmd_data_i,
  output logic[5:0]engine_cmd_valid_o,input logic[5:0]engine_cmd_ready_i,
  output logic[6*128-1:0]engine_cmd_data_o,
  input logic[5:0]engine_completion_valid_i,output logic[5:0]engine_completion_ready_o,
  input logic[6*56-1:0]engine_completion_data_i,
  output logic init_done_o,output logic[4:0]command_level_o,completion_level_o,
  output logic[31:0]event_macro_error_count_o,output logic illegal_engine_o,
  output logic watchdog_lock_o,output logic[31:0]completion_grants_o,
  output logic[31:0]completion_protocol_error_count_o,

  input logic[3:0]l2_rd_valid_i,output logic[3:0]l2_rd_ready_o,
  input logic[4*ADDR_W-1:0]l2_rd_addr_i,output logic[3:0]l2_rd_rsp_valid_o,
  input logic[3:0]l2_rd_rsp_ready_i,output logic[4*DATA_W-1:0]l2_rd_rsp_data_o,
  output logic[3:0]l2_rd_rsp_error_o,input logic[1:0]l2_wr_valid_i,
  output logic[1:0]l2_wr_ready_o,input logic[2*ADDR_W-1:0]l2_wr_addr_i,
  input logic[2*DATA_W-1:0]l2_wr_data_i,input logic[2*(DATA_W/8)-1:0]l2_wr_be_i,
  output logic[1:0]phy_rd_valid_o,input logic[1:0]phy_rd_ready_i,
  output logic[2*ADDR_W-1:0]phy_rd_addr_o,input logic[1:0]phy_rsp_valid_i,
  output logic[1:0]phy_rsp_ready_o,input logic[2*DATA_W-1:0]phy_rsp_data_i,
  input logic[1:0]phy_rsp_error_i,output logic phy_wr_valid_o,input logic phy_wr_ready_i,
  output logic[ADDR_W-1:0]phy_wr_addr_o,output logic[DATA_W-1:0]phy_wr_data_o,
  output logic[DATA_W/8-1:0]phy_wr_be_o,output logic[31:0]descriptor_promotions_o,
  output logic[31:0]l2_read_grants_o,l2_write_grants_o,

  input logic matrix_cfg_valid_i,output logic matrix_cfg_ready_o,
  input logic matrix_cfg_direction_i,matrix_cfg_route_i,input logic[11:0]matrix_cfg_last_addr_i,
  input logic[15:0]matrix_cfg_tag_i,input logic[11:0]matrix_cfg_tensor_id_i,
  input logic[3:0]matrix_cfg_format_i,input logic[3:0]matrix_spad_write_valid_i,
  output logic[3:0]matrix_spad_write_ready_o,input logic[47:0]matrix_spad_write_addr_i,
  input logic[511:0]matrix_spad_write_data_i,input logic[63:0]matrix_spad_write_mask_i,
  input logic[3:0]matrix_spad_read_req_valid_i,output logic[3:0]matrix_spad_read_req_ready_o,
  input logic[47:0]matrix_spad_read_req_addr_i,output logic[3:0]matrix_spad_read_resp_valid_o,
  input logic[3:0]matrix_spad_read_resp_ready_i,output logic[511:0]matrix_spad_read_resp_data_o,
  output logic matrix_transfer_done_o,output logic[31:0]matrix_protocol_error_count_o,

  input logic aha_cfg_valid_i,output logic aha_cfg_ready_o,
  input logic[17:0]aha_cfg_input_base_i,aha_cfg_output_base_i,
  input logic[15:0]aha_cfg_input_beats_i,aha_cfg_output_beats_i,aha_cfg_output_tag_i,
  input logic[11:0]aha_cfg_output_tensor_id_i,input logic[3:0]aha_cfg_output_format_i,
  input logic[63:0]aha_cfg_output_last_be_i,input logic aha_run_done_i,
  output logic aha_proc_packet_wr_en_o,output logic[17:0]aha_proc_packet_wr_addr_o,
  output logic[63:0]aha_proc_packet_wr_data_o,output logic[7:0]aha_proc_packet_wr_strb_o,
  output logic aha_proc_packet_rd_en_o,output logic[17:0]aha_proc_packet_rd_addr_o,
  input logic[63:0]aha_proc_packet_rd_data_i,input logic aha_proc_packet_rd_data_valid_i,
  output logic aha_native_eos_o,aha_transfer_done_o,
  output logic[31:0]aha_protocol_error_count_o,

  input logic kv_cfg_valid_i,output logic kv_cfg_ready_o,input logic kv_cfg_direction_i,
  input logic[18:0]kv_cfg_base_addr_i,input logic[15:0]kv_cfg_beats_i,kv_cfg_tag_i,
  input logic[11:0]kv_cfg_tensor_id_i,input logic[3:0]kv_cfg_format_i,
  input logic[63:0]kv_cfg_last_be_i,output logic kv_mem_write_valid_o,
  input logic kv_mem_write_ready_i,output logic[18:0]kv_mem_write_addr_o,
  output logic[511:0]kv_mem_write_data_o,output logic[63:0]kv_mem_write_be_o,
  output logic kv_mem_read_req_valid_o,input logic kv_mem_read_req_ready_i,
  output logic[18:0]kv_mem_read_req_addr_o,input logic kv_mem_read_rsp_valid_i,
  output logic kv_mem_read_rsp_ready_o,input logic[511:0]kv_mem_read_rsp_data_i,
  input logic kv_mem_read_rsp_error_i,output logic kv_transfer_done_o,
  output logic[31:0]kv_protocol_error_count_o
);
  hetero_l3_command_fabric #(
    .ADDR_W(ADDR_W),.DATA_W(DATA_W),.WATCHDOG_ENABLE(WATCHDOG_ENABLE),
    .WATCHDOG_CYCLES(WATCHDOG_CYCLES)
  )u_command_fabric(
    .clk_i,.rst_ni,.host_cmd_valid_i,.host_cmd_ready_o,.host_cmd_data_i,
    .engine_cmd_valid_o,.engine_cmd_ready_i,.engine_cmd_data_o,
    .engine_completion_valid_i,.engine_completion_ready_o,.engine_completion_data_i,
    .init_done_o,.command_level_o,.completion_level_o,.event_macro_error_count_o,
    .illegal_engine_o,.watchdog_lock_o,.completion_grants_o,
    .completion_protocol_error_count_o,.l2_rd_valid_i,.l2_rd_ready_o,.l2_rd_addr_i,
    .l2_rd_rsp_valid_o,.l2_rd_rsp_ready_i,.l2_rd_rsp_data_o,.l2_rd_rsp_error_o,
    .l2_wr_valid_i,.l2_wr_ready_o,.l2_wr_addr_i,.l2_wr_data_i,.l2_wr_be_i,
    .phy_rd_valid_o,.phy_rd_ready_i,.phy_rd_addr_o,.phy_rsp_valid_i,
    .phy_rsp_ready_o,.phy_rsp_data_i,.phy_rsp_error_i,.phy_wr_valid_o,
    .phy_wr_ready_i,.phy_wr_addr_o,.phy_wr_data_o,.phy_wr_be_o,
    .descriptor_promotions_o,.l2_read_grants_o,.l2_write_grants_o);

  hetero_l3_stream_complex u_stream_complex(
    .clk_i,.rst_ni,.matrix_cfg_valid_i,.matrix_cfg_ready_o,.matrix_cfg_direction_i,
    .matrix_cfg_route_i,.matrix_cfg_last_addr_i,.matrix_cfg_tag_i,
    .matrix_cfg_tensor_id_i,.matrix_cfg_format_i,.matrix_spad_write_valid_i,
    .matrix_spad_write_ready_o,.matrix_spad_write_addr_i,.matrix_spad_write_data_i,
    .matrix_spad_write_mask_i,.matrix_spad_read_req_valid_i,
    .matrix_spad_read_req_ready_o,.matrix_spad_read_req_addr_i,
    .matrix_spad_read_resp_valid_o,.matrix_spad_read_resp_ready_i,
    .matrix_spad_read_resp_data_o,.matrix_transfer_done_o,
    .matrix_protocol_error_count_o,.aha_cfg_valid_i,.aha_cfg_ready_o,
    .aha_cfg_input_base_i,.aha_cfg_output_base_i,.aha_cfg_input_beats_i,
    .aha_cfg_output_beats_i,.aha_cfg_output_tag_i,.aha_cfg_output_tensor_id_i,
    .aha_cfg_output_format_i,.aha_cfg_output_last_be_i,.aha_run_done_i,
    .aha_proc_packet_wr_en_o,.aha_proc_packet_wr_addr_o,.aha_proc_packet_wr_data_o,
    .aha_proc_packet_wr_strb_o,.aha_proc_packet_rd_en_o,.aha_proc_packet_rd_addr_o,
    .aha_proc_packet_rd_data_i,.aha_proc_packet_rd_data_valid_i,.aha_native_eos_o,
    .aha_transfer_done_o,.aha_protocol_error_count_o,.kv_cfg_valid_i,.kv_cfg_ready_o,
    .kv_cfg_direction_i,.kv_cfg_base_addr_i,.kv_cfg_beats_i,.kv_cfg_tag_i,
    .kv_cfg_tensor_id_i,.kv_cfg_format_i,.kv_cfg_last_be_i,.kv_mem_write_valid_o,
    .kv_mem_write_ready_i,.kv_mem_write_addr_o,.kv_mem_write_data_o,.kv_mem_write_be_o,
    .kv_mem_read_req_valid_o,.kv_mem_read_req_ready_i,.kv_mem_read_req_addr_o,
    .kv_mem_read_rsp_valid_i,.kv_mem_read_rsp_ready_o,.kv_mem_read_rsp_data_i,
    .kv_mem_read_rsp_error_i,.kv_transfer_done_o,.kv_protocol_error_count_o);
endmodule
