// SPDX-License-Identifier: Apache-2.0
module operator_state_endpoint_v3(
 input logic clk_i,rst_ni,input logic req_valid_i,output logic req_ready_o,input logic[7:0]req_opcode_i,req_variant_i,
 input logic[15:0]req_tag_i,input logic[7:0]req_parent_phase_i,req_terminal_phase_i,
 input logic config_valid_i,output logic config_ready_o,input logic[63:0]state_address_i,window_base_i,state_stride_i,
 input logic[511:0]write_data_i,input logic[31:0]decay_i,input logic[127:0]conv_weights_i,
 output logic mem_req_valid_o,input logic mem_req_ready_i,output logic mem_req_write_o,output logic[63:0]mem_req_addr_o,
 output logic[511:0]mem_req_wdata_o,output logic[63:0]mem_req_wstrb_o,input logic mem_rsp_valid_i,output logic mem_rsp_ready_o,input logic[511:0]mem_rsp_rdata_i,input logic mem_rsp_error_i,
 output logic result_valid_o,input logic result_ready_i,output logic[511:0]result_data_o,output logic[4:0]exception_flags_o,
 output logic completion_valid_o,input logic completion_ready_i,output logic[15:0]completion_tag_o,
 output logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o,output logic[15:0]generation_o);
 localparam logic[7:0]READ=8'h60,WRITE=8'h61,DECAY=8'h62,CONV=8'h63,BEGIN_TX=8'h64,COMMIT_TX=8'h65,ROLLBACK_TX=8'h66;
 localparam logic[7:0]RANGE=5,PROTOCOL=7;
 localparam logic[4:0]IDLE=0,CONFIG=1,TX_BEGIN=2,TX_MARK=3,TX_COMMIT=4,TX_ROLLBACK=5,TX_EVENT=6,LOAD_CHECK=7,MEM_READ_REQ=8,MEM_READ_RSP=9,DEC_MUL_ISSUE=10,DEC_MUL_WAIT=11,CONV_MUL_ISSUE=12,CONV_MUL_WAIT=13,CONV_ADD_ISSUE=14,CONV_ADD_WAIT=15,JOURNAL=16,FLUSH_REQ=17,FLUSH_RSP=18,RESULT=19,COMPLETE=20;
 logic[4:0]st;logic[7:0]opcode_q,status_q,variant_q;logic[15:0]tag_q;logic[7:0]parent_q,terminal_q;
 logic[63:0]address_q,window_base_q,stride_q,journal_addr[0:15];logic[511:0]data_q,line_q,work_q,result_q,window_q[0:3],journal_data[0:15];logic[31:0]decay_q,weights_q[0:3],mul_q,acc_q;logic[4:0]journal_count_q,flush_q;logic[3:0]lane_q;logic[1:0]window_index_q,tap_q;logic[4:0]flags_q;
 logic journal_hit;logic[511:0]journal_hit_data;logic[63:0]read_address;
 always_comb begin read_address=(opcode_q==CONV)?window_base_q+window_index_q*stride_q:address_q;journal_hit=0;journal_hit_data=0;for(int k=0;k<16;k++)if(k<journal_count_q&&journal_addr[k]==read_address)begin journal_hit=1;journal_hit_data=journal_data[k];end end
 logic tx_ready,tx_valid,tx_event_valid,tx_event_ready,tx_active,tx_error;logic[1:0]tx_op,tx_event_op;logic[15:0]tx_event_id,tx_event_generation,tx_event_dirty,tx_active_id,tx_generation,tx_dirty;
 assign tx_valid=st inside{TX_BEGIN,TX_MARK,TX_COMMIT,TX_ROLLBACK};assign tx_op=st==TX_BEGIN?0:st==TX_MARK?1:st==TX_COMMIT?2:3;assign tx_event_ready=st==TX_EVENT;
 HeteroStateTransaction txn_ctrl(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_cmd_ready(tx_ready),.io_cmd_valid(tx_valid),.io_cmd_bits_op(tx_op),.io_cmd_bits_txnId(tag_q),.io_cmd_bits_domain(variant_q[3:0]),.io_event_ready(tx_event_ready),.io_event_valid(tx_event_valid),.io_event_bits_op(tx_event_op),.io_event_bits_txnId(tx_event_id),.io_event_bits_generation(tx_event_generation),.io_event_bits_dirtyMask(tx_event_dirty),.io_active(tx_active),.io_activeTxn(tx_active_id),.io_generation(tx_generation),.io_dirtyMask(tx_dirty),.io_protocolError(tx_error));
 logic miv,mir,mov,mor,mu,aiv,air,aov,aor,au;logic[31:0]mx,my,mo,ao;logic[4:0]mf,af;
 assign miv=st==DEC_MUL_ISSUE||st==CONV_MUL_ISSUE;assign mor=st==DEC_MUL_WAIT||st==CONV_MUL_WAIT;assign mx=opcode_q==DECAY?line_q[lane_q*32+:32]:window_q[tap_q][lane_q*32+:32];assign my=opcode_q==DECAY?decay_q:weights_q[tap_q];
 HeteroFP32MulPipeBit1 mul(.clock(clk_i),.reset(!rst_ni),.io_inValid(miv),.io_inReady(mir),.io_x(mx),.io_y(my),.io_userIn(1'b0),.io_outValid(mov),.io_outReady(mor),.io_out(mo),.io_exceptionFlags(mf),.io_userOut(mu));
 assign aiv=st==CONV_ADD_ISSUE;assign aor=st==CONV_ADD_WAIT;HeteroFP32AddPipeBit1 add(.clock(clk_i),.reset(!rst_ni),.io_inValid(aiv),.io_inReady(air),.io_x(acc_q),.io_y(mul_q),.io_userIn(1'b0),.io_outValid(aov),.io_outReady(aor),.io_out(ao),.io_exceptionFlags(af),.io_userOut(au));
 assign mem_req_valid_o=st==MEM_READ_REQ||st==FLUSH_REQ;assign mem_req_write_o=st==FLUSH_REQ;assign mem_req_addr_o=st==FLUSH_REQ?journal_addr[flush_q]:read_address;assign mem_req_wdata_o=journal_data[flush_q];assign mem_req_wstrb_o=64'hffffffffffffffff;assign mem_rsp_ready_o=st==MEM_READ_RSP||st==FLUSH_RSP;
 assign req_ready_o=st==IDLE;assign config_ready_o=st==CONFIG;assign result_valid_o=st==RESULT;assign result_data_o=result_q;assign exception_flags_o=flags_q;assign completion_valid_o=st==COMPLETE;assign completion_tag_o=tag_q;assign completion_parent_phase_o=parent_q;assign completion_terminal_phase_o=terminal_q;assign completion_status_o=status_q;assign generation_o=tx_generation;
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin st<=IDLE;opcode_q<=0;variant_q<=0;status_q<=0;tag_q<=0;parent_q<=0;terminal_q<=0;address_q<=0;window_base_q<=0;stride_q<=0;data_q<=0;line_q<=0;work_q<=0;result_q<=0;decay_q<=0;lane_q<=0;window_index_q<=0;tap_q<=0;mul_q<=0;acc_q<=0;flags_q<=0;journal_count_q<=0;flush_q<=0;for(int k=0;k<4;k++)begin window_q[k]<=0;weights_q[k]<=0;end for(int k=0;k<16;k++)begin journal_addr[k]<=0;journal_data[k]<=0;end end else case(st)
  IDLE:if(req_valid_i)begin opcode_q<=req_opcode_i;variant_q<=req_variant_i;tag_q<=req_tag_i;parent_q<=req_parent_phase_i;terminal_q<=req_terminal_phase_i;status_q<=0;flags_q<=0;if(req_opcode_i==BEGIN_TX)begin if(tx_active)begin status_q<=PROTOCOL;st<=COMPLETE;end else st<=TX_BEGIN;end else if(req_opcode_i==COMMIT_TX)begin if(!tx_active||tx_active_id!=req_tag_i)begin status_q<=PROTOCOL;st<=COMPLETE;end else if(journal_count_q==0)st<=TX_COMMIT;else begin flush_q<=0;st<=FLUSH_REQ;end end else if(req_opcode_i==ROLLBACK_TX)begin if(!tx_active||tx_active_id!=req_tag_i)begin status_q<=PROTOCOL;st<=COMPLETE;end else begin journal_count_q<=0;st<=TX_ROLLBACK;end end else if(req_opcode_i inside{READ,WRITE,DECAY,CONV})st<=CONFIG;else begin status_q<=4;st<=COMPLETE;end end
  CONFIG:if(config_valid_i)begin address_q<=state_address_i;window_base_q<=window_base_i;stride_q<=state_stride_i;data_q<=write_data_i;decay_q<=decay_i;for(int k=0;k<4;k++)weights_q[k]<=conv_weights_i[k*32+:32];window_index_q<=0;lane_q<=0;tap_q<=0;flags_q<=0;if((tx_active&&tx_active_id!=tag_q)||(opcode_q!=READ&&(!tx_active||tx_active_id!=tag_q))||(opcode_q==CONV&&state_stride_i==0))begin status_q<=PROTOCOL;st<=COMPLETE;end else if(opcode_q==READ)st<=LOAD_CHECK;else st<=TX_MARK;end
  TX_BEGIN:if(tx_ready)st<=TX_EVENT;
  TX_MARK:if(tx_ready)begin if(opcode_q==WRITE)st<=JOURNAL;else st<=LOAD_CHECK;end
  TX_COMMIT:if(tx_ready)st<=TX_EVENT;TX_ROLLBACK:if(tx_ready)st<=TX_EVENT;
  TX_EVENT:if(tx_event_valid)begin if(tx_event_id!=tag_q)status_q<=PROTOCOL;st<=COMPLETE;end
  LOAD_CHECK:if(journal_hit)begin line_q<=journal_hit_data;if(opcode_q==READ)begin result_q<=journal_hit_data;st<=RESULT;end else if(opcode_q==DECAY)begin lane_q<=0;st<=DEC_MUL_ISSUE;end else begin window_q[window_index_q]<=journal_hit_data;if(window_index_q==3)begin lane_q<=0;tap_q<=0;acc_q<=0;work_q<=0;st<=CONV_MUL_ISSUE;end else begin window_index_q<=window_index_q+1'b1;st<=LOAD_CHECK;end end end else st<=MEM_READ_REQ;
  MEM_READ_REQ:if(mem_req_ready_i)st<=MEM_READ_RSP;
  MEM_READ_RSP:if(mem_rsp_valid_i)begin if(mem_rsp_error_i)begin status_q<=PROTOCOL;st<=COMPLETE;end else begin line_q<=mem_rsp_rdata_i;if(opcode_q==READ)begin result_q<=mem_rsp_rdata_i;st<=RESULT;end else if(opcode_q==DECAY)begin lane_q<=0;st<=DEC_MUL_ISSUE;end else begin window_q[window_index_q]<=mem_rsp_rdata_i;if(window_index_q==3)begin lane_q<=0;tap_q<=0;acc_q<=0;work_q<=0;st<=CONV_MUL_ISSUE;end else begin window_index_q<=window_index_q+1'b1;st<=LOAD_CHECK;end end end end
  DEC_MUL_ISSUE:if(mir)st<=DEC_MUL_WAIT;DEC_MUL_WAIT:if(mov)begin work_q[lane_q*32+:32]<=mo;flags_q<=flags_q|mf;if(lane_q==15)st<=JOURNAL;else begin lane_q<=lane_q+1'b1;st<=DEC_MUL_ISSUE;end end
  CONV_MUL_ISSUE:if(mir)st<=CONV_MUL_WAIT;CONV_MUL_WAIT:if(mov)begin mul_q<=mo;flags_q<=flags_q|mf;st<=CONV_ADD_ISSUE;end
  CONV_ADD_ISSUE:if(air)st<=CONV_ADD_WAIT;CONV_ADD_WAIT:if(aov)begin flags_q<=flags_q|af;if(tap_q==3)begin work_q[lane_q*32+:32]<=ao;if(lane_q==15)st<=JOURNAL;else begin lane_q<=lane_q+1'b1;tap_q<=0;acc_q<=0;st<=CONV_MUL_ISSUE;end end else begin tap_q<=tap_q+1'b1;acc_q<=ao;st<=CONV_MUL_ISSUE;end end
  JOURNAL:begin if(journal_count_q==16)begin status_q<=RANGE;st<=COMPLETE;end else begin journal_addr[journal_count_q]<=address_q;journal_data[journal_count_q]<=opcode_q==WRITE?data_q:work_q;journal_count_q<=journal_count_q+1'b1;if(opcode_q==WRITE)st<=COMPLETE;else begin result_q<=work_q;st<=RESULT;end end end
  FLUSH_REQ:if(mem_req_ready_i)st<=FLUSH_RSP;FLUSH_RSP:if(mem_rsp_valid_i)begin if(mem_rsp_error_i)begin status_q<=PROTOCOL;st<=COMPLETE;end else if(flush_q+1>=journal_count_q)begin journal_count_q<=0;st<=TX_COMMIT;end else begin flush_q<=flush_q+1'b1;st<=FLUSH_REQ;end end
  RESULT:if(result_ready_i)st<=COMPLETE;COMPLETE:if(completion_ready_i)st<=IDLE;default:st<=IDLE;endcase end
endmodule
