// SPDX-License-Identifier: Apache-2.0
module operator_vision_endpoint_v3(
 input logic clk_i,rst_ni,input logic req_valid_i,output logic req_ready_o,input logic[7:0]req_opcode_i,
 input logic[15:0]req_tag_i,input logic[7:0]req_parent_phase_i,req_terminal_phase_i,
 input logic config_valid_i,output logic config_ready_o,input logic[31:0]cfg0_i,cfg1_i,cfg2_i,cfg3_i,cfg4_i,cfg5_i,cfg6_i,cfg7_i,cfg8_i,cfg9_i,
 input logic[191:0]cfg_multipliers_i,input logic[511:0]cfg_head_sizes_i,cfg_head_offsets_i,
 input logic ple_valid_i,output logic ple_ready_o,input logic[31:0]ple_token_i,ple_position_i,input logic ple_last_i,
 output logic map_valid_o,input logic map_ready_i,output logic[255:0]map_data_o,output logic map_last_o,
 output logic completion_valid_o,input logic completion_ready_i,output logic[15:0]completion_tag_o,
 output logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o);
 localparam logic[7:0]WINDOW=8'h80,PATCH_MERGE=8'h81,POS=8'h82,PLE=8'h83,PATCH3D=8'h84,MROPE=8'h85;
 localparam logic[2:0]IDLE=0,CONFIG=1,START=2,RUN=3,COMPLETE=4;logic[2:0]st;logic[7:0]opcode_q,status_q;logic[15:0]tag_q;logic[7:0]parent_q,terminal_q;logic[31:0]c[0:9];logic[191:0]multipliers_q;logic[511:0]sizes_q,offsets_q;integer i;
 logic mr_ready,mr_valid,mr_last,mr_busy,mr_done,mr_bad;logic[7:0]mr_pair,mr_axis_pair;logic[1:0]mr_axis;
 logic raw_ready,raw_valid,raw_last,map_q_valid,map_q_last;logic[255:0]raw_data,map_q_data;assign raw_ready=st==RUN&&(!map_q_valid||map_ready_i);
 HeteroMropeSectionMap mrope(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==START&&opcode_q==MROPE),.io_startReady(mr_ready),.io_pairCount(c[0][8:0]),.io_heightPairs(c[1][8:0]),.io_widthPairs(c[2][8:0]),.io_out_ready(raw_ready&&opcode_q==MROPE),.io_out_valid(mr_valid),.io_out_bits_pair(mr_pair),.io_out_bits_axis(mr_axis),.io_out_bits_axisPair(mr_axis_pair),.io_out_bits_last(mr_last),.io_busy(mr_busy),.io_done(mr_done),.io_invalidConfig(mr_bad));
 logic w_ready,w_valid,w_last,w_busy,w_done,w_bad,w_padding,w_first,w_lastwin;logic[11:0]w_t,w_y,w_x,w_wy,w_wx,w_iy,w_ix;logic[23:0]w_seq;
 HeteroVisionWindowAddressGenerator window(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==START&&opcode_q==WINDOW),.io_startReady(w_ready),.io_temporal(c[0][12:0]),.io_height(c[1][12:0]),.io_imageWidth(c[2][12:0]),.io_paddedHeight(c[3][12:0]),.io_paddedWidth(c[4][12:0]),.io_windowHeight(c[5][12:0]),.io_windowWidth(c[6][12:0]),.io_out_ready(raw_ready&&opcode_q==WINDOW),.io_out_valid(w_valid),.io_out_bits_temporal(w_t),.io_out_bits_y(w_y),.io_out_bits_x(w_x),.io_out_bits_windowY(w_wy),.io_out_bits_windowX(w_wx),.io_out_bits_inWindowY(w_iy),.io_out_bits_inWindowX(w_ix),.io_out_bits_sequence(w_seq),.io_out_bits_padding(w_padding),.io_out_bits_firstInWindow(w_first),.io_out_bits_lastInWindow(w_lastwin),.io_out_bits_last(w_last),.io_busy(w_busy),.io_done(w_done),.io_invalidConfig(w_bad));
 logic pm_ready,pm_valid,pm_last,pm_busy,pm_done,pm_bad,pm_source_valid,pm_first,pm_last_member;logic[11:0]pm_t,pm_y,pm_x;logic[5:0]pm_member;logic[23:0]pm_output;
 HeteroVisionPatchMergeAddressGenerator patch_merge(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==START&&opcode_q==PATCH_MERGE),.io_startReady(pm_ready),.io_temporal(c[0][12:0]),.io_height(c[1][12:0]),.io_imageWidth(c[2][12:0]),.io_mergeHeight(c[3][3:0]),.io_mergeWidth(c[4][3:0]),.io_out_ready(raw_ready&&opcode_q==PATCH_MERGE),.io_out_valid(pm_valid),.io_out_bits_temporal(pm_t),.io_out_bits_sourceY(pm_y),.io_out_bits_sourceX(pm_x),.io_out_bits_member(pm_member),.io_out_bits_outputPatch(pm_output),.io_out_bits_sourceValid(pm_source_valid),.io_out_bits_firstMember(pm_first),.io_out_bits_lastMember(pm_last_member),.io_out_bits_last(pm_last),.io_busy(pm_busy),.io_done(pm_done),.io_invalidConfig(pm_bad));
 logic pos_ready,pos_valid,pos_busy,pos_bad;logic[23:0]pos_y0,pos_y1,pos_x0,pos_x1;logic[15:0]pos_yf,pos_xf;
 HeteroVisionBilinearIndex position(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==START&&opcode_q==POS),.io_startReady(pos_ready),.io_destinationY(c[0][23:0]),.io_destinationX(c[1][23:0]),.io_sourceHeight(c[2][23:0]),.io_sourceWidth(c[3][23:0]),.io_destinationHeight(c[4][23:0]),.io_destinationWidth(c[5][23:0]),.io_out_ready(raw_ready&&opcode_q==POS),.io_out_valid(pos_valid),.io_out_bits_y0(pos_y0),.io_out_bits_y1(pos_y1),.io_out_bits_x0(pos_x0),.io_out_bits_x1(pos_x1),.io_out_bits_yFraction(pos_yf),.io_out_bits_xFraction(pos_xf),.io_busy(pos_busy),.io_invalidConfig(pos_bad));
 logic ple_in_ready,p_valid,p_last_head,p_last_token,p_bad,p_error;logic[31:0]p_row,p_pos;logic[3:0]p_head;
 HeteroPleNgramHash ple(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_ngramSize(c[0][1:0]),.io_headsPerNgram(c[1][4:0]),.io_headCount(c[2][4:0]),.io_sentinel(c[3]),.io_multipliers_0(multipliers_q[63:0]),.io_multipliers_1(multipliers_q[127:64]),.io_multipliers_2(multipliers_q[191:128]),
  .io_headSizes_0(sizes_q[31:0]),.io_headSizes_1(sizes_q[63:32]),.io_headSizes_2(sizes_q[95:64]),.io_headSizes_3(sizes_q[127:96]),.io_headSizes_4(sizes_q[159:128]),.io_headSizes_5(sizes_q[191:160]),.io_headSizes_6(sizes_q[223:192]),.io_headSizes_7(sizes_q[255:224]),.io_headSizes_8(sizes_q[287:256]),.io_headSizes_9(sizes_q[319:288]),.io_headSizes_10(sizes_q[351:320]),.io_headSizes_11(sizes_q[383:352]),.io_headSizes_12(sizes_q[415:384]),.io_headSizes_13(sizes_q[447:416]),.io_headSizes_14(sizes_q[479:448]),.io_headSizes_15(sizes_q[511:480]),
  .io_headOffsets_0(offsets_q[31:0]),.io_headOffsets_1(offsets_q[63:32]),.io_headOffsets_2(offsets_q[95:64]),.io_headOffsets_3(offsets_q[127:96]),.io_headOffsets_4(offsets_q[159:128]),.io_headOffsets_5(offsets_q[191:160]),.io_headOffsets_6(offsets_q[223:192]),.io_headOffsets_7(offsets_q[255:224]),.io_headOffsets_8(offsets_q[287:256]),.io_headOffsets_9(offsets_q[319:288]),.io_headOffsets_10(offsets_q[351:320]),.io_headOffsets_11(offsets_q[383:352]),.io_headOffsets_12(offsets_q[415:384]),.io_headOffsets_13(offsets_q[447:416]),.io_headOffsets_14(offsets_q[479:448]),.io_headOffsets_15(offsets_q[511:480]),
  .io_in_ready(ple_in_ready),.io_in_valid(ple_valid_i&&st==RUN&&opcode_q==PLE),.io_in_bits_token(ple_token_i),.io_in_bits_position(ple_position_i),.io_in_bits_last(ple_last_i),.io_out_ready(raw_ready&&opcode_q==PLE),.io_out_valid(p_valid),.io_out_bits_row(p_row),.io_out_bits_head(p_head),.io_out_bits_position(p_pos),.io_out_bits_lastHead(p_last_head),.io_out_bits_lastToken(p_last_token),.io_invalidConfig(p_bad),.io_protocolError(p_error));
 assign ple_ready_o=st==RUN&&opcode_q==PLE&&ple_in_ready;
 logic p3_ready,p3_valid,p3_last,p3_busy,p3_done,p3_bad,p3_first,p3_lasttap;logic[15:0]p3_ot,p3_oy,p3_ox,p3_it,p3_iy,p3_ix;logic[2:0]p3_ch;logic[3:0]p3_kt,p3_ky,p3_kx;logic[12:0]p3_cfg0,p3_cfg1,p3_cfg2;logic[3:0]p3_cfg3;logic[4:0]p3_cfg4,p3_cfg5,p3_cfg6,p3_cfg7,p3_cfg8,p3_cfg9;
 HeteroVisionPatch3dAddressGenerator patch3d(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==START&&opcode_q==PATCH3D),.io_startReady(p3_ready),.io_outputTemporal(p3_cfg0),.io_outputHeight(p3_cfg1),.io_outputWidth(p3_cfg2),.io_channels(p3_cfg3),.io_kernelTemporal(p3_cfg4),.io_kernelHeight(p3_cfg5),.io_kernelWidth(p3_cfg6),.io_strideTemporal(p3_cfg7),.io_strideHeight(p3_cfg8),.io_strideWidth(p3_cfg9),.io_out_ready(raw_ready&&opcode_q==PATCH3D),.io_out_valid(p3_valid),.io_out_bits_outputTemporal(p3_ot),.io_out_bits_outputY(p3_oy),.io_out_bits_outputX(p3_ox),.io_out_bits_inputTemporal(p3_it),.io_out_bits_inputY(p3_iy),.io_out_bits_inputX(p3_ix),.io_out_bits_channel(p3_ch),.io_out_bits_kernelTemporal(p3_kt),.io_out_bits_kernelY(p3_ky),.io_out_bits_kernelX(p3_kx),.io_out_bits_firstTap(p3_first),.io_out_bits_lastTap(p3_lasttap),.io_out_bits_last(p3_last),.io_busy(p3_busy),.io_done(p3_done),.io_invalidConfig(p3_bad));
 logic start_ready,start_bad;always_comb begin case(opcode_q)WINDOW:begin start_ready=w_ready;start_bad=w_bad;end PATCH_MERGE:begin start_ready=pm_ready;start_bad=pm_bad;end POS:begin start_ready=pos_ready;start_bad=pos_bad;end PATCH3D:begin start_ready=p3_ready;start_bad=p3_bad;end MROPE:begin start_ready=mr_ready;start_bad=mr_bad;end default:begin start_ready=1;start_bad=0;end endcase end
 always_comb begin raw_valid=0;raw_data=0;raw_last=0;case(opcode_q)
  MROPE:begin raw_valid=st==RUN&&mr_valid;raw_data[7:0]=mr_pair;raw_data[9:8]=mr_axis;raw_data[17:10]=mr_axis_pair;raw_last=mr_last;end
  WINDOW:begin raw_valid=st==RUN&&w_valid;raw_data={67'd0,w_lastwin,w_first,w_padding,w_seq,w_ix,w_iy,w_wx,w_wy,w_x,w_y,w_t};raw_last=w_last;end
  PATCH_MERGE:begin raw_valid=st==RUN&&pm_valid;raw_data={144'd0,pm_last_member,pm_first,pm_source_valid,pm_output,pm_member,pm_x,pm_y,pm_t};raw_last=pm_last;end
  POS:begin raw_valid=st==RUN&&pos_valid;raw_data={128'd0,pos_xf,pos_yf,pos_x1,pos_x0,pos_y1,pos_y0};raw_last=1;end
  PLE:begin raw_valid=st==RUN&&p_valid;raw_data={182'd0,p_last_token,p_last_head,p_pos,p_head,p_row};raw_last=p_last_head&&p_last_token;end
  PATCH3D:begin raw_valid=st==RUN&&p3_valid;raw_data={121'd0,p3_lasttap,p3_first,p3_kx,p3_ky,p3_kt,p3_ch,p3_ix,p3_iy,p3_it,p3_ox,p3_oy,p3_ot};raw_last=p3_last;end default:begin end endcase end
 assign map_valid_o=map_q_valid;assign map_data_o=map_q_data;assign map_last_o=map_q_last;
 assign req_ready_o=st==IDLE;assign config_ready_o=st==CONFIG;assign completion_valid_o=st==COMPLETE;assign completion_tag_o=tag_q;assign completion_parent_phase_o=parent_q;assign completion_terminal_phase_o=terminal_q;assign completion_status_o=status_q;
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin st<=IDLE;opcode_q<=0;status_q<=0;tag_q<=0;parent_q<=0;terminal_q<=0;multipliers_q<=0;sizes_q<=0;offsets_q<=0;map_q_valid<=0;map_q_data<=0;map_q_last<=0;p3_cfg0<=0;p3_cfg1<=0;p3_cfg2<=0;p3_cfg3<=0;p3_cfg4<=0;p3_cfg5<=0;p3_cfg6<=0;p3_cfg7<=0;p3_cfg8<=0;p3_cfg9<=0;for(i=0;i<10;i++)c[i]<=0;end else begin
  if(st==RUN)begin if(map_q_valid&&map_ready_i)begin if(map_q_last)begin map_q_valid<=0;if(opcode_q==PLE&&p_error)status_q<=7;st<=COMPLETE;end else map_q_valid<=0;end if(raw_valid&&raw_ready)begin map_q_valid<=1;map_q_data<=raw_data;map_q_last<=raw_last;end end
  case(st)
  IDLE:if(req_valid_i)begin opcode_q<=req_opcode_i;tag_q<=req_tag_i;parent_q<=req_parent_phase_i;terminal_q<=req_terminal_phase_i;status_q<=0;if(req_opcode_i inside{WINDOW,PATCH_MERGE,POS,PLE,PATCH3D,MROPE})st<=CONFIG;else begin status_q<=4;st<=COMPLETE;end end
  CONFIG:if(config_valid_i)begin c[0]<=cfg0_i;c[1]<=cfg1_i;c[2]<=cfg2_i;c[3]<=cfg3_i;c[4]<=cfg4_i;c[5]<=cfg5_i;c[6]<=cfg6_i;c[7]<=cfg7_i;c[8]<=cfg8_i;c[9]<=cfg9_i;p3_cfg0<=cfg0_i[12:0];p3_cfg1<=cfg1_i[12:0];p3_cfg2<=cfg2_i[12:0];p3_cfg3<=cfg3_i[3:0];p3_cfg4<=cfg4_i[4:0];p3_cfg5<=cfg5_i[4:0];p3_cfg6<=cfg6_i[4:0];p3_cfg7<=cfg7_i[4:0];p3_cfg8<=cfg8_i[4:0];p3_cfg9<=cfg9_i[4:0];multipliers_q<=cfg_multipliers_i;sizes_q<=cfg_head_sizes_i;offsets_q<=cfg_head_offsets_i;map_q_valid<=0;if(opcode_q==PLE)begin if(cfg0_i<2||cfg0_i>3||cfg1_i==0||cfg2_i==0)begin status_q<=5;st<=COMPLETE;end else st<=RUN;end else st<=START;end
  START:if(start_ready)begin if(start_bad)begin status_q<=5;st<=COMPLETE;end else st<=RUN;end
  RUN:begin end
  COMPLETE:if(completion_ready_i)st<=IDLE;default:st<=IDLE;endcase end end
endmodule
