// SPDX-License-Identifier: Apache-2.0
module operator_selection_endpoint_v3(
 input logic clk_i,rst_ni,input logic req_valid_i,output logic req_ready_o,input logic[7:0]req_opcode_i,
 input logic[15:0]req_tag_i,input logic[7:0]req_parent_phase_i,req_terminal_phase_i,
 input logic config_valid_i,output logic config_ready_o,input logic[19:0]topk_item_count_i,input logic[8:0]topk_k_i,
 input logic[63:0]expand_base_i,expand_stride_i,input logic[31:0]route_token_i,input logic[4:0]route_count_i,
 input logic[18:0]pool_blocks_i,input logic[4:0]pool_ratio_i,input logic[8:0]pool_dimensions_i,input logic[5:0]mtp_step_count_i,
 input logic score_valid_i,output logic score_ready_o,input logic[31:0]score_i,score_index_i,
 output logic ranked_valid_o,input logic ranked_ready_i,output logic[31:0]ranked_score_o,ranked_index_o,output logic[8:0]ranked_rank_o,output logic ranked_last_o,
 output logic topk_sram_req_valid_o,input logic topk_sram_req_ready_i,output logic topk_sram_req_write_o,output logic[8:0]topk_sram_req_addr_o,output logic[64:0]topk_sram_req_wdata_o,input logic topk_sram_rsp_valid_i,output logic topk_sram_rsp_ready_o,input logic[64:0]topk_sram_rsp_rdata_i,input logic topk_sram_rsp_error_i,
 input logic expand_valid_i,output logic expand_ready_o,input logic[31:0]expand_index_i,input logic[8:0]expand_rank_i,input logic expand_last_i,output logic expand_out_valid_o,input logic expand_out_ready_i,output logic[63:0]expand_address_o,output logic[8:0]expand_out_rank_o,output logic expand_out_last_o,
 input logic route_valid_i,output logic route_ready_o,input logic[9:0]route_expert_i,input logic[31:0]route_weight_i,input logic route_shared_i,output logic dispatch_valid_o,input logic dispatch_ready_i,output logic[31:0]dispatch_token_o,output logic[9:0]dispatch_expert_o,output logic[31:0]dispatch_weight_o,output logic[3:0]dispatch_tag_o,output logic dispatch_shared_o,dispatch_last_o,
 input logic merge_result_valid_i,output logic merge_result_ready_o,input logic[3:0]merge_result_tag_i,input logic[511:0]merge_result_data_i,output logic merge_valid_o,input logic merge_ready_i,output logic[3:0]merge_tag_o,output logic[31:0]merge_weight_o,output logic[511:0]merge_data_o,output logic merge_first_o,merge_last_o,
 output logic pool_valid_o,input logic pool_ready_i,output logic[17:0]pool_block_o,output logic[21:0]pool_token_o,output logic[7:0]pool_dimension_o,output logic pool_first_token_o,pool_last_token_o,pool_last_dimension_o,pool_last_o,
 input logic mtp_valid_i,output logic mtp_ready_o,input logic[31:0]mtp_draft_i,mtp_target_i,input logic[5:0]mtp_step_i,input logic mtp_last_i,output logic mtp_result_valid_o,input logic mtp_result_ready_i,output logic[5:0]mtp_accepted_o,mtp_mismatch_step_o,output logic mtp_all_match_o,mtp_rollback_o,
 output logic completion_valid_o,input logic completion_ready_i,output logic[15:0]completion_tag_o,output logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o,output logic completion_predicate_o);
 localparam logic[7:0]TOPK=8'h70,EXPAND=8'h71,ROUTE=8'h72,MERGE=8'h73,POOL=8'h74,MTP=8'h75;
 localparam logic[3:0]IDLE=0,CONFIG=1,TOPK_START=2,TOPK_RUN=3,EXPAND_RUN=4,ROUTE_START=5,ROUTE_RUN=6,MERGE_RUN=7,POOL_START=8,POOL_RUN=9,MTP_START=10,MTP_RUN=11,COMPLETE=12;
 logic[3:0]st;logic[7:0]opcode_q,status_q;logic[15:0]tag_q;logic[7:0]parent_q,terminal_q;logic[19:0]item_count_q;logic[8:0]k_q;logic[63:0]expand_base_q,expand_stride_q;logic[31:0]route_token_q;logic[4:0]route_count_q;logic[18:0]blocks_q;logic[4:0]ratio_q;logic[8:0]dimensions_q;logic[5:0]steps_q;logic route_pending_q,predicate_q;
 logic topk_start_ready,topk_done;logic[7:0]topk_status;
 selection_topk_sram_v3 topk(.clk_i,.rst_ni,.start_i(st==TOPK_START),.start_ready_o(topk_start_ready),.item_count_i(item_count_q),.k_i(k_q),.in_valid_i(score_valid_i&&st==TOPK_RUN),.in_ready_o(score_ready_o),.score_i,.index_i(score_index_i),.sram_req_valid_o(topk_sram_req_valid_o),.sram_req_ready_i(topk_sram_req_ready_i),.sram_req_write_o(topk_sram_req_write_o),.sram_req_addr_o(topk_sram_req_addr_o),.sram_req_wdata_o(topk_sram_req_wdata_o),.sram_rsp_valid_i(topk_sram_rsp_valid_i),.sram_rsp_ready_o(topk_sram_rsp_ready_o),.sram_rsp_rdata_i(topk_sram_rsp_rdata_i),.sram_rsp_error_i(topk_sram_rsp_error_i),.out_valid_o(ranked_valid_o),.out_ready_i(ranked_ready_i&&st==TOPK_RUN),.out_score_o(ranked_score_o),.out_index_o(ranked_index_o),.out_rank_o(ranked_rank_o),.out_last_o(ranked_last_o),.done_o(topk_done),.status_o(topk_status));
 logic expand_q_valid,expand_q_last;logic[63:0]expand_q_address;logic[8:0]expand_q_rank;assign expand_ready_o=st==EXPAND_RUN&&(!expand_q_valid||(expand_out_ready_i&&!expand_q_last));assign expand_out_valid_o=expand_q_valid;assign expand_address_o=expand_q_address;assign expand_out_rank_o=expand_q_rank;assign expand_out_last_o=expand_q_last;
 logic route_start_ready,route_in_ready,route_dispatch_valid,route_result_ready,route_merge_valid,route_busy,route_done,route_bad,route_error;logic[31:0]r_dispatch_token,r_dispatch_weight,r_merge_weight;logic[9:0]r_dispatch_expert;logic[3:0]r_dispatch_tag,r_merge_tag;logic r_dispatch_shared,r_dispatch_last,r_merge_first,r_merge_last;logic[511:0]r_merge_data;
 HeteroMoeRouteDispatch route_ctrl(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==ROUTE_START),.io_startReady(route_start_ready),.io_token(route_token_q),.io_routeCount(route_count_q),.io_routeIn_ready(route_in_ready),.io_routeIn_valid(route_valid_i&&st==ROUTE_RUN),.io_routeIn_bits_expert(route_expert_i),.io_routeIn_bits_weight(route_weight_i),.io_routeIn_bits_shared(route_shared_i),.io_dispatchOut_ready(dispatch_ready_i&&st==ROUTE_RUN),.io_dispatchOut_valid(route_dispatch_valid),.io_dispatchOut_bits_token(r_dispatch_token),.io_dispatchOut_bits_expert(r_dispatch_expert),.io_dispatchOut_bits_weight(r_dispatch_weight),.io_dispatchOut_bits_routeTag(r_dispatch_tag),.io_dispatchOut_bits_shared(r_dispatch_shared),.io_dispatchOut_bits_last(r_dispatch_last),.io_resultIn_ready(route_result_ready),.io_resultIn_valid(merge_result_valid_i&&st==MERGE_RUN),.io_resultIn_bits_routeTag(merge_result_tag_i),.io_resultIn_bits_data(merge_result_data_i),.io_mergeOut_ready(merge_ready_i&&st==MERGE_RUN),.io_mergeOut_valid(route_merge_valid),.io_mergeOut_bits_routeTag(r_merge_tag),.io_mergeOut_bits_weight(r_merge_weight),.io_mergeOut_bits_data(r_merge_data),.io_mergeOut_bits_first(r_merge_first),.io_mergeOut_bits_last(r_merge_last),.io_busy(route_busy),.io_done(route_done),.io_invalidConfig(route_bad),.io_protocolError(route_error));
 assign route_ready_o=st==ROUTE_RUN&&route_in_ready;assign dispatch_valid_o=st==ROUTE_RUN&&route_dispatch_valid;assign dispatch_token_o=r_dispatch_token;assign dispatch_expert_o=r_dispatch_expert;assign dispatch_weight_o=r_dispatch_weight;assign dispatch_tag_o=r_dispatch_tag;assign dispatch_shared_o=r_dispatch_shared;assign dispatch_last_o=r_dispatch_last;assign merge_result_ready_o=st==MERGE_RUN&&route_result_ready;assign merge_valid_o=st==MERGE_RUN&&route_merge_valid;assign merge_tag_o=r_merge_tag;assign merge_weight_o=r_merge_weight;assign merge_data_o=r_merge_data;assign merge_first_o=r_merge_first;assign merge_last_o=r_merge_last;
 logic pool_start_ready,pool_busy,pool_done,pool_bad,p_valid,p_last;logic[17:0]p_block;logic[21:0]p_token;logic[7:0]p_dim;logic p_first,p_last_token,p_last_dim;
 HeteroBlockPoolAddressGenerator pool_ctrl(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==POOL_START),.io_startReady(pool_start_ready),.io_blocks(blocks_q),.io_ratio(ratio_q),.io_dimensions(dimensions_q),.io_out_ready(pool_ready_i&&st==POOL_RUN),.io_out_valid(p_valid),.io_out_bits_block(p_block),.io_out_bits_token(p_token),.io_out_bits_dimension(p_dim),.io_out_bits_firstToken(p_first),.io_out_bits_lastToken(p_last_token),.io_out_bits_lastDimension(p_last_dim),.io_out_bits_last(p_last),.io_busy(pool_busy),.io_done(pool_done),.io_invalidConfig(pool_bad));
 assign pool_valid_o=st==POOL_RUN&&p_valid;assign pool_block_o=p_block;assign pool_token_o=p_token;assign pool_dimension_o=p_dim;assign pool_first_token_o=p_first;assign pool_last_token_o=p_last_token;assign pool_last_dimension_o=p_last_dim;assign pool_last_o=p_last;
 logic mtp_start_ready,mtp_in_ready,mtp_out_valid,mtp_busy,mtp_done,mtp_bad,mtp_error;logic[5:0]m_accepted,m_mismatch;logic m_all,m_rollback;
 HeteroMtpVerify mtp_ctrl(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_start(st==MTP_START),.io_startReady(mtp_start_ready),.io_stepCount(steps_q),.io_in_ready(mtp_in_ready),.io_in_valid(mtp_valid_i&&st==MTP_RUN),.io_in_bits_draft(mtp_draft_i),.io_in_bits_target(mtp_target_i),.io_in_bits_step(mtp_step_i),.io_in_bits_last(mtp_last_i),.io_out_ready(mtp_result_ready_i&&st==MTP_RUN),.io_out_valid(mtp_out_valid),.io_out_bits_acceptedCount(m_accepted),.io_out_bits_mismatchStep(m_mismatch),.io_out_bits_allMatch(m_all),.io_out_bits_rollback(m_rollback),.io_busy(mtp_busy),.io_done(mtp_done),.io_invalidConfig(mtp_bad),.io_protocolError(mtp_error));
 assign mtp_ready_o=st==MTP_RUN&&mtp_in_ready;assign mtp_result_valid_o=st==MTP_RUN&&mtp_out_valid;assign mtp_accepted_o=m_accepted;assign mtp_mismatch_step_o=m_mismatch;assign mtp_all_match_o=m_all;assign mtp_rollback_o=m_rollback;
 assign req_ready_o=st==IDLE;assign config_ready_o=st==CONFIG;assign completion_valid_o=st==COMPLETE;assign completion_tag_o=tag_q;assign completion_parent_phase_o=parent_q;assign completion_terminal_phase_o=terminal_q;assign completion_status_o=status_q;assign completion_predicate_o=predicate_q;
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin st<=IDLE;opcode_q<=0;status_q<=0;predicate_q<=0;tag_q<=0;parent_q<=0;terminal_q<=0;item_count_q<=0;k_q<=0;expand_base_q<=0;expand_stride_q<=0;expand_q_valid<=0;expand_q_address<=0;expand_q_rank<=0;expand_q_last<=0;route_token_q<=0;route_count_q<=0;route_pending_q<=0;blocks_q<=0;ratio_q<=0;dimensions_q<=0;steps_q<=0;end else begin
  if(st==EXPAND_RUN)begin if(expand_q_valid&&expand_out_ready_i)begin if(expand_q_last)begin expand_q_valid<=0;st<=COMPLETE;end else expand_q_valid<=0;end if(expand_valid_i&&expand_ready_o)begin expand_q_valid<=1;expand_q_address<=expand_base_q+expand_index_i*expand_stride_q;expand_q_rank<=expand_rank_i;expand_q_last<=expand_last_i;end end
  case(st)
   IDLE:if(req_valid_i)begin opcode_q<=req_opcode_i;tag_q<=req_tag_i;parent_q<=req_parent_phase_i;terminal_q<=req_terminal_phase_i;status_q<=0;predicate_q<=0;if(req_opcode_i inside{TOPK,EXPAND,ROUTE,MERGE,POOL,MTP})st<=CONFIG;else begin status_q<=4;st<=COMPLETE;end end
   CONFIG:if(config_valid_i)begin item_count_q<=topk_item_count_i;k_q<=topk_k_i;expand_base_q<=expand_base_i;expand_stride_q<=expand_stride_i;route_token_q<=route_token_i;route_count_q<=route_count_i;blocks_q<=pool_blocks_i;ratio_q<=pool_ratio_i;dimensions_q<=pool_dimensions_i;steps_q<=mtp_step_count_i;case(opcode_q)
    TOPK:if(topk_item_count_i==0||topk_k_i==0||topk_k_i>topk_item_count_i)begin status_q<=5;st<=COMPLETE;end else st<=TOPK_START;
    EXPAND:begin expand_q_valid<=0;st<=EXPAND_RUN;end
    ROUTE:if(route_pending_q||route_busy||route_count_i==0||route_count_i>16)begin status_q<=7;st<=COMPLETE;end else st<=ROUTE_START;
    MERGE:if(!route_pending_q)begin status_q<=7;st<=COMPLETE;end else st<=MERGE_RUN;
    POOL:if(pool_blocks_i==0||pool_ratio_i==0||pool_dimensions_i==0)begin status_q<=5;st<=COMPLETE;end else st<=POOL_START;
    MTP:if(mtp_step_count_i==0||mtp_step_count_i>32)begin status_q<=5;st<=COMPLETE;end else st<=MTP_START;default:begin status_q<=4;st<=COMPLETE;end endcase end
   TOPK_START:if(topk_start_ready)st<=TOPK_RUN;TOPK_RUN:if(ranked_valid_o&&ranked_ready_i&&ranked_last_o)begin status_q<=topk_status;st<=COMPLETE;end else if(topk_done)begin status_q<=topk_status;st<=COMPLETE;end
   ROUTE_START:if(route_start_ready)st<=ROUTE_RUN;ROUTE_RUN:if(route_dispatch_valid&&dispatch_ready_i&&r_dispatch_last)begin route_pending_q<=1;st<=COMPLETE;end
   MERGE_RUN:if(route_merge_valid&&merge_ready_i&&r_merge_last)begin route_pending_q<=0;st<=COMPLETE;end
   POOL_START:if(pool_start_ready)st<=POOL_RUN;POOL_RUN:if(p_valid&&pool_ready_i&&p_last)st<=COMPLETE;
   MTP_START:if(mtp_start_ready)st<=MTP_RUN;MTP_RUN:if(mtp_out_valid&&mtp_result_ready_i)begin if(mtp_error)status_q<=7;else predicate_q<=m_rollback;st<=COMPLETE;end
   COMPLETE:if(completion_ready_i)st<=IDLE;default:begin end endcase
 end end
endmodule
