// SPDX-License-Identifier: Apache-2.0
module operator_sfu_norm_endpoint_v3(input logic clk_i,rst_ni,input logic req_valid_i,output logic req_ready_o,input logic[7:0]req_opcode_i,input logic[15:0]req_tag_i,input logic[7:0]req_parent_phase_i,req_terminal_phase_i,input logic payload_valid_i,output logic payload_ready_o,input logic[511:0]payload_x_i,payload_weight_i,payload_bias_i,input logic[31:0]payload_epsilon_i,output logic result_valid_o,input logic result_ready_i,output logic[511:0]result_y_o,output logic[4:0]exception_flags_o,output logic completion_valid_o,input logic completion_ready_i,output logic[15:0]completion_tag_o,output logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o);
 localparam logic[2:0]IDLE=0,PAYLOAD=1,WAIT=2,RESULT=3,COMPLETE=4;logic[2:0]st;logic mode_q,group_q,layer_q;logic[15:0]tag_q;logic[7:0]parent_q,terminal_q,status_q;logic cv,cr,cov,cor;logic[511:0]cy;logic[4:0]cf;
 assign cv=st==PAYLOAD&&payload_valid_i;assign cor=st==WAIT;fp32_norm16_shared_pipe core(.clk_i,.rst_ni,.in_valid_i(cv),.in_ready_o(cr),.mode_group_i(group_q),.mode_rms_i(mode_q),.mode_layer_i(layer_q),.x_i(payload_x_i),.weight_i(payload_weight_i),.bias_i(payload_bias_i),.epsilon_i(payload_epsilon_i),.out_valid_o(cov),.out_ready_i(cor),.y_o(cy),.exception_flags_o(cf));
 assign req_ready_o=st==IDLE;assign payload_ready_o=st==PAYLOAD&&cr;assign result_valid_o=st==RESULT;assign result_y_o=cy;assign exception_flags_o=cf;assign completion_valid_o=st==COMPLETE;assign completion_tag_o=tag_q;assign completion_parent_phase_o=parent_q;assign completion_terminal_phase_o=terminal_q;assign completion_status_o=status_q;
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin st<=IDLE;mode_q<=0;group_q<=0;layer_q<=0;tag_q<=0;parent_q<=0;terminal_q<=0;status_q<=0;end else case(st)
  IDLE:if(req_valid_i)begin tag_q<=req_tag_i;parent_q<=req_parent_phase_i;terminal_q<=req_terminal_phase_i;status_q<=0;group_q<=0;layer_q<=0;if(req_opcode_i==8'h3d)begin mode_q<=1;st<=PAYLOAD;end else if(req_opcode_i==8'h3e)begin group_q<=1;mode_q<=1;st<=PAYLOAD;end else if(req_opcode_i==8'h42)begin mode_q<=0;st<=PAYLOAD;end else if(req_opcode_i==8'h4b)begin mode_q<=0;layer_q<=1;st<=PAYLOAD;end else begin status_q<=4;st<=COMPLETE;end end
  PAYLOAD:if(payload_valid_i&&payload_ready_o)st<=WAIT;WAIT:if(cov)st<=RESULT;RESULT:if(result_ready_i)st<=COMPLETE;COMPLETE:if(completion_ready_i)st<=IDLE;default:st<=IDLE;endcase end
endmodule
