// SPDX-License-Identifier: Apache-2.0
module operator_matrix_owner_endpoint_v3(
 input logic clk_i,rst_ni,input logic req_valid_i,output logic req_ready_o,input logic[7:0]req_opcode_i,input logic[15:0]req_tag_i,input logic[7:0]req_parent_phase_i,req_terminal_phase_i,input logic[15:0]req_flags_i,req_rows_i,req_columns_i,req_depth_i,input logic[23:0]req_src0_i,req_src1_i,req_dst_i,
 input logic step_valid_i,output logic step_ready_o,input logic[2:0]step_context_i,input logic step_clear_i,step_last_i,input logic[255:0]step_a_i,input logic[511:0]step_b_i,output logic out_valid_o,input logic out_ready_i,output logic[2:0]out_context_o,output logic out_last_o,output logic[16383:0]out_acc_o,output logic[4:0]exception_flags_o,
 output logic conv_command_valid_o,input logic conv_command_ready_i,output logic[127:0]conv_command_data_o,input logic conv_event_valid_i,output logic conv_event_ready_o,input logic[55:0]conv_event_data_i,
 output logic completion_valid_o,input logic completion_ready_i,output logic[15:0]completion_tag_o,output logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o,output logic protocol_error_o);
 logic active_q,conv_q;logic br,bcv,bcr,cr,ccv,ccr;logic[15:0]btag,ctag;logic[7:0]bp,bt,bs,cp,ct,cs;wire is_conv=req_opcode_i==8'h25;
 assign req_ready_o=!active_q&&(is_conv?cr:br);
 operator_matrix_bf16_endpoint_v3 bf16(.clk_i,.rst_ni,.req_valid_i(req_valid_i&&!active_q&&!is_conv),.req_ready_o(br),.req_opcode_i,.req_tag_i,.req_parent_phase_i,.req_terminal_phase_i,.req_rows_i,.req_columns_i,.req_depth_i,.step_valid_i(step_valid_i&&active_q&&!conv_q),.step_ready_o,.step_context_i,.step_clear_i,.step_last_i,.step_a_i,.step_b_i,.out_valid_o,.out_ready_i(out_ready_i&&active_q&&!conv_q),.out_context_o,.out_last_o,.out_acc_o,.exception_flags_o,.completion_valid_o(bcv),.completion_ready_i(bcr),.completion_tag_o(btag),.completion_parent_phase_o(bp),.completion_terminal_phase_o(bt),.completion_status_o(bs),.protocol_error_o);
 operator_matrix_conv_gemmini_adapter_v3 conv(.clk_i,.rst_ni,.req_valid_i(req_valid_i&&!active_q&&is_conv),.req_ready_o(cr),.req_opcode_i,.req_tag_i,.req_parent_phase_i,.req_terminal_phase_i,.req_flags_i,.req_src0_i,.req_src1_i,.req_dst_i,.command_valid_o(conv_command_valid_o),.command_ready_i(conv_command_ready_i),.command_data_o(conv_command_data_o),.event_valid_i(conv_event_valid_i),.event_ready_o(conv_event_ready_o),.event_data_i(conv_event_data_i),.completion_valid_o(ccv),.completion_ready_i(ccr),.completion_tag_o(ctag),.completion_parent_phase_o(cp),.completion_terminal_phase_o(ct),.completion_status_o(cs));
 assign bcr=active_q&&!conv_q&&completion_ready_i;assign ccr=active_q&&conv_q&&completion_ready_i;assign completion_valid_o=active_q&&(conv_q?ccv:bcv);assign completion_tag_o=conv_q?ctag:btag;assign completion_parent_phase_o=conv_q?cp:bp;assign completion_terminal_phase_o=conv_q?ct:bt;assign completion_status_o=conv_q?cs:bs;
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin active_q<=0;conv_q<=0;end else begin if(req_valid_i&&req_ready_o)begin active_q<=1;conv_q<=is_conv;end if(completion_valid_o&&completion_ready_i)active_q<=0;end end
endmodule
