// SPDX-License-Identifier: Apache-2.0
// Canonical batch16 first-nine formal operation controller.
`timescale 1ns/1ps
module qwen2_first9_tile16_controller #(parameter integer ADDR_W=15)(
 input logic clk_i,input logic rst_ni,input logic start_i,
 input logic[127:0]rms_command_i,q_command_i,q_bias_command_i,q_rope_command_i,k_command_i,k_bias_command_i,k_rope_command_i,v_command_i,v_bias_command_i,
 output logic descriptor_req_valid_o,input logic descriptor_req_ready_i,output logic[23:0]descriptor_req_index_o,input logic descriptor_rsp_valid_i,output logic descriptor_rsp_ready_o,input logic[127:0]descriptor_rsp_data_i,input logic descriptor_rsp_error_i,
 output logic dma_req_valid_o,input logic dma_req_ready_i,output logic[1:0]dma_req_kind_o,output logic[63:0]dma_src_addr_o,dma_dst_addr_o,output logic[31:0]dma_row_bytes_o,dma_rows_o,dma_src_stride_o,dma_dst_stride_o,input logic dma_rsp_valid_i,output logic dma_rsp_ready_o,input logic dma_rsp_error_i,
 output logic l2_rd_valid_o,input logic l2_rd_ready_i,output logic[ADDR_W-1:0]l2_rd_addr_o,input logic l2_rsp_valid_i,output logic l2_rsp_ready_o,input logic[511:0]l2_rsp_data_i,output logic l2_wr_valid_o,input logic l2_wr_ready_i,output logic[ADDR_W-1:0]l2_wr_addr_o,output logic[511:0]l2_wr_data_o,output logic[63:0]l2_wr_be_o,
 output logic done_o,output logic[7:0]status_o,output logic[3:0]operation_index_o,output logic[31:0]completions_o,matrix_steps_o,rope_steps_o,values_o,output logic[63:0]ddr_read_bytes_o,ddr_write_bytes_o
);
 logic busy_q,rs,ps,bs,os,rdone,pdone,bdone,odone;logic[7:0]rstatus,pstatus,bstatus,ostatus;logic[31:0]rvalues,psteps,bvalues,ovalues,osteps;logic[17:0]pcols,belem,oelem;logic[5:0]ptiles;logic[63:0]rrdbytes,prdbytes,pwrbytes,brdbytes,bwrbytes,ordbytes,owrbytes;logic[127:0]pcmd,bcmd,ocmd;logic[1:0]sel;logic subdone;logic[7:0]substatus;
 logic[3:0]dqv_s,dsr_s,av_s,asr_s,rv_s,rsr_s,wv_s;logic[3:0][23:0]dqi_s;logic[3:0][1:0]ak_s;logic[3:0][63:0]as_s,ad_s,be_s;logic[3:0][31:0]ab_s,an_s,ass_s,ads_s;logic[3:0][ADDR_W-1:0]ra_s,wa_s;logic[3:0][511:0]wd_s;
 always_comb begin pcmd=operation_index_o==1?q_command_i:(operation_index_o==4?k_command_i:v_command_i);bcmd=operation_index_o==2?q_bias_command_i:(operation_index_o==5?k_bias_command_i:v_bias_command_i);ocmd=operation_index_o==3?q_rope_command_i:k_rope_command_i;sel=operation_index_o==0?0:((operation_index_o==1||operation_index_o==4||operation_index_o==7)?1:((operation_index_o==2||operation_index_o==5||operation_index_o==8)?2:3));subdone=sel==0?rdone:(sel==1?pdone:(sel==2?bdone:odone));substatus=sel==0?rstatus:(sel==1?pstatus:(sel==2?bstatus:ostatus));end
 qwen2_rms_tile16_controller rms(.clk_i,.rst_ni,.start_i(rs),.command_i(rms_command_i),.descriptor_req_valid_o(dqv_s[0]),.descriptor_req_ready_i(descriptor_req_ready_i&&sel==0),.descriptor_req_index_o(dqi_s[0]),.descriptor_rsp_valid_i(descriptor_rsp_valid_i&&sel==0),.descriptor_rsp_ready_o(dsr_s[0]),.descriptor_rsp_data_i,.descriptor_rsp_error_i,.dma_req_valid_o(av_s[0]),.dma_req_ready_i(dma_req_ready_i&&sel==0),.dma_req_kind_o(ak_s[0]),.dma_src_addr_o(as_s[0]),.dma_dst_addr_o(ad_s[0]),.dma_row_bytes_o(ab_s[0]),.dma_rows_o(an_s[0]),.dma_src_stride_o(ass_s[0]),.dma_dst_stride_o(ads_s[0]),.dma_rsp_valid_i(dma_rsp_valid_i&&sel==0),.dma_rsp_ready_o(asr_s[0]),.dma_rsp_error_i,.l2_rd_valid_o(rv_s[0]),.l2_rd_ready_i(l2_rd_ready_i&&sel==0),.l2_rd_addr_o(ra_s[0]),.l2_rsp_valid_i(l2_rsp_valid_i&&sel==0),.l2_rsp_ready_o(rsr_s[0]),.l2_rsp_data_i,.l2_wr_valid_o(wv_s[0]),.l2_wr_ready_i(l2_wr_ready_i&&sel==0),.l2_wr_addr_o(wa_s[0]),.l2_wr_data_o(wd_s[0]),.l2_wr_be_o(be_s[0]),.done_o(rdone),.status_o(rstatus),.values_o(rvalues),.ddr_read_bytes_o(rrdbytes));
 qwen2_projection_tile16_controller proj(.clk_i,.rst_ni,.start_i(ps),.command_i(pcmd),.activation_local_i(64'h40000),.weight_local_i(64'h60000),.output_local_i(64'h78000),.descriptor_req_valid_o(dqv_s[1]),.descriptor_req_ready_i(descriptor_req_ready_i&&sel==1),.descriptor_req_index_o(dqi_s[1]),.descriptor_rsp_valid_i(descriptor_rsp_valid_i&&sel==1),.descriptor_rsp_ready_o(dsr_s[1]),.descriptor_rsp_data_i,.descriptor_rsp_error_i,.dma_req_valid_o(av_s[1]),.dma_req_ready_i(dma_req_ready_i&&sel==1),.dma_req_kind_o(ak_s[1]),.dma_src_addr_o(as_s[1]),.dma_dst_addr_o(ad_s[1]),.dma_row_bytes_o(ab_s[1]),.dma_rows_o(an_s[1]),.dma_src_stride_o(ass_s[1]),.dma_dst_stride_o(ads_s[1]),.dma_rsp_valid_i(dma_rsp_valid_i&&sel==1),.dma_rsp_ready_o(asr_s[1]),.dma_rsp_error_i,.l2_rd_valid_o(rv_s[1]),.l2_rd_ready_i(l2_rd_ready_i&&sel==1),.l2_rd_addr_o(ra_s[1]),.l2_rsp_valid_i(l2_rsp_valid_i&&sel==1),.l2_rsp_ready_o(rsr_s[1]),.l2_rsp_data_i,.l2_wr_valid_o(wv_s[1]),.l2_wr_ready_i(l2_wr_ready_i&&sel==1),.l2_wr_addr_o(wa_s[1]),.l2_wr_data_o(wd_s[1]),.l2_wr_be_o(be_s[1]),.done_o(pdone),.status_o(pstatus),.output_columns_o(pcols),.column_tiles_o(ptiles),.matrix_steps_o(psteps),.ddr_read_bytes_o(prdbytes),.ddr_write_bytes_o(pwrbytes));
 qwen2_bias_tile16_controller bias(.clk_i,.rst_ni,.start_i(bs),.command_i(bcmd),.descriptor_req_valid_o(dqv_s[2]),.descriptor_req_ready_i(descriptor_req_ready_i&&sel==2),.descriptor_req_index_o(dqi_s[2]),.descriptor_rsp_valid_i(descriptor_rsp_valid_i&&sel==2),.descriptor_rsp_ready_o(dsr_s[2]),.descriptor_rsp_data_i,.descriptor_rsp_error_i,.dma_req_valid_o(av_s[2]),.dma_req_ready_i(dma_req_ready_i&&sel==2),.dma_req_kind_o(ak_s[2]),.dma_src_addr_o(as_s[2]),.dma_dst_addr_o(ad_s[2]),.dma_row_bytes_o(ab_s[2]),.dma_rows_o(an_s[2]),.dma_src_stride_o(ass_s[2]),.dma_dst_stride_o(ads_s[2]),.dma_rsp_valid_i(dma_rsp_valid_i&&sel==2),.dma_rsp_ready_o(asr_s[2]),.dma_rsp_error_i,.l2_rd_valid_o(rv_s[2]),.l2_rd_ready_i(l2_rd_ready_i&&sel==2),.l2_rd_addr_o(ra_s[2]),.l2_rsp_valid_i(l2_rsp_valid_i&&sel==2),.l2_rsp_ready_o(rsr_s[2]),.l2_rsp_data_i,.l2_wr_valid_o(wv_s[2]),.l2_wr_ready_i(l2_wr_ready_i&&sel==2),.l2_wr_addr_o(wa_s[2]),.l2_wr_data_o(wd_s[2]),.l2_wr_be_o(be_s[2]),.done_o(bdone),.status_o(bstatus),.elements_o(belem),.values_o(bvalues),.ddr_read_bytes_o(brdbytes),.ddr_write_bytes_o(bwrbytes));
 qwen2_rope_tile16_controller rope(.clk_i,.rst_ni,.start_i(os),.command_i(ocmd),.descriptor_req_valid_o(dqv_s[3]),.descriptor_req_ready_i(descriptor_req_ready_i&&sel==3),.descriptor_req_index_o(dqi_s[3]),.descriptor_rsp_valid_i(descriptor_rsp_valid_i&&sel==3),.descriptor_rsp_ready_o(dsr_s[3]),.descriptor_rsp_data_i,.descriptor_rsp_error_i,.dma_req_valid_o(av_s[3]),.dma_req_ready_i(dma_req_ready_i&&sel==3),.dma_req_kind_o(ak_s[3]),.dma_src_addr_o(as_s[3]),.dma_dst_addr_o(ad_s[3]),.dma_row_bytes_o(ab_s[3]),.dma_rows_o(an_s[3]),.dma_src_stride_o(ass_s[3]),.dma_dst_stride_o(ads_s[3]),.dma_rsp_valid_i(dma_rsp_valid_i&&sel==3),.dma_rsp_ready_o(asr_s[3]),.dma_rsp_error_i,.l2_rd_valid_o(rv_s[3]),.l2_rd_ready_i(l2_rd_ready_i&&sel==3),.l2_rd_addr_o(ra_s[3]),.l2_rsp_valid_i(l2_rsp_valid_i&&sel==3),.l2_rsp_ready_o(rsr_s[3]),.l2_rsp_data_i,.l2_wr_valid_o(wv_s[3]),.l2_wr_ready_i(l2_wr_ready_i&&sel==3),.l2_wr_addr_o(wa_s[3]),.l2_wr_data_o(wd_s[3]),.l2_wr_be_o(be_s[3]),.done_o(odone),.status_o(ostatus),.elements_o(oelem),.values_o(ovalues),.coefficient_steps_o(osteps),.ddr_read_bytes_o(ordbytes),.ddr_write_bytes_o(owrbytes));
 assign descriptor_req_valid_o=dqv_s[sel];assign descriptor_req_index_o=dqi_s[sel];assign descriptor_rsp_ready_o=dsr_s[sel];assign dma_req_valid_o=av_s[sel];assign dma_req_kind_o=ak_s[sel];assign dma_src_addr_o=as_s[sel];assign dma_dst_addr_o=ad_s[sel];assign dma_row_bytes_o=ab_s[sel];assign dma_rows_o=an_s[sel];assign dma_src_stride_o=ass_s[sel];assign dma_dst_stride_o=ads_s[sel];assign dma_rsp_ready_o=asr_s[sel];assign l2_rd_valid_o=rv_s[sel];assign l2_rd_addr_o=ra_s[sel];assign l2_rsp_ready_o=rsr_s[sel];assign l2_wr_valid_o=wv_s[sel];assign l2_wr_addr_o=wa_s[sel];assign l2_wr_data_o=wd_s[sel];assign l2_wr_be_o=be_s[sel];
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin busy_q<=0;operation_index_o<=0;rs<=0;ps<=0;bs<=0;os<=0;done_o<=0;status_o<=0;completions_o<=0;matrix_steps_o<=0;rope_steps_o<=0;values_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;end else begin rs<=0;ps<=0;bs<=0;os<=0;done_o<=0;if(start_i&&!busy_q)begin busy_q<=1;operation_index_o<=0;rs<=1;status_o<=0;completions_o<=0;matrix_steps_o<=0;rope_steps_o<=0;values_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;end else if(busy_q&&subdone)begin completions_o<=completions_o+1;status_o<=status_o|substatus;if(sel==0)begin values_o<=values_o+rvalues;ddr_read_bytes_o<=ddr_read_bytes_o+rrdbytes;end else if(sel==1)begin values_o<=values_o+64'(pcols)*16;matrix_steps_o<=matrix_steps_o+psteps;ddr_read_bytes_o<=ddr_read_bytes_o+prdbytes;ddr_write_bytes_o<=ddr_write_bytes_o+pwrbytes;end else if(sel==2)begin values_o<=values_o+bvalues;ddr_read_bytes_o<=ddr_read_bytes_o+brdbytes;ddr_write_bytes_o<=ddr_write_bytes_o+bwrbytes;end else begin values_o<=values_o+ovalues;rope_steps_o<=rope_steps_o+osteps;ddr_read_bytes_o<=ddr_read_bytes_o+ordbytes;ddr_write_bytes_o<=ddr_write_bytes_o+owrbytes;end if(substatus!=0||operation_index_o==8)begin busy_q<=0;done_o<=1;end else begin operation_index_o<=operation_index_o+1;case(operation_index_o+1)1,4,7:ps<=1;2,5,8:bs<=1;3,6:os<=1;default:rs<=1;endcase end end end end
endmodule
