// SPDX-License-Identifier: Apache-2.0
// One formal RMS command over sixteen rows, producing direct K-major staging.
`timescale 1ns/1ps
module qwen2_rms_tile16_controller #(parameter integer ADDR_W=15)(
 input logic clk_i,input logic rst_ni,input logic start_i,input logic[127:0]command_i,input logic[31:0]token_base_i,input logic store_norm_i,
 output logic descriptor_req_valid_o,input logic descriptor_req_ready_i,output logic[23:0]descriptor_req_index_o,input logic descriptor_rsp_valid_i,output logic descriptor_rsp_ready_o,input logic[127:0]descriptor_rsp_data_i,input logic descriptor_rsp_error_i,
 output logic dma_req_valid_o,input logic dma_req_ready_i,output logic[1:0]dma_req_kind_o,output logic[63:0]dma_src_addr_o,dma_dst_addr_o,output logic[31:0]dma_row_bytes_o,dma_rows_o,dma_src_stride_o,dma_dst_stride_o,input logic dma_rsp_valid_i,output logic dma_rsp_ready_o,input logic dma_rsp_error_i,
 output logic l2_rd_valid_o,input logic l2_rd_ready_i,output logic[ADDR_W-1:0]l2_rd_addr_o,input logic l2_rsp_valid_i,output logic l2_rsp_ready_o,input logic[511:0]l2_rsp_data_i,output logic l2_wr_valid_o,input logic l2_wr_ready_i,output logic[ADDR_W-1:0]l2_wr_addr_o,output logic[511:0]l2_wr_data_o,output logic[63:0]l2_wr_be_o,
 output logic done_o,output logic[7:0]status_o,output logic[31:0]values_o,output logic[63:0]ddr_read_bytes_o,ddr_write_bytes_o
);
 typedef enum logic[3:0]{I,CW,L0Q,L0P,L1Q,L1P,PQ,PP,SQ,SP,D}st_e;st_e st;logic cs,cv,cr,cl;logic[7:0]cstatus;logic[167:0]addr;logic ps,pd;logic[31:0]reads,writes,vectors,tvalues;logic[4:0]flags;logic[31:0]token_base_safe;logic store_norm_safe;always_comb begin token_base_safe=(^token_base_i===1'bx)?0:token_base_i;store_norm_safe=store_norm_i===1'b1;end
 qwen2_rms_descriptor_context u_context(.clk_i,.rst_ni,.start_i(cs),.command_i,.descriptor_req_valid_o,.descriptor_req_ready_i,.descriptor_req_index_o,.descriptor_rsp_valid_i,.descriptor_rsp_ready_o,.descriptor_rsp_data_i,.descriptor_rsp_error_i,.context_valid_o(cv),.context_ready_i(cr),.context_legal_o(cl),.context_status_o(cstatus),.tensor_address_o(addr));assign cr=st==CW;
 qwen2_shared_l2_rms_tile16_stager stager(.clk_i,.rst_ni,.start_i(ps),.hidden_local_i(64'h40000),.weight_local_i(64'h50000),.norm_token_local_i(64'h60000),.norm_kmajor_local_i(64'h80000),.l2_rd_valid_o,.l2_rd_ready_i,.l2_rd_addr_o,.l2_rsp_valid_i,.l2_rsp_ready_o,.l2_rsp_data_i,.l2_wr_valid_o,.l2_wr_ready_i,.l2_wr_addr_o,.l2_wr_data_o,.l2_wr_be_o,.done_o(pd),.read_beats_o(reads),.write_beats_o(writes),.rms_vectors_o(vectors),.transpose_values_o(tvalues),.exception_flags_o(flags));
 assign dma_req_valid_o=st==L0Q||st==L1Q||st==SQ;assign dma_req_kind_o=st==L0Q?1:(st==L1Q?0:2);assign dma_src_addr_o=st==L0Q?{8'd0,addr[0+:56]}+64'(token_base_safe)*3072:(st==L1Q?{8'd0,addr[56+:56]}:64'h60000);assign dma_dst_addr_o=st==L0Q?64'h40000:(st==L1Q?64'h50000:{8'd0,addr[112+:56]}+64'(token_base_safe)*3072);assign dma_row_bytes_o=st==L0Q?3072:(st==L1Q?6144:49152);assign dma_rows_o=st==L0Q?16:1;assign dma_src_stride_o=dma_row_bytes_o;assign dma_dst_stride_o=dma_row_bytes_o;assign dma_rsp_ready_o=st==L0P||st==L1P||st==SP;assign done_o=st==D;assign status_o=cstatus!=0?cstatus:(flags[4:1]?7:0);
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin st<=I;cs<=0;ps<=0;values_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;end else begin cs<=0;ps<=0;case(st)I:if(start_i)begin cs<=1;values_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;st<=CW;end CW:if(cv&&cr)st<=cl?L0Q:D;L0Q:if(dma_req_valid_o&&dma_req_ready_i)st<=L0P;L0P:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(dma_rsp_error_i)st<=D;else begin ddr_read_bytes_o<=49152;st<=L1Q;end end L1Q:if(dma_req_valid_o&&dma_req_ready_i)st<=L1P;L1P:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(dma_rsp_error_i)st<=D;else begin ddr_read_bytes_o<=55296;ps<=1;st<=PQ;end end PQ:st<=PP;PP:if(pd)begin values_o<=tvalues;if(store_norm_safe)st<=SQ;else st<=D;end SQ:if(dma_req_valid_o&&dma_req_ready_i)st<=SP;SP:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(!dma_rsp_error_i)ddr_write_bytes_o<=49152;st<=D;end D:st<=I;default:st<=I;endcase end end
endmodule
