// SPDX-License-Identifier: Apache-2.0
// One formal Q or K RoPE command over sequential positions 0..15.
`timescale 1ns/1ps
module qwen2_rope_tile16_controller #(parameter integer ADDR_W=15)(
 input logic clk_i,input logic rst_ni,input logic start_i,input logic[127:0]command_i,
 output logic descriptor_req_valid_o,input logic descriptor_req_ready_i,output logic[23:0]descriptor_req_index_o,input logic descriptor_rsp_valid_i,output logic descriptor_rsp_ready_o,input logic[127:0]descriptor_rsp_data_i,input logic descriptor_rsp_error_i,
 output logic dma_req_valid_o,input logic dma_req_ready_i,output logic[1:0]dma_req_kind_o,output logic[63:0]dma_src_addr_o,dma_dst_addr_o,output logic[31:0]dma_row_bytes_o,dma_rows_o,dma_src_stride_o,dma_dst_stride_o,input logic dma_rsp_valid_i,output logic dma_rsp_ready_o,input logic dma_rsp_error_i,
 output logic l2_rd_valid_o,input logic l2_rd_ready_i,output logic[ADDR_W-1:0]l2_rd_addr_o,input logic l2_rsp_valid_i,output logic l2_rsp_ready_o,input logic[511:0]l2_rsp_data_i,output logic l2_wr_valid_o,input logic l2_wr_ready_i,output logic[ADDR_W-1:0]l2_wr_addr_o,output logic[511:0]l2_wr_data_o,output logic[63:0]l2_wr_be_o,
 output logic done_o,output logic[7:0]status_o,output logic[17:0]elements_o,output logic[31:0]values_o,coefficient_steps_o,output logic[63:0]ddr_read_bytes_o,ddr_write_bytes_o
);
 typedef enum logic[3:0]{I,CW,L0Q,L0P,L1Q,L1P,PQ,PP,SQ,SP,D}st_e;st_e st;logic cs,cv,cr,cl;logic[7:0]cstatus;logic[167:0]addr;logic[9:0]heads,head_dim;logic[5:0]dbeats;logic[3:0]token_q;logic ps,pd,bad;logic[31:0]pread,pwrite,pairs,pos,psteps;logic[4:0]flags,flags_q;
 qwen2_rope_descriptor_context u_context(.clk_i,.rst_ni,.start_i(cs),.command_i,.descriptor_req_valid_o,.descriptor_req_ready_i,.descriptor_req_index_o,.descriptor_rsp_valid_i,.descriptor_rsp_ready_o,.descriptor_rsp_data_i,.descriptor_rsp_error_i,.context_valid_o(cv),.context_ready_i(cr),.context_legal_o(cl),.context_status_o(cstatus),.tensor_address_o(addr),.elements_o,.heads_o(heads),.head_dim_o(head_dim),.data_beats_o(dbeats));assign cr=st==CW;
 qwen2_shared_l2_rope_payload #(.ADDR_W(ADDR_W))payload(.clk_i,.rst_ni,.start_i(ps),.data_beats_i(dbeats),.heads_i(heads),.head_dim_i(head_dim),.position_lane_i(token_q),.data_local_i(64'hc0000+64'(token_q)*elements_o*2),.position_local_i(64'hd0000),.out_local_i(64'he0000+64'(token_q)*elements_o*2),.l2_rd_valid_o,.l2_rd_ready_i,.l2_rd_addr_o,.l2_rsp_valid_i,.l2_rsp_ready_o,.l2_rsp_data_i,.l2_wr_valid_o,.l2_wr_ready_i,.l2_wr_addr_o,.l2_wr_data_o,.l2_wr_be_o,.done_o(pd),.unsupported_position_o(bad),.read_beats_o(pread),.write_beats_o(pwrite),.pairs_o(pairs),.position_o(pos),.coefficient_steps_o(psteps),.exception_flags_o(flags));
 assign dma_req_valid_o=st==L0Q||st==L1Q||st==SQ;assign dma_req_kind_o=st==L0Q?1:(st==L1Q?0:3);assign dma_src_addr_o=st==L0Q?{8'd0,addr[0+:56]}:(st==L1Q?{8'd0,addr[56+:56]}:64'he0000);assign dma_dst_addr_o=st==L0Q?64'hc0000:(st==L1Q?64'hd0000:{8'd0,addr[112+:56]});assign dma_row_bytes_o=st==L1Q?64:{13'd0,elements_o,1'b0};assign dma_rows_o=st==L1Q?1:16;assign dma_src_stride_o=dma_row_bytes_o;assign dma_dst_stride_o=dma_row_bytes_o;assign dma_rsp_ready_o=st==L0P||st==L1P||st==SP;assign done_o=st==D;
 always_comb begin if(cstatus!=0)status_o=cstatus;else if(bad||flags_q[4:1])status_o=bad?4:7;else status_o=0;end
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin st<=I;cs<=0;ps<=0;token_q<=0;values_o<=0;coefficient_steps_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;flags_q<=0;end else begin cs<=0;ps<=0;case(st)
  I:if(start_i)begin cs<=1;token_q<=0;values_o<=0;coefficient_steps_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;flags_q<=0;st<=CW;end CW:if(cv&&cr)begin if(cl)st<=L0Q;else st<=D;end
  L0Q:if(dma_req_valid_o&&dma_req_ready_i)st<=L0P;L0P:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(dma_rsp_error_i)st<=D;else begin ddr_read_bytes_o<=64'(elements_o)*32;st<=L1Q;end end L1Q:if(dma_req_valid_o&&dma_req_ready_i)st<=L1P;L1P:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(dma_rsp_error_i)st<=D;else begin ddr_read_bytes_o<=ddr_read_bytes_o+64;ps<=1;st<=PQ;end end
  PQ:st<=PP;PP:if(pd)begin values_o<=values_o+elements_o;coefficient_steps_o<=coefficient_steps_o+psteps;flags_q<=flags_q|flags;if(bad)st<=D;else if(token_q==15)st<=SQ;else begin token_q<=token_q+1;ps<=1;st<=PQ;end end SQ:if(dma_req_valid_o&&dma_req_ready_i)st<=SP;SP:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(!dma_rsp_error_i)ddr_write_bytes_o<=64'(elements_o)*32;st<=D;end D:st<=I;default:st<=I;endcase end end
endmodule
