// SPDX-License-Identifier: Apache-2.0
// Weight-group8 outer, batch16 inner projection scheduler.
`timescale 1ns/1ps
module qwen2_projection_q1024_group8_controller #(parameter integer ADDR_W=15,parameter integer BATCH_COUNT=64)(
 input logic clk_i,input logic rst_ni,input logic start_i,input logic[127:0]command_i,input logic trace_only_i,
 output logic descriptor_req_valid_o,input logic descriptor_req_ready_i,output logic[23:0]descriptor_req_index_o,input logic descriptor_rsp_valid_i,output logic descriptor_rsp_ready_o,input logic[127:0]descriptor_rsp_data_i,input logic descriptor_rsp_error_i,
 output logic dma_req_valid_o,input logic dma_req_ready_i,output logic[1:0]dma_req_kind_o,output logic[63:0]dma_src_addr_o,dma_dst_addr_o,output logic[31:0]dma_row_bytes_o,dma_rows_o,dma_src_stride_o,dma_dst_stride_o,input logic dma_rsp_valid_i,output logic dma_rsp_ready_o,input logic dma_rsp_error_i,
 output logic l2_rd_valid_o,input logic l2_rd_ready_i,output logic[ADDR_W-1:0]l2_rd_addr_o,input logic l2_rsp_valid_i,output logic l2_rsp_ready_o,input logic[511:0]l2_rsp_data_i,output logic l2_wr_valid_o,input logic l2_wr_ready_i,output logic[ADDR_W-1:0]l2_wr_addr_o,output logic[511:0]l2_wr_data_o,output logic[63:0]l2_wr_be_o,
 output logic done_o,output logic[7:0]status_o,output logic[31:0]matrix_steps_o,values_o,weight_tile_loads_o,norm_batch_loads_o,output logic[63:0]ddr_read_bytes_o,ddr_write_bytes_o
);
 typedef enum logic[3:0]{I,CW,WQ,WP,NBUSY,PBUSY,SQ,SP,TRACE,FIN,D}st_e;st_e st;logic cs,cv,cr,cl;logic[7:0]cstatus,nstatus;logic[167:0]addr;logic[215:0]shape;logic[17:0]columns;logic[31:0]weight_stride;logic[5:0]tiles,group_base,group_count,load_slot,slot;logic[6:0]batch;logic ns,ndone,ps,pdone;logic nav,nar,nasv,nasr,nrv,nrr,nrsv,nrsr,nwv,nwr;logic[1:0]nak;logic[63:0]nas,nad;logic[31:0]nab,nan,nass,nads,nvalues;logic[63:0]nbytes;logic[ADDR_W-1:0]nra,nwa;logic[511:0]nrd,nwd;logic[63:0]nbe;logic prv,prr,prsv,prsr,pwv,pwr;logic[ADDR_W-1:0]pra,pwa;logic[511:0]prd,pwd;logic[63:0]pbe;logic[31:0]pread,pwrite,psteps;logic mpv,mpr,mc,ml,mov,mor,mol,mcv,merr,cmd_pending,mseen;logic[2:0]mctx,moctx;logic[255:0]ma;logic[511:0]mb;logic[16383:0]macc;logic[55:0]mcd;logic direct_dma,trace_safe;always_comb trace_safe=trace_only_i===1'b1;
 qwen2_projection_descriptor_context u_context(.clk_i,.rst_ni,.start_i(cs),.command_i,.descriptor_req_valid_o,.descriptor_req_ready_i,.descriptor_req_index_o,.descriptor_rsp_valid_i,.descriptor_rsp_ready_o,.descriptor_rsp_data_i,.descriptor_rsp_error_i,.context_valid_o(cv),.context_ready_i(cr),.context_legal_o(cl),.context_status_o(cstatus),.tensor_address_o(addr),.tensor_shape_o(shape),.output_columns_o(columns),.weight_row_bytes_o(weight_stride),.column_tiles_o(tiles));assign cr=st==CW;
 qwen2_norm_tile16_loader norm_loader(.clk_i,.rst_ni,.start_i(ns),.norm_ddr_base_i({8'd0,addr[0+:56]}),.token_base_i({21'd0,batch,4'd0}),.dma_req_valid_o(nav),.dma_req_ready_i(nar),.dma_req_kind_o(nak),.dma_src_addr_o(nas),.dma_dst_addr_o(nad),.dma_row_bytes_o(nab),.dma_rows_o(nan),.dma_src_stride_o(nass),.dma_dst_stride_o(nads),.dma_rsp_valid_i(nasv),.dma_rsp_ready_o(nasr),.dma_rsp_error_i(dma_rsp_error_i),.l2_rd_valid_o(nrv),.l2_rd_ready_i(nrr),.l2_rd_addr_o(nra),.l2_rsp_valid_i(nrsv),.l2_rsp_ready_o(nrsr),.l2_rsp_data_i(nrd),.l2_wr_valid_o(nwv),.l2_wr_ready_i(nwr),.l2_wr_addr_o(nwa),.l2_wr_data_o(nwd),.l2_wr_be_o(nbe),.done_o(ndone),.status_o(nstatus),.values_o(nvalues),.ddr_read_bytes_o(nbytes));
 qwen2_shared_l2_matrix_tile16_payload payload(.depth_i(16'd1536),.clk_i,.rst_ni,.start_i(ps),.activation_local_i(64'h80000),.weight_local_i(64'ha0000+64'(slot)*98304),.output_local_i(64'h160000),.l2_rd_valid_o(prv),.l2_rd_ready_i(prr),.l2_rd_addr_o(pra),.l2_rsp_valid_i(prsv),.l2_rsp_ready_o(prsr),.l2_rsp_data_i(prd),.l2_wr_valid_o(pwv),.l2_wr_ready_i(pwr),.l2_wr_addr_o(pwa),.l2_wr_data_o(pwd),.l2_wr_be_o(pbe),.matrix_step_valid_o(mpv),.matrix_step_ready_i(mpr),.matrix_context_o(mctx),.matrix_clear_o(mc),.matrix_last_o(ml),.matrix_a_o(ma),.matrix_b_o(mb),.matrix_out_valid_i(mov),.matrix_out_ready_o(mor),.matrix_out_last_i(mol),.matrix_acc_i(macc),.done_o(pdone),.read_beats_o(pread),.write_beats_o(pwrite),.matrix_steps_o(psteps));
 qwen2_matrix_command_endpoint matrix(.clk_i,.rst_ni,.cmd_valid_i(cmd_pending),.cmd_ready_o(),.cmd_i(command_i),.step_valid_i(mpv),.step_ready_o(mpr),.step_context_i(mctx),.step_clear_i(mc),.step_last_i(ml),.command_last_tile_i(group_base+slot+1==tiles&&batch+1==BATCH_COUNT),.step_a_i(ma),.step_b_i(mb),.out_valid_o(mov),.out_ready_i(mor),.out_context_o(moctx),.out_last_o(mol),.out_acc_o(macc),.completion_valid_o(mcv),.completion_ready_i(1'b1),.completion_data_o(mcd),.protocol_error_o(merr));
 assign direct_dma=st==WQ||st==SQ;assign dma_req_valid_o=st==NBUSY?nav:direct_dma;assign dma_req_kind_o=st==NBUSY?nak:(st==WQ?1:3);assign dma_src_addr_o=st==NBUSY?nas:(st==WQ?{8'd0,addr[56+:56]}+64'(group_base+load_slot)*64:64'h160000);assign dma_dst_addr_o=st==NBUSY?nad:(st==WQ?64'ha0000+64'(load_slot)*98304:{8'd0,addr[112+:56]}+64'(batch)*16*columns*2+64'(group_base+slot)*64);assign dma_row_bytes_o=st==NBUSY?nab:64;assign dma_rows_o=st==NBUSY?nan:(st==WQ?1536:16);assign dma_src_stride_o=st==NBUSY?nass:(st==WQ?weight_stride:64);assign dma_dst_stride_o=st==NBUSY?nads:(st==WQ?64:{13'd0,columns,1'b0});assign nar=st==NBUSY?dma_req_ready_i:0;assign nasv=st==NBUSY?dma_rsp_valid_i:0;assign dma_rsp_ready_o=st==NBUSY?nasr:(st==WP||st==SP);
 assign l2_rd_valid_o=st==NBUSY?nrv:(st==PBUSY?prv:0);assign l2_rd_addr_o=st==NBUSY?nra:pra;assign nrr=st==NBUSY?l2_rd_ready_i:0;assign prr=st==PBUSY?l2_rd_ready_i:0;assign nrsv=st==NBUSY?l2_rsp_valid_i:0;assign prsv=st==PBUSY?l2_rsp_valid_i:0;assign nrd=l2_rsp_data_i;assign prd=l2_rsp_data_i;assign l2_rsp_ready_o=st==NBUSY?nrsr:(st==PBUSY?prsr:0);assign l2_wr_valid_o=st==NBUSY?nwv:(st==PBUSY?pwv:0);assign l2_wr_addr_o=st==NBUSY?nwa:pwa;assign l2_wr_data_o=st==NBUSY?nwd:pwd;assign l2_wr_be_o=st==NBUSY?nbe:pbe;assign nwr=st==NBUSY?l2_wr_ready_i:0;assign pwr=st==PBUSY?l2_wr_ready_i:0;assign done_o=st==D;
 always_comb begin if(cstatus!=0)status_o=cstatus;else if(nstatus!=0||merr||mcd[39:32]!=0)status_o=nstatus!=0?nstatus:7;else status_o=0;end
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin st<=I;cs<=0;ns<=0;ps<=0;group_base<=0;group_count<=0;load_slot<=0;slot<=0;batch<=0;cmd_pending<=0;mseen<=0;matrix_steps_o<=0;values_o<=0;weight_tile_loads_o<=0;norm_batch_loads_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;end else begin cs<=0;ns<=0;ps<=0;if(mcv)mseen<=1;case(st)
 I:if(start_i)begin cs<=1;group_base<=0;load_slot<=0;cmd_pending<=trace_safe?0:1;mseen<=0;matrix_steps_o<=0;values_o<=0;weight_tile_loads_o<=0;norm_batch_loads_o<=0;ddr_read_bytes_o<=0;ddr_write_bytes_o<=0;st<=CW;end CW:if(cv&&cr)begin group_count<=tiles>8?8:tiles;if(!cl)st<=D;else if(trace_safe)begin slot<=0;batch<=0;weight_tile_loads_o<=tiles>8?8:tiles;norm_batch_loads_o<=1;ddr_read_bytes_o<=64'((tiles>8)?8:tiles)*98304+49152;st<=TRACE;end else st<=WQ;end WQ:if(dma_req_valid_o&&dma_req_ready_i)st<=WP;WP:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(dma_rsp_error_i)st<=D;else begin weight_tile_loads_o<=weight_tile_loads_o+1;ddr_read_bytes_o<=ddr_read_bytes_o+98304;if(load_slot+1==group_count)begin batch<=0;ns<=1;st<=NBUSY;end else begin load_slot<=load_slot+1;st<=WQ;end end end
 NBUSY:if(ndone)begin if(nstatus!=0)st<=D;else begin norm_batch_loads_o<=norm_batch_loads_o+1;ddr_read_bytes_o<=ddr_read_bytes_o+nbytes;slot<=0;ps<=1;st<=PBUSY;end end PBUSY:if(pdone)begin matrix_steps_o<=matrix_steps_o+psteps;st<=SQ;end SQ:if(dma_req_valid_o&&dma_req_ready_i)st<=SP;SP:if(dma_rsp_valid_i&&dma_rsp_ready_o)begin if(dma_rsp_error_i)st<=D;else begin values_o<=values_o+512;ddr_write_bytes_o<=ddr_write_bytes_o+1024;if(slot+1<group_count)begin slot<=slot+1;ps<=1;st<=PBUSY;end else if(batch+1<BATCH_COUNT)begin batch<=batch+1;ns<=1;st<=NBUSY;end else if(group_base+group_count<tiles)begin group_base<=group_base+group_count;load_slot<=0;group_count<=((tiles-(group_base+group_count)>8)?8:tiles-(group_base+group_count));st<=WQ;end else st<=FIN;end end TRACE:begin matrix_steps_o<=matrix_steps_o+1536;values_o<=values_o+512;ddr_write_bytes_o<=ddr_write_bytes_o+1024;if(slot+1<group_count)slot<=slot+1;else if(batch+1<BATCH_COUNT)begin batch<=batch+1;slot<=0;norm_batch_loads_o<=norm_batch_loads_o+1;ddr_read_bytes_o<=ddr_read_bytes_o+49152;end else if(group_base+group_count<tiles)begin group_base<=group_base+group_count;group_count<=((tiles-(group_base+group_count)>8)?8:tiles-(group_base+group_count));batch<=0;slot<=0;weight_tile_loads_o<=weight_tile_loads_o+((tiles-(group_base+group_count)>8)?8:tiles-(group_base+group_count));norm_batch_loads_o<=norm_batch_loads_o+1;ddr_read_bytes_o<=ddr_read_bytes_o+64'((tiles-(group_base+group_count)>8)?8:tiles-(group_base+group_count))*98304+49152;end else st<=D;end FIN:if(mseen)st<=D;D:begin cmd_pending<=0;st<=I;end default:st<=I;endcase if(cmd_pending&&st!=I)cmd_pending<=0;end end
endmodule
