
+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_verification/src/clk_rst_gen.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_verification/src/sim_timeout.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_verification/src/stream_watchdog.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_verification/src/signal_highlighter.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/tech_cells_generic/src/deprecated/pulp_clock_gating_async.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/tech_cells_generic/src/deprecated/cluster_clk_cells.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/tech_cells_generic/src/deprecated/pulp_clk_cells.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/assert_rpt_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_binary_to_gray.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_onehot.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_clk_int_div.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_credit_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_delta_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_edge_propagator_tx.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_exp_backoff.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_fifo.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_gray_to_binary.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_heaviside.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_isochronous_4phase_handshake.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_isochronous_spill_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_lfsr.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_lfsr_16bit.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_lfsr_8bit.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_lossy_valid_to_stream.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_onehot_to_bin.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_plru_tree.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_passthrough_stream_fifo.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_popcount.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_ring_buffer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_rr_arb_tree.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_rstgen_bypass.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_serial_deglitch.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_shift_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_shift_register_gated.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_spill_register_flushable.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_demux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_fork.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_intf.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_join_dynamic.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_mux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_throttle.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_sub_per_hash.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_sync_wedge.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_unread.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_addr_decode_dync.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_boxcar.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cdc_2phase.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cdc_4phase.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_clk_int_div_static.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_edge_detect.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_edge_propagator_ack.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_edge_propagator_rx.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_trip_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_addr_decode.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_addr_decode_napot.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_edge_propagator.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_multiaddr_decode.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cb_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cdc_fifo_2phase.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_clk_mux_glitch_free.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_ecc_decode.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_ecc_encode.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_lzc.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_majority_vote_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_max_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_rstgen.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_spill_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_delay.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_fifo.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_fork_dynamic.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_join.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cdc_reset_ctrlr.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cdc_fifo_gray.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_fall_through_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_id_queue.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_to_mem.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_arbiter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_fifo_optimal_wrap.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_xbar.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cdc_fifo_gray_clearable.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_cdc_2phase_clearable.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_mem_to_banks_detailed.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_stream_omega_net.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/cc_mem_to_banks.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cf_math_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cb_filter_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/ecc_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_reset_ctrlr_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_intf.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/binary_to_gray.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/boxcar.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cb_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_2phase.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_4phase.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_fifo_2phase.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_fifo_gray.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/clk_int_div.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/clk_int_div_static.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/clk_mux_glitch_free.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/credit_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/delta_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/ecc_decode.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/ecc_encode.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/edge_detect.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/edge_propagator_tx.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/edge_propagator_rx.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/edge_propagator_ack.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/edge_propagator.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/exp_backoff.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/fifo_v3.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/gray_to_binary.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/heaviside.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/isochronous_4phase_handshake.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/isochronous_spill_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/lfsr.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/lfsr_16bit.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/lfsr_8bit.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/lossy_valid_to_stream.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/lzc.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/onehot_to_bin.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/passthrough_stream_fifo.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/plru_tree.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/popcount.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/ring_buffer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/rr_arb_tree.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/rstgen_bypass.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/rstgen.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/serial_deglitch.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/shift_reg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/shift_reg_gated.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/spill_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/spill_register_flushable.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/sub_per_hash.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/sync.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/sync_wedge.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/unread.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/fall_through_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/max_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/mv_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/trip_counter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/addr_decode.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/addr_decode_dync.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/addr_decode_napot.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/multiaddr_decode.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_reset_ctrlr.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_demux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_mux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_throttle.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_2phase_clearable.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/cdc_fifo_gray_clearable.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/id_queue.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_arbiter_flushable.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_delay.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_fifo.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_fifo_optimal_wrap.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_fork.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_fork_dynamic.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_join.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_join_dynamic.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_register.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_to_mem.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_xbar.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/mem_to_banks_detailed.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_arbiter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/stream_omega_net.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/src/deprecated/mem_to_banks.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/src/apb_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/src/apb_intf.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/src/apb_err_slv.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/src/apb_regs.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/src/apb_cdc.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/src/apb_demux.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_demux_id_counters.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_intf.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_atop_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_burst_splitter_gran.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_burst_unwrap.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_bus_compare.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_cdc_dst.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_cdc_src.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_cut.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_delayer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_demux_simple.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_dw_downsizer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_dw_upsizer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_fifo.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_fifo_delay_dyn.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_id_remap.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_id_prepend.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_inval_filter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_isolate.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_join.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_demux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_dw_converter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_from_mem.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_join.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_lfsr.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_mailbox.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_mux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_regs.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_to_apb.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_to_axi.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_modify_address.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_mux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_rw_join.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_rw_split.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_serializer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_slave_compare.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_throttle.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_to_detailed_mem.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_burst_splitter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_cdc.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_demux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_err_slv.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_dw_converter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_from_mem.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_id_serialize.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lfsr.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_multicut.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_to_axi_lite.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_to_mem.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_zero_mem.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_interleaved_xbar.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_iw_converter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_lite_xbar.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_xbar_unmuxed.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_to_mem_banked.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_to_mem_interleaved.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_to_mem_split.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_xbar.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/src/axi_xp.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/src/axi_stream_intf.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/src/axi_stream_cut.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/src/axi_stream_dw_downsizer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/src/axi_stream_dw_upsizer.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/src/axi_stream_multicut.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/include
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_intf.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_rready_converter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/apb_to_obi.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_to_apb.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_atop_resolver.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_cut.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_demux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_err_sbr.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_mux.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_sram_shim.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/src/obi_xbar.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/target/rtl/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/test
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/idma_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/idma_float_pkg.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_axil_read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_axil_write.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_axi_read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_axi_write.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_axis_read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_axis_write.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_channel_coupler.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_dataflow_element.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_otf_transpose.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_otf_mxquant.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_otf_mxdequant.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_otf_compute.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_error_handler.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_init_read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_init_write.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_legalizer_page_splitter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_legalizer_pow2_splitter.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_obi_read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_obi_write.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_tilelink_read.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/backend/idma_tilelink_write.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/target/rtl/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/test
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/target/rtl/idma_generated.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/target/rtl/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/test
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/midend/idma_mp_dist_midend.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/midend/idma_mp_split_midend.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/midend/idma_nd_midend.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/midend/idma_rt_midend.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/midend/idma_transpose_midend.sv

+define+TARGET_ASIC
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/apb/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/axi_stream/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/common_cells/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/deps/obi/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/target/rtl/include
+incdir+/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/test
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/desc64/idma_desc64_ar_gen.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/desc64/idma_desc64_ar_gen_prefetch.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/desc64/idma_desc64_reader.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/desc64/idma_desc64_reader_gater.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/desc64/idma_desc64_reshaper.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/idma_transfer_id_gen.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/desc64/idma_desc64_reg_wrapper.sv
/home/runner/work/hetero_cnn_llm_aha/hetero_cnn_llm_aha/work/native_upstream/idma_export/idma/src/frontend/desc64/idma_desc64_top.sv

