// SPDX-License-Identifier: Apache-2.0
// Scalar ABI wrappers are Chisel source. Never rewrite the emitted SystemVerilog.
package heteronpu.p0
import chisel3._
import chisel3.util._

class MatrixTilePayloadTop(val cfg: LocalSramConfig = LocalSramConfig()) extends RawModule {
  override def desiredName = "qwen2_shared_l2_matrix_tile16_payload"
  val clk_i = IO(Input(Clock()))
  val rst_ni = IO(Input(Bool()))
  val start_i = IO(Input(Bool()))
  val activation_local_i = IO(Input(UInt(64.W)))
  val weight_local_i = IO(Input(UInt(64.W)))
  val output_local_i = IO(Input(UInt(64.W)))
  val depth_i = IO(Input(UInt(16.W)))
  val weight_k_stride_i = IO(Input(UInt(32.W)))
  val rows_i = IO(Input(UInt(16.W)))
  val columns_i = IO(Input(UInt(16.W)))
  val output_fp32_i = IO(Input(Bool()))
  val status_o = IO(Output(UInt(8.W)))
  val l2_rd_valid_o = IO(Output(Bool()))
  val l2_rd_ready_i = IO(Input(Bool()))
  val l2_rd_addr_o = IO(Output(UInt(cfg.addressBits.W)))
  val l2_rsp_valid_i = IO(Input(Bool()))
  val l2_rsp_ready_o = IO(Output(Bool()))
  val l2_rsp_data_i = IO(Input(UInt(512.W)))
  val l2_wr_valid_o = IO(Output(Bool()))
  val l2_wr_ready_i = IO(Input(Bool()))
  val l2_wr_addr_o = IO(Output(UInt(cfg.addressBits.W)))
  val l2_wr_data_o = IO(Output(UInt(512.W)))
  val l2_wr_be_o = IO(Output(UInt(64.W)))
  val matrix_step_valid_o = IO(Output(Bool()))
  val matrix_step_ready_i = IO(Input(Bool()))
  val matrix_context_o = IO(Output(UInt(3.W)))
  val matrix_clear_o = IO(Output(Bool()))
  val matrix_last_o = IO(Output(Bool()))
  val matrix_a_o = IO(Output(UInt(256.W)))
  val matrix_b_o = IO(Output(UInt(512.W)))
  val matrix_out_valid_i = IO(Input(Bool()))
  val matrix_out_ready_o = IO(Output(Bool()))
  val matrix_out_last_i = IO(Input(Bool()))
  val matrix_acc_i = IO(Input(UInt(16384.W)))
  val done_o = IO(Output(Bool()))
  val read_beats_o = IO(Output(UInt(32.W)))
  val write_beats_o = IO(Output(UInt(32.W)))
  val core = withClockAndReset(clk_i,(!rst_ni).asAsyncReset) { Module(new MatrixTilePayload(cfg)) }
  core.io.start_i := start_i
  core.io.activation_local_i := activation_local_i
  core.io.weight_local_i := weight_local_i
  core.io.output_local_i := output_local_i
  core.io.depth_i := depth_i
  core.io.weight_k_stride_i := weight_k_stride_i
  core.io.rows_i := rows_i
  core.io.columns_i := columns_i
  core.io.output_fp32_i := output_fp32_i
  status_o := core.io.status_o
  l2_rd_valid_o := core.io.l2_rd_valid_o
  core.io.l2_rd_ready_i := l2_rd_ready_i
  l2_rd_addr_o := core.io.l2_rd_addr_o
  core.io.l2_rsp_valid_i := l2_rsp_valid_i
  l2_rsp_ready_o := core.io.l2_rsp_ready_o
  core.io.l2_rsp_data_i := l2_rsp_data_i
  l2_wr_valid_o := core.io.l2_wr_valid_o
  core.io.l2_wr_ready_i := l2_wr_ready_i
  l2_wr_addr_o := core.io.l2_wr_addr_o
  l2_wr_data_o := core.io.l2_wr_data_o
  l2_wr_be_o := core.io.l2_wr_be_o
  matrix_step_valid_o := core.io.matrix_step_valid_o
  core.io.matrix_step_ready_i := matrix_step_ready_i
  matrix_context_o := core.io.matrix_context_o
  matrix_clear_o := core.io.matrix_clear_o
  matrix_last_o := core.io.matrix_last_o
  matrix_a_o := core.io.matrix_a_o
  matrix_b_o := core.io.matrix_b_o
  core.io.matrix_out_valid_i := matrix_out_valid_i
  matrix_out_ready_o := core.io.matrix_out_ready_o
  core.io.matrix_out_last_i := matrix_out_last_i
  core.io.matrix_acc_i := matrix_acc_i
  done_o := core.io.done_o
  read_beats_o := core.io.read_beats_o
  write_beats_o := core.io.write_beats_o
}

class TileTransposeTop(val cfg: LocalSramConfig = LocalSramConfig()) extends RawModule {
  override def desiredName = "bf16_tile_transpose_stager"
  val clk_i = IO(Input(Clock()))
  val rst_ni = IO(Input(Bool()))
  val request_valid_i = IO(Input(Bool()))
  val request_ready_o = IO(Output(Bool()))
  val source_i = IO(Input(UInt(64.W)))
  val destination_i = IO(Input(UInt(64.W)))
  val source_stride_i = IO(Input(UInt(32.W)))
  val rows_i = IO(Input(UInt(16.W)))
  val depth_i = IO(Input(UInt(16.W)))
  val rd_valid_o = IO(Output(Bool()))
  val rd_ready_i = IO(Input(Bool()))
  val rd_addr_o = IO(Output(UInt(cfg.addressBits.W)))
  val rsp_valid_i = IO(Input(Bool()))
  val rsp_ready_o = IO(Output(Bool()))
  val rsp_data_i = IO(Input(UInt(512.W)))
  val rsp_error_i = IO(Input(Bool()))
  val wr_valid_o = IO(Output(Bool()))
  val wr_ready_i = IO(Input(Bool()))
  val wr_addr_o = IO(Output(UInt(cfg.addressBits.W)))
  val wr_data_o = IO(Output(UInt(512.W)))
  val wr_be_o = IO(Output(UInt(64.W)))
  val completion_valid_o = IO(Output(Bool()))
  val completion_ready_i = IO(Input(Bool()))
  val status_o = IO(Output(UInt(8.W)))
  val read_beats_o = IO(Output(UInt(64.W)))
  val core = withClockAndReset(clk_i,(!rst_ni).asAsyncReset) { Module(new TileTranspose(cfg)) }
  core.io.request_valid_i := request_valid_i
  request_ready_o := core.io.request_ready_o
  core.io.source_i := source_i
  core.io.destination_i := destination_i
  core.io.source_stride_i := source_stride_i
  core.io.rows_i := rows_i
  core.io.depth_i := depth_i
  rd_valid_o := core.io.rd_valid_o
  core.io.rd_ready_i := rd_ready_i
  rd_addr_o := core.io.rd_addr_o
  core.io.rsp_valid_i := rsp_valid_i
  rsp_ready_o := core.io.rsp_ready_o
  core.io.rsp_data_i := rsp_data_i
  core.io.rsp_error_i := rsp_error_i
  wr_valid_o := core.io.wr_valid_o
  core.io.wr_ready_i := wr_ready_i
  wr_addr_o := core.io.wr_addr_o
  wr_data_o := core.io.wr_data_o
  wr_be_o := core.io.wr_be_o
  completion_valid_o := core.io.completion_valid_o
  core.io.completion_ready_i := completion_ready_i
  status_o := core.io.status_o
  read_beats_o := core.io.read_beats_o
}

class SharedL2FabricTop(val cfg: LocalSramConfig = LocalSramConfig()) extends RawModule {
  override def desiredName = "shared_l2_fabric"
  val clk_i = IO(Input(Clock()))
  val rst_ni = IO(Input(Bool()))
  val rd_valid_i = IO(Input(UInt(2.W)))
  val rd_ready_o = IO(Output(UInt(2.W)))
  val rd_addr_i = IO(Input(UInt((2*cfg.addressBits).W)))
  val rd_resp_valid_o = IO(Output(UInt(2.W)))
  val rd_resp_ready_i = IO(Input(UInt(2.W)))
  val rd_data_o = IO(Output(UInt(1024.W)))
  val wr_valid_i = IO(Input(Bool()))
  val wr_ready_o = IO(Output(Bool()))
  val wr_addr_i = IO(Input(UInt(cfg.addressBits.W)))
  val wr_data_i = IO(Input(UInt(512.W)))
  val wr_be_i = IO(Input(UInt(64.W)))
  val cycle_count_o = IO(Output(UInt(64.W)))
  val read_count_o = IO(Output(UInt(64.W)))
  val write_count_o = IO(Output(UInt(64.W)))
  val bank_conflict_count_o = IO(Output(UInt(64.W)))
  val read_stall_count_o = IO(Output(UInt(64.W)))
  val write_stall_count_o = IO(Output(UInt(64.W)))
  val core = withClockAndReset(clk_i,(!rst_ni).asAsyncReset) { Module(new SharedL2Fabric(cfg)) }
  core.io.rd_valid_i := rd_valid_i
  rd_ready_o := core.io.rd_ready_o
  core.io.rd_addr_i := rd_addr_i
  rd_resp_valid_o := core.io.rd_resp_valid_o
  core.io.rd_resp_ready_i := rd_resp_ready_i
  rd_data_o := core.io.rd_data_o
  core.io.wr_valid_i := wr_valid_i
  wr_ready_o := core.io.wr_ready_o
  core.io.wr_addr_i := wr_addr_i
  core.io.wr_data_i := wr_data_i
  core.io.wr_be_i := wr_be_i
  cycle_count_o := core.io.cycle_count_o
  read_count_o := core.io.read_count_o
  write_count_o := core.io.write_count_o
  bank_conflict_count_o := core.io.bank_conflict_count_o
  read_stall_count_o := core.io.read_stall_count_o
  write_stall_count_o := core.io.write_stall_count_o
}

class Group8IntegrationTop(val cfg: LocalSramConfig = LocalSramConfig()) extends RawModule {
  override def desiredName = "qwen2_projection_q1024_group8_controller"
  val clk_i = IO(Input(Clock()))
  val rst_ni = IO(Input(Bool()))
  val start_i = IO(Input(Bool()))
  val command_i = IO(Input(UInt(128.W)))
  val trace_only_i = IO(Input(Bool()))
  val batch_count_i = IO(Input(UInt(32.W)))
  val descriptor_req_valid_o = IO(Output(Bool()))
  val descriptor_req_ready_i = IO(Input(Bool()))
  val descriptor_req_index_o = IO(Output(UInt(24.W)))
  val descriptor_rsp_valid_i = IO(Input(Bool()))
  val descriptor_rsp_ready_o = IO(Output(Bool()))
  val descriptor_rsp_data_i = IO(Input(UInt(128.W)))
  val descriptor_rsp_error_i = IO(Input(Bool()))
  val dma_req_valid_o = IO(Output(Bool()))
  val dma_req_ready_i = IO(Input(Bool()))
  val dma_req_kind_o = IO(Output(UInt(2.W)))
  val dma_src_addr_o = IO(Output(UInt(64.W)))
  val dma_dst_addr_o = IO(Output(UInt(64.W)))
  val dma_row_bytes_o = IO(Output(UInt(32.W)))
  val dma_rows_o = IO(Output(UInt(32.W)))
  val dma_src_stride_o = IO(Output(UInt(32.W)))
  val dma_dst_stride_o = IO(Output(UInt(32.W)))
  val dma_rsp_valid_i = IO(Input(Bool()))
  val dma_rsp_ready_o = IO(Output(Bool()))
  val dma_rsp_error_i = IO(Input(Bool()))
  val l2_rd_valid_o = IO(Output(Bool()))
  val l2_rd_ready_i = IO(Input(Bool()))
  val l2_rd_addr_o = IO(Output(UInt(cfg.addressBits.W)))
  val l2_rsp_valid_i = IO(Input(Bool()))
  val l2_rsp_ready_o = IO(Output(Bool()))
  val l2_rsp_data_i = IO(Input(UInt(512.W)))
  val l2_wr_valid_o = IO(Output(Bool()))
  val l2_wr_ready_i = IO(Input(Bool()))
  val l2_wr_addr_o = IO(Output(UInt(cfg.addressBits.W)))
  val l2_wr_data_o = IO(Output(UInt(512.W)))
  val l2_wr_be_o = IO(Output(UInt(64.W)))
  val done_o = IO(Output(Bool()))
  val status_o = IO(Output(UInt(8.W)))
  val matrix_steps_o = IO(Output(UInt(32.W)))
  val values_o = IO(Output(UInt(32.W)))
  val weight_tile_loads_o = IO(Output(UInt(32.W)))
  val norm_batch_loads_o = IO(Output(UInt(32.W)))
  val ddr_read_bytes_o = IO(Output(UInt(64.W)))
  val ddr_write_bytes_o = IO(Output(UInt(64.W)))
  val core = withClockAndReset(clk_i,(!rst_ni).asAsyncReset) { Module(new Group8Integration(cfg)) }
  core.io.start_i := start_i
  core.io.command_i := command_i
  core.io.trace_only_i := trace_only_i
  core.io.batch_count_i := batch_count_i
  descriptor_req_valid_o := core.io.descriptor_req_valid_o
  core.io.descriptor_req_ready_i := descriptor_req_ready_i
  descriptor_req_index_o := core.io.descriptor_req_index_o
  core.io.descriptor_rsp_valid_i := descriptor_rsp_valid_i
  descriptor_rsp_ready_o := core.io.descriptor_rsp_ready_o
  core.io.descriptor_rsp_data_i := descriptor_rsp_data_i
  core.io.descriptor_rsp_error_i := descriptor_rsp_error_i
  dma_req_valid_o := core.io.dma_req_valid_o
  core.io.dma_req_ready_i := dma_req_ready_i
  dma_req_kind_o := core.io.dma_req_kind_o
  dma_src_addr_o := core.io.dma_src_addr_o
  dma_dst_addr_o := core.io.dma_dst_addr_o
  dma_row_bytes_o := core.io.dma_row_bytes_o
  dma_rows_o := core.io.dma_rows_o
  dma_src_stride_o := core.io.dma_src_stride_o
  dma_dst_stride_o := core.io.dma_dst_stride_o
  core.io.dma_rsp_valid_i := dma_rsp_valid_i
  dma_rsp_ready_o := core.io.dma_rsp_ready_o
  core.io.dma_rsp_error_i := dma_rsp_error_i
  l2_rd_valid_o := core.io.l2_rd_valid_o
  core.io.l2_rd_ready_i := l2_rd_ready_i
  l2_rd_addr_o := core.io.l2_rd_addr_o
  core.io.l2_rsp_valid_i := l2_rsp_valid_i
  l2_rsp_ready_o := core.io.l2_rsp_ready_o
  core.io.l2_rsp_data_i := l2_rsp_data_i
  l2_wr_valid_o := core.io.l2_wr_valid_o
  core.io.l2_wr_ready_i := l2_wr_ready_i
  l2_wr_addr_o := core.io.l2_wr_addr_o
  l2_wr_data_o := core.io.l2_wr_data_o
  l2_wr_be_o := core.io.l2_wr_be_o
  done_o := core.io.done_o
  status_o := core.io.status_o
  matrix_steps_o := core.io.matrix_steps_o
  values_o := core.io.values_o
  weight_tile_loads_o := core.io.weight_tile_loads_o
  norm_batch_loads_o := core.io.norm_batch_loads_o
  ddr_read_bytes_o := core.io.ddr_read_bytes_o
  ddr_write_bytes_o := core.io.ddr_write_bytes_o
}

class P0AllRoots(val cfg: LocalSramConfig = LocalSramConfig()) extends RawModule {
  val clk_i = IO(Input(Clock()))
  val rst_ni = IO(Input(Bool()))
  val port0 = IO(new MatrixTilePayloadIO(cfg.addressBits))
  val root0 = Module(new MatrixTilePayloadTop(cfg))
  root0.clk_i := clk_i
  root0.rst_ni := rst_ni
  root0.start_i := port0.start_i
  root0.activation_local_i := port0.activation_local_i
  root0.weight_local_i := port0.weight_local_i
  root0.output_local_i := port0.output_local_i
  root0.depth_i := port0.depth_i
  root0.weight_k_stride_i := port0.weight_k_stride_i
  root0.rows_i := port0.rows_i
  root0.columns_i := port0.columns_i
  root0.output_fp32_i := port0.output_fp32_i
  port0.status_o := root0.status_o
  port0.l2_rd_valid_o := root0.l2_rd_valid_o
  root0.l2_rd_ready_i := port0.l2_rd_ready_i
  port0.l2_rd_addr_o := root0.l2_rd_addr_o
  root0.l2_rsp_valid_i := port0.l2_rsp_valid_i
  port0.l2_rsp_ready_o := root0.l2_rsp_ready_o
  root0.l2_rsp_data_i := port0.l2_rsp_data_i
  port0.l2_wr_valid_o := root0.l2_wr_valid_o
  root0.l2_wr_ready_i := port0.l2_wr_ready_i
  port0.l2_wr_addr_o := root0.l2_wr_addr_o
  port0.l2_wr_data_o := root0.l2_wr_data_o
  port0.l2_wr_be_o := root0.l2_wr_be_o
  port0.matrix_step_valid_o := root0.matrix_step_valid_o
  root0.matrix_step_ready_i := port0.matrix_step_ready_i
  port0.matrix_context_o := root0.matrix_context_o
  port0.matrix_clear_o := root0.matrix_clear_o
  port0.matrix_last_o := root0.matrix_last_o
  port0.matrix_a_o := root0.matrix_a_o
  port0.matrix_b_o := root0.matrix_b_o
  root0.matrix_out_valid_i := port0.matrix_out_valid_i
  port0.matrix_out_ready_o := root0.matrix_out_ready_o
  root0.matrix_out_last_i := port0.matrix_out_last_i
  root0.matrix_acc_i := port0.matrix_acc_i
  port0.done_o := root0.done_o
  port0.read_beats_o := root0.read_beats_o
  port0.write_beats_o := root0.write_beats_o
  val port1 = IO(new TileTransposeIO(cfg.addressBits))
  val root1 = Module(new TileTransposeTop(cfg))
  root1.clk_i := clk_i
  root1.rst_ni := rst_ni
  root1.request_valid_i := port1.request_valid_i
  port1.request_ready_o := root1.request_ready_o
  root1.source_i := port1.source_i
  root1.destination_i := port1.destination_i
  root1.source_stride_i := port1.source_stride_i
  root1.rows_i := port1.rows_i
  root1.depth_i := port1.depth_i
  port1.rd_valid_o := root1.rd_valid_o
  root1.rd_ready_i := port1.rd_ready_i
  port1.rd_addr_o := root1.rd_addr_o
  root1.rsp_valid_i := port1.rsp_valid_i
  port1.rsp_ready_o := root1.rsp_ready_o
  root1.rsp_data_i := port1.rsp_data_i
  root1.rsp_error_i := port1.rsp_error_i
  port1.wr_valid_o := root1.wr_valid_o
  root1.wr_ready_i := port1.wr_ready_i
  port1.wr_addr_o := root1.wr_addr_o
  port1.wr_data_o := root1.wr_data_o
  port1.wr_be_o := root1.wr_be_o
  port1.completion_valid_o := root1.completion_valid_o
  root1.completion_ready_i := port1.completion_ready_i
  port1.status_o := root1.status_o
  port1.read_beats_o := root1.read_beats_o
  val port2 = IO(new SharedL2FabricIO(cfg.addressBits))
  val root2 = Module(new SharedL2FabricTop(cfg))
  root2.clk_i := clk_i
  root2.rst_ni := rst_ni
  root2.rd_valid_i := port2.rd_valid_i
  port2.rd_ready_o := root2.rd_ready_o
  root2.rd_addr_i := port2.rd_addr_i
  port2.rd_resp_valid_o := root2.rd_resp_valid_o
  root2.rd_resp_ready_i := port2.rd_resp_ready_i
  port2.rd_data_o := root2.rd_data_o
  root2.wr_valid_i := port2.wr_valid_i
  port2.wr_ready_o := root2.wr_ready_o
  root2.wr_addr_i := port2.wr_addr_i
  root2.wr_data_i := port2.wr_data_i
  root2.wr_be_i := port2.wr_be_i
  port2.cycle_count_o := root2.cycle_count_o
  port2.read_count_o := root2.read_count_o
  port2.write_count_o := root2.write_count_o
  port2.bank_conflict_count_o := root2.bank_conflict_count_o
  port2.read_stall_count_o := root2.read_stall_count_o
  port2.write_stall_count_o := root2.write_stall_count_o
  val port3 = IO(new Group8TopIO(cfg.addressBits))
  val root3 = Module(new Group8IntegrationTop(cfg))
  root3.clk_i := clk_i
  root3.rst_ni := rst_ni
  root3.start_i := port3.start_i
  root3.command_i := port3.command_i
  root3.trace_only_i := port3.trace_only_i
  root3.batch_count_i := port3.batch_count_i
  port3.descriptor_req_valid_o := root3.descriptor_req_valid_o
  root3.descriptor_req_ready_i := port3.descriptor_req_ready_i
  port3.descriptor_req_index_o := root3.descriptor_req_index_o
  root3.descriptor_rsp_valid_i := port3.descriptor_rsp_valid_i
  port3.descriptor_rsp_ready_o := root3.descriptor_rsp_ready_o
  root3.descriptor_rsp_data_i := port3.descriptor_rsp_data_i
  root3.descriptor_rsp_error_i := port3.descriptor_rsp_error_i
  port3.dma_req_valid_o := root3.dma_req_valid_o
  root3.dma_req_ready_i := port3.dma_req_ready_i
  port3.dma_req_kind_o := root3.dma_req_kind_o
  port3.dma_src_addr_o := root3.dma_src_addr_o
  port3.dma_dst_addr_o := root3.dma_dst_addr_o
  port3.dma_row_bytes_o := root3.dma_row_bytes_o
  port3.dma_rows_o := root3.dma_rows_o
  port3.dma_src_stride_o := root3.dma_src_stride_o
  port3.dma_dst_stride_o := root3.dma_dst_stride_o
  root3.dma_rsp_valid_i := port3.dma_rsp_valid_i
  port3.dma_rsp_ready_o := root3.dma_rsp_ready_o
  root3.dma_rsp_error_i := port3.dma_rsp_error_i
  port3.l2_rd_valid_o := root3.l2_rd_valid_o
  root3.l2_rd_ready_i := port3.l2_rd_ready_i
  port3.l2_rd_addr_o := root3.l2_rd_addr_o
  root3.l2_rsp_valid_i := port3.l2_rsp_valid_i
  port3.l2_rsp_ready_o := root3.l2_rsp_ready_o
  root3.l2_rsp_data_i := port3.l2_rsp_data_i
  port3.l2_wr_valid_o := root3.l2_wr_valid_o
  root3.l2_wr_ready_i := port3.l2_wr_ready_i
  port3.l2_wr_addr_o := root3.l2_wr_addr_o
  port3.l2_wr_data_o := root3.l2_wr_data_o
  port3.l2_wr_be_o := root3.l2_wr_be_o
  port3.done_o := root3.done_o
  port3.status_o := root3.status_o
  port3.matrix_steps_o := root3.matrix_steps_o
  port3.values_o := root3.values_o
  port3.weight_tile_loads_o := root3.weight_tile_loads_o
  port3.norm_batch_loads_o := root3.norm_batch_loads_o
  port3.ddr_read_bytes_o := root3.ddr_read_bytes_o
  port3.ddr_write_bytes_o := root3.ddr_write_bytes_o
}
