package gemmini

import chisel3._
import chisel3.util._

class HeteroStableTopK(val maxK:Int=512,val indexBits:Int=16) extends Module {
  require(maxK>=1); private val cb=math.max(1,log2Ceil(maxK+1)); val io=IO(new Bundle { val start=Input(Bool());val k=Input(UInt(cb.W));val in=Flipped(Decoupled(new HeteroScoreIndex(indexBits)));val out=Decoupled(new HeteroRankedScore(indexBits,cb));val busy=Output(Bool());val done=Output(Bool());val acceptedEntries=Output(UInt(32.W));val retainedEntries=Output(UInt(cb.W)) })
  val sIdle::sAccept::sScan::sShift::sEmit::Nil=Enum(5);val state=RegInit(sIdle);val kr=RegInit(1.U(cb.W));val count=RegInit(0.U(cb.W));val accepted=RegInit(0.U(32.W));val scores=Reg(Vec(maxK,UInt(32.W)));val indices=Reg(Vec(maxK,UInt(indexBits.W)));val cs=Reg(UInt(32.W));val ci=Reg(UInt(indexBits.W));val cl=RegInit(false.B);val scan=RegInit(0.U(cb.W));val ins=RegInit(0.U(cb.W));val shift=RegInit(0.U(cb.W));val emit=RegInit(0.U(cb.W));val done=RegInit(false.B);val ksafe=Mux(io.k===0.U,1.U,Mux(io.k>maxK.U,maxK.U,io.k))
  io.in.ready:=state===sAccept;io.out.valid:=state===sEmit&&emit<count;io.out.bits.score:=scores(emit);io.out.bits.index:=indices(emit);io.out.bits.rank:=emit;io.out.bits.last:=emit+1.U>=count;io.busy:=state=/=sIdle;io.done:=done;io.acceptedEntries:=accepted;io.retainedEntries:=count;done:=false.B
  when(state===sIdle){when(io.start){kr:=ksafe;count:=0.U;accepted:=0.U;emit:=0.U;state:=sAccept}}.elsewhen(state===sAccept){when(io.in.fire){cs:=io.in.bits.score;ci:=io.in.bits.index;cl:=io.in.bits.last;scan:=0.U;accepted:=accepted+1.U;state:=sScan}}.elsewhen(state===sScan){val occupied=scan<count;val wins=occupied&&HeteroFp32Order.better(cs,ci,scores(scan),indices(scan));when(scan>=kr){when(cl){emit:=0.U;state:=sEmit}.otherwise{state:=sAccept}}.elsewhen(!occupied||wins){ins:=scan;shift:=Mux(count<kr,count,kr-1.U);state:=sShift}.elsewhen(scan+1.U>=kr){when(cl){emit:=0.U;state:=sEmit}.otherwise{state:=sAccept}}.otherwise{scan:=scan+1.U}}.elsewhen(state===sShift){when(shift>ins){scores(shift):=scores(shift-1.U);indices(shift):=indices(shift-1.U);shift:=shift-1.U}.otherwise{scores(ins):=cs;indices(ins):=ci;when(count<kr){count:=count+1.U};when(cl){emit:=0.U;state:=sEmit}.otherwise{state:=sAccept}}}.elsewhen(state===sEmit){when(io.out.fire){when(emit+1.U>=count){state:=sIdle;done:=true.B}.otherwise{emit:=emit+1.U}}}
}
class HeteroStableArgmax(val indexBits:Int=20) extends Module { val io=IO(new Bundle {val start=Input(Bool());val in=Flipped(Decoupled(new HeteroScoreIndex(indexBits)));val out=Decoupled(new HeteroScoreIndex(indexBits));val busy=Output(Bool());val done=Output(Bool())});val top=Module(new HeteroStableTopK(1,indexBits));top.io.start:=io.start;top.io.k:=1.U;top.io.in<>io.in;io.out.valid:=top.io.out.valid;top.io.out.ready:=io.out.ready;io.out.bits.score:=top.io.out.bits.score;io.out.bits.index:=top.io.out.bits.index;io.out.bits.last:=true.B;io.busy:=top.io.busy;io.done:=top.io.done }

class HeteroIndexItem(val indexBits:Int=16) extends Bundle {val index=UInt(indexBits.W);val last=Bool();override def cloneType:this.type=new HeteroIndexItem(indexBits).asInstanceOf[this.type]}
class HeteroStableIndexSorter(val maxItems:Int=512,val indexBits:Int=16) extends Module {
  private val cb=math.max(1,log2Ceil(maxItems+1));val io=IO(new Bundle{val start=Input(Bool());val in=Flipped(Decoupled(new HeteroIndexItem(indexBits)));val out=Decoupled(new HeteroIndexItem(indexBits));val busy=Output(Bool());val done=Output(Bool());val itemCount=Output(UInt(cb.W))});val sIdle::sAccept::sScan::sShift::sEmit::Nil=Enum(5);val state=RegInit(sIdle);val values=Reg(Vec(maxItems,UInt(indexBits.W)));val count=RegInit(0.U(cb.W));val cand=Reg(UInt(indexBits.W));val last=RegInit(false.B);val scan=RegInit(0.U(cb.W));val ins=RegInit(0.U(cb.W));val shift=RegInit(0.U(cb.W));val emit=RegInit(0.U(cb.W));val done=RegInit(false.B);io.in.ready:=state===sAccept;io.out.valid:=state===sEmit&&emit<count;io.out.bits.index:=values(emit);io.out.bits.last:=emit+1.U>=count;io.busy:=state=/=sIdle;io.done:=done;io.itemCount:=count;done:=false.B
  when(state===sIdle){when(io.start){count:=0.U;emit:=0.U;state:=sAccept}}.elsewhen(state===sAccept){when(io.in.fire){cand:=io.in.bits.index;last:=io.in.bits.last;scan:=0.U;state:=sScan}}.elsewhen(state===sScan){when(scan>=count||cand<values(scan)){ins:=scan;shift:=count;state:=sShift}.otherwise{scan:=scan+1.U}}.elsewhen(state===sShift){when(shift>ins){when(shift<maxItems.U){values(shift):=values(shift-1.U)};shift:=shift-1.U}.otherwise{when(ins<maxItems.U){values(ins):=cand};when(count<maxItems.U){count:=count+1.U};when(last){emit:=0.U;state:=sEmit}.otherwise{state:=sAccept}}}.elsewhen(state===sEmit){when(io.out.fire){when(emit+1.U>=count){state:=sIdle;done:=true.B}.otherwise{emit:=emit+1.U}}}
}

class HeteroTokenItem(val tokenBits:Int=32) extends Bundle {val token=UInt(tokenBits.W);val last=Bool();override def cloneType:this.type=new HeteroTokenItem(tokenBits).asInstanceOf[this.type]}
class HeteroGatherRun(val tokenBits:Int=32,val countBits:Int=16) extends Bundle {val firstToken=UInt(tokenBits.W);val tokenCount=UInt(countBits.W);val page=UInt(tokenBits.W);val last=Bool();override def cloneType:this.type=new HeteroGatherRun(tokenBits,countBits).asInstanceOf[this.type]}
class HeteroSparseGatherRunCoalescer(val tokenBits:Int=32,val countBits:Int=16) extends Module {
  val io=IO(new Bundle{val start=Input(Bool());val pageTokens=Input(UInt(countBits.W));val in=Flipped(Decoupled(new HeteroTokenItem(tokenBits)));val out=Decoupled(new HeteroGatherRun(tokenBits,countBits));val busy=Output(Bool());val done=Output(Bool())});val sIdle::sCollect::sEmit::Nil=Enum(3);val state=RegInit(sIdle);val pt=RegInit(1.U(countBits.W));val valid=RegInit(false.B);val first=Reg(UInt(tokenBits.W));val lastTok=Reg(UInt(tokenBits.W));val count=Reg(UInt(countBits.W));val finalRun=RegInit(false.B);val pending=RegInit(false.B);val pendTok=Reg(UInt(tokenBits.W));val pendLast=RegInit(false.B);val done=RegInit(false.B);val runPage=first/pt;val inPage=io.in.bits.token/pt;val cont=io.in.bits.token===lastTok+1.U&&inPage===runPage
  io.in.ready:=state===sCollect&&!pending;io.out.valid:=state===sEmit&&valid;io.out.bits.firstToken:=first;io.out.bits.tokenCount:=count;io.out.bits.page:=runPage;io.out.bits.last:=finalRun&&!pending;io.busy:=state=/=sIdle;io.done:=done;done:=false.B
  when(state===sIdle){when(io.start){pt:=Mux(io.pageTokens===0.U,1.U,io.pageTokens);valid:=false.B;pending:=false.B;state:=sCollect}}.elsewhen(state===sCollect){when(io.in.fire){when(!valid){valid:=true.B;first:=io.in.bits.token;lastTok:=io.in.bits.token;count:=1.U;finalRun:=io.in.bits.last;when(io.in.bits.last){state:=sEmit}}.elsewhen(cont){lastTok:=io.in.bits.token;count:=count+1.U;finalRun:=io.in.bits.last;when(io.in.bits.last){state:=sEmit}}.otherwise{pending:=true.B;pendTok:=io.in.bits.token;pendLast:=io.in.bits.last;finalRun:=false.B;state:=sEmit}}}.elsewhen(state===sEmit){when(io.out.fire){when(pending){first:=pendTok;lastTok:=pendTok;count:=1.U;finalRun:=pendLast;pending:=false.B;when(!pendLast){state:=sCollect}}.otherwise{valid:=false.B;state:=sIdle;done:=true.B}}}
}

class HeteroMtpTokenPair(val tokenBits:Int=20) extends Bundle {val draftToken=UInt(tokenBits.W);val targetToken=UInt(tokenBits.W);val last=Bool();override def cloneType:this.type=new HeteroMtpTokenPair(tokenBits).asInstanceOf[this.type]}
class HeteroMtpDecision(val countBits:Int=8,val domainBits:Int=16,val generationBits:Int=16) extends Bundle {val acceptedPrefix=UInt(countBits.W);val comparedTokens=UInt(countBits.W);val rollbackTokens=UInt(countBits.W);val mismatch=Bool();val commitDomainMask=UInt(domainBits.W);val rollbackDomainMask=UInt(domainBits.W);val nextGeneration=UInt(generationBits.W);override def cloneType:this.type=new HeteroMtpDecision(countBits,domainBits,generationBits).asInstanceOf[this.type]}
class HeteroMtpVerifyCommit(val tokenBits:Int=20,val maxDraftTokens:Int=16,val domainBits:Int=16,val generationBits:Int=16) extends Module {
  private val cb=math.max(1,log2Ceil(maxDraftTokens+1));val io=IO(new Bundle{val start=Input(Bool());val domainMask=Input(UInt(domainBits.W));val generation=Input(UInt(generationBits.W));val in=Flipped(Decoupled(new HeteroMtpTokenPair(tokenBits)));val out=Decoupled(new HeteroMtpDecision(cb,domainBits,generationBits));val busy=Output(Bool());val done=Output(Bool())});val sIdle::sCompare::sEmit::Nil=Enum(3);val state=RegInit(sIdle);val acc=RegInit(0.U(cb.W));val cmp=RegInit(0.U(cb.W));val mismatch=RegInit(false.B);val dm=Reg(UInt(domainBits.W));val gen=Reg(UInt(generationBits.W));val done=RegInit(false.B);io.in.ready:=state===sCompare;io.out.valid:=state===sEmit;io.out.bits.acceptedPrefix:=acc;io.out.bits.comparedTokens:=cmp;io.out.bits.rollbackTokens:=cmp-acc;io.out.bits.mismatch:=mismatch;io.out.bits.commitDomainMask:=Mux(acc=/=0.U,dm,0.U);io.out.bits.rollbackDomainMask:=Mux(mismatch,dm,0.U);io.out.bits.nextGeneration:=gen+Mux(mismatch,1.U,0.U);io.busy:=state=/=sIdle;io.done:=done;done:=false.B
  when(state===sIdle){when(io.start){acc:=0.U;cmp:=0.U;mismatch:=false.B;dm:=io.domainMask;gen:=io.generation;state:=sCompare}}.elsewhen(state===sCompare){when(io.in.fire){val equal=io.in.bits.draftToken===io.in.bits.targetToken;when(!mismatch&&equal){acc:=acc+1.U};when(!equal){mismatch:=true.B};cmp:=cmp+1.U;when(io.in.bits.last||cmp+1.U>=maxDraftTokens.U){state:=sEmit}}}.elsewhen(state===sEmit){when(io.out.fire){state:=sIdle;done:=true.B}}
}
