package gemmini

import chisel3._
import chisel3.util._

class HeteroMtpStateAction(val descriptorBits: Int = 24, val dimensionBits: Int = 16, val tagBits: Int = 16, val domainBits: Int = 16, val generationBits: Int = 16, val countBits: Int = 8) extends Module {
  val io = IO(new Bundle {
    val start = Flipped(Decoupled(new Bundle { val decision = new HeteroMtpDecision(countBits, domainBits, generationBits); val journalDescriptor = UInt(descriptorBits.W); val tag = UInt(tagBits.W) }))
    val microOp = Decoupled(new HeteroTensorMicroOp(descriptorBits, dimensionBits, tagBits)); val completion = Flipped(Decoupled(new HeteroPrimitiveCompletion(tagBits))); val result = Decoupled(new HeteroOperatorResult(tagBits)); val busy = Output(Bool()); val protocolError = Output(Bool()) })
  val sIdle::sIssueCommit::sWaitCommit::sIssueRollback::sWaitRollback::sResult::Nil=Enum(6); val state=RegInit(sIdle); val decision=Reg(new HeteroMtpDecision(countBits,domainBits,generationBits)); val journal=Reg(UInt(descriptorBits.W)); val tag=Reg(UInt(tagBits.W)); val status=RegInit(0.U(8.W)); val completed=RegInit(0.U(16.W)); val protocolError=RegInit(false.B); val needRollback=decision.mismatch&&decision.rollbackDomainMask=/=0.U
  io.start.ready:=state===sIdle;io.microOp.valid:=state===sIssueCommit||state===sIssueRollback;io.microOp.bits:=0.U.asTypeOf(io.microOp.bits);io.microOp.bits.kind:=Mux(state===sIssueRollback,HeteroPrimitiveKind.StateRollback,HeteroPrimitiveKind.StateCommit);io.microOp.bits.phase:=Mux(state===sIssueRollback,1.U,0.U);io.microOp.bits.flags:=Mux(state===sIssueRollback,(1<<HeteroPrimitiveFlags.Stateful|1<<HeteroPrimitiveFlags.Rollback).U,(1<<HeteroPrimitiveFlags.Stateful|1<<HeteroPrimitiveFlags.Commit).U);io.microOp.bits.src0:=journal;io.microOp.bits.dst:=journal;io.microOp.bits.m:=decision.acceptedPrefix;io.microOp.bits.n:=decision.rollbackTokens;io.microOp.bits.index0:=decision.nextGeneration;io.microOp.bits.index1:=Mux(state===sIssueRollback,decision.rollbackDomainMask,decision.commitDomainMask);io.microOp.bits.tag:=tag;io.completion.ready:=state===sWaitCommit||state===sWaitRollback;io.result.valid:=state===sResult;io.result.bits.tag:=tag;io.result.bits.status:=status;io.result.bits.completedSteps:=completed;io.busy:=state=/=sIdle;io.protocolError:=protocolError
  when(state===sIdle){when(io.start.fire){decision:=io.start.bits.decision;journal:=io.start.bits.journalDescriptor;tag:=io.start.bits.tag;status:=0.U;completed:=0.U;protocolError:=false.B;when(io.start.bits.decision.acceptedPrefix=/=0.U&&io.start.bits.decision.commitDomainMask=/=0.U){state:=sIssueCommit}.elsewhen(io.start.bits.decision.mismatch&&io.start.bits.decision.rollbackDomainMask=/=0.U){state:=sIssueRollback}.otherwise{state:=sResult}}}.elsewhen(state===sIssueCommit){when(io.microOp.fire){state:=sWaitCommit}}.elsewhen(state===sWaitCommit){when(io.completion.fire){val tagMatches=io.completion.bits.tag===tag;val nextStatus=Mux(tagMatches,io.completion.bits.status,"hfe".U);completed:=completed+1.U;when(!tagMatches){protocolError:=true.B};when(nextStatus=/=0.U){status:=nextStatus;state:=sResult}.elsewhen(needRollback){state:=sIssueRollback}.otherwise{state:=sResult}}}.elsewhen(state===sIssueRollback){when(io.microOp.fire){state:=sWaitRollback}}.elsewhen(state===sWaitRollback){when(io.completion.fire){val tagMatches=io.completion.bits.tag===tag;status:=Mux(tagMatches,io.completion.bits.status,"hfe".U);completed:=completed+1.U;when(!tagMatches){protocolError:=true.B};state:=sResult}}.elsewhen(state===sResult){when(io.result.fire){state:=sIdle}}
}

class HeteroVisionEncoderLoopController(val maxDepth:Int=64,val layerBits:Int=6) extends Module {require(maxDepth>=1);require((1<<layerBits)>=maxDepth);val io=IO(new Bundle{val start=Input(Bool());val depth=Input(UInt(layerBits.W));val stageValid=Output(Bool());val stageReady=Input(Bool());val stage=Output(UInt(2.W));val layer=Output(UInt(layerBits.W));val busy=Output(Bool());val done=Output(Bool());val invalidDepth=Output(Bool())});val sIdle::sPatch::sBlocks::sMerge::Nil=Enum(4);val state=RegInit(sIdle);val depth=Reg(UInt(layerBits.W));val layer=Reg(UInt(layerBits.W));val donePulse=RegInit(false.B);val invalidDepth=RegInit(false.B);io.stageValid:=state=/=sIdle;io.stage:=Mux(state===sPatch,0.U,Mux(state===sBlocks,1.U,2.U));io.layer:=layer;io.busy:=state=/=sIdle;io.done:=donePulse;io.invalidDepth:=invalidDepth;donePulse:=false.B;when(state===sIdle){when(io.start){val valid=io.depth=/=0.U&&io.depth<=maxDepth.U;invalidDepth:=!valid;depth:=Mux(valid,io.depth,1.U);layer:=0.U;state:=sPatch}}.elsewhen(io.stageValid&&io.stageReady){when(state===sPatch){layer:=0.U;state:=sBlocks}.elsewhen(state===sBlocks){when(layer+1.U>=depth){state:=sMerge}.otherwise{layer:=layer+1.U}}.otherwise{state:=sIdle;donePulse:=true.B}}}

object HeteroModelStage {val Width=5;val InputNorm=0.U(Width.W);val Gdn=1.U(Width.W);val DenseAttention=2.U(Width.W);val Qsa=3.U(Width.W);val Ple=4.U(Width.W);val GatedResidualRead=5.U(Width.W);val GatedResidualWrite=6.U(Width.W);val ResidualAdd=7.U(Width.W);val PostNorm=8.U(Width.W);val Moe=9.U(Width.W);val FinalNorm=10.U(Width.W)}
class HeteroQwen35LayerController extends Module {val io=IO(new Bundle{val start=Input(Bool());val fullAttention=Input(Bool());val stageValid=Output(Bool());val stageReady=Input(Bool());val stage=Output(UInt(HeteroModelStage.Width.W));val busy=Output(Bool());val done=Output(Bool())});val sIdle::sInputNorm::sMixer::sResidual0::sPostNorm::sMoe::sResidual1::Nil=Enum(7);val state=RegInit(sIdle);val fullAttention=RegInit(false.B);val donePulse=RegInit(false.B);io.stageValid:=state=/=sIdle;io.stage:=MuxLookup(state,HeteroModelStage.InputNorm)(Seq(sInputNorm->HeteroModelStage.InputNorm,sMixer->Mux(fullAttention,HeteroModelStage.DenseAttention,HeteroModelStage.Gdn),sResidual0->HeteroModelStage.ResidualAdd,sPostNorm->HeteroModelStage.PostNorm,sMoe->HeteroModelStage.Moe,sResidual1->HeteroModelStage.ResidualAdd));io.busy:=state=/=sIdle;io.done:=donePulse;donePulse:=false.B;when(state===sIdle){when(io.start){fullAttention:=io.fullAttention;state:=sInputNorm}}.elsewhen(io.stageValid&&io.stageReady){switch(state){is(sInputNorm){state:=sMixer};is(sMixer){state:=sResidual0};is(sResidual0){state:=sPostNorm};is(sPostNorm){state:=sMoe};is(sMoe){state:=sResidual1};is(sResidual1){state:=sIdle;donePulse:=true.B}}}}
class HeteroQwen38LayerController extends Module {val io=IO(new Bundle{val start=Input(Bool());val usePle=Input(Bool());val qsaLayer=Input(Bool());val stageValid=Output(Bool());val stageReady=Input(Bool());val stage=Output(UInt(HeteroModelStage.Width.W));val busy=Output(Bool());val done=Output(Bool())});val sIdle::sPle::sRead0::sNorm0::sMixer::sWrite0::sRead1::sNorm1::sMoe::sWrite1::Nil=Enum(10);val state=RegInit(sIdle);val usePle=RegInit(false.B);val qsaLayer=RegInit(false.B);val donePulse=RegInit(false.B);io.stageValid:=state=/=sIdle;io.stage:=MuxLookup(state,HeteroModelStage.Ple)(Seq(sPle->HeteroModelStage.Ple,sRead0->HeteroModelStage.GatedResidualRead,sNorm0->HeteroModelStage.InputNorm,sMixer->Mux(qsaLayer,HeteroModelStage.Qsa,HeteroModelStage.Gdn),sWrite0->HeteroModelStage.GatedResidualWrite,sRead1->HeteroModelStage.GatedResidualRead,sNorm1->HeteroModelStage.PostNorm,sMoe->HeteroModelStage.Moe,sWrite1->HeteroModelStage.GatedResidualWrite));io.busy:=state=/=sIdle;io.done:=donePulse;donePulse:=false.B;when(state===sIdle){when(io.start){usePle:=io.usePle;qsaLayer:=io.qsaLayer;state:=Mux(io.usePle,sPle,sRead0)}}.elsewhen(io.stageValid&&io.stageReady){switch(state){is(sPle){state:=sRead0};is(sRead0){state:=sNorm0};is(sNorm0){state:=sMixer};is(sMixer){state:=sWrite0};is(sWrite0){state:=sRead1};is(sRead1){state:=sNorm1};is(sNorm1){state:=sMoe};is(sMoe){state:=sWrite1};is(sWrite1){state:=sIdle;donePulse:=true.B}}}}
