// SPDX-License-Identifier: Apache-2.0
// One fully-elastic fused BF16 SiLU(gate)*up lane. The 128-entry ROM stores
// FP16 SiLU values on an inclusive [-8,8] grid. Interpolation and the final
// product use shared generated FP32 add/mul pipelines; no exp/reciprocal path.
module bf16_silu_mul_lut_lane#(parameter integer TAG_W=12,parameter integer META_FIFO_DEPTH=8,localparam integer FRONT_W=32+32+32+32+5+TAG_W+1,localparam integer META0_W=32+32+32+5+TAG_W+1,localparam integer META1_W=32+32+5+TAG_W+1,localparam integer META2_W=32+5+TAG_W+1,localparam integer META3_W=5+TAG_W+1)(input logic clk_i,rst_ni,in_valid_i,output logic in_ready_o,input logic[15:0]gate_bf16_i,up_bf16_i,input logic[TAG_W-1:0]tag_i,input logic last_i,output logic out_valid_o,input logic out_ready_i,output logic[15:0]result_bf16_o,output logic[TAG_W-1:0]tag_o,output logic last_o,output logic[4:0]exception_flags_o);
 `include "bf16_silu_lut_128.svh"
 logic[31:0]gate_fp32,up_fp32,y0_fp32,y1_fp32,fraction_fp32;logic signed[18:0]gate_q12;logic[16:0]shifted_q12;logic[23:0]scaled_position;logic[18:0]position_q12;logic[6:0]lut_index;logic[11:0]fraction_q12;logic gate_nan,gate_zero;
 logic delta_in_valid,delta_in_ready,delta_out_valid,delta_out_ready;logic[31:0]delta_out;logic[4:0]delta_flags;logic interp_in_valid,interp_in_ready,interp_out_valid,interp_out_ready;logic[31:0]interp_out;logic[4:0]interp_flags;logic silu_in_valid,silu_in_ready,silu_out_valid,silu_out_ready;logic[31:0]silu_out;logic[4:0]silu_flags;logic product_in_valid,product_in_ready,product_out_valid,product_out_ready;logic[31:0]product_out;logic[4:0]product_flags;
 logic meta0_in_valid,meta0_in_ready,meta0_out_valid,meta0_out_ready;logic[META0_W-1:0]meta0_in_data,meta0_out_data;logic meta1_in_valid,meta1_in_ready,meta1_out_valid,meta1_out_ready;logic[META1_W-1:0]meta1_in_data,meta1_out_data;logic meta2_in_valid,meta2_in_ready,meta2_out_valid,meta2_out_ready;logic[META2_W-1:0]meta2_in_data,meta2_out_data;logic meta3_in_valid,meta3_in_ready,meta3_out_valid,meta3_out_ready;logic[META3_W-1:0]meta3_in_data,meta3_out_data;
 logic front_in_ready,front_out_valid,front_out_ready;logic[FRONT_W-1:0]front_in_data,front_out_data;logic[31:0]front_y0,front_y1,front_fraction,front_up;logic[4:0]front_flags;logic[TAG_W-1:0]front_tag;logic front_last;
 logic[3:0]front_level_unused,meta0_level_unused,meta1_level_unused,meta2_level_unused,meta3_level_unused;logic delta_user_unused,interp_user_unused,silu_user_unused,product_user_unused;
 logic[31:0]meta0_y0,meta0_fraction,meta0_up;logic[4:0]meta0_flags;logic[TAG_W-1:0]meta0_tag;logic meta0_last;logic[31:0]meta1_y0,meta1_up;logic[4:0]meta1_flags;logic[TAG_W-1:0]meta1_tag;logic meta1_last;logic[31:0]meta2_up;logic[4:0]meta2_flags;logic[TAG_W-1:0]meta2_tag;logic meta2_last;logic[4:0]meta3_flags;logic[TAG_W-1:0]meta3_tag;logic meta3_last;
 function automatic logic[31:0]fp16_to_fp32(input logic[15:0]value);logic sign;logic[4:0]exponent;logic[9:0]fraction;logic[31:0]normalized;integer msb,index;begin sign=value[15];exponent=value[14:10];fraction=value[9:0];if(exponent==0)begin if(fraction==0)fp16_to_fp32={sign,31'b0};else begin msb=-1;for(index=9;index>=0;index=index-1)if((msb<0)&&fraction[index])msb=index;normalized={22'b0,fraction}<<(23-msb);fp16_to_fp32={sign,8'(103+msb),normalized[22:0]};end end else if(exponent==5'h1f)fp16_to_fp32={sign,8'hff,fraction,13'b0};else fp16_to_fp32={sign,8'(exponent+112),fraction,13'b0};end endfunction
 function automatic logic signed[18:0]bf16_to_q12_sat(input logic[15:0]value);integer exponent,significand,shift,right_shift,magnitude;integer signed signed_value;begin exponent=value[14:7];significand=128+value[6:0];if(exponent==255)magnitude=32768;else if(exponent==0)magnitude=0;else begin shift=exponent-122;if(shift>=0)magnitude=significand<<shift;else begin right_shift=-shift;if(right_shift>=16)magnitude=0;else magnitude=(significand+(1<<(right_shift-1)))>>right_shift;end if(magnitude>32768)magnitude=32768;end signed_value=value[15]?-magnitude:magnitude;bf16_to_q12_sat=signed_value;end endfunction
 function automatic logic[31:0]fraction_q12_to_fp32(input logic[11:0]value);integer msb,index;logic[34:0]normalized;begin if(value==0)fraction_q12_to_fp32=0;else begin msb=-1;for(index=11;index>=0;index=index-1)if((msb<0)&&value[index])msb=index;normalized={23'b0,value}<<(23-msb);fraction_q12_to_fp32={1'b0,8'(115+msb),normalized[22:0]};end end endfunction
 function automatic logic[31:0]fp32_half(input logic[31:0]value);logic[7:0]exponent;logic[22:0]fraction;logic[23:0]subnormal;begin exponent=value[30:23];fraction=value[22:0];if(exponent==0)fp32_half={value[31],8'd0,1'b0,fraction[22:1]};else if(exponent==1)begin subnormal={1'b1,fraction}>>1;fp32_half={value[31],8'd0,subnormal[22:0]};end else if(exponent==8'hff)fp32_half=value;else fp32_half={value[31],exponent-1'b1,fraction};end endfunction
 function automatic logic[15:0]fp32_to_bf16_rne(input logic[31:0]value);logic[31:0]rounded;logic[15:0]result;begin if((value[30:23]==8'hff)&&(value[22:0]!=0))begin result=value[31:16];result[6]=1'b1;if(result[6:0]==0)result[0]=1'b1;fp32_to_bf16_rne=result;end else begin rounded=value+32'h00007fff+value[16];fp32_to_bf16_rne=rounded[31:16];end end endfunction
 assign gate_fp32={gate_bf16_i,16'b0};assign up_fp32={up_bf16_i,16'b0};assign gate_nan=(gate_bf16_i[14:7]==8'hff)&&(gate_bf16_i[6:0]!=0);assign gate_zero=(gate_bf16_i[14:0]==0);
 always_comb begin gate_q12=bf16_to_q12_sat(gate_bf16_i);shifted_q12=0;scaled_position=0;position_q12=0;lut_index=0;fraction_q12=0;y0_fp32=0;y1_fp32=0;fraction_fp32=0;if(gate_nan)begin y0_fp32=gate_fp32;y1_fp32=gate_fp32;end else if(gate_zero||($signed(gate_q12)<=-19'sd32768))begin y0_fp32=0;y1_fp32=0;end else if($signed(gate_q12)==0)begin y0_fp32=fp32_half(gate_fp32);y1_fp32=fp32_half(gate_fp32);end else if($signed(gate_q12)>=19'sd32768)begin y0_fp32=gate_fp32;y1_fp32=gate_fp32;end else begin shifted_q12=17'($signed(gate_q12)+19'sd32768);scaled_position=shifted_q12*7'd127;position_q12=scaled_position>>4;lut_index=position_q12[18:12];if(lut_index>=127)lut_index=126;fraction_q12=position_q12[11:0];y0_fp32=fp16_to_fp32(bf16_silu_lut_fp16(lut_index));y1_fp32=fp16_to_fp32(bf16_silu_lut_fp16(lut_index+1'b1));fraction_fp32=fraction_q12_to_fp32(fraction_q12);end end
 rv_fifo#(.WIDTH(FRONT_W),.DEPTH(META_FIFO_DEPTH))front_fifo(.clk_i(clk_i),.rst_ni(rst_ni),.in_valid_i(in_valid_i),.in_ready_o(front_in_ready),.in_data_i(front_in_data),.out_valid_o(front_out_valid),.out_ready_i(front_out_ready),.out_data_o(front_out_data),.level_o(front_level_unused));rv_fifo#(.WIDTH(META0_W),.DEPTH(META_FIFO_DEPTH))m0(.clk_i(clk_i),.rst_ni(rst_ni),.in_valid_i(meta0_in_valid),.in_ready_o(meta0_in_ready),.in_data_i(meta0_in_data),.out_valid_o(meta0_out_valid),.out_ready_i(meta0_out_ready),.out_data_o(meta0_out_data),.level_o(meta0_level_unused));rv_fifo#(.WIDTH(META1_W),.DEPTH(META_FIFO_DEPTH))m1(.clk_i(clk_i),.rst_ni(rst_ni),.in_valid_i(meta1_in_valid),.in_ready_o(meta1_in_ready),.in_data_i(meta1_in_data),.out_valid_o(meta1_out_valid),.out_ready_i(meta1_out_ready),.out_data_o(meta1_out_data),.level_o(meta1_level_unused));rv_fifo#(.WIDTH(META2_W),.DEPTH(META_FIFO_DEPTH))m2(.clk_i(clk_i),.rst_ni(rst_ni),.in_valid_i(meta2_in_valid),.in_ready_o(meta2_in_ready),.in_data_i(meta2_in_data),.out_valid_o(meta2_out_valid),.out_ready_i(meta2_out_ready),.out_data_o(meta2_out_data),.level_o(meta2_level_unused));rv_fifo#(.WIDTH(META3_W),.DEPTH(META_FIFO_DEPTH))m3(.clk_i(clk_i),.rst_ni(rst_ni),.in_valid_i(meta3_in_valid),.in_ready_o(meta3_in_ready),.in_data_i(meta3_in_data),.out_valid_o(meta3_out_valid),.out_ready_i(meta3_out_ready),.out_data_o(meta3_out_data),.level_o(meta3_level_unused));
 assign front_in_data={last_i,tag_i,5'b0,up_fp32,fraction_fp32,y1_fp32,y0_fp32};assign{front_last,front_tag,front_flags,front_up,front_fraction,front_y1,front_y0}=front_out_data;assign in_ready_o=front_in_ready;assign front_out_ready=delta_in_ready&&meta0_in_ready;assign delta_in_valid=front_out_valid&&meta0_in_ready;assign meta0_in_valid=front_out_valid&&delta_in_ready;assign meta0_in_data={front_last,front_tag,front_flags,front_up,front_fraction,front_y0};
 HeteroFP32AddPipeBit1 delta_add(.clock(clk_i),.reset(!rst_ni),.io_inValid(delta_in_valid),.io_inReady(delta_in_ready),.io_x(front_y1),.io_y({~front_y0[31],front_y0[30:0]}),.io_userIn(front_last),.io_outValid(delta_out_valid),.io_outReady(delta_out_ready),.io_out(delta_out),.io_exceptionFlags(delta_flags),.io_userOut(delta_user_unused));
 assign{meta0_last,meta0_tag,meta0_flags,meta0_up,meta0_fraction,meta0_y0}=meta0_out_data;assign interp_in_valid=delta_out_valid&&meta0_out_valid&&meta1_in_ready;assign meta1_in_valid=delta_out_valid&&meta0_out_valid&&interp_in_ready;assign delta_out_ready=meta0_out_valid&&interp_in_ready&&meta1_in_ready;assign meta0_out_ready=delta_out_valid&&interp_in_ready&&meta1_in_ready;assign meta1_in_data={meta0_last,meta0_tag,meta0_flags|delta_flags,meta0_up,meta0_y0};
 HeteroFP32MulPipeBit1 interp_mul(.clock(clk_i),.reset(!rst_ni),.io_inValid(interp_in_valid),.io_inReady(interp_in_ready),.io_x(delta_out),.io_y(meta0_fraction),.io_userIn(meta0_last),.io_outValid(interp_out_valid),.io_outReady(interp_out_ready),.io_out(interp_out),.io_exceptionFlags(interp_flags),.io_userOut(interp_user_unused));
 assign{meta1_last,meta1_tag,meta1_flags,meta1_up,meta1_y0}=meta1_out_data;assign silu_in_valid=interp_out_valid&&meta1_out_valid&&meta2_in_ready;assign meta2_in_valid=interp_out_valid&&meta1_out_valid&&silu_in_ready;assign interp_out_ready=meta1_out_valid&&silu_in_ready&&meta2_in_ready;assign meta1_out_ready=interp_out_valid&&silu_in_ready&&meta2_in_ready;assign meta2_in_data={meta1_last,meta1_tag,meta1_flags|interp_flags,meta1_up};
 HeteroFP32AddPipeBit1 silu_add(.clock(clk_i),.reset(!rst_ni),.io_inValid(silu_in_valid),.io_inReady(silu_in_ready),.io_x(meta1_y0),.io_y(interp_out),.io_userIn(meta1_last),.io_outValid(silu_out_valid),.io_outReady(silu_out_ready),.io_out(silu_out),.io_exceptionFlags(silu_flags),.io_userOut(silu_user_unused));
 assign{meta2_last,meta2_tag,meta2_flags,meta2_up}=meta2_out_data;assign product_in_valid=silu_out_valid&&meta2_out_valid&&meta3_in_ready;assign meta3_in_valid=silu_out_valid&&meta2_out_valid&&product_in_ready;assign silu_out_ready=meta2_out_valid&&product_in_ready&&meta3_in_ready;assign meta2_out_ready=silu_out_valid&&product_in_ready&&meta3_in_ready;assign meta3_in_data={meta2_last,meta2_tag,meta2_flags|silu_flags};
 HeteroFP32MulPipeBit1 product_mul(.clock(clk_i),.reset(!rst_ni),.io_inValid(product_in_valid),.io_inReady(product_in_ready),.io_x(silu_out),.io_y(meta2_up),.io_userIn(meta2_last),.io_outValid(product_out_valid),.io_outReady(product_out_ready),.io_out(product_out),.io_exceptionFlags(product_flags),.io_userOut(product_user_unused));
 assign{meta3_last,meta3_tag,meta3_flags}=meta3_out_data;assign out_valid_o=product_out_valid&&meta3_out_valid;assign product_out_ready=out_ready_i&&meta3_out_valid;assign meta3_out_ready=out_ready_i&&product_out_valid;assign result_bf16_o=fp32_to_bf16_rne(product_out);assign tag_o=meta3_tag;assign last_o=meta3_last;assign exception_flags_o=meta3_flags|product_flags;
`ifndef SYNTHESIS
 initial begin assert(TAG_W>0);assert(META_FIFO_DEPTH>=4);end
`endif
endmodule
