// SPDX-License-Identifier: Apache-2.0
// Candidate coefficient path using internally-pipelined HardFloat multipliers
// and adder. The proven canonical module remains unchanged until local E1/E4.
module fp32_mlo_merge_coeff_rawpipe(
 input logic clk_i,rst_ni,in_valid_i,output logic in_ready_o,
 input logic [31:0] ma_i,la_i,mb_i,lb_i,
 output logic out_valid_o,input logic out_ready_i,
 output logic [31:0] m_o,l_o,alpha_o,beta_o,output logic [4:0] flags_o);
 typedef enum logic[3:0]{IDLE,SUBTRACT,SCALE_ISSUE,SCALE_WAIT,EXP_ISSUE,EXP_WAIT,LMUL_ISSUE,LMUL_WAIT,LADD_ISSUE,LADD_WAIT,OUT}state_t;state_t state_q;
 logic[31:0] ma_q,la_q,mb_q,lb_q,m_new_q,delta_a,delta_b,delta_a_q,delta_b_q,delta2_a_q,delta2_b_q,alpha_q,beta_q,product_a_q,product_b_q;logic[4:0] flags_q,sub_flags_a,sub_flags_b;
 logic scale_fire,scale_consume,scale_a_ready,scale_b_ready,scale_a_valid,scale_b_valid;logic[31:0] scale_a_out,scale_b_out;logic[4:0] scale_a_flags,scale_b_flags;logic[11:0] scale_a_tag,scale_b_tag;
 logic exp_fire,exp_consume,exp_a_ready,exp_b_ready,exp_a_valid,exp_b_valid;logic[31:0] exp_a_out,exp_b_out;logic[12:0] exp_a_flags,exp_b_flags;logic[31:0] exp_a_accepted,exp_b_accepted,exp_a_completed,exp_b_completed;
 logic lmul_fire,lmul_consume,lmul_a_ready,lmul_b_ready,lmul_a_valid,lmul_b_valid;logic[31:0] lmul_a_out,lmul_b_out;logic[4:0] lmul_a_flags,lmul_b_flags;logic[11:0] lmul_a_tag,lmul_b_tag;
 logic ladd_fire,ladd_ready,ladd_valid;logic[31:0] ladd_out;logic[4:0] ladd_flags;logic[11:0] ladd_tag;
 function automatic logic fp32_gt(input logic[31:0]a,input logic[31:0]b);if(a[31]!=b[31])fp32_gt=!a[31];else if(!a[31])fp32_gt=a[30:0]>b[30:0];else fp32_gt=a[30:0]<b[30:0];endfunction
 HeteroFP32Alu sub_a(.io_op(1'b0),.io_x(ma_q),.io_y({~m_new_q[31],m_new_q[30:0]}),.io_out(delta_a),.io_exceptionFlags(sub_flags_a));HeteroFP32Alu sub_b(.io_op(1'b0),.io_x(mb_q),.io_y({~m_new_q[31],m_new_q[30:0]}),.io_out(delta_b),.io_exceptionFlags(sub_flags_b));
 assign scale_fire=state_q==SCALE_ISSUE&&scale_a_ready&&scale_b_ready;assign scale_consume=state_q==SCALE_WAIT&&scale_a_valid&&scale_b_valid;
 HeteroFP32MulPipeTag12 scale_a(.clock(clk_i),.reset(!rst_ni),.io_inValid(scale_fire),.io_inReady(scale_a_ready),.io_x(delta_a_q),.io_y(32'h3fb8aa3b),.io_userIn(12'd0),.io_outValid(scale_a_valid),.io_outReady(scale_consume),.io_out(scale_a_out),.io_exceptionFlags(scale_a_flags),.io_userOut(scale_a_tag));
 HeteroFP32MulPipeTag12 scale_b(.clock(clk_i),.reset(!rst_ni),.io_inValid(scale_fire),.io_inReady(scale_b_ready),.io_x(delta_b_q),.io_y(32'h3fb8aa3b),.io_userIn(12'd0),.io_outValid(scale_b_valid),.io_outReady(scale_consume),.io_out(scale_b_out),.io_exceptionFlags(scale_b_flags),.io_userOut(scale_b_tag));
 assign exp_fire=state_q==EXP_ISSUE&&exp_a_ready&&exp_b_ready;assign exp_consume=state_q==EXP_WAIT&&exp_a_valid&&exp_b_valid;
 fp32_exp2_pwl exp_a(.clk_i,.rst_ni,.in_valid_i(exp_fire),.in_ready_o(exp_a_ready),.x_i(delta2_a_q),.out_valid_o(exp_a_valid),.out_ready_i(exp_consume),.y_o(exp_a_out),.exception_flags_o(exp_a_flags),.accepted_o(exp_a_accepted),.completed_o(exp_a_completed));fp32_exp2_pwl exp_b(.clk_i,.rst_ni,.in_valid_i(exp_fire),.in_ready_o(exp_b_ready),.x_i(delta2_b_q),.out_valid_o(exp_b_valid),.out_ready_i(exp_consume),.y_o(exp_b_out),.exception_flags_o(exp_b_flags),.accepted_o(exp_b_accepted),.completed_o(exp_b_completed));
 assign lmul_fire=state_q==LMUL_ISSUE&&lmul_a_ready&&lmul_b_ready;assign lmul_consume=state_q==LMUL_WAIT&&lmul_a_valid&&lmul_b_valid;
 HeteroFP32MulPipeTag12 lmul_a(.clock(clk_i),.reset(!rst_ni),.io_inValid(lmul_fire),.io_inReady(lmul_a_ready),.io_x(la_q),.io_y(alpha_q),.io_userIn(12'd0),.io_outValid(lmul_a_valid),.io_outReady(lmul_consume),.io_out(lmul_a_out),.io_exceptionFlags(lmul_a_flags),.io_userOut(lmul_a_tag));HeteroFP32MulPipeTag12 lmul_b(.clock(clk_i),.reset(!rst_ni),.io_inValid(lmul_fire),.io_inReady(lmul_b_ready),.io_x(lb_q),.io_y(beta_q),.io_userIn(12'd0),.io_outValid(lmul_b_valid),.io_outReady(lmul_consume),.io_out(lmul_b_out),.io_exceptionFlags(lmul_b_flags),.io_userOut(lmul_b_tag));
 assign ladd_fire=state_q==LADD_ISSUE&&ladd_ready;HeteroFP32AddPipeTag12 ladd(.clock(clk_i),.reset(!rst_ni),.io_inValid(ladd_fire),.io_inReady(ladd_ready),.io_x(product_a_q),.io_y(product_b_q),.io_userIn(12'd0),.io_outValid(ladd_valid),.io_outReady(state_q==LADD_WAIT),.io_out(ladd_out),.io_exceptionFlags(ladd_flags),.io_userOut(ladd_tag));
 assign in_ready_o=state_q==IDLE;assign out_valid_o=state_q==OUT;assign flags_o=flags_q;
 always_ff@(posedge clk_i or negedge rst_ni)begin if(!rst_ni)begin state_q<=IDLE;ma_q<='0;la_q<='0;mb_q<='0;lb_q<='0;m_new_q<='0;delta_a_q<='0;delta_b_q<='0;delta2_a_q<='0;delta2_b_q<='0;alpha_q<='0;beta_q<='0;product_a_q<='0;product_b_q<='0;m_o<='0;l_o<='0;alpha_o<='0;beta_o<='0;flags_q<='0;end else case(state_q)
 IDLE:if(in_valid_i)begin if(la_i[30:0]==0)begin m_o<=mb_i;l_o<=lb_i;alpha_o<=0;beta_o<=32'h3f800000;flags_q<=0;state_q<=OUT;end else if(lb_i[30:0]==0)begin m_o<=ma_i;l_o<=la_i;alpha_o<=32'h3f800000;beta_o<=0;flags_q<=0;state_q<=OUT;end else begin ma_q<=ma_i;la_q<=la_i;mb_q<=mb_i;lb_q<=lb_i;m_new_q<=fp32_gt(mb_i,ma_i)?mb_i:ma_i;flags_q<=0;state_q<=SUBTRACT;end end
 SUBTRACT:begin delta_a_q<=delta_a;delta_b_q<=delta_b;flags_q<=sub_flags_a|sub_flags_b;state_q<=SCALE_ISSUE;end SCALE_ISSUE:if(scale_fire)state_q<=SCALE_WAIT;SCALE_WAIT:if(scale_consume)begin delta2_a_q<=scale_a_out;delta2_b_q<=scale_b_out;flags_q<=flags_q|scale_a_flags|scale_b_flags;state_q<=EXP_ISSUE;end EXP_ISSUE:if(exp_fire)state_q<=EXP_WAIT;EXP_WAIT:if(exp_consume)begin alpha_q<=exp_a_out;beta_q<=exp_b_out;m_o<=m_new_q;alpha_o<=exp_a_out;beta_o<=exp_b_out;flags_q<=flags_q|exp_a_flags[4:0]|exp_b_flags[4:0];state_q<=LMUL_ISSUE;end LMUL_ISSUE:if(lmul_fire)state_q<=LMUL_WAIT;LMUL_WAIT:if(lmul_consume)begin product_a_q<=lmul_a_out;product_b_q<=lmul_b_out;flags_q<=flags_q|lmul_a_flags|lmul_b_flags;state_q<=LADD_ISSUE;end LADD_ISSUE:if(ladd_fire)state_q<=LADD_WAIT;LADD_WAIT:if(ladd_valid)begin l_o<=ladd_out;flags_q<=flags_q|ladd_flags;state_q<=OUT;end OUT:if(out_ready_i)state_q<=IDLE;default:state_q<=IDLE;endcase end
endmodule
