package gemmini

import chisel3._
import chisel3.util._

object HeteroQwen2DecoderBlockProgram { import HeteroMicroInstruction.flag; import HeteroPrimitiveCode._; val program:Seq[HeteroMicroInstruction]=Seq(
HeteroMicroInstruction(RmsNorm,0x00,src0=0,src1=1,dst=8,m=0,n=1),HeteroMicroInstruction(MatrixGemm,0x01,src0=8,src1=2,dst=6,m=0,n=2,k=1,index0=0),HeteroMicroInstruction(VectorAdd,0x02,flag(HeteroPrimitiveFlags.ApplyBias),src0=6,src1=3,dst=6,m=0,n=2,k=4,index0=0),HeteroMicroInstruction(Rope,0x03,src0=6,src1=4,dst=6,m=0,n=2,k=4,index0=0),HeteroMicroInstruction(MatrixGemm,0x04,src0=8,src1=2,dst=6,m=0,n=3,k=1,index0=1),HeteroMicroInstruction(VectorAdd,0x05,flag(HeteroPrimitiveFlags.ApplyBias),src0=6,src1=3,dst=6,m=0,n=3,k=4,index0=1),HeteroMicroInstruction(Rope,0x06,src0=6,src1=4,dst=6,m=0,n=3,k=4,index0=1),HeteroMicroInstruction(MatrixGemm,0x07,src0=8,src1=2,dst=6,m=0,n=3,k=1,index0=2),HeteroMicroInstruction(VectorAdd,0x08,flag(HeteroPrimitiveFlags.ApplyBias),src0=6,src1=3,dst=6,m=0,n=3,k=4,index0=2),HeteroMicroInstruction(KvAppend,0x09,flag(HeteroPrimitiveFlags.Stateful),src0=6,dst=5,m=0,n=3,k=4),HeteroMicroInstruction(MatrixQk,0x0a,flag(HeteroPrimitiveFlags.Causal),src0=6,src1=5,src2=14,dst=6,m=2,n=6,k=4),HeteroMicroInstruction(OnlineSoftmax,0x0b,flag(HeteroPrimitiveFlags.Causal),src0=6,src1=14,dst=6,m=2,n=6),HeteroMicroInstruction(MatrixPv,0x0c,src0=6,src1=5,dst=6,m=2,n=4,k=6),HeteroMicroInstruction(MatrixGemm,0x0d,src0=6,src1=7,dst=8,m=0,n=1,k=1),HeteroMicroInstruction(VectorAdd,0x0e,src0=0,src1=8,dst=8,m=0,n=1),HeteroMicroInstruction(RmsNorm,0x0f,src0=8,src1=9,dst=11,m=0,n=1),HeteroMicroInstruction(MatrixGemm,0x10,src0=11,src1=10,dst=11,m=0,n=5,k=1,index0=0),HeteroMicroInstruction(MatrixGemm,0x11,src0=11,src1=10,dst=6,m=0,n=5,k=1,index0=1),HeteroMicroInstruction(Silu,0x12,src0=11,dst=11,m=0,n=5),HeteroMicroInstruction(VectorMul,0x13,src0=11,src1=6,dst=11,m=0,n=5),HeteroMicroInstruction(MatrixGemm,0x14,src0=11,src1=12,dst=11,m=0,n=1,k=5),HeteroMicroInstruction(VectorAdd,0x15,flag(HeteroPrimitiveFlags.Last),src0=8,src1=11,dst=13,m=0,n=1),HeteroMicroInstruction(StateCommit,0x16,flag(HeteroPrimitiveFlags.Stateful,HeteroPrimitiveFlags.Commit,HeteroPrimitiveFlags.Last),src0=15,dst=15)) }
class HeteroQwen2DecoderBlockOperatorPrimitive(descriptorBits:Int=24,dimensionBits:Int=16,tagBits:Int=16) extends HeteroCompositeOperatorPrimitive(HeteroQwen2DecoderBlockProgram.program,"HeteroQwen2DecoderBlockOperatorPrimitive",descriptorBits,dimensionBits,tagBits)

object HeteroQwen35AttentionProgram { import HeteroMicroInstruction.flag; import HeteroPrimitiveCode._; val program:Seq[HeteroMicroInstruction]=Seq(HeteroMicroInstruction(MatrixGemm,0x00,src0=0,src1=1,dst=6,m=0,n=2,k=1,index0=0),HeteroMicroInstruction(MatrixGemm,0x01,src0=0,src1=1,dst=6,m=0,n=3,k=1,index0=1),HeteroMicroInstruction(MatrixGemm,0x02,src0=0,src1=1,dst=6,m=0,n=3,k=1,index0=2),HeteroMicroInstruction(MatrixGemm,0x03,src0=0,src1=2,dst=7,m=0,n=2,k=1),HeteroMicroInstruction(RmsNorm,0x04,src0=6,src1=3,dst=6,m=0,n=2,k=4,index0=0),HeteroMicroInstruction(RmsNorm,0x05,src0=6,src1=3,dst=6,m=0,n=3,k=4,index0=1),HeteroMicroInstruction(Rope,0x06,flag(HeteroPrimitiveFlags.PartialRotary,HeteroPrimitiveFlags.MropeInterleaved),src0=6,src1=4,dst=6,m=0,n=2,k=4),HeteroMicroInstruction(KvAppend,0x07,flag(HeteroPrimitiveFlags.Stateful),src0=6,dst=5,m=0,n=3,k=4),HeteroMicroInstruction(MatrixQk,0x08,flag(HeteroPrimitiveFlags.Causal),src0=6,src1=5,dst=8,m=2,n=6,k=4),HeteroMicroInstruction(OnlineSoftmax,0x09,flag(HeteroPrimitiveFlags.Causal),src0=8,dst=8,m=2,n=6),HeteroMicroInstruction(MatrixPv,0x0a,src0=8,src1=5,dst=8,m=2,n=4,k=6),HeteroMicroInstruction(Sigmoid,0x0b,src0=7,dst=7,m=0,n=2,k=4),HeteroMicroInstruction(VectorMul,0x0c,src0=8,src1=7,dst=8,m=0,n=2,k=4),HeteroMicroInstruction(MatrixGemm,0x0d,flag(HeteroPrimitiveFlags.Last),src0=8,src1=9,dst=10,m=0,n=1,k=2)) }
class HeteroQwen35DenseAttentionOperatorPrimitive(descriptorBits:Int=24,dimensionBits:Int=16,tagBits:Int=16) extends HeteroCompositeOperatorPrimitive(HeteroQwen35AttentionProgram.program,"HeteroQwen35DenseAttentionOperatorPrimitive",descriptorBits,dimensionBits,tagBits)

object HeteroLanguageModelBoundaryProgram { import HeteroPrimitiveCode._; val program:Seq[HeteroMicroInstruction]=Seq(HeteroMicroInstruction(EmbeddingLookup,0x00,src0=0,src1=1,dst=2,m=0,n=1),HeteroMicroInstruction(RmsNorm,0x01,src0=3,src1=4,dst=5,m=0,n=1),HeteroMicroInstruction(MatrixGemv,0x02,src0=5,src1=6,dst=7,m=0,n=2,k=1),HeteroMicroInstruction(Argmax,0x03,flags=HeteroMicroInstruction.flag(HeteroPrimitiveFlags.Last),src0=7,dst=8,n=2)) }
class HeteroLanguageModelBoundaryOperatorPrimitive(descriptorBits:Int=24,dimensionBits:Int=16,tagBits:Int=16) extends HeteroCompositeOperatorPrimitive(HeteroLanguageModelBoundaryProgram.program,"HeteroLanguageModelBoundaryOperatorPrimitive",descriptorBits,dimensionBits,tagBits)

object HeteroMtpDraftProgram { import HeteroMicroInstruction.flag; import HeteroPrimitiveCode._; val program:Seq[HeteroMicroInstruction]=Seq(HeteroMicroInstruction(StateRead,0x00,flag(HeteroPrimitiveFlags.Stateful),src0=0,dst=1),HeteroMicroInstruction(SubgraphLaunch,0x01,flag(HeteroPrimitiveFlags.Stateful),src0=2,src1=1,dst=3,m=0),HeteroMicroInstruction(MatrixGemv,0x02,src0=3,src1=4,dst=5,m=0,n=1,k=2),HeteroMicroInstruction(Argmax,0x03,src0=5,dst=6,m=0,n=1),HeteroMicroInstruction(SubgraphLaunch,0x04,flag(HeteroPrimitiveFlags.Stateful),src0=7,src1=1,dst=8,m=0),HeteroMicroInstruction(MatrixGemv,0x05,src0=8,src1=9,dst=10,m=0,n=1,k=2),HeteroMicroInstruction(Argmax,0x06,flag(HeteroPrimitiveFlags.Last),src0=10,dst=11,m=0,n=1)) }
class HeteroMtpDraftTargetOperatorPrimitive(descriptorBits:Int=24,dimensionBits:Int=16,tagBits:Int=16) extends HeteroCompositeOperatorPrimitive(HeteroMtpDraftProgram.program,"HeteroMtpDraftTargetOperatorPrimitive",descriptorBits,dimensionBits,tagBits)
