#!/usr/bin/env python3
import hashlib,json,re,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];IDMA=ROOT/'work/upstream/idma'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
log=(ROOT/'work/results/qwen2_pinned_idma_tile/tb.log').read_text();m=re.search(r'QWEN2_PINNED_IDMA_TILE_PASS abstract_requests=(\d+) flat_requests=(\d+) read_beats=(\d+) write_beats=(\d+) max_load_flat_bytes=(\d+) max_store_flat_bytes=(\d+) coalesced_load16=(\d+) coalesced_store16=(\d+) idma_errors=(\d+)',log)
if not m or tuple(map(int,m.groups()))!=(6,2362,3217,3217,1024,64,48,768,0)or'Error:'in log:raise SystemExit('pinned iDMA PASS missing')
commit=subprocess.check_output(['git','-C',str(IDMA),'rev-parse','HEAD'],text=True).strip();dirty=subprocess.check_output(['git','-C',str(IDMA),'status','--porcelain'],text=True).strip()
lock=json.loads((ROOT/'reports/execution/idma_backend_contract_lock.json').read_text());checks={'pinned_commit':commit==lock['idma_commit']=='2e0b0fe53b6f8823319e2428e2e9abc2db149b7d','upstream_clean':not dirty,'abstract_requests':True,'2d_expansion_rows':True,'actual_AXI_beats':True,'zero_errors':True}
if not all(checks.values()):raise SystemExit(f'idma checks:{checks}')
r={'schema_version':1,'status':'PASS_PINNED_IDMA_TILE_TRANSFERS','evidence_class':'actual_pinned_idma_backend_rw_axi_VCS','commit':commit,'checks':checks,'abstract_requests':6,'flat_requests':2362,'read_beats':3217,'write_beats':3217,'q_weight_rows':1536,'max_load_flat_bytes':1024,'max_store_flat_bytes':64,'errors':0,'provenance':{'log_sha256':sha('work/results/qwen2_pinned_idma_tile/tb.log'),'expand_rtl_sha256':sha('rtl/integration/qwen2_tile_idma_expand.sv'),'flat_wrapper_sha256':sha('rtl/integration/idma_backend_rw_axi_flat_wrap.sv'),'contract_lock_sha256':sha('reports/execution/idma_backend_contract_lock.json')},'non_claims':['pinned iDMA VCS uses AXI simulation memory, not the Shared-L2 AXI slave','monolithic tile top still connects through the abstract DMA interface','does not close full layer or P3']};out=ROOT/'reports/execution/qwen2_pinned_idma_tile_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'flat_requests':2362,'beats':3217},sort_keys=True))
