#!/usr/bin/env python3
import hashlib,json,re,subprocess
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'work/results/llama_hetero_full_graph';LOG=OUT/'run.log';text=LOG.read_text();assert'HETERO_GGUF_BIND_PASS tensors=338 tokens=1024 direct_buffers=1'in text;m=re.search(r'LLAMA_HETERO_FULL_GRAPH_PASS nodes=(\d+) splits=(\d+) commands=(\d+) vocab=(\d+) argmax=(\d+) cpu_fallback=(\d+) gguf_model=(\d+)',text);assert m and tuple(map(int,m.groups()))==(958,1,588,151936,7559,0,1);commit=subprocess.check_output(['git','-C',str(ROOT/'work/upstream/llama_cpp'),'rev-parse','HEAD'],text=True).strip();assert commit=='0b5be7e4a25862bc2777d0c47eae18788a8c963a';bound=OUT/'payload/gguf_bound_inputs';accepted=ROOT/'work/results/qwen2_q1024_full28_inputs';parity=[]
for layer in range(28):
 for name in ('input_norm_weight_bf16.bin','q_weight_bf16.bin','q_bias_fp32.bin','k_weight_bf16.bin','k_bias_fp32.bin','v_weight_bf16.bin','v_bias_fp32.bin','oproj_weight_bf16.bin','post_norm_weight_bf16.bin','gate_weight_bf16.bin','up_weight_bf16.bin','down_weight_bf16.bin'):parity.append((bound/f'layer{layer}'/name,accepted/f'layer{layer}'/name))
parity.extend(((bound/'final_head/final_norm_weight_bf16.bin',accepted/'final_head/final_norm_weight_bf16.bin'),(bound/'final_head/lm_head_weight_bf16.bin',accepted/'final_head/lm_head_weight_bf16.bin')))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
assert len(parity)==338 and all(sha(a)==sha(b)for a,b in parity);actual=np.fromfile(OUT/'logits.bin',np.float32);reference=np.fromfile(ROOT/'work/results/llama_cpp_qwen2_baseline/pytorch_logits.bin',np.float32);top=np.argsort(actual)[-10:];rtop=np.argsort(reference)[-10:];overlap=len(set(map(int,top))&set(map(int,rtop)));assert int(actual.argmax())==int(reference.argmax())==7559 and overlap==10
r={'schema_version':1,'status':'PASS_LLAMA_ORIGINAL_GRAPH_DIRECT_GGUF_HETERO_DEVICE','evidence_class':'pinned_llama_decode_dynamic_HETERO_958node_direct_338_GGUF_buffers','llama_cpp_commit':commit,'graph':{'nodes':958,'splits':1,'commands':588,'layers':28,'groups':7,'cpu_fallback':0},'gguf':{'model_loaded':True,'tensors_assigned_HETERO0':338,'direct_buffer_bindings':338,'byte_parity_pass':338,'norm_f32_to_bf16_RNE':57},'output':{'vocab':151936,'argmax':7559,'top10_overlap':10,'logits_sha256':sha(OUT/'logits.bin')},'checks':{'original_llama_graph':True,'direct_GGUF_weight_buffers':True,'embedding_from_inp_tokens_and_GGUF':True,'final_norm_LM_head_in_graph_compute':True,'llama_decode_success':True},'provenance':{'log':sha(LOG),'plugin':sha(OUT/'libggml-hetero.so'),'exported_weight_reference_manifest':sha(accepted/'manifest.json'),'previous_full_graph_report':sha(ROOT/'reports/execution/llama_hetero_full_graph_result.json')},'open':['integrated random-backpressure stress for all seven groups','summary storage macro mapping and real layer5 QK/PV RTL','formal L5.6d final audit'],'non_claims':['direct GGUF device functional PASS is not all-row RTL','summary scheduler PPA remains open outside this device functional gate']};(ROOT/'reports/execution/llama_hetero_direct_gguf_result.json').write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'bindings':338,'argmax':7559,'top10_overlap':10},sort_keys=True))
