#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def load(p):return json.loads((ROOT/p).read_text())
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
ref=load('work/results/l5_qwen2_four_layer_reference/result.json');lm=load('work/results/l5_qwen2_lm_head_sample/result.json')
checks={'exact_revision':ref['revision']=='ba1cf1846d7df0a0591d6c00649f57e798519da8','model_hash':ref['model_safetensors_sha256']=='302e327795994403cb1e3cb6a3345c76b246b894d14078c936b570c83a4e9057','four_layer_reference':ref['status']=='PASS_REFERENCE'and ref['layers']==4 and ref['sequence']==1024,'last_token_lm_head_shape':ref['last_token_logits_shape']==[1,1,151936],'sampled_revision8b_b_rtl':lm['status']=='PASS'and lm['samples']==160 and lm['contexts']==5 and lm['array_steps']==7680,'bf16_boundary_threshold':lm['max_absolute_error']<=0.002 and lm['bit_exact_samples']==160,'argmax_preserved':lm['sampled_rtl_argmax_token']==lm['reference_argmax_token']==ref['argmax_token']}
if not all(checks.values()):raise SystemExit(f'numerical subset checks failed:{checks}')
r={'schema_version':1,'stage':'L5','subgate':'L5.6_NUMERICAL_SUBSET','status':'PASS_REFERENCE_AND_LM_HEAD_SAMPLED_RTL_FOUR_LAYER_RTL_OPEN','checks':checks,'reference':{'sequence':1024,'layers':4,'hidden_state_count':ref['hidden_state_count'],'hidden_state_sha256':ref['hidden_state_sha256'],'last_token_logits_sha256':ref['last_token_logits_sha256'],'argmax_token':ref['argmax_token'],'run_seconds':ref['run_seconds']},'lm_head_rtl':{'architecture':'Revision8B-B 5-stage/5-context 16x32','samples':lm['samples'],'array_steps':lm['array_steps'],'tensor_boundary':lm['tensor_boundary'],'max_absolute_error':lm['max_absolute_error'],'raw_fp32_accumulator_max_difference_from_bf16_reference':lm['raw_fp32_accumulator_max_difference_from_bf16_reference'],'bit_exact_samples':lm['bit_exact_samples']},'provenance':{'model_safetensors_sha256':ref['model_safetensors_sha256'],'config_sha256':ref['config_sha256'],'reference_result_sha256':sha('work/results/l5_qwen2_four_layer_reference/result.json'),'lm_head_rtl_result_sha256':sha('work/results/l5_qwen2_lm_head_sample/result.json'),'rtl_log_sha256':sha('work/results/l5_qwen2_lm_head_sample/tb.log')},'non_claims':['four-layer official-weight execution is PyTorch reference, not integrated RTL','LM-head RTL E2 samples 160 of 151936 vocabulary columns','full 28-layer payload numerical simulation not run'],'next_action':'Replay a reduced official-weight four-layer node set through the project operator/RTL chain; keep L5.6 open until that cross-layer RTL boundary passes.'}
out=ROOT/'reports/execution/l5_qwen2_numerical_subset_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'max_error':lm['max_absolute_error'],'argmax':ref['argmax_token'],'next_action':r['next_action']},sort_keys=True))
