#!/usr/bin/env python3
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def text(p):return (ROOT/p).read_text()
dma=re.search(r'QWEN2_TILE_DMA_PLAN_PASS requests=(\d+) load1d=(\d+) load2d=(\d+) store1d=(\d+) read_bytes=(\d+) write_bytes=(\d+) q_weight_rows=(\d+) q_weight_row_bytes=(\d+) src_stride=(\d+) dst_stride=(\d+) random_backpressure=1',text('work/results/qwen2_tile_dma_plan/tb.log'))
payload=re.search(r'QWEN2_SHARED_L2_TILE_PAYLOAD_PASS read_beats=(\d+) write_beats=(\d+) rms_values=(\d+) matrix_steps=(\d+) matrix_outputs=(\d+) bf16_bit_exact=(\d+) random_l2_backpressure=1 q_weight_2d_gather=1',text('work/results/qwen2_shared_l2_tile_payload/tb.log'))
if not dma or tuple(map(int,dma.groups()))!=(4,2,1,1,107520,64,1536,64,3072,64):raise SystemExit('DMA plan PASS missing')
if not payload or tuple(map(int,payload.groups()))!=(1680,49,1536,1536,32,1568):raise SystemExit('payload PASS missing')
ctx=json.loads(text('reports/execution/qwen2_descriptor_tile_context_result.json'));img=json.loads(text('reports/execution/qwen2_descriptor_image_result.json'))
r={'schema_version':1,'status':'PASS_COMPOSED_DESCRIPTOR_DMA_SHARED_L2_REAL_TILE_PAYLOAD','evidence_class':'separate_real_RTL_context_DMA_plan_and_payload_datapath_not_monolithic_command','scope':'layer0 token0 RMSNorm plus Q output columns0_31','descriptor':{'formal_records':6188,'image_sha256':img['packed_records_sha256'],'roots':6,'fetches':12,'context_status':ctx['status']},'dma':{'requests':4,'load1d':2,'load2d':1,'store1d':1,'ddr_read_bytes':107520,'ddr_write_bytes':64,'q_weight_rows':1536,'row_bytes':64,'src_stride':3072,'dst_stride':64},'payload':{'shared_l2_read_beats':1680,'shared_l2_write_beats':49,'rms_values':1536,'matrix_steps':1536,'matrix_outputs':32,'bf16_bit_exact':1568,'random_backpressure':True},'checks':{'descriptor_context':ctx['status']=='PASS_DESCRIPTOR_BACKED_TILE_CONTEXT','dma_shape':True,'real_SFU_Matrix':True,'shared_l2_read_writeback':True,'no_testbench_payload_injection_after_start':True},'provenance':{'dma_log_sha256':sha('work/results/qwen2_tile_dma_plan/tb.log'),'payload_log_sha256':sha('work/results/qwen2_shared_l2_tile_payload/tb.log'),'dma_rtl_sha256':sha('rtl/integration/qwen2_tile_dma_plan.sv'),'payload_rtl_sha256':sha('rtl/integration/qwen2_shared_l2_tile_payload.sv')},'non_claims':['descriptor context, DMA plan and payload execute in separate RTL tests, not one monolithic command path','only token0 and 32 Q output columns execute','does not close one layer, seven groups or P3','DMA plan is not yet connected to pinned iDMA AXI data movement in the payload test']};out=ROOT/'reports/execution/qwen2_shared_l2_tile_payload_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'bf16_bit_exact':1568,'read_beats':1680,'write_beats':49},sort_keys=True))
