#!/usr/bin/env python3
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];D=Path('work/results/qwen2_bias_rope_q1024_repeated');K=Path('work/results/qwen2_kv_append_repeated_payload/tb.log');vr=json.loads((ROOT/'work/results/qwen2_rope_q1024_repeated/result.json').read_text());assert vr['status']=='PASS'and vr['recurrence_vs_direct_max_absolute_error']==0
bp=re.compile(r'QWEN2_BIAS_Q1024_REPEATED_PASS projection=(\d+) batches=64 descriptor_fetches=6 bias_loads=1 dma_requests=129 values=(\d+) bf16_bit_exact=(\d+) repeated_payload=1');rp=re.compile(r'QWEN2_ROPE_Q1024_REPEATED_PASS projection=(\d+) batches=64 positions=0_1023 descriptor_fetches=10 dma_requests=192 coefficient_steps=65472 values=(\d+) bf16_bit_exact=(\d+) repeated_payload=1')
for p,vals in enumerate((1572864,262144,262144)):m=bp.search((ROOT/D/f'bias_p{p}.log').read_text());assert m and tuple(map(int,m.groups()))==(p,vals,vals)
for p,vals in enumerate((1572864,262144)):m=rp.search((ROOT/D/f'rope_p{p}.log').read_text());assert m and tuple(map(int,m.groups()))==(p,vals,vals)
km=re.search(r'QWEN2_KV_APPEND_REPEATED_PAYLOAD_PASS command=1 tokens=(\d+) pages=(\d+) descriptor_fetches=(\d+) pte_updates=(\d+) idma_requests=(\d+) axi_beats=(\d+) payload_bytes=(\d+) byte_exact=(\d+) source=Q2p46_K_rope_plus_V_bias repeated_payload=1',(ROOT/K).read_text());assert km and tuple(map(int,km.groups()))==(1024,64,13,65,128,16384,1048576,1048576)
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
r={'schema_version':1,'status':'PASS_Q1024_POST_PROJECTION_REPEATED_PAYLOAD_STRESS','evidence_class':'batch64_real_bias_RoPE_plus_formal_KV_append_repeated_payload_not_model_continuity','bias':{'values':2097152,'bf16_bit_exact':2097152,'bias_loads':3},'rope':{'positions':[0,1023],'values':1835008,'bf16_bit_exact':1835008,'coefficient_steps':130944,'state_format':'Q2.46','direct_max_absolute_error':0.0},'kv_append':{'tokens':1024,'pages':64,'descriptor_fetches':13,'pte_updates':65,'idma_requests':128,'axi_beats':16384,'byte_exact':1048576},'checks':{'fixed_state_context_scaling':True,'formal_token_count1024':True,'K_rope_to_KV_source_format':True,'V_bias_to_KV_source_format':True,'pinned_idma_clean':True},'provenance':{'bias_Q_sha256':sha(D/'bias_p0.log'),'rope_Q_sha256':sha(D/'rope_p0.log'),'kv_log_sha256':sha(K),'q46_rtl_sha256':sha('rtl/sfu/qwen2_rope_base_coeff_q46.sv'),'kv_stage_sha256':sha('rtl/kv/qwen2_kv_append_ddr_stage_top.sv')},'open':['model_q1024_projection_payload','full_PTE_DDR_writes','attention_and_remaining_layer0','seven_groups','P3'],'non_claims':['QKV input batches repeat canonical rows0_15','projection trace64 is non-numerical','this does not close model q1024 numerical continuity']};(ROOT/'reports/execution/qwen2_q1024_post_projection_stress_result.json').write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'rope_error':0,'kv_bytes':1048576},sort_keys=True))
