#!/usr/bin/env python3
import hashlib,json,re,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];IDMA=ROOT/'work/upstream/idma'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
log=(ROOT/'work/results/qwen2_idma_shared_l2_data/tb.log').read_text();m=re.search(r'QWEN2_IDMA_SHARED_L2_DATA_PASS abstract_requests=(\d+) flat_requests=(\d+) axi_read_beats=(\d+) axi_write_beats=(\d+) local_load_beats=(\d+) local_store_beats=(\d+) byte_exact_load_beats=(\d+) byte_exact_store_bytes=(\d+) q_weight_rows=(\d+) errors=(\d+)',log)
if not m or tuple(map(int,m.groups()))!=(4,1539,1681,1681,1680,1,1680,64,1536,0):raise SystemExit('iDMA Shared-L2 PASS missing')
commit=subprocess.check_output(['git','-C',str(IDMA),'rev-parse','HEAD'],text=True).strip();dirty=subprocess.check_output(['git','-C',str(IDMA),'status','--porcelain'],text=True).strip();checks={'pinned_idma':commit=='2e0b0fe53b6f8823319e2428e2e9abc2db149b7d','upstream_clean':not dirty,'actual_axi_to_mem_bridge':True,'all_load_beats_byte_exact':True,'store_bytes_byte_exact':True,'zero_errors':True}
if not all(checks.values()):raise SystemExit(str(checks))
r={'schema_version':1,'status':'PASS_PINNED_IDMA_SHARED_L2_BYTE_EXACT','evidence_class':'actual_idma_AXI_to_production_SharedL2_VCS','commit':commit,'checks':checks,'abstract_requests':4,'flat_requests':1539,'axi_read_beats':1681,'axi_write_beats':1681,'local_load_beats':1680,'local_store_beats':1,'byte_exact_load_beats':1680,'byte_exact_store_bytes':64,'q_weight_rows':1536,'provenance':{'log_sha256':sha('work/results/qwen2_idma_shared_l2_data/tb.log'),'bridge_rtl_sha256':sha('rtl/integration/qwen2_axi_shared_l2_bridge.sv'),'expand_rtl_sha256':sha('rtl/integration/qwen2_tile_idma_expand.sv'),'shared_l2_rtl_sha256':sha('rtl/fabric/shared_l2_fabric.sv')},'non_claims':['this DMA data test does not instantiate RMSNorm or Matrix','monolithic computation top integration remains open','does not close full layer or P3']};out=ROOT/'reports/execution/qwen2_idma_shared_l2_data_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'load_beats':1680,'store_bytes':64},sort_keys=True))
