#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,re
from pathlib import Path
import yaml
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def status(p):return dict(x.split('=',1)for x in(ROOT/p).read_text().splitlines()if'='in x)
hs=status('work/results/l10_owner_hierarchy/status.txt');hq=(ROOT/'work/results/l10_owner_hierarchy/qor.rpt').read_text(errors='replace');ha=(ROOT/'work/results/l10_owner_hierarchy/area_hier.rpt').read_text(errors='replace');ss=status('work/results/l10_sram_macro_inventory/status.txt');arch=yaml.safe_load((ROOT/'configs/arch_v1.yaml').read_text());l3=json.loads((ROOT/'reports/execution/l3_closeout_result.json').read_text())
owners={m.group(1):float(m.group(2))for m in re.finditer(r'^u_(matrix|attention_controller|attention_tile16|attention_merge8|silu|refined_rsqrt)\s+([0-9.]+)',ha,re.M)};parent=float(re.search(r'Design Area:\s*([0-9.]+)',hq).group(1));owner_sum=sum(owners.values());area_delta=abs(parent-owner_sum)
macro_map={'shared_l2':{'macro':'SP6144x128','physical_instances':16,'kib':1536},'matrix_scratchpad':{'macro':'SP6144x128','physical_instances':8,'kib':768},'matrix_accumulator':{'macro':'2xDP2048x64/logical','physical_instances':32,'kib':512},'aha_lake_local':{'macro':'2xDP2048x64/logical','physical_instances':16,'kib':256},'aha_wrapper_local':{'macro':'2xDP2048x64/logical','physical_instances':16,'kib':256},'kv_staging':{'macro':'4xDP4096x32/logical','physical_instances':32,'kib':512},'control_trace':{'macro':'SP4096x128','physical_instances':4,'kib':256}}
offset=0;ranges=[]
for name,spec in arch['memory']['owners'].items():
 offset=(offset+4095)&~4095;size=int(spec['kib'])*1024;ranges.append({'owner':name,'base':offset,'limit':offset+size,'bytes':size});offset+=size
overlaps=sum(not(a['limit']<=b['base']or b['limit']<=a['base'])for i,a in enumerate(ranges)for b in ranges[i+1:]);total_kib=sum(x['kib']for x in macro_map.values());arcs={k:int(ss[k])for k in('SP6144_TIMING_ARCS','SP4096_TIMING_ARCS','DP2048_TIMING_ARCS','DP4096_TIMING_ARCS')}
checks={'owner_link':hs['LINK_STATUS']=='1','wns':float(hs['WORST_SLACK_NS'])>=0,'unmapped_unresolved_blackbox':hs['UNMAPPED_CELLS']==hs['UNRESOLVED_REFERENCES']==hs['BLACKBOX_CELLS']=='0','timing_exceptions':hs['NON_RESET_DATA_FALSE_PATHS']==hs['MULTICYCLE_EXCEPTIONS']=='0','transition_cap':re.search(r'Max Trans Violations:\s+0',hq)is not None and re.search(r'Max Cap Violations:\s+0',hq)is not None,'area_no_double_count':area_delta<0.1 and hs['PARENT_LOGIC_AREA']=='0','macro_link':ss['LINK_STATUS']=='1'and ss['UNMAPPED_CELLS']=='0','macro_count':int(ss['PHYSICAL_MACROS'])==124,'macro_timing_arcs':all(v>0 for v in arcs.values()),'capacity':total_kib==arch['memory']['total_sram_kib']==4096,'address_overlap':overlaps==0,'bank_conflict_counters':l3['status']=='PASS'and l3['combined']['bank_conflicts']>=0}
if not all(checks.values()):raise SystemExit(f'L10 checks failed:{checks}')
r={'schema_version':1,'status':'PASS_L10_1_L10_2_EARLY_PPA','evidence_class':'hierarchy_preserving_frozen_DDC_link_STA_plus_real_SRAM_DB_inventory_not_post_route','clock_ns':1.0,'owner_hierarchy':{'authoritative_parent_area':parent,'owner_top_areas':owners,'owner_area_sum':owner_sum,'area_delta':area_delta,'area_double_count':0,'wns_ns':float(hs['WORST_SLACK_NS']),'unmapped':0,'unresolved':0,'blackboxes':0,'parent_logic_area':0},'sram':{'total_kib':total_kib,'physical_macros':124,'owner_map':macro_map,'address_ranges':ranges,'address_overlap':overlaps,'timing_arcs':arcs,'bank_conflicts_measured':l3['combined']['bank_conflicts'],'db_sha256':{'sp6144':sha('work/generated/l10_sram/l2_sp_6144x128wm_base_0p8v_tt25/l2sp6144x128wm_tt.db'),'sp4096':sha('work/generated/l10_sram/ct_sp_4096x128wm_base_0p8v_tt25/ctsp4096x128wm_tt.db'),'dp2048':sha('work/generated/l10_sram/dp2048x64wm_ll_0p8v_tt25/dp2048x64wm_tt.db'),'dp4096':sha('work/generated/l10_sram/dp4096x32wm_ll_0p8v_tt25/dp4096x32wm_tt.db')}},'checks':checks,'physical_view_blockers':['DP GDS2 generation failed','all SRAM LEF generation remains blocked by ARM bifrun crash'],'non_claims':['owner parent has zero cross-owner logic and reports frozen-DDC internal paths','not integrated cross-owner data-path timing','not post-route/PVT/OCV','not workload SAIF power']};out=ROOT/'reports/execution/l10_hierarchical_synthesis_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');(ROOT/'reports/execution/l10_sram_macro_result.json').write_text(json.dumps({'schema_version':1,'status':'PASS_L10_2_EARLY_MACRO_DB','sram':r['sram'],'checks':{k:v for k,v in checks.items()if k.startswith('macro')or k in('capacity','address_overlap','bank_conflict_counters')},'physical_view_blockers':r['physical_view_blockers']},indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'wns_ns':r['owner_hierarchy']['wns_ns'],'area':parent,'sram_kib':total_kib,'macros':124},sort_keys=True))
