#!/usr/bin/env python3
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
log_path='work/results/qwen2_full_q_token_single_command/tb.log'
if not (ROOT/log_path).exists():log_path='work/results/qwen2_full_q_token_iterative/tb.log'
log=(ROOT/log_path).read_text();m=re.search(r'QWEN2_FULL_Q_TOKEN_SINGLE_COMMAND_PASS physical_columns=(\d+) column_tiles=(\d+) descriptor_fetches=(\d+) abstract_dma=(\d+) flat_idma=(\d+) axi_beats=(\d+) ddr_read_bytes=(\d+) ddr_write_bytes=(\d+) l2_read_beats=(\d+) l2_write_beats=(\d+) rms_executions=(\d+) matrix_completion=(\d+) bf16_bit_exact=(\d+) pingpong_buffers=(\d+)',log)
expected=(1536,48,12,98,73778,73920,4727808,3072,73872,96,1,1,3072,2)
if not m or tuple(map(int,m.groups()))!=expected:raise SystemExit('full Q single-command PASS missing')
r={'schema_version':1,'status':'PASS_FULL_Q_TOKEN0_SINGLE_COMMAND','evidence_class':'single_VCS_one_descriptor_snapshot_one_RMS_one_Matrix_completion','token':0,'physical_Q_columns':1536,'column_tiles':48,'descriptor_fetches':12,'abstract_dma_requests':98,'flat_idma_requests':73778,'axi_beats_each_direction':73920,'ddr_read_bytes':4727808,'ddr_write_bytes':3072,'shared_l2_read_beats':73872,'shared_l2_write_beats':96,'rms_executions':1,'matrix_completions':1,'bf16_bit_exact':3072,'weight_buffers':2,'checks':{'one_command':True,'one_descriptor_snapshot':True,'one_RMS':True,'one_Matrix_completion':True,'all_physical_Q_columns':True,'contiguous_Q_DDR_output':True,'pinned_idma':True},'provenance':{'log_sha256':sha(log_path),'top_sha256':sha('rtl/integration/qwen2_descriptor_shared_l2_tile_top.sv'),'matrix_endpoint_sha256':sha('rtl/integration/qwen2_matrix_command_endpoint.sv'),'vector_result_sha256':sha('reports/execution/qwen2_shared_l2_tile_vector_result.json')},'supersedes':'reports/execution/qwen2_full_q_token_iterative_result.json','open':['true_DMA_Matrix_overlap','all_1024_query_tokens','Q_bias_and_RoPE','K_and_V','attention','complete_layer','seven_groups','P3'],'non_claims':['two weight buffers alternate but DMA and Matrix are not yet overlapped','only token0 is executed','Q bias and RoPE are separate later commands','does not close one layer, P2 or P3']};out=ROOT/'reports/execution/qwen2_full_q_token_single_command_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'columns':1536,'bit_exact':3072},sort_keys=True))
