#!/usr/bin/env python3
import hashlib,json,re
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'work/results/qwen2_q1024_final_head_backend';IN=ROOT/'work/results/qwen2_q1024_final_head_inputs';REF=ROOT/'work/results/llama_cpp_qwen2_baseline/pytorch_logits.bin'
text=(OUT/'run.log').read_text();m=re.search(r'QWEN2_Q1024_FINAL_HEAD_BACKEND_PASS final_norm_values=(\d+) vocab=(\d+) argmax=(\d+) logits_fnv=([0-9a-f]+)',text);assert m and tuple(map(int,m.groups()[:2]))==(1536,151936)
logits=np.fromfile(OUT/'logits_fp32.bin',np.float32);reference=np.fromfile(REF,np.float32);assert logits.size==reference.size==151936 and np.isfinite(logits).all();argmax=int(logits.argmax());ref_argmax=int(reference.argmax());top=np.argsort(logits)[-10:][::-1];rtop=np.argsort(reference)[-10:][::-1];overlap=len(set(map(int,top))&set(map(int,rtop)))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
r={'schema_version':1,'status':'PASS_Q1024_FINAL_RMSNORM_FULL_LM_HEAD_BACKEND' if argmax==ref_argmax and overlap>=8 else 'FAIL','evidence_class':'full_vocab_hardware_semantics_backend_not_RTL','final_norm_values':1536,'vocab':151936,'argmax':argmax,'reference_argmax':ref_argmax,'top10_overlap':overlap,'top10':list(map(int,top)),'reference_top10':list(map(int,rtop)),'logits_max_absolute_error':float(np.max(np.abs(logits.astype(np.float64)-reference.astype(np.float64)))),'hashes':{'final_norm':sha(OUT/'final_norm_fp32.bin'),'logits':sha(OUT/'logits_fp32.bin')},'provenance':{'input_manifest':sha(IN/'manifest.json'),'layer27_final':sha(ROOT/'work/results/qwen2_q1024_full28_backend/layer27/final_fp32.bin'),'reference_logits':sha(REF),'source':sha(ROOT/'src/qwen2_q1024_final_head_backend.cpp')},'open':['sampled_final_head_RTL_ext32_policy','llama_device_backend_registration','P3_final_audit'],'non_claims':['full-vocab C++ hardware-semantics backend is not full RTL','PyTorch logit hash is not expected bit-exact after approximate hardware operators']};(ROOT/'reports/execution/qwen2_q1024_final_head_backend_result.json').write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'argmax':argmax,'reference_argmax':ref_argmax,'top10_overlap':overlap,'max_error':r['logits_max_absolute_error']},sort_keys=True));raise SystemExit(0 if r['status'].startswith('PASS') else 1)
