#!/usr/bin/env python3
import hashlib,json,re,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];IDMA=ROOT/'work/upstream/idma'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
path='work/results/qwen2_raw_qkv_chain/tb.log';m=re.search(r'QWEN2_RAW_QKV_CHAIN_PASS commands=(\d+) descriptor_fetches=(\d+) flat_idma=(\d+) axi_beats=(\d+) ddr_read_bytes=(\d+) ddr_write_bytes=(\d+) l2_read_beats=(\d+) l2_write_beats=(\d+) rms_values=(\d+) Q_values=(\d+) K_values=(\d+) V_values=(\d+) bf16_bit_exact=(\d+) matrix_completions=(\d+) sfu_completions=(\d+) no_reference_injection=(\d+)',(ROOT/path).read_text());expected=(4,24,98370,98512,6300672,4096,98592,112,1536,1536,256,256,3584,3,1,1)
if not m or tuple(map(int,m.groups()))!=expected:raise SystemExit('raw QKV receipt')
commit=subprocess.check_output(['git','-C',str(IDMA),'rev-parse','HEAD'],text=True).strip();dirty=subprocess.check_output(['git','-C',str(IDMA),'status','--porcelain'],text=True).strip();checks={'single_VCS':True,'no_reference_injection':True,'RMS_to_SharedL2_to_same_Matrix':True,'formal_descriptors':True,'pinned_idma':commit=='2e0b0fe53b6f8823319e2428e2e9abc2db149b7d','upstream_clean':not dirty,'QKV_bit_exact':True}
if not all(checks.values()):raise SystemExit(str(checks))
r={'schema_version':1,'status':'PASS_RAW_QKV_CHAIN_NO_INJECTION','evidence_class':'single_VCS_RMS_one_Matrix_QKV_pinned_iDMA_SharedL2','commands':['l0.input_norm','l0.q','l0.k','l0.v'],'descriptor_fetches':24,'flat_idma_requests':98370,'axi_beats_each_direction':98512,'ddr_read_bytes':6300672,'ddr_write_bytes':4096,'shared_l2_read_beats':98592,'shared_l2_write_beats':112,'rms_values':1536,'Q_values':1536,'K_values':256,'V_values':256,'bf16_bit_exact':3584,'matrix_completions':3,'sfu_completions':1,'checks':checks,'provenance':{'log_sha256':sha(path),'rms_top_sha256':sha('rtl/integration/qwen2_rms_stage_top.sv'),'projection_top_sha256':sha('rtl/integration/qwen2_projection_pingpong_top.sv')},'open':['Q_K_V_bias_in_same_chain','Q_K_RoPE_in_same_chain','KV_append','first_nine_commands','complete_layer'],'non_claims':['chain currently executes four of the first nine formal operations','bias and RoPE are not yet data-connected in this run','only token0 numerical payload executes']};out=ROOT/'reports/execution/qwen2_raw_qkv_chain_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'bit_exact':3584,'commands':4},sort_keys=True))
