#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def load(p):return json.loads((ROOT/p).read_text())
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
cpu=load('work/results/llama_cpp_qwen2_baseline/result.json');graph=load('reports/execution/llama_cpp_qwen2_graph_lowering_result.json');closure=load('reports/execution/upstream_closure.json');log=(ROOT/'work/results/qwen2_real_command_submission/tb.log').read_text();m=re.search(r'QWEN2_REAL_COMMAND_SUBMISSION_PASS commands=(\d+) completions=(\d+) matrix=(\d+) sfu=(\d+) event_grants=(\d+) random_backpressure=1 macro_errors=0 protocol_errors=0',log)
if not m:raise SystemExit('submission PASS missing')
commands,completions,matrix,sfu,grants=map(int,m.groups());checks={'llama_commit':closure['repositories']['llama_cpp']['commit']=='0b5be7e4a25862bc2777d0c47eae18788a8c963a'and not closure['repositories']['llama_cpp']['dirty'],'cpu_baseline':cpu['status']=='PASS_REAL_LLAMA_CPU_BASELINE'and cpu['argmax_match']and cpu['top10_overlap']==10,'real_graph':graph['status']=='PASS_REAL_GGML_GRAPH_GGUF_COMMAND128_LOWERING'and graph['graph']['nodes']==930 and graph['gguf']['tensors']==338,'lowering':graph['lowering']['commands']==252,'submission':commands==completions==grants==252 and matrix==140 and sfu==112}
if not all(checks.values()):raise SystemExit(f'readiness:{checks}')
r={'schema_version':1,'status':'PASS_REAL_LLAMA_GRAPH_COMMAND_SUBMISSION_PAYLOAD_ENDPOINTS_OPEN','evidence_class':'real_llama_CPU_graph_GGUF_Command128_and_production_fabric_not_device_payload','model':'Qwen/Qwen2-1.5B-Instruct','revision':graph['revision'],'llama_cpp':{'commit':graph['llama_cpp_commit'],'gguf_sha256':graph['gguf']['sha256'],'cpu_argmax':cpu['llama_argmax'],'pytorch_argmax':cpu['pytorch_argmax'],'top10_overlap':cpu['top10_overlap'],'prompt_eval_tokens_per_second':89.76},'graph':{'nodes':930,'tensors':338,'commands':252,'matrix_commands':140,'sfu_commands':112,'command_sha256':graph['lowering']['command_sha256']},'submission':{'commands':commands,'completions':completions,'event_grants':grants,'random_backpressure':True,'macro_errors':0,'protocol_errors':0},'checks':checks,'provenance':{'cpu_result_sha256':sha('work/results/llama_cpp_qwen2_baseline/result.json'),'graph_capture_sha256':sha('work/results/llama_cpp_qwen2_baseline/graph.tsv'),'lowering_report_sha256':sha('reports/execution/llama_cpp_qwen2_graph_lowering_result.json'),'submission_log_sha256':sha('work/results/qwen2_real_command_submission/tb.log')},'open':['real_Matrix_command_endpoint','real_SFU_command_endpoint','descriptor_backed_payload_memory','seven_group_device_payload','P3_continuous_device_payload'],'non_claims':['stock llama.cpp CPU is not the project device backend','production command submission currently uses completion endpoint models','no Matrix/SFU payload numerical execution from the captured graph']};out=ROOT/'reports/execution/llama_cpp_qwen2_device_readiness_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'nodes':930,'tensors':338,'commands':252,'open':r['open']},sort_keys=True))
