#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def load(p):return json.loads((ROOT/p).read_text())
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
cross=load('work/results/l5_qwen2_four_layer_cross_replay/result.json');full=load('reports/execution/l5_qwen2_full_model_trace_result.json');integrity=load('reports/execution/local_upstream_integrity.json');log=(ROOT/'work/results/l5_qwen2_four_layer_cross_replay/tb.log').read_text();m=re.search(r'L5_QWEN2_FOUR_LAYER_CROSS_RTL_PASS nodes=5 layers=4 rms_vectors=5 rms_rsqrt_cycles=(\d+) matrix_samples=160 matrix_steps=7680 cycles=(\d+)',log)
if not m:raise SystemExit('cross replay PASS line missing')
rsqrt_cycles,rtl_cycles=map(int,m.groups());status=dict(x.split('=',1)for x in(ROOT/'work/results/l5_fp32_rsqrt_nr2_dc/status.txt').read_text().splitlines()if'='in x);qor=(ROOT/'work/results/l5_fp32_rsqrt_nr2_dc/qor.rpt').read_text(errors='replace');area_match=re.search(r'Cell Area:\s*([0-9.]+)',qor);wns=float(status['WORST_SLACK_NS'])
checks={'cross_rtl':cross['status']=='PASS','four_layers':cross['layers']==4 and len(cross['nodes'])==5,'rms_fp32_threshold':cross['rms']['fp32_max_absolute_error']<=0.002,'rms_bf16_exact':cross['rms']['bf16_model_bit_exact']==7680 and cross['rms']['bf16_model_max_ulp']==0,'matrix_operator_exact':cross['matrix']['fp32_bit_exact']==160 and cross['matrix']['fp32_max_absolute_error']==0,'matrix_bf16_exact':cross['matrix']['bf16_model_bit_exact']==160 and cross['matrix']['bf16_model_max_ulp']==0,'random_backpressure':cross['backpressure']=='deterministic_random_ready','refined_rsqrt_latency':rsqrt_cycles==270,'refined_rsqrt_dc':wns>=0 and status['UNMAPPED_CELLS']=='0' and status['UNRESOLVED_REFERENCES']=='0','adjusted_full_trace':full['trace']['total_cycles']==3192103543 and full['trace']['tokens_per_second']>=300,'upstream_immutable':integrity['status']=='PASS' and integrity['upstream_source_edits']==0}
if not all(checks.values()):raise SystemExit(f'cross replay checks failed:{checks}')
r={'schema_version':1,'stage':'L5','subgate':'L5.6_REDUCED_FOUR_LAYER_CROSS_RTL','status':'PASS','evidence_class':'official_weight_reference_anchored_reduced_cross_layer_RTL_E2_E4','model':'Qwen/Qwen2-1.5B-Instruct','revision':'ba1cf1846d7df0a0591d6c00649f57e798519da8','sequence':1024,'layers':4,'nodes':cross['nodes'],'checks':checks,'rtl':{'cycles':rtl_cycles,'rms_vectors':5,'rms_values':7680,'matrix_samples':160,'matrix_steps':7680,'rms_fp32_max_error':cross['rms']['fp32_max_absolute_error'],'matrix_fp32_max_error':cross['matrix']['fp32_max_absolute_error'],'bf16_bit_exact':7840,'backpressure':'deterministic_random_ready'},'refined_rsqrt':{'implementation':'13 operations through accepted 1GHz FP32 add/mul pipelines','cycles_per_vector':rsqrt_cycles//5,'dc_wns_ns':wns,'dc_area':float(area_match.group(1))if area_match else 0.0,'unmapped':0,'unresolved':0},'full_model_adjustment':{'cycles':full['trace']['total_cycles'],'tokens_per_second':full['trace']['tokens_per_second'],'delta_cycles_from_refined_rsqrt':2924595},'provenance':{'cross_log_sha256':sha('work/results/l5_qwen2_four_layer_cross_replay/tb.log'),'cross_result_sha256':sha('work/results/l5_qwen2_four_layer_cross_replay/result.json'),'rms_rtl_sha256':sha('rtl/sfu/fp32_rmsnorm1536_chunked.sv'),'rsqrt_rtl_sha256':sha('rtl/sfu/fp32_rsqrt_nr2.sv'),'matrix_rtl_sha256':sha('rtl/matrix/candidates/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv'),'dc_status_sha256':sha('work/results/l5_fp32_rsqrt_nr2_dc/status.txt')},'source_policy':{'canonical_upstream_modified':False,'generated_rtl_modified':False,'project_authored_rtl_only':True},'non_claims':['reference hidden snapshots anchor each layer; this is not a full q1024 payload RTL simulation','refined rsqrt standalone E4 does not replace later integrated-top/post-route PPA']}
out=ROOT/'reports/execution/l5_qwen2_four_layer_cross_replay_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'bf16_bit_exact':r['rtl']['bf16_bit_exact'],'wns_ns':wns,'adjusted_tps':r['full_model_adjustment']['tokens_per_second']},sort_keys=True))
