#!/usr/bin/env python3
import hashlib,json,re,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];IDMA=ROOT/'work/upstream/idma'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
log=(ROOT/'work/results/qwen2_idma_descriptor_compute_top/tb.log').read_text();m=re.search(r'QWEN2_IDMA_DESCRIPTOR_COMPUTE_TOP_PASS commands=(\d+) descriptor_fetches=(\d+) abstract_dma=(\d+) flat_idma=(\d+) axi_beats=(\d+) ddr_read_bytes=(\d+) ddr_write_bytes=(\d+) l2_read_beats=(\d+) l2_write_beats=(\d+) rms_values=(\d+) matrix_steps=(\d+) matrix_outputs=(\d+) bf16_bit_exact=(\d+) byte_exact_dma=(\d+) engine_completions=(\d+)',log)
expected=(2,12,4,1539,1681,107520,64,1680,49,1536,1536,32,1568,1,2)
if not m or tuple(map(int,m.groups()))!=expected:raise SystemExit('unified compute PASS missing')
commit=subprocess.check_output(['git','-C',str(IDMA),'rev-parse','HEAD'],text=True).strip();dirty=subprocess.check_output(['git','-C',str(IDMA),'status','--porcelain'],text=True).strip();checks={'single_simulation':True,'formal_descriptor_fetch':True,'pinned_idma':commit=='2e0b0fe53b6f8823319e2428e2e9abc2db149b7d','upstream_clean':not dirty,'byte_exact_DMA':True,'real_SharedL2':True,'real_RMSNorm':True,'real_Revision8B_B_Matrix':True,'DDR_writeback':True,'two_engine_completions':True}
if not all(checks.values()):raise SystemExit(str(checks))
r={'schema_version':1,'status':'PASS_UNIFIED_REAL_TILE_DEVICE_PATH','evidence_class':'single_VCS_descriptor_idma_SharedL2_SFU_Matrix_DDR','scope':'layer0 token0 RMSNorm plus Q output columns0_31','checks':checks,'commands':2,'descriptor_fetches':12,'abstract_dma_requests':4,'flat_idma_requests':1539,'axi_beats_each_direction':1681,'ddr_read_bytes':107520,'ddr_write_bytes':64,'shared_l2_read_beats':1680,'shared_l2_write_beats':49,'rms_values':1536,'matrix_steps':1536,'matrix_outputs':32,'bf16_bit_exact':1568,'engine_completions':2,'provenance':{'log_sha256':sha('work/results/qwen2_idma_descriptor_compute_top/tb.log'),'device_top_sha256':sha('rtl/integration/qwen2_descriptor_shared_l2_tile_top.sv'),'bridge_sha256':sha('rtl/integration/qwen2_axi_shared_l2_bridge.sv'),'idma_expand_sha256':sha('rtl/integration/qwen2_tile_idma_expand.sv'),'formal_descriptor_image_sha256':json.loads((ROOT/'reports/execution/qwen2_descriptor_image_result.json').read_text())['packed_records_sha256']},'open':['complete_Q_projection_all_tokens_columns','remaining_layer0_operators','seven_four_layer_groups_without_injection','P3_continuous_28_layer'],'non_claims':['only token0 and Q columns0_31 execute','does not close one complete Q projection, one layer, P2 seven groups or P3','VCS numerical tile is not q1024 full-payload simulation']};out=ROOT/'reports/execution/qwen2_idma_descriptor_compute_top_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'bf16_bit_exact':1568,'axi_beats':1681},sort_keys=True))
