#!/usr/bin/env python3
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
log=(ROOT/'work/results/qwen2_descriptor_shared_l2_tile_top/tb.log').read_text();m=re.search(r'QWEN2_DESCRIPTOR_SHARED_L2_TILE_TOP_PASS commands=(\d+) descriptor_fetches=(\d+) dma_requests=(\d+) ddr_read_bytes=(\d+) ddr_write_bytes=(\d+) l2_read_beats=(\d+) l2_write_beats=(\d+) bf16_bit_exact=(\d+) engine_completions=(\d+) random_backpressure=1',log)
expected=(2,12,4,107520,64,1680,49,1568,2)
if not m or tuple(map(int,m.groups()))!=expected:raise SystemExit('monolithic tile top PASS missing')
r={'schema_version':1,'status':'PASS_MONOLITHIC_DESCRIPTOR_SHARED_L2_REAL_TILE_TOP','evidence_class':'single_RTL_top_descriptor_context_DMA_plan_SharedL2_SFU_Matrix','scope':'layer0 token0 RMSNorm plus Q output columns0_31','commands':2,'descriptor_fetches':12,'dma_requests':4,'ddr_read_bytes':107520,'ddr_write_bytes':64,'shared_l2_read_beats':1680,'shared_l2_write_beats':49,'bf16_bit_exact':1568,'engine_completions':2,'random_backpressure':True,'checks':{'formal_descriptor_image':True,'preissue_snapshot':True,'DMA_load_before_payload':True,'payload_before_store':True,'real_RMSNorm':True,'real_Revision8B_B_Matrix':True,'Shared_L2_writeback':True},'provenance':{'log_sha256':sha('work/results/qwen2_descriptor_shared_l2_tile_top/tb.log'),'top_rtl_sha256':sha('rtl/integration/qwen2_descriptor_shared_l2_tile_top.sv'),'payload_rtl_sha256':sha('rtl/integration/qwen2_shared_l2_tile_payload.sv'),'descriptor_image_sha256':json.loads((ROOT/'reports/execution/qwen2_descriptor_image_result.json').read_text())['packed_records_sha256']},'open':['pinned_iDMA_binding_for_four_requests','complete_Q_projection','remaining_layer0_operators','seven_groups','P3'],'non_claims':['DMA request/response is modeled in this top test; pinned iDMA AXI movement remains separate','only token0 and Q columns0_31 execute','does not close a full layer or L5.6d P2/P3']};out=ROOT/'reports/execution/qwen2_descriptor_shared_l2_tile_top_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'bf16_bit_exact':1568,'dma_requests':4},sort_keys=True))
