#!/usr/bin/env python3
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
log=(ROOT/'work/results/qwen2_full_q_token_iterative/tb.log').read_text();m=re.search(r'QWEN2_FULL_Q_TOKEN_ITERATIVE_PASS iterations=(\d+) physical_columns=(\d+) descriptor_fetches=(\d+) abstract_dma=(\d+) flat_idma=(\d+) axi_beats=(\d+) ddr_read_bytes=(\d+) ddr_write_bytes=(\d+) l2_read_beats=(\d+) l2_write_beats=(\d+) bf16_bit_exact=(\d+) repeated_rms=(\d+) repeated_command_completion=(\d+)',log)
expected=(48,1536,576,192,73872,80688,5160960,3072,80640,2352,75264,48,48)
if not m or tuple(map(int,m.groups()))!=expected:raise SystemExit('full Q iterative PASS missing')
r={'schema_version':1,'status':'PASS_FULL_Q_TOKEN0_ITERATIVE_SAME_RTL','evidence_class':'single_VCS_same_RTL_48_sequential_physical_column_tiles','token':0,'physical_Q_columns':1536,'tiles':48,'descriptor_fetches':576,'abstract_dma_requests':192,'flat_idma_requests':73872,'axi_beats_each_direction':80688,'ddr_read_bytes':5160960,'ddr_write_bytes':3072,'shared_l2_read_beats':80640,'shared_l2_write_beats':2352,'bf16_bit_exact':75264,'checks':{'same_RTL_instance':True,'all_physical_columns':True,'contiguous_DDR_Q_output':True,'exact_safetensors_weights':True,'pinned_idma':True},'known_inefficiency':{'RMS_executions':48,'descriptor_snapshots':48,'matrix_command_completions':48,'production_target_each':1},'provenance':{'log_sha256':sha('work/results/qwen2_full_q_token_iterative/tb.log'),'vector_result_sha256':sha('reports/execution/qwen2_shared_l2_tile_vector_result.json'),'top_sha256':sha('rtl/integration/qwen2_descriptor_shared_l2_tile_top.sv')},'open':['single_command_48_tile_controller','RMS_once','weight_pingpong_overlap','complete_QKV','complete_layer','seven_groups','P3'],'non_claims':['iterative 48 starts are not one Matrix command','RMS and descriptor fetch repeat 48 times','does not close production full-Q scheduling, one layer, P2 or P3']};out=ROOT/'reports/execution/qwen2_full_q_token_iterative_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'columns':1536,'bit_exact':75264},sort_keys=True))
