#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def load(p):return json.loads((ROOT/p).read_text())
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
cp=load('work/results/l5_qwen2_payload_checkpoints/result.json');groups=load('work/results/l5_qwen2_contiguous_groups/reference_result.json');log=(ROOT/'work/results/l5_qwen2_payload_group_controller/tb.log').read_text();m=re.search(r'QWEN2_PAYLOAD_GROUP_CONTROLLER_PASS groups=7 layers=28 commands=168 completions=168 reference_injections_inside_groups=0 command_stalls=(\d+) event_wait_cycles=(\d+)',log)
if not m:raise SystemExit('group controller PASS missing')
stalls,waits=map(int,m.groups());checks={'checkpoints':cp['status']=='PASS_168_OFFICIAL_CHECKPOINTS'and cp['checkpoint_count']==168 and cp['sample_values']==10752,'checkpoint_revision':cp['revision']=='ba1cf1846d7df0a0591d6c00649f57e798519da8','groups':groups['status']=='PASS_7_CONTIGUOUS_REFERENCE_GROUPS'and groups['group_count']==7 and groups['layers_covered']==28,'no_internal_injection':groups['reference_hidden_injections_inside_groups']==0 and all(x['reference_hidden_injections_inside_group']==0 for x in groups['groups']),'group_outputs_exact':all(x['bit_exact']and x['output_sha256']==x['expected_sha256']for x in groups['groups']),'rtl_transactions':stalls>0 and waits>0}
if not all(checks.values()):raise SystemExit(f'payload checks:{checks}')
r={'schema_version':1,'status':'PASS_P1_CHECKPOINTS_AND_P2_REFERENCE_CONTINUITY_RTL_CONTROL','evidence_class':'official_reference_continuous_groups_plus_RTL_transaction_control_not_payload_datapath','model':cp['model'],'revision':cp['revision'],'sequence':1024,'phase1':{'status':'PASS','checkpoint_count':168,'sample_values':10752,'aggregate_sha256':cp['aggregate_sha256'],'layers':28,'phases_per_layer':6},'phase2':{'status':'PASS_MIXED_EVIDENCE','groups':7,'layers':28,'reference_hidden_injections_inside_groups':0,'group_outputs_bit_exact':7,'rtl_commands':168,'rtl_completions':168,'command_stalls':stalls,'event_wait_cycles':waits},'checks':checks,'provenance':{'checkpoint_raw_sha256':sha('work/results/l5_qwen2_payload_checkpoints/result.json'),'checkpoint_log_sha256':sha('work/results/l5_qwen2_payload_checkpoints/run.log'),'group_reference_raw_sha256':sha('work/results/l5_qwen2_contiguous_groups/reference_result.json'),'group_reference_log_sha256':sha('work/results/l5_qwen2_contiguous_groups/reference.log'),'group_controller_log_sha256':sha('work/results/l5_qwen2_payload_group_controller/tb.log'),'model_safetensors_sha256':cp['model_safetensors_sha256']},'open':{'P2_real_payload_RTL_datapath':'OPEN','P3_continuous_28_layer_payload_RTL_or_real_backend':'OPEN'},'non_claims':['reference group numerical execution and RTL transaction control are separate evidence paths','no real Matrix/SFU payload datapath executes all seven groups','does not close L5.6d full payload numerical RTL']};out=ROOT/'reports/execution/qwen2_payload_checkpoint_result.json';out.write_text(json.dumps({'schema_version':1,'status':'PASS_168_OFFICIAL_CHECKPOINTS','checkpoint_count':168,'sample_values':10752,'aggregate_sha256':cp['aggregate_sha256'],'revision':cp['revision'],'raw_sha256':r['provenance']['checkpoint_raw_sha256'],'non_claim':'reference checkpoints are not RTL evidence'},indent=2,sort_keys=True)+'\n');(ROOT/'reports/execution/qwen2_payload_group_result.json').write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'checkpoints':168,'groups':7,'stalls':stalls,'waits':waits,'P3':'OPEN'},sort_keys=True))
