#!/usr/bin/env python3
import hashlib,json,re,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];IDMA=ROOT/'work/upstream/idma'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
path='work/results/qwen2_bias_stage_vcs/tb.log';m=re.search(r'QWEN2_BIAS_STAGE_VCS_PASS commands=(\d+) descriptor_fetches=(\d+) flat_idma=(\d+) axi_beats=(\d+) ddr_read_bytes=(\d+) ddr_write_bytes=(\d+) l2_read_beats=(\d+) l2_write_beats=(\d+) Q_values=(\d+) K_values=(\d+) V_values=(\d+) bf16_bit_exact=(\d+) bias_format=FP32 no_reference_inside_stage=(\d+)',(ROOT/path).read_text());expected=(3,18,70,256,12288,4096,192,64,1536,256,256,2048,1)
if not m or tuple(map(int,m.groups()))!=expected:raise SystemExit('bias stage receipt')
commit=subprocess.check_output(['git','-C',str(IDMA),'rev-parse','HEAD'],text=True).strip();dirty=subprocess.check_output(['git','-C',str(IDMA),'status','--porcelain'],text=True).strip();checks={'formal_descriptors':True,'FP32_bias_dtype7':True,'pinned_idma':commit=='2e0b0fe53b6f8823319e2428e2e9abc2db149b7d','upstream_clean':not dirty,'SharedL2_HardFloat':True,'BF16_boundary_output':True}
if not all(checks.values()):raise SystemExit(str(checks))
r={'schema_version':1,'status':'PASS_DESCRIPTOR_DRIVEN_QKV_BIAS_STAGE','evidence_class':'formal_descriptor_pinned_iDMA_SharedL2_HardFloat','commands':['l0.q_bias','l0.k_bias','l0.v_bias'],'descriptor_fetches':18,'flat_idma_requests':70,'axi_beats_each_direction':256,'ddr_read_bytes':12288,'ddr_write_bytes':4096,'shared_l2_read_beats':192,'shared_l2_write_beats':64,'Q_values':1536,'K_values':256,'V_values':256,'bf16_bit_exact':2048,'checks':checks,'provenance':{'log_sha256':sha(path),'top_sha256':sha('rtl/integration/qwen2_bias_stage_top.sv'),'payload_sha256':sha('rtl/integration/qwen2_shared_l2_bias_payload.sv'),'context_sha256':sha('rtl/integration/qwen2_bias_descriptor_context.sv')},'open':['same_run_raw_QKV_to_bias','Q_K_RoPE','first_nine_event_chain'],'non_claims':['standalone stage preloads raw projection inputs','raw projection and bias are not yet one VCS run','RoPE remains separate']};out=ROOT/'reports/execution/qwen2_bias_stage_vcs_result.json';out.write_text(json.dumps(r,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':r['status'],'bit_exact':2048,'commands':3},sort_keys=True))
