#!/usr/bin/env python3
import argparse,json,struct
from pathlib import Path
import numpy as np
def bits(x):return struct.unpack('<I',struct.pack('<f',float(np.float32(x))))[0]
def main():
 p=argparse.ArgumentParser();p.add_argument('--svh',type=Path,required=True);p.add_argument('--json',type=Path,required=True);p.add_argument('--cpp',type=Path);p.add_argument('--python',type=Path);p.add_argument('--segments',type=int,default=256);p.add_argument('--input-min',type=float,default=-16.0);p.add_argument('--function-name',default='exp2_pwl_coeff');a=p.parse_args();coeff=[];max_abs=0.;max_rel=0.;worst=0.;step=-a.input_min/a.segments;index_bits=max(1,(a.segments-1).bit_length())
 if a.segments<=0 or a.input_min>=0:raise SystemExit('range')
 for i in range(a.segments):
  x0=np.float32(a.input_min+i*step);x1=np.float32(x0+np.float32(step));y0=np.float32(np.exp2(x0));y1=np.float32(np.exp2(x1))
  m=np.float32((np.float64(y1)-np.float64(y0))/step);b=np.float32(np.float64(y0)-np.float64(m)*np.float64(x0));coeff.append((m,b))
  xs=np.linspace(float(x0),float(x1),4097,dtype=np.float32);got=np.float32(np.float32(m*xs)+b);ref=np.exp2(xs.astype(np.float64));ae=np.abs(got.astype(np.float64)-ref);re=ae/ref
  j=int(np.argmax(re));
  if float(re[j])>max_rel:max_rel=float(re[j]);worst=float(xs[j])
  max_abs=max(max_abs,float(np.max(ae)))
 lines=['// Generated by scripts/generate_exp2_pwl_coeffs.py',f'function automatic logic [63:0] {a.function_name}(input logic [{index_bits-1}:0] index);','  case(index)']
 for i,(m,b) in enumerate(coeff):lines.append(f"    {index_bits}'d{i}: {a.function_name}=64'h{bits(m):08x}{bits(b):08x};")
 lines+=[f"    default: {a.function_name}=64'h0000000000000000;",'  endcase','endfunction']
 a.svh.parent.mkdir(parents=True,exist_ok=True);a.svh.write_text('\n'.join(lines)+'\n')
 packed=[bits(m)<<32|bits(b) for m,b in coeff]
 if a.cpp:
  a.cpp.parent.mkdir(parents=True,exist_ok=True)
  cpp=['#pragma once','#include <array>','#include <cstdint>',f'static constexpr std::array<uint64_t,{a.segments}> kCoeff={{']
  cpp.extend(f'UINT64_C(0x{x:016x}),' for x in packed);cpp.append('};')
  a.cpp.write_text('\n'.join(cpp)+'\n')
 if a.python:
  a.python.parent.mkdir(parents=True,exist_ok=True)
  py=['"""Generated by scripts/generate_exp2_pwl_coeffs.py; do not edit."""','EXP2_PWL_COEFF = (']
  py.extend(f'    0x{x:016x},' for x in packed);py.append(')')
  a.python.write_text('\n'.join(py)+'\n')
 result={'segments':a.segments,'input_min':a.input_min,'input_max':0.0,'step':step,'below_min':0.0,'at_or_above_max':1.0,
  'operation_order':'float32(m*x) then float32(+b)','max_absolute_error_dense':max_abs,'max_relative_error_dense':max_rel,'worst_relative_x':worst,
  'absolute_threshold':0.00025,'relative_threshold':0.0003,'threshold_pass':max_abs<=0.00025 and max_rel<=0.0003}
 a.json.parent.mkdir(parents=True,exist_ok=True);a.json.write_text(json.dumps(result,indent=2)+'\n')
 if not result['threshold_pass']:raise SystemExit(f"EXP2_PWL_COEFF_FAIL {result}")
 print(f"EXP2_PWL_COEFF_PASS segments={a.segments} input_min={a.input_min:g} max_abs={max_abs:.9g} max_rel={max_rel:.9g} worst_x={worst:.6f}")
if __name__=='__main__':main()
