#!/usr/bin/env python3
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OWNERS=[
 (0,'control','operator_control_endpoint_v3','rtl/integration/operator_control_endpoint_v3.sv'),
 (1,'dma','operator_dma_endpoint_v3','rtl/integration/operator_dma_endpoint_v3.sv'),
 (2,'matrix','operator_matrix_owner_endpoint_v3','rtl/integration/operator_matrix_owner_endpoint_v3.sv'),
 (3,'sfu','operator_sfu_owner_endpoint_v3','rtl/integration/operator_sfu_owner_endpoint_v3.sv'),
 (4,'kv','operator_kv_memory_endpoint_v3','rtl/integration/operator_kv_memory_endpoint_v3.sv'),
 (5,'state','operator_state_endpoint_v3','rtl/integration/operator_state_endpoint_v3.sv'),
 (6,'selection','operator_selection_endpoint_v3','rtl/integration/operator_selection_endpoint_v3.sv'),
 (7,'vision','operator_vision_endpoint_v3','rtl/integration/operator_vision_endpoint_v3.sv')]
COMMON={'clk_i','rst_ni','req_valid_i','req_ready_o','req_opcode_i','req_tag_i','req_parent_phase_i','req_terminal_phase_i','completion_valid_o','completion_ready_i','completion_tag_o','completion_parent_phase_o','completion_terminal_phase_o','completion_status_o'}
REQMAP={
 'req_index0_i':'index0','req_flags_i':'flags','req_src0_i':'src0','req_src1_i':'src1','req_src2_i':'src2','req_dst_i':'dst',
 'req_rows_i':'rows','req_columns_i':'columns','req_depth_i':'depth','req_variant_i':'variant'}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def balanced(s,start):
 d=0
 for i in range(start,len(s)):
  if s[i]=='(':d+=1
  elif s[i]==')':
   d-=1
   if d==0:return i
 raise ValueError('unbalanced')
def header(path,module):
 s=path.read_text();m=re.search(rf'\bmodule\s+{re.escape(module)}\b',s)
 if not m:raise ValueError(f'{module} missing')
 p=s.find('(',m.end());
 if s[m.end():p].strip().startswith('#'):p=s.find('(',balanced(s,p)+1)
 e=balanced(s,p);return s[m.start():e+2],s[p+1:e]
def split_ports(body):
 out=[];start=0;d=0
 for i,ch in enumerate(body):
  if ch in '([{':d+=1
  elif ch in ')]}':d-=1
  elif ch==',' and d==0:out.append(body[start:i]);start=i+1
 out.append(body[start:]);return out
def ports(path,module):
 _,body=header(path,module);body=re.sub(r'//.*','',body);result=[];direction=kind='';
 for raw in split_ports(body):
  x=' '.join(raw.split());m=re.match(r'^(input|output|inout)\s+(.*)$',x)
  if m:direction=m.group(1);rest=m.group(2);nm=re.search(r'([A-Za-z_]\w*)$',rest);name=nm.group(1);kind=rest[:nm.start()].strip()
  else:name=re.search(r'([A-Za-z_]\w*)$',x).group(1)
  if name=='ack_domain_i' and 'DOMAIN' in kind:kind='logic [3:0]'
  result.append((direction,kind,name))
 return result
def decl(direction,kind,name):return f'  {direction} {kind} {name}'.replace('  ',' ',1)
def main():
 parsed={};headers={}
 for idx,prefix,module,rel in OWNERS:
  path=ROOT/rel;headers[module]=header(path,module)[0];parsed[module]=ports(path,module)
 ext=[]
 for idx,prefix,module,rel in OWNERS:
  for direction,kind,name in parsed[module]:
   if name in COMMON or name in REQMAP:continue
   if name.startswith('req_'):raise SystemExit(f'unmapped request field {module}.{name}')
   ext.append((direction,kind,f'{prefix}_{name}'))
 common=[('input','logic','clk_i'),('input','logic','rst_ni'),('input','logic','terminal_valid_i'),('output','logic','terminal_ready_o'),
  ('input','logic [3:0]','terminal_owner_i'),('input','logic [7:0]','terminal_opcode_i'),('input','logic [15:0]','terminal_tag_i'),('input','logic [7:0]','terminal_parent_phase_i'),('input','logic [7:0]','terminal_terminal_phase_i'),('input','logic [15:0]','terminal_flags_i'),('input','logic [7:0]','terminal_mode_i'),('input','logic [23:0]','terminal_src0_i'),('input','logic [23:0]','terminal_src1_i'),('input','logic [23:0]','terminal_src2_i'),('input','logic [23:0]','terminal_dst_i'),('input','logic [15:0]','terminal_rows_i'),('input','logic [15:0]','terminal_columns_i'),('input','logic [15:0]','terminal_depth_i'),('input','logic [15:0]','terminal_index0_i'),('input','logic [15:0]','terminal_index1_i'),('input','logic','terminal_scratch_valid_i'),('input','logic [3:0]','terminal_scratch_src0_i'),('input','logic [3:0]','terminal_scratch_src1_i'),('input','logic [3:0]','terminal_scratch_dst_i'),('input','logic [7:0]','terminal_variant_i'),('input','logic','terminal_first_i'),('input','logic','terminal_last_i'),('output','logic','completion_valid_o'),('input','logic','completion_ready_i'),('output','logic [15:0]','completion_tag_o'),('output','logic [7:0]','completion_parent_phase_o'),('output','logic [7:0]','completion_terminal_phase_o'),('output','logic [7:0]','completion_status_o'),('output','logic','router_busy_o'),('output','logic','router_protocol_error_o')]
 lines=['// Generated by scripts/generate_operator_endpoint_bound_shell_v3.py; do not edit.','module operator_endpoint_bound_owner_shell_v3(']
 allp=common+ext
 for n,(d,k,name) in enumerate(allp):lines.append(decl(d,k,name)+(',' if n+1<len(allp) else ''))
 lines+=[');',' logic[7:0]ov,ordy,ccv,ccr;logic[8*8-1:0]oop,opp,otp,ocs,ovariant;logic[8*16-1:0]otag,oflags,oindex0,orows,ocols,odepth,ctag;logic[8*24-1:0]osrc0,osrc1,osrc2,odst;logic[8*8-1:0]cp,ct;']
 rp=['.clock(clk_i)','.reset(!rst_ni)',".io_clear(1'b0)",'.io_in_ready(terminal_ready_o)','.io_in_valid(terminal_valid_i)','.io_in_bits_owner(terminal_owner_i)','.io_in_bits_opcode(terminal_opcode_i)','.io_in_bits_tag(terminal_tag_i)','.io_in_bits_parentPhase(terminal_parent_phase_i)','.io_in_bits_terminalPhase(terminal_terminal_phase_i)','.io_in_bits_flags(terminal_flags_i)','.io_in_bits_mode(terminal_mode_i)','.io_in_bits_src0(terminal_src0_i)','.io_in_bits_src1(terminal_src1_i)','.io_in_bits_src2(terminal_src2_i)','.io_in_bits_dst(terminal_dst_i)','.io_in_bits_rows(terminal_rows_i)','.io_in_bits_columns(terminal_columns_i)','.io_in_bits_depth(terminal_depth_i)','.io_in_bits_index0(terminal_index0_i)','.io_in_bits_index1(terminal_index1_i)','.io_in_bits_scratchValid(terminal_scratch_valid_i)','.io_in_bits_scratchSrc0(terminal_scratch_src0_i)','.io_in_bits_scratchSrc1(terminal_scratch_src1_i)','.io_in_bits_scratchDst(terminal_scratch_dst_i)','.io_in_bits_variant(terminal_variant_i)','.io_in_bits_first(terminal_first_i)','.io_in_bits_last(terminal_last_i)']
 for i in range(8):
  rp += [f'.io_owner_{i}_ready(ordy[{i}])',f'.io_owner_{i}_valid(ov[{i}])',f'.io_owner_{i}_bits_opcode(oop[{i}*8+:8])',f'.io_owner_{i}_bits_tag(otag[{i}*16+:16])',f'.io_owner_{i}_bits_parentPhase(opp[{i}*8+:8])',f'.io_owner_{i}_bits_terminalPhase(otp[{i}*8+:8])',f'.io_owner_{i}_bits_flags(oflags[{i}*16+:16])',f'.io_owner_{i}_bits_src0(osrc0[{i}*24+:24])',f'.io_owner_{i}_bits_src1(osrc1[{i}*24+:24])',f'.io_owner_{i}_bits_src2(osrc2[{i}*24+:24])',f'.io_owner_{i}_bits_dst(odst[{i}*24+:24])',f'.io_owner_{i}_bits_rows(orows[{i}*16+:16])',f'.io_owner_{i}_bits_columns(ocols[{i}*16+:16])',f'.io_owner_{i}_bits_depth(odepth[{i}*16+:16])',f'.io_owner_{i}_bits_index0(oindex0[{i}*16+:16])',f'.io_owner_{i}_bits_variant(ovariant[{i}*8+:8])',f'.io_ownerCompletion_{i}_ready(ccr[{i}])',f'.io_ownerCompletion_{i}_valid(ccv[{i}])',f'.io_ownerCompletion_{i}_bits_tag(ctag[{i}*16+:16])',f'.io_ownerCompletion_{i}_bits_parentPhase(cp[{i}*8+:8])',f'.io_ownerCompletion_{i}_bits_terminalPhase(ct[{i}*8+:8])',f'.io_ownerCompletion_{i}_bits_status(ocs[{i}*8+:8])']
 rp += ['.io_completion_ready(completion_ready_i)','.io_completion_valid(completion_valid_o)','.io_completion_bits_tag(completion_tag_o)','.io_completion_bits_parentPhase(completion_parent_phase_o)','.io_completion_bits_terminalPhase(completion_terminal_phase_o)','.io_completion_bits_status(completion_status_o)','.io_busy(router_busy_o)','.io_protocolError(router_protocol_error_o)']
 lines += [' HeteroV3TerminalOwnerRouter router('+','.join(rp)+');']
 cmap={'clk_i':'clk_i','rst_ni':'rst_ni','req_valid_i':None,'req_ready_o':None,'req_opcode_i':None,'req_tag_i':None,'req_parent_phase_i':None,'req_terminal_phase_i':None,'completion_valid_o':None,'completion_ready_i':None,'completion_tag_o':None,'completion_parent_phase_o':None,'completion_terminal_phase_o':None,'completion_status_o':None}
 for idx,prefix,module,rel in OWNERS:
  con=[]
  for direction,kind,name in parsed[module]:
   if name=='clk_i' or name=='rst_ni':sig=name
   elif name=='req_valid_i':sig=f'ov[{idx}]'
   elif name=='req_ready_o':sig=f'ordy[{idx}]'
   elif name=='req_opcode_i':sig=f'oop[{idx}*8+:8]'
   elif name=='req_tag_i':sig=f'otag[{idx}*16+:16]'
   elif name=='req_parent_phase_i':sig=f'opp[{idx}*8+:8]'
   elif name=='req_terminal_phase_i':sig=f'otp[{idx}*8+:8]'
   elif name=='completion_valid_o':sig=f'ccv[{idx}]'
   elif name=='completion_ready_i':sig=f'ccr[{idx}]'
   elif name=='completion_tag_o':sig=f'ctag[{idx}*16+:16]'
   elif name=='completion_parent_phase_o':sig=f'cp[{idx}*8+:8]'
   elif name=='completion_terminal_phase_o':sig=f'ct[{idx}*8+:8]'
   elif name=='completion_status_o':sig=f'ocs[{idx}*8+:8]'
   elif name in REQMAP:
    fld=REQMAP[name];width={'flags':16,'src0':24,'src1':24,'src2':24,'dst':24,'rows':16,'columns':16,'depth':16,'index0':16,'variant':8}[fld];arr={'flags':'oflags','src0':'osrc0','src1':'osrc1','src2':'osrc2','dst':'odst','rows':'orows','columns':'ocols','depth':'odepth','index0':'oindex0','variant':'ovariant'}[fld];sig=f'{arr}[{idx}*{width}+:{width}]'
   else:sig=f'{prefix}_{name}'
   con.append(f'.{name}({sig})')
  lines.append(f' {module} {prefix}_owner('+','.join(con)+');')
 lines.append('endmodule\n')
 out=ROOT/'generated/operator_endpoint_shell_v3';out.mkdir(parents=True,exist_ok=True);sv=out/'operator_endpoint_bound_owner_shell_v3.sv';sv.write_text('\n'.join(lines))
 bb=ROOT/'dc/blackboxes/operator_owner_endpoints_v3_blackboxes.sv';bb.parent.mkdir(parents=True,exist_ok=True);bb.write_text('\n\n'.join(headers[m]+'\nendmodule' for _,_,m,_ in OWNERS)+'\n')
 manifest={'schema_version':1,'top':str(sv.relative_to(ROOT)),'top_sha256':sha(sv),'blackboxes':str(bb.relative_to(ROOT)),'blackboxes_sha256':sha(bb),'owners':{m:{'index':i,'source':r,'source_sha256':sha(ROOT/r)} for i,p,m,r in OWNERS},'generated_rtl_hand_edited':False}
 (out/'manifest.json').write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n');print(json.dumps(manifest,sort_keys=True))
if __name__=='__main__':main()
