#!/usr/bin/env python3
import argparse, json, math, random, struct
from pathlib import Path

def f32(x): return struct.unpack('<f', struct.pack('<f', float(x)))[0]
def bits(x): return struct.unpack('<I', struct.pack('<f', f32(x)))[0]
def from_bits(x): return struct.unpack('<f', struct.pack('<I', x))[0]
def softplus(x):
    x=f32(x)
    if x >= 16.0: return x
    if x <= -16.0: return f32(0.0)
    return f32(math.log1p(math.exp(x)))
def gelu(x):
    x=f32(x)
    if x >= 8.0: return x
    if x <= -8.0: return f32(0.0)
    c=f32(math.sqrt(2.0/math.pi))
    return f32(f32(0.5*x)*f32(1.0+math.tanh(f32(c*f32(x+f32(0.044715*f32(x*x*x)))))))
def table(fn, lo, step):
    out=[]
    for i in range(128):
        x0=f32(lo+i*step); x1=f32(x0+step); y0=fn(x0); y1=fn(x1)
        m=f32(f32(y1-y0)/step); b=f32(y0-f32(m*x0)); out.append((bits(m),bits(b)))
    return out
def eval_pwl(x, variant, tables):
    x=f32(x)
    if math.isnan(x): return from_bits(bits(x)|0x00400000)
    if variant==1:
        if x <= -16.0: return f32(0.0)
        if x >= 16.0: return x
        idx=max(0,min(127,math.floor(x*4.0)+64))
    else:
        if x <= -8.0: return f32(0.0)
        if x >= 8.0: return x
        idx=max(0,min(127,math.floor(x*8.0)+64))
    m,b=tables[variant][idx]
    return f32(f32(from_bits(m)*x)+from_bits(b))
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--svh',required=True);ap.add_argument('--vectors',required=True);ap.add_argument('--manifest',required=True);a=ap.parse_args()
    tables={1:table(softplus,-16.0,0.25),2:table(gelu,-8.0,0.125)}
    lines=['// Generated by scripts/generate_fp32_pwl_nonlinear.py; do not edit.','function automatic logic [63:0] fp32_pwl_coeff(input logic is_gelu,input logic[6:0] index);',' begin case({is_gelu,index})']
    for v in (1,2):
        for i,(m,b) in enumerate(tables[v]): lines.append(f"  8'h{((v==2)<<7)|i:02x}: fp32_pwl_coeff=64'h{m:08x}{b:08x};")
    lines += ["  default: fp32_pwl_coeff=64'h0000000000000000;"," endcase end","endfunction",""]
    Path(a.svh).parent.mkdir(parents=True,exist_ok=True);Path(a.svh).write_text('\n'.join(lines))
    rng=random.Random(0x47_800); values=[-math.inf,-32.0,-16.0,-8.0,-1.0,-0.0,0.0,1.0,8.0,16.0,32.0,math.inf]
    for _ in range(9988): values.append(f32(rng.uniform(-24.0,24.0)))
    with Path(a.vectors).open('w') as f:
        f.write('# variant input expected\n')
        for v in (1,2):
            for x in values: f.write(f'{v} {bits(x):08x} {bits(eval_pwl(x,v,tables)):08x}\n')
    metrics={}
    for v,fn,lo,hi in ((1,softplus,-24.0,24.0),(2,gelu,-12.0,12.0)):
        max_abs=0.0;arg=0.0
        for i in range(200001):
            x=f32(lo+(hi-lo)*i/200000);err=abs(float(eval_pwl(x,v,tables))-float(fn(x)))
            if err>max_abs:max_abs,arg=err,x
        metrics[str(v)]={'name':'softplus' if v==1 else 'tanh_gelu','segments':128,'range':[-16,16] if v==1 else [-8,8],'max_abs_error':max_abs,'argmax':arg}
    manifest={'schema_version':1,'variants':{'1':'softplus','2':'tanh_gelu'},'vectors_per_variant':len(values),'total_vectors':2*len(values),'metrics':metrics,'coefficient_format':'FP32 slope/intercept, FP32 mul then add'}
    Path(a.manifest).parent.mkdir(parents=True,exist_ok=True);Path(a.manifest).write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n')
    print(json.dumps(manifest,sort_keys=True))
if __name__=='__main__':main()
