#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);R=$ROOT/scripts/run_memory_capped.sh;V=$ROOT/work/toolchain/conda/bin/verilator;PY=$ROOT/work/toolchain/cnn_py312/bin/python
"$ROOT/scripts/generate_fp32_primitives.sh";taskset -c 8-25 "$PY" "$ROOT/scripts/generate_rsqrt_pwl_coeffs.py" --svh "$ROOT/rtl/sfu/fp32_rsqrt_coeffs.svh" --json "$ROOT/config/fp32_rsqrt_coeffs.json"
A=$ROOT/work/results/l5_rmsnorm;mkdir -p "$A";taskset -c 8-25 "$PY" "$ROOT/scripts/generate_rmsnorm_vectors.py" --output "$A/vectors.memh" --manifest "$A/vectors.json"
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$V" --lint-only --timing -Wall -Wno-DECLFILENAME -Wno-TIMESCALEMOD -Wno-UNUSEDSIGNAL --top-module tb_fp32_rmsnorm16 "$ROOT/work/generated/l5_fp32_primitives/HeteroFP32Primitives.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rmsnorm16.sv" "$ROOT/tb/tb_fp32_rmsnorm16.sv" >"$A/lint.log" 2>&1
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$V" --binary --timing -Wall -Wno-DECLFILENAME -Wno-TIMESCALEMOD -Wno-UNUSEDSIGNAL -j 4 -MAKEFLAGS "AR=/usr/bin/ar CXX=/usr/bin/g++" --top-module tb_fp32_rmsnorm16 --Mdir "$A/obj" -o tb "$ROOT/work/generated/l5_fp32_primitives/HeteroFP32Primitives.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rmsnorm16.sv" "$ROOT/tb/tb_fp32_rmsnorm16.sv" >"$A/build.log" 2>&1;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$A/obj/tb"|tee "$A/tb.log"
B=$ROOT/work/results/l5_silu;mkdir -p "$B";taskset -c 8-25 "$PY" "$ROOT/scripts/generate_silu_vectors.py" --output "$B/vectors.memh" --manifest "$B/vectors.json"
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$V" --lint-only --timing -Wall -Wno-DECLFILENAME -Wno-TIMESCALEMOD -Wno-UNUSEDSIGNAL --top-module tb_fp32_silu "$ROOT/work/generated/l5_fp32_primitives/HeteroFP32Primitives.sv" "$ROOT/rtl/sfu/fp32_exp2_pwl.sv" "$ROOT/rtl/sfu/fp32_reciprocal_nr.sv" "$ROOT/rtl/sfu/fp32_silu.sv" "$ROOT/tb/tb_fp32_silu.sv" >"$B/lint.log" 2>&1
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$V" --binary --timing -Wall -Wno-DECLFILENAME -Wno-TIMESCALEMOD -Wno-UNUSEDSIGNAL -j 4 -MAKEFLAGS "AR=/usr/bin/ar CXX=/usr/bin/g++" --top-module tb_fp32_silu --Mdir "$B/obj" -o tb "$ROOT/work/generated/l5_fp32_primitives/HeteroFP32Primitives.sv" "$ROOT/rtl/sfu/fp32_exp2_pwl.sv" "$ROOT/rtl/sfu/fp32_reciprocal_nr.sv" "$ROOT/rtl/sfu/fp32_silu.sv" "$ROOT/tb/tb_fp32_silu.sv" >"$B/build.log" 2>&1;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$B/obj/tb"|tee "$B/tb.log"
grep -q 'FP32_RMSNORM16_PASS vectors=10000' "$A/tb.log";grep -q 'FP32_SILU_PASS vectors=10000' "$B/tb.log";echo L5_RMSNORM_SILU_GATE_PASS
