#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);IDMA=${IDMA_ROOT:-$ROOT/work/upstream/idma};VD=$IDMA/target/sim/vcs;OUT=${OUT:-$ROOT/work/results/qwen2_kv_projection_pingpong};R=$ROOT/scripts/run_memory_capped.sh;mkdir -p "$OUT"
[[ $(git -C "$IDMA" rev-parse HEAD) == 2e0b0fe53b6f8823319e2428e2e9abc2db149b7d ]];[[ -z $(git -C "$IDMA" status --porcelain) ]]
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_macro_vectors.py" --packed-records "$ROOT/work/generated/qwen2_q1024_descriptor_image/packed_records.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_projection_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_kv_projection_vectors.py"
AXI_INC=$(find "$IDMA/.bender/git/checkouts" -maxdepth 2 -path '*/axi-*/include'|head -n1);C=$ROOT/rtl/matrix/candidates;cd "$VD"
run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$R" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";}
S=("$ROOT/rtl/integration/idma_backend_rw_axi_flat_wrap.sv" "$ROOT/rtl/integration/qwen2_tile_idma_expand.sv" "$ROOT/rtl/integration/qwen2_axi_shared_l2_bridge.sv" "$ROOT/rtl/fabric/shared_l2_fabric.sv" "$ROOT/rtl/fabric/shared_l2_descriptor_port.sv" "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$C/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$C/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/integration/qwen2_matrix_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_projection_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_tile_dma_plan.sv" "$ROOT/rtl/integration/qwen2_shared_l2_tile_payload.sv" "$ROOT/rtl/integration/qwen2_projection_pingpong_top.sv" "$ROOT/tb/tb_qwen2_kv_projection_pingpong.sv")
run 600s vlogan -sverilog -full64 +define+USE_UPSTREAM_IDMA +define+SYNTHESIS +incdir+../../../src/include +incdir+"$AXI_INC" +incdir+"$ROOT" "${S[@]}" >"$OUT/vlogan.log" 2>&1
VEC=$ROOT/work/results/qwen2_kv_projection_vectors;NORM=$ROOT/work/results/qwen2_shared_l2_tile_payload/norm_expected_beats.memh
for spec in 'k 1' 'v 2';do set -- $spec;kind=$1;idx=$2;run 600s vcs -full64 -top tb_qwen2_kv_projection_pingpong -pvalue+tb_qwen2_kv_projection_pingpong.PROJECTION=$idx -o simv_${kind}_projection >"$OUT/vcs_${kind}.log" 2>&1;run 600s ./simv_${kind}_projection +BEATS="$OUT/beats.memh" +COMMANDS="$OUT/projection_commands.memh" +ADDR="$OUT/projection_addresses.memh" +NORM="$NORM" +WEIGHTS="$VEC/${kind}_weight_all_tiles.memh" +EXPECTED="$VEC/${kind}_raw_expected_beats.memh"|tee "$OUT/${kind}.log";grep -q "QWEN2_KV_PROJECTION_PINGPONG_PASS projection=$idx" "$OUT/${kind}.log";done
