#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);IDMA=${IDMA_ROOT:-$ROOT/work/upstream/idma};VCS_DIR=$IDMA/target/sim/vcs
OUT=${OUT:-$ROOT/work/results/qwen2_idma_descriptor_compute_top};R=$ROOT/scripts/run_memory_capped.sh;mkdir -p "$OUT"
FULL_Q=${FULL_Q:-0}
[[ $(git -C "$IDMA" rev-parse HEAD) == 2e0b0fe53b6f8823319e2428e2e9abc2db149b7d ]];[[ -z $(git -C "$IDMA" status --porcelain) ]];[[ -d "$VCS_DIR/AN.DB" ]]
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_macro_vectors.py" --packed-records "$ROOT/work/generated/qwen2_q1024_descriptor_image/packed_records.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_shared_l2_tile_vectors.py"
AXI_INC=$(find "$IDMA/.bender/git/checkouts" -maxdepth 2 -path '*/axi-*/include'|head -n1);C=$ROOT/rtl/matrix/candidates;cd "$VCS_DIR"
run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$R" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";}
S=("$ROOT/rtl/integration/idma_backend_rw_axi_flat_wrap.sv" "$ROOT/rtl/integration/qwen2_tile_idma_expand.sv" "$ROOT/rtl/integration/qwen2_axi_shared_l2_bridge.sv" "$ROOT/rtl/fabric/shared_l2_fabric.sv" "$ROOT/rtl/fabric/shared_l2_descriptor_port.sv" "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$C/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$C/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/integration/qwen2_sfu_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_matrix_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_descriptor_tile_context.sv" "$ROOT/rtl/integration/qwen2_tile_dma_plan.sv" "$ROOT/rtl/integration/qwen2_shared_l2_tile_payload.sv" "$ROOT/rtl/integration/qwen2_descriptor_shared_l2_tile_top.sv" "$ROOT/tb/tb_qwen2_idma_descriptor_compute_top.sv")
run 600s vlogan -sverilog -full64 +define+USE_UPSTREAM_IDMA +define+SYNTHESIS +incdir+../../../src/include +incdir+"$AXI_INC" +incdir+"$ROOT" "${S[@]}" >"$OUT/vlogan.log" 2>&1
PARGS=();[[ "$FULL_Q" == 1 ]]&&PARGS+=("-pvalue+tb_qwen2_idma_descriptor_compute_top.FULL_Q=1")
run 600s vcs -full64 -top tb_qwen2_idma_descriptor_compute_top "${PARGS[@]}" -o simv_qwen2_compute >"$OUT/vcs.log" 2>&1
VEC=$ROOT/work/results/qwen2_shared_l2_tile_payload
run 600s ./simv_qwen2_compute +ADDR_MEM="$OUT/addresses.memh" +HIDDEN="$VEC/hidden_beats.memh" +NORM_WEIGHT="$VEC/rms_weight_beats.memh" +Q_WEIGHT="$VEC/q_weight_beats.memh" +Q_WEIGHT_ALL="$VEC/q_weight_all_tiles.memh" +EXPECTED="$VEC/norm_expected_beats.memh" +DESCRIPTOR_BEATS="$OUT/beats.memh" +COMMANDS="$OUT/commands.memh" +Q_OUT="$VEC/q_expected_beat.memh" +Q_OUT_ALL="$VEC/q_expected_all_beats.memh"|tee "$OUT/tb.log"
if [[ "$FULL_Q" == 1 ]];then grep -q 'QWEN2_FULL_Q_TOKEN_SINGLE_COMMAND_PASS physical_columns=1536' "$OUT/tb.log";else grep -q 'QWEN2_IDMA_DESCRIPTOR_COMPUTE_TOP_PASS commands=2 descriptor_fetches=12' "$OUT/tb.log";fi
