#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);OUT=${CANARY_OUT:-$ROOT/work/results/qwen2_root_owner_canary_v3};RUN=$ROOT/scripts/run_memory_capped.sh;V=$ROOT/work/toolchain/conda/bin/verilator;ROOT_RTL=${ROOT_RTL:-$ROOT/generated/operator_primitives_v3/roots/HeteroQwen2DecoderBlockPrimitiveV3.sv};EXPECTED_MARKER=${EXPECTED_MARKER:-QWEN2_ROOT_OWNER_CANARY_V3_PASS};DEFINES=();if [[ -n ${ROOT_DEFINE:-} ]];then DEFINES+=("-D$ROOT_DEFINE");fi;mkdir -p "$OUT"
S=(
 "$ROOT_RTL"
 "$ROOT/generated/operator_primitives_v3/bridge/HeteroV3TerminalBridge.sv" "$ROOT/generated/operator_primitives_v3/bridge/HeteroV3TerminalOwnerRouter.sv"
 "$ROOT/rtl/state/state_commit_barrier.sv" "$ROOT/rtl/integration/qwen2_tile_idma_expand.sv"
 "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/common/rv_fifo.sv"
 "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$ROOT/rtl/matrix/candidates/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv"
 "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv"
 "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_reduce_max16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_reciprocal_nr2.sv" "$ROOT/rtl/sfu/fp32_exp2_pwl_pipe.sv" "$ROOT/rtl/sfu/fp32_norm16_rms_l2_pipe.sv" "$ROOT/rtl/sfu/fp32_group_rmsnorm16_pipe.sv" "$ROOT/rtl/sfu/fp32_rope_pair_pipe.sv" "$ROOT/rtl/sfu/fp32_exp2_pwl_rawpipe.sv" "$ROOT/rtl/attention/fp32_block32_softmax_weights.sv" "$ROOT/rtl/sfu/fp32_mlo_merge_coeff_rawpipe.sv" "$ROOT/rtl/sfu/fp32_mlo_merge_beat_rawpipe.sv" "$ROOT/rtl/sfu/fp32_mlo_summary_merge_stream_rawpipe.sv" "$ROOT/rtl/sfu/fp32_mlo_summary_merge_stream.sv" "$ROOT/rtl/sfu/bf16_silu_mul_lut_lane.sv" "$ROOT/rtl/sfu/bf16_silu_mul_lut_array8_fixed.sv" "$ROOT/rtl/sfu/fp32_pwl_nonlinear_pipe.sv"
 "$ROOT/rtl/kv/kv_ddr_pte_resolver_v3.sv" "$ROOT/generated/operator_primitives_v3/primitives/state_transaction.sv" "$ROOT/rtl/selection/selection_topk_sram_v3.sv" "$ROOT/generated/operator_primitives_v3/primitives/moe_route_dispatch.sv" "$ROOT/generated/operator_primitives_v3/primitives/block_pool_address.sv" "$ROOT/generated/operator_primitives_v3/primitives/mtp_verify.sv"
 "$ROOT/generated/operator_primitives_v3/primitives/mrope_section_map.sv" "$ROOT/generated/operator_primitives_v3/primitives/vision_window_address.sv" "$ROOT/generated/operator_primitives_v3/primitives/vision_patch_merge_address.sv" "$ROOT/generated/operator_primitives_v3/primitives/vision_bilinear_index.sv" "$ROOT/generated/operator_primitives_v3/primitives/ple_ngram_hash.sv" "$ROOT/generated/operator_primitives_v3/primitives/vision_patch3d_address.sv"
 "$ROOT/rtl/integration/operator_control_endpoint_v3.sv" "$ROOT/rtl/integration/operator_dma_endpoint_v3.sv" "$ROOT/rtl/integration/operator_matrix_bf16_endpoint_v3.sv" "$ROOT/rtl/integration/operator_matrix_conv_gemmini_adapter_v3.sv" "$ROOT/rtl/integration/operator_matrix_owner_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_vector_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_scalar_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_norm_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_rope_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_online_softmax_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_gate_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_pwl_endpoint_v3.sv" "$ROOT/rtl/integration/operator_sfu_owner_endpoint_v3.sv" "$ROOT/rtl/integration/operator_kv_memory_endpoint_v3.sv" "$ROOT/rtl/integration/operator_state_endpoint_v3.sv" "$ROOT/rtl/integration/operator_selection_endpoint_v3.sv" "$ROOT/rtl/integration/operator_vision_endpoint_v3.sv"
 "$ROOT/rtl/common/operator_reset_fanout_branch_v3.sv" "$ROOT/generated/operator_endpoint_shell_v3/operator_endpoint_bound_owner_shell_v3.sv" "$ROOT/generated/operator_endpoint_shell_v3/operator_root_bridge_owner_shell_v3.sv" "$ROOT/tb/tb_qwen2_root_owner_canary_v3.sv")
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s 600s "$V" --binary --threads 4 --timing -Wall -I"$ROOT/rtl/sfu" -Wno-DECLFILENAME -Wno-TIMESCALEMOD -Wno-UNUSEDSIGNAL -Wno-UNOPTTHREADS -Wno-WIDTH -Wno-SYNCASYNCNET -Wno-PINCONNECTEMPTY -Wno-PINMISSING -Wno-MODDUP -j 4 -MAKEFLAGS "AR=/usr/bin/ar CXX=/usr/bin/g++" "${DEFINES[@]}" --top-module tb_qwen2_root_owner_canary_v3 --Mdir "$OUT/obj" -o tb "${S[@]}" >"$OUT/build.log" 2>&1
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s 600s "$OUT/obj/tb"|tee "$OUT/test.log"
grep -q "$EXPECTED_MARKER" "$OUT/test.log"
