#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);IDMA=${IDMA_ROOT:-$ROOT/work/upstream/idma};VD=$IDMA/target/sim/vcs;OUT=${OUT:-$ROOT/work/results/qwen2_group8_pinned_idma};RUN=$ROOT/scripts/run_memory_capped.sh;C=$ROOT/rtl/matrix/candidates;mkdir -p "$OUT";MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s 600s taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_canonical_tile16_vectors.py"|tee "$OUT/tile_vectors.log";MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s 600s taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_canonical_q_tile16_all.py"|tee "$OUT/q_vectors.log";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_macro_vectors.py" --packed-records "$ROOT/work/generated/qwen2_q1024_descriptor_image/packed_records.jsonl" --out "$OUT";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_projection_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
test "$(df --output=avail -k "$ROOT" | tail -1)" -gt 52428800
if [[ ${NUMERICAL_BATCHES:-2} == 2 ]]; then
 MIN_AVAILABLE_KIB=10485760 "$RUN" timeout 600 python3 "$ROOT/scripts/generate_qwen2_canonical_tile16_vectors.py" --token-start 16 --out "$ROOT/work/results/qwen2_true_rows16_31"
 MIN_AVAILABLE_KIB=10485760 "$RUN" timeout 600 python3 "$ROOT/scripts/generate_qwen2_canonical_q_tile16_all.py" --source "$ROOT/work/results/qwen2_true_rows16_31" --out "$ROOT/work/results/qwen2_true_rows16_31_projection"
fi
[[ $(git -C "$IDMA" rev-parse HEAD) == 2e0b0fe53b6f8823319e2428e2e9abc2db149b7d ]]
[[ -z $(git -C "$IDMA" status --porcelain) ]]
AXI_INC=$(find "$IDMA/.bender/git/checkouts" -maxdepth 2 -path '*/axi-*/include'|head -n1)
cd "$VD";run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";};S=("$ROOT/rtl/integration/idma_backend_rw_axi_flat_wrap.sv" "$ROOT/rtl/integration/qwen2_tile_idma_expand.sv" "$ROOT/rtl/integration/qwen2_axi_shared_l2_bridge.sv" "$ROOT/tb/models/ddr_beat_credit.sv" "$ROOT/tb/models/axi_ddr_100_40_800mhz.sv" "$ROOT/rtl/fabric/shared_l2_fabric.sv" "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$C/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$C/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/integration/qwen2_matrix_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_projection_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_shared_l2_rms_tile16_stager.sv" "$ROOT/rtl/integration/bf16_tile_transpose_stager.sv" "$ROOT/rtl/integration/qwen2_norm_tile16_loader.sv" "$ROOT/rtl/integration/qwen2_shared_l2_matrix_tile16_payload.sv" "$ROOT/rtl/integration/qwen2_projection_q1024_group8_controller.sv" "$ROOT/tb/tb_qwen2_group8_pinned_idma.sv")
DEBUG_ARGS=()
SIM_BINARY=simv_group8_pinned
if [[ ${CHECKPOINT_BUILD_ONLY:-0} == 1 ]]; then DEBUG_ARGS+=(-debug_access+r); SIM_BINARY=simv_group8_checkpoint; fi
run 600s vlogan -sverilog -full64 -timescale=1ns/1ps +define+SYNTHESIS +define+USE_UPSTREAM_IDMA +incdir+../../../src/include +incdir+"$AXI_INC" +incdir+"$ROOT" "${S[@]}" >"$OUT/vlogan.log" 2>&1;run 600s vcs -full64 "${DEBUG_ARGS[@]}" -top tb_qwen2_group8_pinned_idma -o "$SIM_BINARY" >"$OUT/vcs.log" 2>&1;cd "$ROOT";
if [[ ${CHECKPOINT_BUILD_ONLY:-0} == 1 ]]; then exit 0; fi
for projection_case in 0 1 2; do
 case "$projection_case" in 0) projection_kind=q;; 1) projection_kind=k;; 2) projection_kind=v;; esac
 run 600s "$VD/simv_group8_pinned" +PROJECTION="$projection_case" +COMMANDS="$OUT/projection_commands.memh" +RECORDS="$OUT/records.memh" +ADDR="$OUT/projection_addresses.memh" +BATCHES="${NUMERICAL_BATCHES:-2}" +NEXT_NORM="$ROOT/work/results/qwen2_true_rows16_31/norm_token_major.memh" +NEXT_EXPECTED="$ROOT/work/results/qwen2_true_rows16_31_projection/${projection_kind}_expected_token_major.memh" | tee "$OUT/tb_p${projection_case}.log"
 grep -q "GROUP8_PINNED_IDMA_NUMERICAL_PASS projection=$projection_case" "$OUT/tb_p${projection_case}.log"
done
