#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);IDMA=${IDMA_ROOT:-$ROOT/work/upstream/idma};VD=$IDMA/target/sim/vcs;OUT=${OUT:-$ROOT/work/results/qwen2_first9_tile16_pinned_idma};RUN=$ROOT/scripts/run_memory_capped.sh;C=$ROOT/rtl/matrix/candidates;mkdir -p "$OUT";[[ $(git -C "$IDMA" rev-parse HEAD) == 2e0b0fe53b6f8823319e2428e2e9abc2db149b7d ]];[[ -z $(git -C "$IDMA" status --porcelain) ]]
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s 600s taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_canonical_tile16_vectors.py"|tee "$OUT/tile_vectors.log";MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s 600s taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_canonical_q_tile16_all.py"|tee "$OUT/qkv_vectors.log"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_macro_vectors.py" --packed-records "$ROOT/work/generated/qwen2_q1024_descriptor_image/packed_records.jsonl" --out "$OUT";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_projection_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_bias_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_rope_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
AXI_INC=$(find "$IDMA/.bender/git/checkouts" -maxdepth 2 -path '*/axi-*/include'|head -n1);cd "$VD";run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";}
S=("$ROOT/rtl/integration/idma_backend_rw_axi_flat_wrap.sv" "$ROOT/rtl/integration/qwen2_tile_idma_expand.sv" "$ROOT/rtl/integration/qwen2_axi_shared_l2_bridge.sv" "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/sfu/bf16_bias_add_tile32.sv" "$ROOT/rtl/sfu/fp32_rope_pair.sv" "$ROOT/rtl/sfu/qwen2_rope_base_coeff64.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$C/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$C/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/integration/qwen2_matrix_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_rms_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_projection_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_bias_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_rope_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_shared_l2_rms_tile16_stager.sv" "$ROOT/rtl/integration/qwen2_shared_l2_matrix_tile16_payload.sv" "$ROOT/rtl/integration/qwen2_shared_l2_bias_payload.sv" "$ROOT/rtl/integration/qwen2_shared_l2_rope_payload.sv" "$ROOT/rtl/integration/qwen2_rms_tile16_controller.sv" "$ROOT/rtl/integration/qwen2_projection_tile16_controller.sv" "$ROOT/rtl/integration/qwen2_bias_tile16_controller.sv" "$ROOT/rtl/integration/qwen2_rope_tile16_controller.sv" "$ROOT/rtl/integration/qwen2_first9_tile16_controller.sv" "$ROOT/tb/tb_qwen2_first9_tile16_pinned_idma_vcs.sv")
S+=("$ROOT/rtl/fabric/shared_l2_fabric.sv")
run 600s vlogan -sverilog -full64 +define+USE_UPSTREAM_IDMA +define+SYNTHESIS +incdir+../../../src/include +incdir+"$AXI_INC" +incdir+"$ROOT" "${S[@]}" >"$OUT/vlogan.log" 2>&1;run 600s vcs -full64 -top tb_qwen2_first9_tile16_pinned_idma_vcs -o simv_first9_tile16_idma >"$OUT/vcs.log" 2>&1
cd "$ROOT";run 600s "$VD/simv_first9_tile16_idma" +RECORDS="$OUT/records.memh" +RMS="$OUT/commands.memh" +PROJ="$OUT/projection_commands.memh" +BIAS="$OUT/bias_commands.memh" +ROPE="$OUT/rope_commands.memh" +RMS_ADDR="$OUT/addresses.memh" +PROJ_ADDR="$OUT/projection_addresses.memh" +BIAS_ADDR="$OUT/bias_addresses.memh" +ROPE_ADDR="$OUT/rope_addresses.memh"|tee "$OUT/tb.log";! grep -q '^Error:' "$OUT/tb.log";grep -q 'QWEN2_FIRST9_TILE16_PINNED_IDMA_PASS commands=9 rows=16' "$OUT/tb.log"
