#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);IDMA=${IDMA_ROOT:-$ROOT/work/upstream/idma};VD=$IDMA/target/sim/vcs;OUT=${OUT:-$ROOT/work/results/qwen2_bias_stage_vcs};R=$ROOT/scripts/run_memory_capped.sh;mkdir -p "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_macro_vectors.py" --packed-records "$ROOT/work/generated/qwen2_q1024_descriptor_image/packed_records.jsonl" --out "$OUT";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_bias_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_shared_l2_tile_vectors.py";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_kv_projection_vectors.py"
AXI_INC=$(find "$IDMA/.bender/git/checkouts" -maxdepth 2 -path '*/axi-*/include'|head -n1);cd "$VD";run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$R" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";}
S=("$ROOT/rtl/integration/idma_backend_rw_axi_flat_wrap.sv" "$ROOT/rtl/integration/qwen2_tile_idma_expand.sv" "$ROOT/rtl/integration/qwen2_axi_shared_l2_bridge.sv" "$ROOT/rtl/fabric/shared_l2_fabric.sv" "$ROOT/rtl/fabric/shared_l2_descriptor_port.sv" "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/bf16_bias_add_tile32.sv" "$ROOT/rtl/integration/qwen2_bias_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_shared_l2_bias_payload.sv" "$ROOT/rtl/integration/qwen2_bias_stage_top.sv" "$ROOT/tb/tb_qwen2_bias_stage_vcs.sv")
run 600s vlogan -sverilog -full64 +define+USE_UPSTREAM_IDMA +define+SYNTHESIS +incdir+../../../src/include +incdir+"$AXI_INC" +incdir+"$ROOT" "${S[@]}" >"$OUT/vlogan.log" 2>&1;run 600s vcs -full64 -top tb_qwen2_bias_stage_vcs -o simv_bias >"$OUT/vcs.log" 2>&1
Q=$ROOT/work/results/qwen2_shared_l2_tile_payload;K=$ROOT/work/results/qwen2_kv_projection_vectors
run 600s ./simv_bias +BEATS="$OUT/beats.memh" +COMMANDS="$OUT/bias_commands.memh" +ADDR="$OUT/bias_addresses.memh" +Q_RAW="$Q/q_expected_all_beats.memh" +Q_BIAS="$Q/q_bias_fp32_beats.memh" +Q_EXPECT="$Q/q_biased_expected_all_beats.memh" +K_RAW="$K/k_raw_expected_beats.memh" +K_BIAS="$K/k_bias_fp32_beats.memh" +K_EXPECT="$K/k_biased_expected_beats.memh" +V_RAW="$K/v_raw_expected_beats.memh" +V_BIAS="$K/v_bias_fp32_beats.memh" +V_EXPECT="$K/v_biased_expected_beats.memh"|tee "$OUT/tb.log";grep -q 'QWEN2_BIAS_STAGE_VCS_PASS commands=3' "$OUT/tb.log"
