#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);DEFAULT_OUT=$ROOT/work/results/l5_q128_attention_integrated;if [[ ${MODE:-full} == sampled384 ]];then DEFAULT_OUT=$ROOT/work/results/l5_q384_attention_sampled;elif [[ ${MODE:-full} == sampled1024a || ${MODE:-full} == sampled1024b ]];then DEFAULT_OUT=$ROOT/work/results/l5_q1024_attention_sampled;fi;OUT=${OUT:-$DEFAULT_OUT};R=$ROOT/scripts/run_memory_capped.sh;V=${VERILATOR:-$ROOT/work/toolchain/conda/bin/verilator};PY=${PYTHON:-python3};mkdir -p "$OUT/vectors";MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$R" timeout --foreground --signal=INT --kill-after=30s 600s taskset -c 8-23 "$ROOT/scripts/generate_all_hardfloat_primitives.sh"
run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$R" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";}
SEQ=128;if [[ ${MODE:-full} == sampled384 ]];then SEQ=384;elif [[ ${MODE:-full} == sampled1024a || ${MODE:-full} == sampled1024b ]];then SEQ=1024;fi
run 600s env PYTHONPATH="$ROOT/src" "$PY" "$ROOT/scripts/generate_l5_q128_integrated_attention_vectors.py" --sequence "$SEQ" --out "$OUT/vectors" >"$OUT/vector_generation.log"
S=("$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/common/rv_fifo.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$ROOT/rtl/matrix/candidates/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/attention/blocked_attention_stream_controller.sv" "$ROOT/rtl/attention/fp32_probability_to_bf16_hilo.sv" "$ROOT/rtl/sfu/fp32_exp2_pwl_rawpipe.sv" "$ROOT/rtl/attention/fp32_block32_softmax_weights.sv" "$ROOT/rtl/sfu/fp32_mlo_merge_coeff_rawpipe.sv" "$ROOT/rtl/sfu/fp32_mlo_merge_beat_rawpipe.sv" "$ROOT/rtl/sfu/fp32_mlo_summary_merge_stream_rawpipe.sv" "$ROOT/rtl/sfu/fp32_reciprocal_nr.sv" "$ROOT/rtl/sfu/fp32_vector_alu.sv" "$ROOT/tb/tb_l5_q128_attention_integrated.sv")
run 600s "$V" --binary --threads 4 --timing -Wall -Wno-DECLFILENAME -Wno-TIMESCALEMOD -Wno-UNUSEDSIGNAL -Wno-SYNCASYNCNET -Wno-SHORTREAL -Wno-WIDTH -Wno-PINCONNECTEMPTY -Wno-PINMISSING -j 8 -MAKEFLAGS "AR=/usr/bin/ar CXX=/usr/bin/g++" --top-module tb_l5_q128_attention_integrated --Mdir "$OUT/obj" -o tb "${S[@]}" >"$OUT/build.log" 2>&1
if [[ ${BUILD_ONLY:-0} == 1 ]];then echo L5_ATTENTION_INTEGRATED_BUILD_ONLY_PASS;exit 0;fi
ARGS=(+VECTORS="$OUT/vectors");EXPECT='L5_Q128_SINGLE_SIM_E2_PASS rows=1536 tasks=240';TB_LOG=$OUT/tb.log;if [[ ${MODE:-full} == direct ]];then ARGS+=(+DIRECT_DIAG);EXPECT='L5_ONE_TASK_QK_SFU_PV_PASS rows=16 qk_steps=128 pv_steps=256';elif [[ ${MODE:-full} == sampled384 ]];then ARGS+=(+SAMPLED_384);EXPECT='L5_Q384_SAMPLED_E2_PASS compared_rows=2304 frozen_rows_covered=180 tasks=756 sampled_merge_rows=1728 controller_merge_rows=4608';elif [[ ${MODE:-full} == sampled1024a ]];then ARGS+=(+SAMPLED_1024 +SHARD=0);EXPECT='L5_Q1024_REVIEWED_SHARD_PASS shard=0 compared_rows=960 tasks=306 sampled_merge_rows=672 controller_tasks=12672 controller_merge_rows=43008';TB_LOG=$OUT/tb_shard0.log;elif [[ ${MODE:-full} == sampled1024b ]];then ARGS+=(+SAMPLED_1024 +SHARD=1);EXPECT='L5_Q1024_REVIEWED_SHARD_PASS shard=1 compared_rows=480 tasks=756 sampled_merge_rows=2688 controller_tasks=12672 controller_merge_rows=43008';TB_LOG=$OUT/tb_shard1.log;fi
run 600s "$OUT/obj/tb" "${ARGS[@]}"|tee "$TB_LOG";grep -q "$EXPECT" "$TB_LOG"
