#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);OUT=${OUT:-$ROOT/work/results/qwen2_real_payload_endpoint};R=$ROOT/scripts/run_memory_capped.sh;V=${VERILATOR:-$ROOT/work/toolchain/conda/bin/verilator};MACRO=$ROOT/work/generated/l10_sram/ct_sp_4096x128wm_base_0p8v_tt25/ctsp4096x128wm.v;mkdir -p "$OUT"
taskset -c 8-23 python3 - "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" "$ROOT/work/results/l5_qwen2_four_layer_reference/cross_vectors/expected.json" "$OUT" <<'PY'
import json,sys,pathlib
r=[json.loads(line)for line in open(sys.argv[1])];e=json.load(open(sys.argv[2]));o=pathlib.Path(sys.argv[3]);o.mkdir(parents=True,exist_ok=True);(o/'commands.memh').write_text(''.join(x['word'].removeprefix('0x')+'\n'for x in r[:2]));(o/'rms_expected.memh').write_text(''.join(x+'\n'for x in e['rms_bf16_bits'][:1536]));(o/'matrix_expected.memh').write_text(''.join(x+'\n'for x in e['matrix_bf16_bits'][:32]))
PY
C=$ROOT/rtl/matrix/candidates;S=("$ROOT/rtl/memory/ct_sp4096x128_macro_wrapper.sv" "$ROOT/rtl/common/rv_fifo.sv" "$ROOT/rtl/top/command_dispatch.sv" "$ROOT/rtl/integration/command_event_scoreboard_sram.sv" "$ROOT/rtl/integration/command_event_frontend_sram.sv" "$ROOT/rtl/integration/engine_completion_rr_arbiter.sv" "$ROOT/rtl/fabric/shared_l2_client_arbiter.sv" "$ROOT/rtl/integration/hetero_l3_command_fabric.sv" "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$C/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$C/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/integration/qwen2_sfu_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_matrix_command_endpoint.sv" "$ROOT/tb/tb_qwen2_real_payload_endpoint.sv")
run(){ local t=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$R" timeout --foreground --signal=INT --kill-after=30s "$t" "$@";}
run 600s "$V" --binary --timing --assert -Wall -Wno-fatal -Wno-DECLFILENAME -Wno-TIMESCALEMOD -Wno-UNUSEDSIGNAL -Wno-WIDTH -Wno-SYNCASYNCNET -Wno-PROCASSINIT -DARM_DISABLE_EMA_CHECK -j 8 -MAKEFLAGS "AR=/usr/bin/ar CXX=/usr/bin/g++" --top-module tb_qwen2_real_payload_endpoint --Mdir "$OUT/obj" -o tb "$MACRO" "${S[@]}">"$OUT/build.log" 2>&1
cd "$ROOT";run 600s "$OUT/obj/tb"|tee "$OUT/tb.log";grep -q 'QWEN2_REAL_PAYLOAD_ENDPOINT_PASS commands=2 completions=2 rms_values=1536 matrix_steps=1536 matrix_outputs=32 bf16_bit_exact=1568' "$OUT/tb.log"
