#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);IDMA=${IDMA_ROOT:-$ROOT/work/upstream/idma};VD=$IDMA/target/sim/vcs;OUT=${OUT:-$ROOT/work/results/qwen2_raw_qkv_chain};R=$ROOT/scripts/run_memory_capped.sh;mkdir -p "$OUT"
[[ $(git -C "$IDMA" rev-parse HEAD) == 2e0b0fe53b6f8823319e2428e2e9abc2db149b7d ]];[[ -z $(git -C "$IDMA" status --porcelain) ]]
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_macro_vectors.py" --packed-records "$ROOT/work/generated/qwen2_q1024_descriptor_image/packed_records.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_descriptor_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_projection_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_bias_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_rope_context_vectors.py" --manifest "$ROOT/reports/execution/llama_cpp_qwen2_graph_lowering_manifest.jsonl" --chains "$ROOT/work/generated/qwen2_q1024_symbolic_descriptors/descriptor_chains.jsonl" --out "$OUT"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_shared_l2_tile_vectors.py";taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_kv_projection_vectors.py"
taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_canonical_token01_vectors.py"
AXI_INC=$(find "$IDMA/.bender/git/checkouts" -maxdepth 2 -path '*/axi-*/include'|head -n1);C=$ROOT/rtl/matrix/candidates;cd "$VD";run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$R" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";}
S=("$ROOT/rtl/integration/idma_backend_rw_axi_flat_wrap.sv" "$ROOT/rtl/integration/qwen2_tile_idma_expand.sv" "$ROOT/rtl/integration/qwen2_axi_shared_l2_bridge.sv" "$ROOT/rtl/fabric/shared_l2_fabric.sv" "$ROOT/rtl/fabric/shared_l2_descriptor_port.sv" "$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/sfu/bf16_bias_add_tile32.sv" "$ROOT/rtl/sfu/fp32_rope_pair.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$C/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$C/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$C/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/integration/qwen2_sfu_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_matrix_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_tile_dma_plan.sv" "$ROOT/rtl/integration/qwen2_shared_l2_tile_payload.sv" "$ROOT/rtl/integration/qwen2_projection_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_projection_pingpong_top.sv" "$ROOT/rtl/integration/qwen2_rms_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_shared_l2_rms_payload.sv" "$ROOT/rtl/integration/qwen2_rms_stage_top.sv" "$ROOT/rtl/integration/qwen2_bias_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_shared_l2_bias_payload.sv" "$ROOT/rtl/integration/qwen2_bias_stage_top.sv" "$ROOT/rtl/integration/qwen2_rope_descriptor_context.sv" "$ROOT/rtl/integration/qwen2_shared_l2_rope_payload.sv" "$ROOT/rtl/integration/qwen2_rope_stage_top.sv" "$ROOT/tb/tb_qwen2_raw_qkv_chain.sv")
S+=("$ROOT/rtl/sfu/qwen2_rope_base_coeff64.sv")
run 600s vlogan -sverilog -full64 +define+USE_UPSTREAM_IDMA +define+SYNTHESIS +incdir+../../../src/include +incdir+"$AXI_INC" +incdir+"$ROOT" "${S[@]}" >"$OUT/vlogan.log" 2>&1
run 600s vcs -full64 -top tb_qwen2_raw_qkv_chain -o simv_raw_qkv >"$OUT/vcs.log" 2>&1
TOKEN_INDEX=${TOKEN_INDEX:-0};QV=$ROOT/work/results/qwen2_shared_l2_tile_payload;KV=$ROOT/work/results/qwen2_kv_projection_vectors;CAN=$ROOT/work/results/qwen2_canonical_token01_vectors/token$TOKEN_INDEX;POS=$ROOT/work/results/qwen2_canonical_token01_vectors/positions_0_15.memh
run 600s ./simv_raw_qkv +TOKEN_INDEX="$TOKEN_INDEX" +BEATS="$OUT/beats.memh" +RMS_COMMANDS="$OUT/commands.memh" +RMS_ADDR="$OUT/addresses.memh" +PROJ_COMMANDS="$OUT/projection_commands.memh" +PROJ_ADDR="$OUT/projection_addresses.memh" +BIAS_COMMANDS="$OUT/bias_commands.memh" +BIAS_ADDR="$OUT/bias_addresses.memh" +ROPE_COMMANDS="$OUT/rope_commands.memh" +ROPE_ADDR="$OUT/rope_addresses.memh" +POSITION0="$POS" +HIDDEN="$CAN/hidden_beats.memh" +NORM_WEIGHT="$QV/rms_weight_beats.memh" +Q_WEIGHT="$QV/q_weight_all_tiles.memh" +K_WEIGHT="$KV/k_weight_all_tiles.memh" +V_WEIGHT="$KV/v_weight_all_tiles.memh" +Q_EXPECT="$CAN/q_raw_expected.memh" +K_EXPECT="$CAN/k_raw_expected.memh" +V_EXPECT="$CAN/v_raw_expected.memh" +Q_BIAS="$QV/q_bias_fp32_beats.memh" +K_BIAS="$KV/k_bias_fp32_beats.memh" +V_BIAS="$KV/v_bias_fp32_beats.memh" +Q_BIASED="$CAN/q_biased_expected.memh" +K_BIASED="$CAN/k_biased_expected.memh" +V_BIASED="$CAN/v_biased_expected.memh" +Q_ROPE_EXPECT="$CAN/q_rope_expected.memh" +K_ROPE_EXPECT="$CAN/k_rope_expected.memh"|tee "$OUT/tb.log"
grep -q "QWEN2_FIRST9_CHAIN_PASS commands=9 descriptor_fetches=62.*token_index=$TOKEN_INDEX" "$OUT/tb.log"
