#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.."&&pwd);IDMA=${IDMA_ROOT:-$ROOT/work/upstream/idma};VD=$IDMA/target/sim/vcs;OUT=${OUT:-$ROOT/work/results/qwen2_rms_tile16_stager};RUN=$ROOT/scripts/run_memory_capped.sh;mkdir -p "$OUT"
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s 600s taskset -c 8-23 python3 "$ROOT/scripts/generate_qwen2_canonical_tile16_vectors.py"|tee "$OUT/vectors.log"
cd "$VD";run(){ local limit=$1;shift;MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=24G MEMORY_MAX=30G "$RUN" timeout --foreground --signal=INT --kill-after=30s "$limit" taskset -c 8-23 "$@";}
S=("$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/integration/qwen2_shared_l2_rms_tile16_stager.sv" "$ROOT/tb/tb_qwen2_rms_tile16_stager.sv")
run 600s vlogan -sverilog -full64 -timescale=1ns/1ps +define+SYNTHESIS +incdir+"$ROOT" "${S[@]}" >"$OUT/vlogan.log" 2>&1;run 600s vcs -full64 -top tb_qwen2_rms_tile16_stager -o simv_rms_tile16 >"$OUT/vcs.log" 2>&1
cd "$ROOT";run 600s "$VD/simv_rms_tile16"|tee "$OUT/tb.log";grep -q 'QWEN2_RMS_TILE16_STAGER_PASS rows=16' "$OUT/tb.log"
cd "$VD";S2=("$ROOT/work/generated/l5_all_primitives/HeteroAllPrimitives.sv" "$ROOT/rtl/sfu/fp32_reduce16.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr.sv" "$ROOT/rtl/sfu/fp32_rsqrt_nr2.sv" "$ROOT/rtl/sfu/fp32_rmsnorm1536_chunked.sv" "$ROOT/rtl/matrix/bf16_outer_product_array_glue512.sv" "$ROOT/rtl/matrix/candidates/rev8b_a/bf16_operand_distribution512_rev8b_a_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_scheduler5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_outer_product_array_control5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_tag_pipeline5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_fma_pipeline_lane5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_lane_cluster16_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_cluster_flags_glue32_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_context_front_control5_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_front_to_cluster_broadcast32_rev8b_b_candidate.sv" "$ROOT/rtl/matrix/candidates/rev8b_b/bf16_outer_product_context_array_rev8b_b_candidate.sv" "$ROOT/rtl/integration/qwen2_matrix_command_endpoint.sv" "$ROOT/rtl/integration/qwen2_shared_l2_rms_tile16_stager.sv" "$ROOT/rtl/integration/qwen2_shared_l2_matrix_tile16_payload.sv" "$ROOT/tb/tb_qwen2_rms_matrix_tile16_chain.sv")
run 600s vlogan -sverilog -full64 -timescale=1ns/1ps +define+SYNTHESIS +incdir+"$ROOT" "${S2[@]}" >"$OUT/chain_vlogan.log" 2>&1;run 600s vcs -full64 -top tb_qwen2_rms_matrix_tile16_chain -o simv_rms_matrix_tile16 >"$OUT/chain_vcs.log" 2>&1
cd "$ROOT";run 600s "$VD/simv_rms_matrix_tile16"|tee "$OUT/chain_tb.log";grep -q 'QWEN2_RMS_MATRIX_TILE16_CHAIN_PASS rows=16' "$OUT/chain_tb.log"
