#!/usr/bin/env bash
set -euo pipefail
[[ $# -eq 2 ]]||{ echo 'usage: run_l4_matrix_trace_case.sh <top> <out>' >&2;exit 2;}
ROOT=$(cd "$(dirname "$0")/.."&&pwd);TOP=$1;OUT=$2;mkdir -p "$OUT";R=$ROOT/scripts/run_memory_capped.sh;V=$ROOT/work/toolchain/conda/bin/verilator;M=$ROOT/work/generated/l10_sram/ct_sp_4096x128wm_base_0p8v_tt25/ctsp4096x128wm.v
P=("$ROOT/rtl/memory/ct_sp4096x128_macro_wrapper.sv" "$ROOT/rtl/common/rv_fifo.sv" "$ROOT/rtl/common/tensor_stream_skid.sv" "$ROOT/rtl/top/command_dispatch.sv" "$ROOT/rtl/integration/command_event_scoreboard_sram.sv" "$ROOT/rtl/integration/command_event_frontend_sram.sv" "$ROOT/rtl/integration/engine_completion_rr_arbiter.sv" "$ROOT/rtl/fabric/shared_l2_client_arbiter.sv" "$ROOT/rtl/fabric/shared_l2_fabric.sv" "$ROOT/rtl/fabric/matrix_direct_streams.sv" "$ROOT/rtl/integration/gemmini_spad_tensor_gateway.sv" "$ROOT/rtl/integration/aha_garnet_proc_packet_writer.sv" "$ROOT/rtl/integration/aha_tensor_stream_endpoint.sv" "$ROOT/rtl/integration/kv_tensor_stream_endpoint.sv" "$ROOT/rtl/integration/hetero_l3_command_fabric.sv" "$ROOT/rtl/integration/hetero_l3_stream_complex.sv" "$ROOT/rtl/integration/hetero_l3_production_top.sv" "$ROOT/tb/tb_l4_int8_gemm_l3_trace.sv")
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$V" --lint-only --timing -Wall --top-module "$TOP" "$ROOT/tb/ctsp4096x128wm_lint_stub.sv" "${P[@]}" >"$OUT/lint.log" 2>&1
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$V" --binary --timing --assert -Wall -Wno-fatal -DARM_DISABLE_EMA_CHECK -j 4 -MAKEFLAGS "AR=/usr/bin/ar CXX=/usr/bin/g++" --top-module "$TOP" --Mdir "$OUT/obj" -o tb "$M" "${P[@]}" >"$OUT/build.log" 2>&1
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" "$OUT/obj/tb"|tee "$OUT/tb.log"
MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" iverilog -g2012 -s tb_gemmini_descriptor_v2_pipeline -o "$OUT/descriptor_tb" "$ROOT/rtl/integration/matrix_descriptor_v2_snapshot.sv" "$ROOT/rtl/integration/matrix_descriptor_v2_decode.sv" "$ROOT/rtl/integration/gemmini_descriptor_v2_emitter.sv" "$ROOT/tb/tb_gemmini_descriptor_v2_pipeline.sv"
(cd "$ROOT"&&MIN_AVAILABLE_KIB=10485760 MEMORY_HIGH=8G MEMORY_MAX=10G "$R" vvp "$OUT/descriptor_tb")|tee "$OUT/descriptor.log"
