module operator_endpoint_bound_owner_shell_v3(
 input logic clk_i,
 input logic rst_ni,
 input logic terminal_valid_i,
 output logic terminal_ready_o,
 input logic [3:0] terminal_owner_i,
 input logic [7:0] terminal_opcode_i,
 input logic [15:0] terminal_tag_i,
 input logic [7:0] terminal_parent_phase_i,
 input logic [7:0] terminal_terminal_phase_i,
 input logic [15:0] terminal_flags_i,
 input logic [7:0] terminal_mode_i,
 input logic [23:0] terminal_src0_i,
 input logic [23:0] terminal_src1_i,
 input logic [23:0] terminal_src2_i,
 input logic [23:0] terminal_dst_i,
 input logic [15:0] terminal_rows_i,
 input logic [15:0] terminal_columns_i,
 input logic [15:0] terminal_depth_i,
 input logic [15:0] terminal_index0_i,
 input logic [15:0] terminal_index1_i,
 input logic terminal_scratch_valid_i,
 input logic [3:0] terminal_scratch_src0_i,
 input logic [3:0] terminal_scratch_src1_i,
 input logic [3:0] terminal_scratch_dst_i,
 input logic [7:0] terminal_variant_i,
 input logic terminal_first_i,
 input logic terminal_last_i,
 output logic completion_valid_o,
 input logic completion_ready_i,
 output logic [15:0] completion_tag_o,
 output logic [7:0] completion_parent_phase_o,
 output logic [7:0] completion_terminal_phase_o,
 output logic [7:0] completion_status_o,
 output logic router_busy_o,
 output logic router_protocol_error_o,
 input logic control_ack_valid_i,
 input logic [3:0] control_ack_domain_i,
 input logic control_fail_valid_i,
 output logic control_protocol_error_o,
 output logic dma_descriptor_req_valid_o,
 input logic dma_descriptor_req_ready_i,
 output logic [23:0] dma_descriptor_req_index_o,
 output logic dma_descriptor_req_destination_o,
 input logic dma_descriptor_rsp_valid_i,
 output logic dma_descriptor_rsp_ready_o,
 input logic [7:0] dma_descriptor_rsp_status_i,
 input logic [63:0] dma_descriptor_rsp_address_i,
 input logic [31:0] dma_descriptor_rsp_row_bytes_i,
 input logic [31:0] dma_descriptor_rsp_rows_i,
 input logic [31:0] dma_descriptor_rsp_stride_i,
 output logic dma_idma_req_valid_o,
 input logic dma_idma_req_ready_i,
 output logic [63:0] dma_idma_src_addr_o,
 output logic [63:0] dma_idma_dst_addr_o,
 output logic [31:0] dma_idma_length_o,
 input logic dma_idma_rsp_valid_i,
 output logic dma_idma_rsp_ready_o,
 input logic dma_idma_rsp_error_i,
 output logic [31:0] dma_flat_requests_o,
 input logic matrix_step_valid_i,
 output logic matrix_step_ready_o,
 input logic[2:0] matrix_step_context_i,
 input logic matrix_step_clear_i,
 input logic matrix_step_last_i,
 input logic[255:0] matrix_step_a_i,
 input logic[511:0] matrix_step_b_i,
 output logic matrix_out_valid_o,
 input logic matrix_out_ready_i,
 output logic[2:0] matrix_out_context_o,
 output logic matrix_out_last_o,
 output logic[16383:0] matrix_out_acc_o,
 output logic[4:0] matrix_exception_flags_o,
 output logic matrix_conv_command_valid_o,
 input logic matrix_conv_command_ready_i,
 output logic[127:0] matrix_conv_command_data_o,
 input logic matrix_conv_event_valid_i,
 output logic matrix_conv_event_ready_o,
 input logic[55:0] matrix_conv_event_data_i,
 output logic matrix_protocol_error_o,
 input logic sfu_payload_valid_i,
 output logic sfu_payload_ready_o,
 input logic[511:0] sfu_payload_a_i,
 input logic[511:0] sfu_payload_b_i,
 input logic[511:0] sfu_payload_c_i,
 input logic[15:0] sfu_payload_mask_i,
 input logic[31:0] sfu_payload_epsilon_i,
 input logic sfu_payload_last_i,
 output logic sfu_result_valid_o,
 input logic sfu_result_ready_i,
 output logic[511:0] sfu_result_data_o,
 output logic sfu_result_last_o,
 output logic[12:0] sfu_exception_flags_o,
 output logic sfu_domain_error_o,
 input logic sfu_soft_score_valid_i,
 output logic sfu_soft_score_ready_o,
 input logic[31:0] sfu_soft_score_i,
 input logic sfu_soft_score_mask_i,
 input logic sfu_soft_merge_header_valid_i,
 output logic sfu_soft_merge_header_ready_o,
 input logic[31:0] sfu_soft_ma_i,
 input logic[31:0] sfu_soft_la_i,
 input logic[31:0] sfu_soft_mb_i,
 input logic[31:0] sfu_soft_lb_i,
 input logic sfu_soft_merge_beat_valid_i,
 output logic sfu_soft_merge_beat_ready_o,
 input logic[127:0] sfu_soft_oa_i,
 input logic[127:0] sfu_soft_ob_i,
 input logic sfu_soft_merge_beat_last_i,
 output logic sfu_soft_header_valid_o,
 input logic sfu_soft_header_ready_i,
 output logic[31:0] sfu_soft_m_o,
 output logic[31:0] sfu_soft_l_o,
 output logic sfu_soft_weight_valid_o,
 input logic sfu_soft_weight_ready_i,
 output logic[31:0] sfu_soft_weight_o,
 output logic sfu_soft_weight_last_o,
 output logic sfu_soft_beat_valid_o,
 input logic sfu_soft_beat_ready_i,
 output logic[127:0] sfu_soft_o_o,
 output logic sfu_soft_beat_last_o,
 input logic kv_config_valid_i,
 output logic kv_config_ready_o,
 input logic[31:0] kv_sequence_id_i,
 input logic[11:0] kv_layer_id_i,
 input logic[11:0] kv_kv_head_id_i,
 input logic[31:0] kv_token_start_i,
 input logic[31:0] kv_token_count_i,
 input logic[31:0] kv_generation_i,
 input logic[31:0] kv_physical_page_limit_i,
 input logic[31:0] kv_bytes_per_token_i,
 input logic[63:0] kv_table_base_i,
 input logic[63:0] kv_data_base_i,
 input logic[63:0] kv_k_address_i,
 input logic[63:0] kv_v_address_i,
 input logic[63:0] kv_output_address_i,
 input logic[7:0] kv_format_i,
 output logic kv_ddr_req_valid_o,
 input logic kv_ddr_req_ready_i,
 output logic kv_ddr_req_write_o,
 output logic[63:0] kv_ddr_req_addr_o,
 output logic[127:0] kv_ddr_req_wdata_o,
 output logic[15:0] kv_ddr_req_wstrb_o,
 input logic kv_ddr_rsp_valid_i,
 output logic kv_ddr_rsp_ready_o,
 input logic[127:0] kv_ddr_rsp_rdata_i,
 input logic kv_ddr_rsp_error_i,
 output logic kv_page_req_valid_o,
 input logic kv_page_req_ready_i,
 output logic kv_page_req_free_o,
 output logic[31:0] kv_page_req_id_o,
 input logic kv_page_rsp_valid_i,
 output logic kv_page_rsp_ready_o,
 input logic[31:0] kv_page_rsp_id_i,
 input logic kv_page_rsp_error_i,
 output logic kv_idma_req_valid_o,
 input logic kv_idma_req_ready_i,
 output logic[63:0] kv_idma_src_addr_o,
 output logic[63:0] kv_idma_dst_addr_o,
 output logic[31:0] kv_idma_length_o,
 input logic kv_idma_rsp_valid_i,
 output logic kv_idma_rsp_ready_o,
 input logic kv_idma_rsp_error_i,
 output logic[63:0] kv_bytes_moved_o,
 input logic state_config_valid_i,
 output logic state_config_ready_o,
 input logic[63:0] state_state_address_i,
 input logic[63:0] state_window_base_i,
 input logic[63:0] state_state_stride_i,
 input logic[511:0] state_write_data_i,
 input logic[31:0] state_decay_i,
 input logic[127:0] state_conv_weights_i,
 output logic state_mem_req_valid_o,
 input logic state_mem_req_ready_i,
 output logic state_mem_req_write_o,
 output logic[63:0] state_mem_req_addr_o,
 output logic[511:0] state_mem_req_wdata_o,
 output logic[63:0] state_mem_req_wstrb_o,
 input logic state_mem_rsp_valid_i,
 output logic state_mem_rsp_ready_o,
 input logic[511:0] state_mem_rsp_rdata_i,
 input logic state_mem_rsp_error_i,
 output logic state_result_valid_o,
 input logic state_result_ready_i,
 output logic[511:0] state_result_data_o,
 output logic[4:0] state_exception_flags_o,
 output logic[15:0] state_generation_o,
 input logic selection_config_valid_i,
 output logic selection_config_ready_o,
 input logic[19:0] selection_topk_item_count_i,
 input logic[8:0] selection_topk_k_i,
 input logic[63:0] selection_expand_base_i,
 input logic[63:0] selection_expand_stride_i,
 input logic[31:0] selection_route_token_i,
 input logic[4:0] selection_route_count_i,
 input logic[18:0] selection_pool_blocks_i,
 input logic[4:0] selection_pool_ratio_i,
 input logic[8:0] selection_pool_dimensions_i,
 input logic[5:0] selection_mtp_step_count_i,
 input logic selection_score_valid_i,
 output logic selection_score_ready_o,
 input logic[31:0] selection_score_i,
 input logic[31:0] selection_score_index_i,
 output logic selection_ranked_valid_o,
 input logic selection_ranked_ready_i,
 output logic[31:0] selection_ranked_score_o,
 output logic[31:0] selection_ranked_index_o,
 output logic[8:0] selection_ranked_rank_o,
 output logic selection_ranked_last_o,
 output logic selection_topk_sram_req_valid_o,
 input logic selection_topk_sram_req_ready_i,
 output logic selection_topk_sram_req_write_o,
 output logic[8:0] selection_topk_sram_req_addr_o,
 output logic[64:0] selection_topk_sram_req_wdata_o,
 input logic selection_topk_sram_rsp_valid_i,
 output logic selection_topk_sram_rsp_ready_o,
 input logic[64:0] selection_topk_sram_rsp_rdata_i,
 input logic selection_topk_sram_rsp_error_i,
 input logic selection_expand_valid_i,
 output logic selection_expand_ready_o,
 input logic[31:0] selection_expand_index_i,
 input logic[8:0] selection_expand_rank_i,
 input logic selection_expand_last_i,
 output logic selection_expand_out_valid_o,
 input logic selection_expand_out_ready_i,
 output logic[63:0] selection_expand_address_o,
 output logic[8:0] selection_expand_out_rank_o,
 output logic selection_expand_out_last_o,
 input logic selection_route_valid_i,
 output logic selection_route_ready_o,
 input logic[9:0] selection_route_expert_i,
 input logic[31:0] selection_route_weight_i,
 input logic selection_route_shared_i,
 output logic selection_dispatch_valid_o,
 input logic selection_dispatch_ready_i,
 output logic[31:0] selection_dispatch_token_o,
 output logic[9:0] selection_dispatch_expert_o,
 output logic[31:0] selection_dispatch_weight_o,
 output logic[3:0] selection_dispatch_tag_o,
 output logic selection_dispatch_shared_o,
 output logic selection_dispatch_last_o,
 input logic selection_merge_result_valid_i,
 output logic selection_merge_result_ready_o,
 input logic[3:0] selection_merge_result_tag_i,
 input logic[511:0] selection_merge_result_data_i,
 output logic selection_merge_valid_o,
 input logic selection_merge_ready_i,
 output logic[3:0] selection_merge_tag_o,
 output logic[31:0] selection_merge_weight_o,
 output logic[511:0] selection_merge_data_o,
 output logic selection_merge_first_o,
 output logic selection_merge_last_o,
 output logic selection_pool_valid_o,
 input logic selection_pool_ready_i,
 output logic[17:0] selection_pool_block_o,
 output logic[21:0] selection_pool_token_o,
 output logic[7:0] selection_pool_dimension_o,
 output logic selection_pool_first_token_o,
 output logic selection_pool_last_token_o,
 output logic selection_pool_last_dimension_o,
 output logic selection_pool_last_o,
 input logic selection_mtp_valid_i,
 output logic selection_mtp_ready_o,
 input logic[31:0] selection_mtp_draft_i,
 input logic[31:0] selection_mtp_target_i,
 input logic[5:0] selection_mtp_step_i,
 input logic selection_mtp_last_i,
 output logic selection_mtp_result_valid_o,
 input logic selection_mtp_result_ready_i,
 output logic[5:0] selection_mtp_accepted_o,
 output logic[5:0] selection_mtp_mismatch_step_o,
 output logic selection_mtp_all_match_o,
 output logic selection_mtp_rollback_o,
 input logic vision_config_valid_i,
 output logic vision_config_ready_o,
 input logic[31:0] vision_cfg0_i,
 input logic[31:0] vision_cfg1_i,
 input logic[31:0] vision_cfg2_i,
 input logic[31:0] vision_cfg3_i,
 input logic[31:0] vision_cfg4_i,
 input logic[31:0] vision_cfg5_i,
 input logic[31:0] vision_cfg6_i,
 input logic[31:0] vision_cfg7_i,
 input logic[31:0] vision_cfg8_i,
 input logic[31:0] vision_cfg9_i,
 input logic[191:0] vision_cfg_multipliers_i,
 input logic[511:0] vision_cfg_head_sizes_i,
 input logic[511:0] vision_cfg_head_offsets_i,
 input logic vision_ple_valid_i,
 output logic vision_ple_ready_o,
 input logic[31:0] vision_ple_token_i,
 input logic[31:0] vision_ple_position_i,
 input logic vision_ple_last_i,
 output logic vision_map_valid_o,
 input logic vision_map_ready_i,
 output logic[255:0] vision_map_data_o,
 output logic vision_map_last_o
);
endmodule
