#include "ggml-backend-impl.h"
#include "ggml-cpu.h"
#include "ggml-impl.h"
#include "ggml.h"
#include "hetero_qwen2_device_api.h"
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>
struct hetero_ctx{std::string input_root,output_root,probe_path;int submissions=0;};
static ggml_guid_t hetero_guid(){static ggml_guid guid={0x48,0x45,0x54,0x45,0x52,0x4f,0x2d,0x51,0x57,0x45,0x4e,0x32,0x2d,0x50,0x33,0x01};return&guid;}
static void collect_tensors(ggml_tensor *tensor,std::set<ggml_tensor *> &seen,std::unordered_map<std::string,ggml_tensor *> &named){if(!tensor||!seen.insert(tensor).second)return;if(ggml_get_name(tensor)[0])named[ggml_get_name(tensor)]=tensor;for(int i=0;i<GGML_MAX_SRC;++i)collect_tensors(tensor->src[i],seen,named);}
static bool write_tensor(const ggml_tensor *tensor,const std::filesystem::path &path){if(!tensor||!tensor->data)return false;std::ofstream stream(path,std::ios::binary);stream.write(static_cast<const char *>(tensor->data),ggml_nbytes(tensor));return bool(stream);}
static bool write_tensor_bf16(const ggml_tensor *tensor,const std::filesystem::path &path){if(!tensor||!tensor->data)return false;if(tensor->type==GGML_TYPE_BF16)return write_tensor(tensor,path);if(tensor->type!=GGML_TYPE_F32)return false;const auto *source=static_cast<const float *>(tensor->data);std::vector<uint16_t>result(ggml_nelements(tensor));for(size_t i=0;i<result.size();++i){uint32_t word;std::memcpy(&word,&source[i],4);word+=0x7fff+((word>>16)&1);result[i]=uint16_t(word>>16);}std::ofstream stream(path,std::ios::binary);stream.write(reinterpret_cast<const char *>(result.data()),result.size()*sizeof(uint16_t));return bool(stream);}
static bool bind_gguf_graph_inputs(ggml_cgraph *graph,const std::string &contract_root,const std::string &bound_root){std::set<ggml_tensor *>seen;std::unordered_map<std::string,ggml_tensor *>named;for(int i=0;i<graph->n_nodes;++i)collect_tensors(graph->nodes[i],seen,named);static const std::unordered_map<std::string,std::string>suffixes={{"attn_norm.weight","input_norm_weight_bf16.bin"},{"attn_q.weight","q_weight_bf16.bin"},{"attn_q.bias","q_bias_fp32.bin"},{"attn_k.weight","k_weight_bf16.bin"},{"attn_k.bias","k_bias_fp32.bin"},{"attn_v.weight","v_weight_bf16.bin"},{"attn_v.bias","v_bias_fp32.bin"},{"attn_output.weight","oproj_weight_bf16.bin"},{"ffn_norm.weight","post_norm_weight_bf16.bin"},{"ffn_gate.weight","gate_weight_bf16.bin"},{"ffn_up.weight","up_weight_bf16.bin"},{"ffn_down.weight","down_weight_bf16.bin"}};int bound=0;for(int layer=0;layer<28;++layer){const auto directory=std::filesystem::path(bound_root)/("layer"+std::to_string(layer));std::filesystem::create_directories(directory);for(const auto &[suffix,file]:suffixes){const std::string name="blk."+std::to_string(layer)+"."+suffix;auto it=named.find(name);const bool is_norm=suffix=="attn_norm.weight"||suffix=="ffn_norm.weight";if(it==named.end()||!(is_norm?write_tensor_bf16(it->second,directory/file):write_tensor(it->second,directory/file)))return false;bound++;}std::filesystem::copy_file(std::filesystem::path(contract_root)/("layer"+std::to_string(layer))/"first21_commands.bin",directory/"first21_commands.bin",std::filesystem::copy_options::overwrite_existing);std::filesystem::copy_file(std::filesystem::path(contract_root)/("layer"+std::to_string(layer))/"silu_lut_fp16.bin",directory/"silu_lut_fp16.bin",std::filesystem::copy_options::overwrite_existing);}
 auto emb_it=named.find("token_embd.weight"),norm_it=named.find("output_norm.weight"),tok_it=named.find("inp_tokens");if(emb_it==named.end()||norm_it==named.end()||tok_it==named.end()||emb_it->second->type!=GGML_TYPE_BF16||tok_it->second->type!=GGML_TYPE_I32||ggml_nelements(tok_it->second)!=1024)return false;const auto embedding_dir=std::filesystem::path(bound_root)/"embedding",final_dir=std::filesystem::path(bound_root)/"final_head";std::filesystem::create_directories(embedding_dir);std::filesystem::create_directories(final_dir);const auto *weights=static_cast<const uint16_t *>(emb_it->second->data);const auto *tokens=static_cast<const int32_t *>(tok_it->second->data);std::vector<float>embedding(size_t(1024)*1536);for(int token=0;token<1024;++token)for(int d=0;d<1536;++d){uint32_t word=uint32_t(weights[size_t(tokens[token])*1536+d])<<16;std::memcpy(&embedding[size_t(token)*1536+d],&word,4);}std::ofstream embedding_stream(embedding_dir/"final_fp32.bin",std::ios::binary);embedding_stream.write(reinterpret_cast<const char *>(embedding.data()),embedding.size()*sizeof(float));if(!embedding_stream||!write_tensor_bf16(norm_it->second,final_dir/"final_norm_weight_bf16.bin")||!write_tensor(emb_it->second,final_dir/"lm_head_weight_bf16.bin"))return false;bound+=2;std::printf("HETERO_GGUF_BIND_PASS tensors=%d tokens=1024 direct_buffers=1\n",bound);return bound==338;}
static const char * backend_name(ggml_backend_t){return"HETERO";}
static void backend_free(ggml_backend_t backend){delete static_cast<hetero_ctx *>(backend->context);delete backend;}
static enum ggml_status graph_compute(ggml_backend_t backend,ggml_cgraph * graph){auto *ctx=static_cast<hetero_ctx *>(backend->context);if(!ctx->probe_path.empty()){std::ofstream probe(ctx->probe_path);probe<<"nodes\t"<<graph->n_nodes<<'\n';for(int i=0;i<graph->n_nodes;++i){auto *node=graph->nodes[i];probe<<i<<'\t'<<(ggml_get_name(node)[0]?ggml_get_name(node):"_")<<'\t'<<ggml_op_name(node->op)<<'\t'<<ggml_type_name(node->type);for(int d=0;d<GGML_MAX_DIMS;++d)probe<<'\t'<<node->ne[d];probe<<'\n';}return GGML_STATUS_FAILED;}ggml_tensor *node=nullptr;std::string result_path,submission_input=ctx->input_root;if(graph->n_nodes==1){node=graph->nodes[0];if(node->op!=GGML_OP_MAP_CUSTOM1||std::strcmp(ggml_get_name(node),"hetero.layer27")||node->type!=GGML_TYPE_F32||ggml_nelements(node)!=1572864)return GGML_STATUS_FAILED;result_path=ctx->output_root+"/layer27/final_fp32.bin";}else if(graph->n_nodes==958){node=graph->nodes[957];if(std::strcmp(ggml_get_name(node),"result_output")||node->op!=GGML_OP_MUL_MAT||node->type!=GGML_TYPE_F32||ggml_nelements(node)!=151936)return GGML_STATUS_FAILED;submission_input=ctx->output_root+"/gguf_bound_inputs";if(!bind_gguf_graph_inputs(graph,ctx->input_root,submission_input))return GGML_STATUS_FAILED;result_path=ctx->output_root+"/final/logits_fp32.bin";}else return GGML_STATUS_FAILED;if(!node->data)return GGML_STATUS_FAILED;hetero_qwen2_submit_config config{submission_input.c_str(),ctx->output_root.c_str(),nullptr,nullptr};if(hetero_qwen2_submit_588(&config))return GGML_STATUS_FAILED;std::ifstream stream(result_path,std::ios::binary);stream.read(static_cast<char *>(node->data),ggml_nbytes(node));if(!stream||size_t(stream.gcount())!=ggml_nbytes(node))return GGML_STATUS_FAILED;ctx->submissions++;return GGML_STATUS_SUCCESS;}
static ggml_backend_i backend_iface={backend_name,backend_free,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,nullptr,graph_compute,nullptr,nullptr,nullptr};
static const char * dev_name(ggml_backend_dev_t){return"HETERO0";}static const char * dev_desc(ggml_backend_dev_t){return"Hetero Qwen2 Command128 device submission";}static void dev_mem(ggml_backend_dev_t,size_t *free,size_t *total){*free=0;*total=0;}static enum ggml_backend_dev_type dev_type(ggml_backend_dev_t){return GGML_BACKEND_DEVICE_TYPE_ACCEL;}
static void dev_props(ggml_backend_dev_t dev,ggml_backend_dev_props *props){props->name=dev_name(dev);props->description=dev_desc(dev);props->memory_free=props->memory_total=0;props->type=dev_type(dev);props->device_id=nullptr;props->caps={false,false,true,false,true};}
static ggml_backend_t dev_init(ggml_backend_dev_t dev,const char *params){std::string input,output,probe;if(params){std::string p=params,key1="input=",key2=";output=";auto split=p.find(key2);if(p.rfind(key1,0)!=0||split==std::string::npos)return nullptr;input=p.substr(key1.size(),split-key1.size());auto tail=p.substr(split+key2.size());auto probe_pos=tail.find(";probe=");if(probe_pos==std::string::npos)output=tail;else{output=tail.substr(0,probe_pos);probe=tail.substr(probe_pos+7);}}else{const char *i=std::getenv("HETERO_INPUT_ROOT"),*o=std::getenv("HETERO_OUTPUT_ROOT"),*p=std::getenv("HETERO_PROBE_PATH");if(!i||!o)return nullptr;input=i;output=o;if(p)probe=p;}auto *ctx=new hetero_ctx{input,output,probe,0};return new ggml_backend{hetero_guid(),backend_iface,dev,ctx};}
static ggml_backend_buffer_type_t dev_buft(ggml_backend_dev_t){return ggml_backend_cpu_buffer_type();}static ggml_backend_buffer_t dev_from_ptr(ggml_backend_dev_t,void *ptr,size_t size,size_t){return ggml_backend_cpu_buffer_from_ptr(ptr,size);}static bool dev_supports(ggml_backend_dev_t,const ggml_tensor *op){if(!op)return false;if(op->op==GGML_OP_MAP_CUSTOM1)return!std::strcmp(ggml_get_name(op),"hetero.layer27")&&op->type==GGML_TYPE_F32&&ggml_nelements(op)==1572864;switch(op->op){case GGML_OP_GET_ROWS:case GGML_OP_RMS_NORM:case GGML_OP_MUL:case GGML_OP_MUL_MAT:case GGML_OP_ADD:case GGML_OP_RESHAPE:case GGML_OP_ROPE:case GGML_OP_VIEW:case GGML_OP_SET_ROWS:case GGML_OP_PERMUTE:case GGML_OP_FLASH_ATTN_EXT:case GGML_OP_GLU:return true;default:return false;}}static bool dev_supports_buft(ggml_backend_dev_t,ggml_backend_buffer_type_t buft){return ggml_backend_buft_is_host(buft);}
static ggml_backend_device_i device_iface={dev_name,dev_desc,dev_mem,dev_type,dev_props,dev_init,dev_buft,nullptr,dev_from_ptr,dev_supports,dev_supports_buft,nullptr,nullptr,nullptr,nullptr};
static const char * reg_name(ggml_backend_reg_t){return"HETERO";}static size_t reg_count(ggml_backend_reg_t){return 1;}static ggml_backend_dev_t reg_dev(ggml_backend_reg_t reg,size_t index){if(index)return nullptr;static ggml_backend_device dev{device_iface,nullptr,nullptr};dev.reg=reg;return&dev;}static void *reg_proc(ggml_backend_reg_t,const char *){return nullptr;}static ggml_backend_reg_i reg_iface={reg_name,reg_count,reg_dev,reg_proc};
extern "C" ggml_backend_reg_t ggml_backend_hetero_reg(){static ggml_backend_reg reg{GGML_BACKEND_API_VERSION,reg_iface,nullptr};return&reg;}
#ifdef GGML_BACKEND_DL
GGML_BACKEND_DL_IMPL(ggml_backend_hetero_reg)
#endif
