`timescale 1ns/1ps
// Full generated Garnet-top wiring for the pinned Gaussian control transcript.
// This first harness proves real macro acceptance and PCFG interrupt ordering;
// output memory comparison is added only after this launch path is stable.
module tb_aha_garnet_gaussian_transcript;
  localparam logic [1:0] OP_PACKET = 2'd0;
  localparam logic [1:0] OP_AXI = 2'd1;
  localparam logic [1:0] OP_WAIT_INTERRUPT = 2'd2;

  logic clk = 0;
  logic reset = 1;
  always #5 clk = ~clk;

  logic op_valid, op_ready;
  logic [1:0] op_kind;
  logic [12:0] op_axi_addr;
  logic [31:0] op_axi_data;
  logic [17:0] op_packet_addr;
  logic [511:0] op_packet_data;
  logic [63:0] op_packet_strb;
  logic op_done, op_error;

  logic [12:0] axi_awaddr;
  logic axi_awvalid, axi_awready;
  logic [31:0] axi_wdata;
  logic axi_wvalid, axi_wready;
  logic axi_bready;
  logic [1:0] axi_bresp;
  logic axi_bvalid;
  logic [31:0] axi_rdata;
  logic [1:0] axi_rresp;
  logic axi_rvalid, axi_arready;
  logic [17:0] proc_rd_addr, proc_wr_addr;
  logic proc_rd_en, proc_wr_en;
  logic [63:0] proc_rd_data, proc_wr_data;
  logic proc_rd_data_valid;
  logic [7:0] proc_wr_strb;
  logic garnet_interrupt, cgra_running_clk, jtag_tdo;
  logic stimulus_ready;
  logic [12:0] PCFG_ADDR, STREAM_ADDR;
  logic [31:0] PCFG_DATA, STREAM_DATA;
  int cycle_count;

  // Generated by scripts/generate_aha_gaussian_sv_stimulus.py and supplied
  // through the generated trace directory's include path.
  `include "gaussian_transcript_stim.svh"

  aha_garnet_microsequencer u_microsequencer (
    .clk_i(clk), .rst_ni(!reset),
    .op_valid_i(op_valid), .op_ready_o(op_ready), .op_kind_i(op_kind),
    .op_axi_addr_i(op_axi_addr), .op_axi_data_i(op_axi_data),
    .op_packet_addr_i(op_packet_addr), .op_packet_data_i(op_packet_data), .op_packet_strb_i(op_packet_strb),
    .garnet_interrupt_i(garnet_interrupt),
    .axi_awaddr_o(axi_awaddr), .axi_awvalid_o(axi_awvalid), .axi_awready_i(axi_awready),
    .axi_wdata_o(axi_wdata), .axi_wvalid_o(axi_wvalid), .axi_wready_i(axi_wready),
    .axi_bready_o(axi_bready), .axi_bvalid_i(axi_bvalid), .axi_bresp_i(axi_bresp),
    .proc_packet_wr_en_o(proc_wr_en), .proc_packet_wr_addr_o(proc_wr_addr),
    .proc_packet_wr_data_o(proc_wr_data), .proc_packet_wr_strb_o(proc_wr_strb),
    .op_done_o(op_done), .op_error_o(op_error)
  );

  Garnet u_garnet (
    .axi4_slave_araddr('0), .axi4_slave_arready(axi_arready), .axi4_slave_arvalid(1'b0),
    .axi4_slave_awaddr(axi_awaddr), .axi4_slave_awready(axi_awready), .axi4_slave_awvalid(axi_awvalid),
    .axi4_slave_bready(axi_bready), .axi4_slave_bresp(axi_bresp), .axi4_slave_bvalid(axi_bvalid),
    .axi4_slave_rdata(axi_rdata), .axi4_slave_rready(1'b0), .axi4_slave_rresp(axi_rresp), .axi4_slave_rvalid(axi_rvalid),
    .axi4_slave_wdata(axi_wdata), .axi4_slave_wready(axi_wready), .axi4_slave_wvalid(axi_wvalid),
    .cgra_running_clk_out(cgra_running_clk), .clk_in(clk), .interrupt(garnet_interrupt),
    .jtag_tck(1'b0), .jtag_tdi(1'b0), .jtag_tdo(jtag_tdo), .jtag_tms(1'b0), .jtag_trst_n(1'b1),
    .proc_packet_rd_addr(proc_rd_addr), .proc_packet_rd_data(proc_rd_data), .proc_packet_rd_data_valid(proc_rd_data_valid),
    .proc_packet_rd_en(proc_rd_en), .proc_packet_wr_addr(proc_wr_addr), .proc_packet_wr_data(proc_wr_data),
    .proc_packet_wr_en(proc_wr_en), .proc_packet_wr_strb(proc_wr_strb), .reset_in(reset)
  );

  always @(posedge clk) cycle_count <= cycle_count + 1;

  task automatic issue_axi(input logic [12:0] addr, input logic [31:0] data);
    begin
      @(negedge clk);
      op_kind = OP_AXI; op_axi_addr = addr; op_axi_data = data; op_valid = 1'b1;
      do @(posedge clk); while (!op_ready);
      @(negedge clk); op_valid = 1'b0;
      do @(posedge clk); while (!op_done);
      if (op_error) $fatal(1, "AXI micro-op error addr=%h", addr);
    end
  endtask

  task automatic issue_packet(input logic [17:0] addr, input logic [511:0] data, input logic [63:0] strb);
    begin
      @(negedge clk);
      op_kind = OP_PACKET; op_packet_addr = addr; op_packet_data = data; op_packet_strb = strb; op_valid = 1'b1;
      do @(posedge clk); while (!op_ready);
      @(negedge clk); op_valid = 1'b0;
      do @(posedge clk); while (!op_done);
      if (op_error) $fatal(1, "proc-packet micro-op error addr=%h", addr);
    end
  endtask

  task automatic wait_pcfg_interrupt;
    begin
      @(negedge clk);
      op_kind = OP_WAIT_INTERRUPT; op_valid = 1'b1;
      do @(posedge clk); while (!op_ready);
      @(negedge clk); op_valid = 1'b0;
      do @(posedge clk); while (!op_done);
      if (op_error) $fatal(1, "PCFG interrupt micro-op error");
    end
  endtask

  initial begin
    op_valid = 0; op_kind = 0; op_axi_addr = 0; op_axi_data = 0;
    op_packet_addr = 0; op_packet_data = 0; op_packet_strb = 0;
    proc_rd_addr = 0; proc_rd_en = 0; cycle_count = 0;
    $display("AHA_GARNET_STAGE stimulus_initializing");
    $fflush();
    wait (stimulus_ready);
    repeat (5) @(posedge clk);
    reset = 0;
    $display("AHA_GARNET_STAGE interrupt_enable");
    $fflush();
    for (int i = 0; i < INTERRUPT_ENABLE_COUNT; i++) issue_axi(INTERRUPT_ENABLE_ADDR[i], INTERRUPT_ENABLE_DATA[i]);
    $display("AHA_GARNET_STAGE bitstream_packets");
    $fflush();
    for (int i = 0; i < BS_COUNT; i++) issue_packet(BS_ADDR[i], BS_DATA[i], BS_STRB[i]);
    $display("AHA_GARNET_STAGE bs_cfg");
    $fflush();
    for (int i = 0; i < BS_CFG_COUNT; i++) issue_axi(BS_CFG_ADDR[i], BS_CFG_DATA[i]);
    $display("AHA_GARNET_STAGE kernel_cfg");
    $fflush();
    for (int i = 0; i < KERNEL_CFG_COUNT; i++) issue_axi(KERNEL_CFG_ADDR[i], KERNEL_CFG_DATA[i]);
    $display("AHA_GARNET_STAGE pcfg_start");
    $fflush();
    issue_axi(PCFG_ADDR, PCFG_DATA);
    $display("AHA_GARNET_STAGE pcfg_interrupt_wait");
    $fflush();
    wait_pcfg_interrupt();
    // Official Env_clear_interrupt uses PCFG ISR address 0x38 and tile mask 1.
    issue_axi(13'h038, 32'h0000_0001);
    if ($test$plusargs("PCFG_ONLY")) begin
      $display("AHA_GARNET_PCFG_TRANSCRIPT_PASS cycles=%0d", cycle_count);
      $fflush();
      $finish;
    end
    $display("AHA_GARNET_STAGE input_packets");
    $fflush();
    for (int i = 0; i < INPUT0_COUNT; i++) issue_packet(INPUT0_ADDR[i], INPUT0_DATA[i], INPUT0_STRB[i]);
    for (int i = 0; i < INPUT1_COUNT; i++) issue_packet(INPUT1_ADDR[i], INPUT1_DATA[i], INPUT1_STRB[i]);
    issue_axi(STREAM_ADDR, STREAM_DATA);
    $display("AHA_GARNET_STAGE stream_started");
    $fflush();
    repeat (1000) @(posedge clk);
    $display("AHA_GARNET_GAUSSIAN_TRANSCRIPT_LAUNCHED cycles=%0d", cycle_count);
    $finish;
  end

  initial begin
    repeat (2_000_000) @(posedge clk);
    $fatal(1, "Gaussian transcript timeout");
  end
endmodule
