`timescale 1ns/1ps
// Full generated Garnet-top wiring for the pinned Gaussian control transcript.
// This first harness proves real macro acceptance and PCFG interrupt ordering;
// output memory comparison is added only after this launch path is stable.
module tb_aha_garnet_gaussian_transcript;
  localparam logic [1:0] OP_PACKET = 2'd0;
  localparam logic [1:0] OP_AXI = 2'd1;
  localparam logic [1:0] OP_WAIT_INTERRUPT = 2'd2;

  logic clk = 0;
  // The generated GlobalController has asynchronous reset branches that set
  // AXI AWREADY.  Start low and drive a real 0->1 transition below so the
  // branches execute under Verilator, rather than relying on declaration-time
  // initialization at time zero.
  logic reset = 0;
  logic reset_finished = 0;
  always #5 clk = ~clk;

  logic op_valid, op_ready;
  logic [1:0] op_kind;
  logic [12:0] op_axi_addr;
  logic [31:0] op_axi_data;
  logic [17:0] op_packet_addr;
  logic [511:0] op_packet_data;
  logic [63:0] op_packet_strb;
  logic op_done, op_error;

  logic [12:0] axi_awaddr;
  logic axi_awvalid, axi_awready;
  logic [31:0] axi_wdata;
  logic axi_wvalid, axi_wready;
  logic axi_bready;
  logic [1:0] axi_bresp;
  logic axi_bvalid;
  logic [31:0] axi_rdata;
  logic [1:0] axi_rresp;
  logic axi_rvalid, axi_arready;
  logic [12:0] axi_araddr;
  logic axi_arvalid, axi_rready;
  logic [17:0] proc_rd_addr, proc_wr_addr;
  logic proc_rd_en, proc_wr_en;
  logic [63:0] proc_rd_data, proc_wr_data;
  logic proc_rd_data_valid;
  logic [7:0] proc_wr_strb;
  logic garnet_interrupt, cgra_running_clk, jtag_tdo;
  logic stimulus_ready;
  logic [12:0] PCFG_ADDR, STREAM_ADDR;
  logic [31:0] PCFG_DATA, STREAM_DATA;
  logic [31:0] cgra_stall_before, cgra_stall_after;
  int cycle_count;

  // Generated by scripts/generate_aha_gaussian_sv_stimulus.py and supplied
  // through the generated trace directory's include path.
  `include "gaussian_transcript_stim.svh"

  aha_garnet_microsequencer u_microsequencer (
    .clk_i(clk), .rst_ni(!reset),
    .op_valid_i(op_valid), .op_ready_o(op_ready), .op_kind_i(op_kind),
    .op_axi_addr_i(op_axi_addr), .op_axi_data_i(op_axi_data),
    .op_packet_addr_i(op_packet_addr), .op_packet_data_i(op_packet_data), .op_packet_strb_i(op_packet_strb),
    .garnet_interrupt_i(garnet_interrupt),
    .axi_awaddr_o(axi_awaddr), .axi_awvalid_o(axi_awvalid), .axi_awready_i(axi_awready),
    .axi_wdata_o(axi_wdata), .axi_wvalid_o(axi_wvalid), .axi_wready_i(axi_wready),
    .axi_bready_o(axi_bready), .axi_bvalid_i(axi_bvalid), .axi_bresp_i(axi_bresp),
    .proc_packet_wr_en_o(proc_wr_en), .proc_packet_wr_addr_o(proc_wr_addr),
    .proc_packet_wr_data_o(proc_wr_data), .proc_packet_wr_strb_o(proc_wr_strb),
    .op_done_o(op_done), .op_error_o(op_error)
  );

  Garnet u_garnet (
    .axi4_slave_araddr(axi_araddr), .axi4_slave_arready(axi_arready), .axi4_slave_arvalid(axi_arvalid),
    .axi4_slave_awaddr(axi_awaddr), .axi4_slave_awready(axi_awready), .axi4_slave_awvalid(axi_awvalid),
    .axi4_slave_bready(axi_bready), .axi4_slave_bresp(axi_bresp), .axi4_slave_bvalid(axi_bvalid),
    .axi4_slave_rdata(axi_rdata), .axi4_slave_rready(axi_rready), .axi4_slave_rresp(axi_rresp), .axi4_slave_rvalid(axi_rvalid),
    .axi4_slave_wdata(axi_wdata), .axi4_slave_wready(axi_wready), .axi4_slave_wvalid(axi_wvalid),
    .cgra_running_clk_out(cgra_running_clk), .clk_in(clk), .interrupt(garnet_interrupt),
    .jtag_tck(1'b0), .jtag_tdi(1'b0), .jtag_tdo(jtag_tdo), .jtag_tms(1'b0), .jtag_trst_n(1'b1),
    .proc_packet_rd_addr(proc_rd_addr), .proc_packet_rd_data(proc_rd_data), .proc_packet_rd_data_valid(proc_rd_data_valid),
    .proc_packet_rd_en(proc_rd_en), .proc_packet_wr_addr(proc_wr_addr), .proc_packet_wr_data(proc_wr_data),
    .proc_packet_wr_en(proc_wr_en), .proc_packet_wr_strb(proc_wr_strb), .reset_in(reset)
  );

  always @(posedge clk) cycle_count <= cycle_count + 1;

  // Exact reset shape from upstream tests/test_app/genesis_tb/top.svp.
  // In particular, Garnet must see initial low clocks before the asserted
  // reset pulse; a declaration-time high value is not equivalent in Verilator.
  initial begin
    reset = 1'b0;
    repeat (3) @(posedge clk);
    reset = 1'b1;
    repeat (3) @(posedge clk);
    reset = 1'b0;
    reset_finished = 1'b1;
  end

  task automatic issue_axi(input logic [12:0] addr, input logic [31:0] data);
    int guard;
    begin
      @(negedge clk);
      op_kind = OP_AXI; op_axi_addr = addr; op_axi_data = data; op_valid = 1'b1;
      do @(posedge clk); while (!op_ready);
      @(negedge clk); op_valid = 1'b0;
      guard = 0;
      while (!op_done) begin
        @(posedge clk);
        guard++;
        if (guard == 256) begin
          $display("AHA_GARNET_AXI_TIMEOUT addr=%h aw_vr=%b%b w_vr=%b%b b_vr=%b%b reset=%b interrupt=%b", addr,
                   axi_awvalid, axi_awready, axi_wvalid, axi_wready, axi_bvalid, axi_bready, reset, garnet_interrupt);
          $fflush();
          $fatal(1, "AXI micro-op timeout");
        end
      end
      if (op_error) $fatal(1, "AXI micro-op error addr=%h", addr);
    end
  endtask

  task automatic read_axi(input logic [12:0] addr, output logic [31:0] data);
    int guard;
    begin
      @(negedge clk); axi_araddr = addr; axi_arvalid = 1'b1; axi_rready = 1'b1;
      guard = 0;
      while (!axi_arready) begin
        @(posedge clk);
        guard++;
        if (guard == 256) $fatal(1, "Garnet AXI read address timeout addr=%h", addr);
      end
      @(negedge clk); axi_arvalid = 1'b0;
      guard = 0;
      while (!axi_rvalid) begin
        @(posedge clk);
        guard++;
        if (guard == 256) $fatal(1, "Garnet AXI read data timeout addr=%h", addr);
      end
      data = axi_rdata;
      if (axi_rresp != 2'b00) $fatal(1, "Garnet AXI read response error addr=%h resp=%b", addr, axi_rresp);
      @(negedge clk); axi_rready = 1'b0; axi_araddr = '0;
    end
  endtask

  task automatic wait_isr(input string stage, input logic [12:0] isr_addr, input logic [31:0] tile_mask, input int max_cycles);
    int guard;
    logic [31:0] isr;
    begin
      guard = 0;
      while (1) begin
        while (!garnet_interrupt) begin
          @(posedge clk);
          guard++;
          if (guard == max_cycles) $fatal(1, "Garnet ISR timeout stage=%s", stage);
        end
        // Official test_app reads the selected ISR after every level interrupt;
        // a G2F interrupt is not evidence that F2G output has completed.
        read_axi(isr_addr, isr);
        $display("AHA_GARNET_ISR stage=%s addr=%h value=%h", stage, isr_addr, isr);
        $fflush();
        if ((isr & tile_mask) == tile_mask) break;
      end
    end
  endtask

  task automatic issue_packet(input logic [17:0] addr, input logic [511:0] data, input logic [63:0] strb);
    int guard;
    begin
      @(negedge clk);
      op_kind = OP_PACKET; op_packet_addr = addr; op_packet_data = data; op_packet_strb = strb; op_valid = 1'b1;
      do @(posedge clk); while (!op_ready);
      @(negedge clk); op_valid = 1'b0;
      guard = 0;
      while (!op_done) begin
        @(posedge clk);
        guard++;
        if (guard == 256) begin
          $display("AHA_GARNET_PACKET_TIMEOUT addr=%h wr_en=%b reset=%b", addr, proc_wr_en, reset);
          $fflush();
          $fatal(1, "proc-packet micro-op timeout");
        end
      end
      if (op_error) $fatal(1, "proc-packet micro-op error addr=%h", addr);
    end
  endtask

  task automatic wait_interrupt(input string stage, input int max_cycles);
    int guard;
    begin
      @(negedge clk);
      op_kind = OP_WAIT_INTERRUPT; op_valid = 1'b1;
      do @(posedge clk); while (!op_ready);
      @(negedge clk); op_valid = 1'b0;
      guard = 0;
      while (!op_done) begin
        @(posedge clk);
        guard++;
        if (guard == max_cycles) begin
          $display("AHA_GARNET_INTERRUPT_TIMEOUT stage=%s interrupt=%b", stage, garnet_interrupt);
          $fflush();
          $fatal(1, "Garnet interrupt timeout stage=%s", stage);
        end
      end
      if (op_error) $fatal(1, "Garnet interrupt micro-op error stage=%s", stage);
    end
  endtask

  task automatic wait_interrupt_low(input string stage);
    int guard;
    begin
      guard = 0;
      while (garnet_interrupt) begin
        @(posedge clk);
        guard++;
        if (guard == 256) $fatal(1, "Garnet interrupt did not clear before %s", stage);
      end
    end
  endtask

  task automatic read_and_compare(input logic [17:0] base, input int words, input int block);
    logic [63:0] expected;
    logic [63:0] observed;
    begin
      // This is the official ProcDriver_read_data protocol, not a sequence
      // of isolated reads.  The generated global-buffer read clock is gated
      // by the delayed rd_en, so requests must remain continuous while the
      // response pipeline drains.
      fork
        begin
          @(posedge clk);
          for (int index = 0; index < words; index++) begin
            proc_rd_en = 1'b1;
            proc_rd_addr = base + index * 8;
            @(posedge clk);
          end
          proc_rd_en = 1'b0;
          proc_rd_addr = '0;
        end
        begin
          for (int index = 0; index < words; index++) begin
            int guard = 0;
            while (!proc_rd_data_valid) begin
              @(posedge clk);
              guard++;
              if (guard == 256) $fatal(1, "Garnet proc read timeout block=%0d word=%0d", block, index);
            end
            // Match ProcDriver_read_data's Verilator-specific sample point.
            @(posedge clk);
            observed = proc_rd_data;
            expected = (block == 0) ? OUTPUT0_EXPECTED[index] : OUTPUT1_EXPECTED[index];
            if (observed !== expected)
              $fatal(1, "Garnet output mismatch block=%0d word=%0d addr=%h expected=%h observed=%h",
                     block, index, base + index * 8, expected, observed);
          end
        end
      join
    end
  endtask

  initial begin
    op_valid = 0; op_kind = 0; op_axi_addr = 0; op_axi_data = 0;
    op_packet_addr = 0; op_packet_data = 0; op_packet_strb = 0;
    proc_rd_addr = 0; proc_rd_en = 0; axi_araddr = 0; axi_arvalid = 0; axi_rready = 0; cycle_count = 0;
    $display("AHA_GARNET_STAGE stimulus_initializing");
    $fflush();
    wait (stimulus_ready);
    wait (reset_finished);
    // Pinned test_app waits twenty clocks after reset propagation before its
    // first AXI transaction; Garnet's controller otherwise holds AWREADY low.
    repeat (20) @(posedge clk);
    $display("AHA_GARNET_STAGE interrupt_enable");
    $fflush();
    for (int i = 0; i < INTERRUPT_ENABLE_COUNT; i++) issue_axi(INTERRUPT_ENABLE_ADDR[i], INTERRUPT_ENABLE_DATA[i]);
    $display("AHA_GARNET_STAGE bitstream_packets");
    $fflush();
    for (int i = 0; i < BS_COUNT; i++) issue_packet(BS_ADDR[i], BS_DATA[i], BS_STRB[i]);
    // Exact ProcDriver_write_bs post-write drain from test_app.
    repeat (10) @(posedge clk);
    $display("AHA_GARNET_STAGE bs_cfg");
    $fflush();
    for (int i = 0; i < BS_CFG_COUNT; i++) issue_axi(BS_CFG_ADDR[i], BS_CFG_DATA[i]);
    $display("AHA_GARNET_STAGE kernel_cfg");
    $fflush();
    for (int i = 0; i < KERNEL_CFG_COUNT; i++) issue_axi(KERNEL_CFG_ADDR[i], KERNEL_CFG_DATA[i]);
    // Preserve the upstream test_app sequence: stall the mapped CGRA group
    // before PCFG, then restore all of its stall bits after PCFG completes.
    read_axi(13'h008, cgra_stall_before);
    issue_axi(13'h008, cgra_stall_before | CGRA_STALL_MASK);
    $display("AHA_GARNET_STAGE pcfg_start");
    $fflush();
    issue_axi(PCFG_ADDR, PCFG_DATA);
    $display("AHA_GARNET_STAGE pcfg_interrupt_wait");
    $fflush();
    wait_interrupt("pcfg", 4096);
    // Official Env_clear_interrupt uses PCFG ISR address 0x38 and tile mask 1.
    issue_axi(13'h038, 32'h0000_0001);
    wait_interrupt_low("stream_start");
    if ($test$plusargs("PCFG_ONLY")) begin
      $display("AHA_GARNET_PCFG_TRANSCRIPT_PASS cycles=%0d", cycle_count);
      $fflush();
      $finish;
    end
    $display("AHA_GARNET_STAGE input_packets");
    $fflush();
    for (int i = 0; i < INPUT0_COUNT; i++) issue_packet(INPUT0_ADDR[i], INPUT0_DATA[i], INPUT0_STRB[i]);
    // Exact ProcDriver_write_data drain between independently mapped IO tiles.
    repeat (10) @(posedge clk);
    for (int i = 0; i < INPUT1_COUNT; i++) issue_packet(INPUT1_ADDR[i], INPUT1_DATA[i], INPUT1_STRB[i]);
    repeat (10) @(posedge clk);
    // Exact test_app order: complete all host writes, then unstall immediately
    // before the stream-start transaction.
    read_axi(13'h008, cgra_stall_after);
    issue_axi(13'h008, cgra_stall_after & ~CGRA_STALL_MASK);
    issue_axi(STREAM_ADDR, STREAM_DATA);
    $display("AHA_GARNET_STAGE stream_started");
    $fflush();
    wait_isr("g2f", 13'h034, 32'h0000_0003, 30000);
    issue_axi(13'h034, 32'h0000_0003);
    wait_isr("f2g", 13'h030, 32'h0000_0003, 30000);
    issue_axi(13'h030, 32'h0000_0003);
    // Upstream Env_read_data deliberately drains twenty system clocks after
    // F2G completion before issuing proc reads.
    repeat (20) @(posedge clk);
    $display("AHA_GARNET_STAGE output_readback");
    $fflush();
    read_and_compare(OUTPUT0_BASE, OUTPUT0_WORDS, 0);
    read_and_compare(OUTPUT1_BASE, OUTPUT1_WORDS, 1);
    $display("AHA_GARNET_GAUSSIAN_NUMERICAL_PASS cycles=%0d", cycle_count);
    $finish;
  end

  initial begin
    repeat (2_000_000) @(posedge clk);
    $fatal(1, "Gaussian transcript timeout");
  end
endmodule
