`timescale 1ns/1ps
module tb_blocked_attention_stream_controller;
 logic clk;always #0.5 clk=~clk;logic rst_n,start;logic[15:0]seq_len;logic busy,done;
 logic mcv,mcr,mck;logic[19:0]mct,mdt;logic[6:0]mcq;logic[9:0]mckv;logic[3:0]mcqh;logic[1:0]mckh;logic[4:0]mcrows;logic mcclose,mcmerge,mclast;logic mdv,mdr,mdk;
 logic scv,scr;logic[19:0]sct,sdt;logic[6:0]scq;logic[9:0]sckv;logic[3:0]scqh;logic[1:0]sckh;logic[4:0]scrows;logic scclose,scmerge,sclast;logic sdv,sdr;logic[31:0]qki,qkc,sfc,pvc,merges;logic[1:0]sl,pl;logic perr;
 logic[31:0]lfsr;logic matrix_model_busy,sfu_model_busy;integer matrix_countdown,sfu_countdown;logic matrix_pending_valid,sfu_pending_valid,matrix_pending_kind;logic[19:0]matrix_pending_task,sfu_pending_task;
 integer trace_fd;string trace_path;
 blocked_attention_stream_controller dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.sequence_tokens_i(seq_len),.busy_o(busy),.done_o(done),.matrix_cmd_valid_o(mcv),.matrix_cmd_ready_i(mcr),.matrix_cmd_kind_o(mck),.matrix_cmd_task_id_o(mct),.matrix_cmd_query_tile_o(mcq),.matrix_cmd_kv_tile_o(mckv),.matrix_cmd_q_head_o(mcqh),.matrix_cmd_kv_head_o(mckh),.matrix_cmd_valid_rows_o(mcrows),.matrix_cmd_close_block_o(mcclose),.matrix_cmd_merge_global_o(mcmerge),.matrix_cmd_last_kv_o(mclast),.matrix_done_valid_i(mdv),.matrix_done_ready_o(mdr),.matrix_done_kind_i(mdk),.matrix_done_task_id_i(mdt),.sfu_cmd_valid_o(scv),.sfu_cmd_ready_i(scr),.sfu_cmd_task_id_o(sct),.sfu_cmd_query_tile_o(scq),.sfu_cmd_kv_tile_o(sckv),.sfu_cmd_q_head_o(scqh),.sfu_cmd_kv_head_o(sckh),.sfu_cmd_valid_rows_o(scrows),.sfu_cmd_close_block_o(scclose),.sfu_cmd_merge_global_o(scmerge),.sfu_cmd_last_kv_o(sclast),.sfu_done_valid_i(sdv),.sfu_done_ready_o(sdr),.sfu_done_task_id_i(sdt),.qk_issued_o(qki),.qk_completed_o(qkc),.sfu_completed_o(sfc),.pv_completed_o(pvc),.summary_merge_rows_o(merges),.score_fifo_level_o(sl),.probability_fifo_level_o(pl),.protocol_error_o(perr));
 assign mcr=!matrix_model_busy&&lfsr[0];assign scr=!sfu_model_busy&&lfsr[1];assign mdv=matrix_pending_valid;assign mdk=matrix_pending_kind;assign mdt=matrix_pending_task;assign sdv=sfu_pending_valid;assign sdt=sfu_pending_task;
 function automatic integer expected_tasks(input integer seq);integer qt,limit,ktiles,total;begin total=0;for(qt=0;qt<(seq+15)/16;qt=qt+1)begin limit=(qt+1)*16;if(limit>seq)limit=seq;ktiles=(limit+31)/32;total=total+12*ktiles;end expected_tasks=total;end endfunction
 function automatic integer expected_merges(input integer seq);integer token,total;begin total=0;for(token=0;token<seq;token=token+1)total=total+12*(token/128);expected_merges=total;end endfunction
 always_ff@(posedge clk)begin if(!rst_n)begin lfsr<=32'h1aceb00c;matrix_model_busy<=0;sfu_model_busy<=0;matrix_countdown<=0;sfu_countdown<=0;matrix_pending_valid<=0;sfu_pending_valid<=0;matrix_pending_kind<=0;matrix_pending_task<=0;sfu_pending_task<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(mcv&&mcr)begin matrix_model_busy<=1;matrix_countdown<=1+(lfsr[5:2]%7);matrix_pending_kind<=mck;matrix_pending_task<=mct;if(trace_fd)$fwrite(trace_fd,"M %0d %0d %0d %0d %0d %0d %0d %0d %0d %0d %0d %0t\n",seq_len,mck,mct,mcq,mckv,mcqh,mckh,mcrows,mcclose,mcmerge,mclast,$time);end if(matrix_model_busy&&!matrix_pending_valid)begin if(matrix_countdown==0)matrix_pending_valid<=1;else matrix_countdown<=matrix_countdown-1;end if(matrix_pending_valid&&mdr)begin matrix_pending_valid<=0;matrix_model_busy<=0;end if(scv&&scr)begin sfu_model_busy<=1;sfu_countdown<=1+(lfsr[9:6]%5);sfu_pending_task<=sct;if(trace_fd)$fwrite(trace_fd,"S %0d 0 %0d %0d %0d %0d %0d %0d %0d %0d %0d %0t\n",seq_len,sct,scq,sckv,scqh,sckh,scrows,scclose,scmerge,sclast,$time);end if(sfu_model_busy&&!sfu_pending_valid)begin if(sfu_countdown==0)sfu_pending_valid<=1;else sfu_countdown<=sfu_countdown-1;end if(sfu_pending_valid&&sdr)begin sfu_pending_valid<=0;sfu_model_busy<=0;end end end
 task automatic run_case(input integer seq);integer timeout,et,em;begin et=expected_tasks(seq);em=expected_merges(seq);@(posedge clk);seq_len<=seq;start<=1;@(posedge clk);start<=0;timeout=0;while(!done&&timeout<2000000)begin @(posedge clk);timeout=timeout+1;end if(timeout>=2000000)$fatal(1,"timeout seq=%0d",seq);if(perr)$fatal(1,"protocol error");if(qki!=et||qkc!=et||sfc!=et||pvc!=et)$fatal(1,"count mismatch");if(merges!=em)$fatal(1,"merge mismatch");if(sl!=0||pl!=0)$fatal(1,"FIFO not empty");$display("CASE_PASS seq=%0d tasks=%0d merges=%0d service_cycles=%0d",seq,et,em,timeout);repeat(4)@(posedge clk);end endtask
 initial begin clk=0;rst_n=0;start=0;seq_len=0;trace_fd=0;if($value$plusargs("TRACE=%s",trace_path))begin trace_fd=$fopen(trace_path,"w");if(!trace_fd)$fatal(1,"trace open");end repeat(5)@(posedge clk);rst_n=1;run_case(128);run_case(384);run_case(1024);if(trace_fd)$fclose(trace_fd);$display("TB_PASS");$finish;end
endmodule
