`timescale 1ns/1ps
module tb_bf16_silu_mul_lut_array#(parameter integer LANES=1,parameter integer MAX_CASES=8192);
 logic clk;always #0.5 clk=~clk;logic rst_n,in_valid,in_ready,out_valid,out_ready,last_i,last_o;logic[LANES*16-1:0]gate_i,up_i,result_o;logic[11:0]tag_i,tag_o;logic[4:0]flags;logic[31:0]lfsr;
 logic[11:0]tags[0:MAX_CASES-1];logic lasts[0:MAX_CASES-1];logic[15:0]g0[0:MAX_CASES-1],u0[0:MAX_CASES-1],e0[0:MAX_CASES-1],g1[0:MAX_CASES-1],u1[0:MAX_CASES-1],e1[0:MAX_CASES-1];logic[11:0]exp_tag[0:MAX_CASES-1];logic exp_last[0:MAX_CASES-1];logic[LANES*16-1:0]exp_data[0:MAX_CASES-1];integer count,input_index,output_index,queue_write,queue_read,fd,scan,timeout,pairs_offered,pairs_accepted,producer_stall_cycles,producer_stalled_pairs,queue_high_water,consumer_backpressure_cycles;string path,line;logic offer_valid;
 bf16_silu_mul_lut_array#(.LANES(LANES),.TAG_W(12))dut(.clk_i(clk),.rst_ni(rst_n),.in_valid_i(in_valid),.in_ready_o(in_ready),.gate_bf16_i(gate_i),.up_bf16_i(up_i),.tag_i(tag_i),.last_i(last_i),.out_valid_o(out_valid),.out_ready_i(out_ready),.result_bf16_o(result_o),.tag_o(tag_o),.last_o(last_o),.exception_flags_o(flags));
 assign in_valid=offer_valid;assign out_ready=lfsr[3]||lfsr[7];always_comb begin tag_i=tags[input_index];last_i=lasts[input_index];gate_i='0;up_i='0;gate_i[15:0]=g0[input_index];up_i[15:0]=u0[input_index];if(LANES==2)begin gate_i[31:16]=g1[input_index];up_i[31:16]=u1[input_index];end end
 always_ff@(posedge clk)begin if(!rst_n)begin lfsr<=32'h51a9cafe;offer_valid<=0;input_index<=0;output_index<=0;queue_write<=0;queue_read<=0;pairs_offered<=0;pairs_accepted<=0;producer_stall_cycles<=0;producer_stalled_pairs<=0;queue_high_water<=0;consumer_backpressure_cycles<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(!offer_valid&&input_index<count&&(lfsr[0]||lfsr[5]))begin offer_valid<=1;pairs_offered<=pairs_offered+LANES;end if(offer_valid&&!in_ready)begin producer_stall_cycles<=producer_stall_cycles+1;producer_stalled_pairs<=producer_stalled_pairs+LANES;end if(offer_valid&&in_ready)begin exp_tag[queue_write]<=tags[input_index];exp_last[queue_write]<=lasts[input_index];exp_data[queue_write][15:0]<=e0[input_index];if(LANES==2)exp_data[queue_write][31:16]<=e1[input_index];queue_write<=queue_write+1;input_index<=input_index+1;pairs_accepted<=pairs_accepted+LANES;offer_valid<=0;end if(out_valid&&!out_ready)consumer_backpressure_cycles<=consumer_backpressure_cycles+1;if(queue_write-queue_read>queue_high_water)queue_high_water<=queue_write-queue_read;if(out_valid&&out_ready)begin if(queue_read>=queue_write)$fatal(1,"output without expectation");if(result_o!==exp_data[queue_read])$fatal(1,"data mismatch idx=%0d",queue_read);if(tag_o!==exp_tag[queue_read]||last_o!==exp_last[queue_read])$fatal(1,"metadata mismatch");queue_read<=queue_read+1;output_index<=output_index+1;end end end
 initial begin clk=0;rst_n=0;if(!$value$plusargs("VECTORS=%s",path))path="tests/vectors/bf16_silu_mul_lut_vectors.txt";fd=$fopen(path,"r");if(fd==0)$fatal(1,"cannot open vectors");count=0;while(!$feof(fd)&&count<MAX_CASES)begin line="";void'($fgets(line,fd));if(line.len()>0&&line.getc(0)!=8'h23)begin scan=$sscanf(line,"%h %d %h %h %h %h %h %h",tags[count],lasts[count],g0[count],u0[count],e0[count],g1[count],u1[count],e1[count]);if(scan==8)count=count+1;end end $fclose(fd);if(count==0)$fatal(1,"no vectors");repeat(5)@(posedge clk);rst_n=1;timeout=0;while(output_index<count&&timeout<2000000)begin @(posedge clk);timeout=timeout+1;end if(timeout>=2000000)$fatal(1,"timeout");if(queue_read!=count||queue_write!=count||pairs_offered!=count*LANES||pairs_accepted!=count*LANES)$fatal(1,"count mismatch");$display("SILU_STALL_COUNTERS LANES=%0d pairs_offered=%0d pairs_accepted=%0d producer_stall_cycles=%0d producer_stalled_pairs=%0d queue_high_water=%0d consumer_backpressure_cycles=%0d total_cycles=%0d",LANES,pairs_offered,pairs_accepted,producer_stall_cycles,producer_stalled_pairs,queue_high_water,consumer_backpressure_cycles,timeout);$display("TB_PASS LANES=%0d cases=%0d",LANES,count);$finish;end
endmodule
