`timescale 1ns/1ps
module tb_fp32_mlo_balanced_summary_scheduler;
 logic clk,rst_n,start,hiv,hir,biv,bir,blast,hov,hor,bov,bor,bol,busy,done,perr;logic[3:0]count;logic[31:0]mi,li,mo,lo,merges,lfsr;logic[127:0]oi,oo;
 logic[3:0]counts[0:3];logic[63:0]ih[0:16],eh[0:3];logic[127:0]ib[0:543],eb[0:127];integer in_summary_base,in_beat_base,out_beat_base,header_stalls,beat_stalls;
 always #0.5 clk=~clk;always_ff@(posedge clk)if(!rst_n)lfsr<=32'hba1a8ce;else lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};
 fp32_mlo_balanced_summary_scheduler dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.summary_count_i(count),.header_valid_i(hiv),.header_ready_o(hir),.m_i(mi),.l_i(li),.beat_valid_i(biv),.beat_ready_o(bir),.o_i(oi),.beat_last_i(blast),.header_valid_o(hov),.header_ready_i(hor),.m_o(mo),.l_o(lo),.beat_valid_o(bov),.beat_ready_i(bor),.o_o(oo),.beat_last_o(bol),.busy_o(busy),.done_o(done),.protocol_error_o(perr),.merges_completed_o(merges));
 task automatic send_header(input logic[63:0]value);begin repeat(lfsr[2:1])@(posedge clk);@(negedge clk);mi=value[31:0];li=value[63:32];hiv=1;do@(posedge clk);while(!hir);@(negedge clk);hiv=0;end endtask
 task automatic send_beat(input logic[127:0]value,input logic last);begin repeat(lfsr[3:2])@(posedge clk);@(negedge clk);oi=value;blast=last;biv=1;do@(posedge clk);while(!bir);@(negedge clk);biv=0;end endtask
 task automatic run_case(input integer id);integer c;begin count=counts[id];@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;for(integer s=0;s<count;s++)begin send_header(ih[in_summary_base+s]);for(integer b=0;b<32;b++)send_beat(ib[in_beat_base+s*32+b],b==31);end
  hor=0;while(!hov)@(posedge clk);while(!(hov&&hor))begin @(negedge clk);hor=lfsr[0]||lfsr[5];if(hov&&!hor)header_stalls++;@(posedge clk);end if({lo,mo}!==eh[id])$fatal(1,"header case=%0d",id);@(negedge clk);hor=0;
  for(integer b=0;b<32;b++)begin logic accepted;logic[127:0]got;logic got_last;accepted=0;bor=0;while(!accepted)begin @(negedge clk);bor=lfsr[1]||lfsr[6];if(bov&&!bor)beat_stalls++;@(posedge clk);if(bov&&bor)begin got=oo;got_last=bol;accepted=1;end end @(negedge clk);bor=0;if(got!==eb[out_beat_base+b]||got_last!==(b==31))begin $display("BEAT_MISMATCH case=%0d b=%0d actual=%032h expected=%032h last=%0d",id,b,got,eb[out_beat_base+b],got_last);$fatal(1,"beat case=%0d b=%0d",id,b);end end if(perr||merges!=count-1)$fatal(1,"accounting case=%0d merges=%0d",id,merges);in_summary_base+=count;in_beat_base+=count*32;out_beat_base+=32;while(busy)@(posedge clk);
 end endtask
 initial begin clk=0;rst_n=0;start=0;hiv=0;biv=0;blast=0;hor=0;bor=0;mi=0;li=0;oi=0;count=0;in_summary_base=0;in_beat_base=0;out_beat_base=0;header_stalls=0;beat_stalls=0;$readmemh("work/results/l5_balanced_summary_scheduler/counts.memh",counts);$readmemh("work/results/l5_balanced_summary_scheduler/input_headers.memh",ih);$readmemh("work/results/l5_balanced_summary_scheduler/input_beats.memh",ib);$readmemh("work/results/l5_balanced_summary_scheduler/expected_headers.memh",eh);$readmemh("work/results/l5_balanced_summary_scheduler/expected_beats.memh",eb);repeat(6)@(posedge clk);rst_n=1;for(integer id=0;id<4;id++)run_case(id);$display("BALANCED_SUMMARY_SCHEDULER_PASS cases=4 input_summaries=17 merges=13 beats=128 header_stalls=%0d beat_stalls=%0d",header_stalls,beat_stalls);$finish;end
 initial begin repeat(200000)@(posedge clk);$fatal(1,"timeout state=%0d",dut.state_q);end
endmodule
