`timescale 1ns/1ps
module tb_idma_e3_efficiency;
 import hetero_idma_512_pkg::*;
 logic clk=0,rst_n=0;always #0.5 clk=~clk;logic req_valid,req_ready,rsp_valid,rsp_ready,rsp_error;logic[63:0]src,dst;logic[31:0]length;logic[7:0]busy;axi_req_t read_req,write_req,joined_req;axi_rsp_t read_rsp,write_rsp,joined_rsp;integer cycles,start_cycle,done_cycle,r_beats,w_beats,r_first,r_last,w_first,w_last;
 idma_backend_rw_axi_flat_wrap dut(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(req_valid),.req_ready_o(req_ready),.src_addr_i(src),.dst_addr_i(dst),.length_i(length),.rsp_valid_o(rsp_valid),.rsp_ready_i(rsp_ready),.rsp_error_o(rsp_error),.axi_read_req_o(read_req),.axi_read_rsp_i(read_rsp),.axi_write_req_o(write_req),.axi_write_rsp_i(write_rsp),.busy_o(busy));
 axi_rw_join#(.axi_req_t(axi_req_t),.axi_resp_t(axi_rsp_t))i_join(.clk_i(clk),.rst_ni(rst_n),.slv_read_req_i(read_req),.slv_read_resp_o(read_rsp),.slv_write_req_i(write_req),.slv_write_resp_o(write_rsp),.mst_req_o(joined_req),.mst_resp_i(joined_rsp));
 axi_sim_mem#(.AddrWidth(64),.DataWidth(512),.IdWidth(4),.UserWidth(1),.axi_req_t(axi_req_t),.axi_rsp_t(axi_rsp_t),.WarnUninitialized(1'b0),.ClearErrOnAccess(1'b1),.ApplDelay(0ns),.AcqDelay(0ns))mem(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(joined_req),.axi_rsp_o(joined_rsp),.mon_r_last_o(),.mon_r_beat_count_o(),.mon_r_user_o(),.mon_r_id_o(),.mon_r_data_o(),.mon_r_addr_o(),.mon_r_valid_o(),.mon_w_last_o(),.mon_w_beat_count_o(),.mon_w_user_o(),.mon_w_id_o(),.mon_w_data_o(),.mon_w_addr_o(),.mon_w_valid_o());
 always_ff@(posedge clk)begin if(!rst_n)begin cycles<=0;r_beats<=0;w_beats<=0;r_first<=-1;r_last<=-1;w_first<=-1;w_last<=-1;end else begin cycles<=cycles+1;if(joined_rsp.r_valid&&joined_req.r_ready)begin if(r_first<0)r_first<=cycles;r_last<=cycles;r_beats<=r_beats+1;end if(joined_req.w_valid&&joined_rsp.w_ready)begin if(w_first<0)w_first<=cycles;w_last<=cycles;w_beats<=w_beats+1;end end end
 initial begin req_valid=0;rsp_ready=1;src=64'h10000000;dst=64'h20000000;length=32'd1048576;repeat(6)@(posedge clk);rst_n=1;@(negedge clk);req_valid=1;do@(posedge clk);while(!req_ready);start_cycle=cycles;@(negedge clk);req_valid=0;do@(posedge clk);while(!(rsp_valid&&rsp_ready));done_cycle=cycles;if(rsp_error||busy!=0||r_beats!=16384||w_beats!=16384)$fatal(1,"idma accounting r=%0d w=%0d busy=%h err=%0d",r_beats,w_beats,busy,rsp_error);$display("IDMA_E3_EFFICIENCY_PASS length=%0d total_cycles=%0d r_beats=%0d r_span=%0d w_beats=%0d w_span=%0d read_eff_ppm=%0d write_eff_ppm=%0d",length,done_cycle-start_cycle,r_beats,r_last-r_first+1,w_beats,w_last-w_first+1,(64'(r_beats)*64'd1000000)/64'(r_last-r_first+1),(64'(w_beats)*64'd1000000)/64'(w_last-w_first+1));$finish;end
 initial begin repeat(2_000_000)@(posedge clk);$fatal(1,"timeout");end
endmodule
