`timescale 1ns/1ps
module tb_l5_q1024_8x8_performance_trace;
 logic clk,rst_n,start,busy,done,mcv,mcr,mck,mdv,mdr,mdk,scv,scr,sdv,sdr,perr;logic[19:0]mct,mdt,sct,sdt;logic[6:0]mcq,scq;logic[9:0]mckv,sckv;logic[3:0]mcqh,scqh;logic[1:0]mckh,sckh;logic[4:0]mcrows,scrows;logic mcclose,mcmerge,mclast,scclose,scmerge,sclast;logic[31:0]qki,qkc,sfc,pvc,merges,lfsr;logic[1:0]sl,pl;integer cycles,matrix_countdown,sfu_countdown,matrix_active,sfu_active,matrix_queue_bubbles,sfu_queue_bubbles,matrix_accepts,sfu_accepts;logic matrix_model_busy,sfu_model_busy,matrix_pending,sfu_pending,matrix_kind;logic[19:0]matrix_task,sfu_task;
 always #0.5 clk=~clk;
 blocked_attention_stream_controller dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.sequence_tokens_i(16'd1024),.busy_o(busy),.done_o(done),.matrix_cmd_valid_o(mcv),.matrix_cmd_ready_i(mcr),.matrix_cmd_kind_o(mck),.matrix_cmd_task_id_o(mct),.matrix_cmd_query_tile_o(mcq),.matrix_cmd_kv_tile_o(mckv),.matrix_cmd_q_head_o(mcqh),.matrix_cmd_kv_head_o(mckh),.matrix_cmd_valid_rows_o(mcrows),.matrix_cmd_close_block_o(mcclose),.matrix_cmd_merge_global_o(mcmerge),.matrix_cmd_last_kv_o(mclast),.matrix_done_valid_i(mdv),.matrix_done_ready_o(mdr),.matrix_done_kind_i(mdk),.matrix_done_task_id_i(mdt),.sfu_cmd_valid_o(scv),.sfu_cmd_ready_i(scr),.sfu_cmd_task_id_o(sct),.sfu_cmd_query_tile_o(scq),.sfu_cmd_kv_tile_o(sckv),.sfu_cmd_q_head_o(scqh),.sfu_cmd_kv_head_o(sckh),.sfu_cmd_valid_rows_o(scrows),.sfu_cmd_close_block_o(scclose),.sfu_cmd_merge_global_o(scmerge),.sfu_cmd_last_kv_o(sclast),.sfu_done_valid_i(sdv),.sfu_done_ready_o(sdr),.sfu_done_task_id_i(sdt),.qk_issued_o(qki),.qk_completed_o(qkc),.sfu_completed_o(sfc),.pv_completed_o(pvc),.summary_merge_rows_o(merges),.score_fifo_level_o(sl),.probability_fifo_level_o(pl),.protocol_error_o(perr));
 assign mcr=!matrix_model_busy&&(lfsr[0]||lfsr[3]);assign scr=!sfu_model_busy&&(lfsr[1]||lfsr[5]);assign mdv=matrix_pending;assign mdk=matrix_kind;assign mdt=matrix_task;assign sdv=sfu_pending;assign sdt=sfu_task;
 always_ff@(posedge clk)begin
  if(!rst_n)begin lfsr<=32'h8e3ace51;cycles<=0;matrix_countdown<=0;sfu_countdown<=0;matrix_active<=0;sfu_active<=0;matrix_queue_bubbles<=0;sfu_queue_bubbles<=0;matrix_accepts<=0;sfu_accepts<=0;matrix_model_busy<=0;sfu_model_busy<=0;matrix_pending<=0;sfu_pending<=0;matrix_kind<=0;matrix_task<=0;sfu_task<=0;end else begin
   cycles<=cycles+1;lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(mcv&&!mcr)matrix_queue_bubbles<=matrix_queue_bubbles+1;if(scv&&!scr)sfu_queue_bubbles<=sfu_queue_bubbles+1;if(matrix_model_busy)matrix_active<=matrix_active+1;if(sfu_model_busy)sfu_active<=sfu_active+1;
   if(mcv&&mcr)begin matrix_model_busy<=1;matrix_kind<=mck;matrix_task<=mct;matrix_countdown<=mck?260:132;matrix_accepts<=matrix_accepts+1;end else if(matrix_model_busy&&!matrix_pending)begin if(matrix_countdown==0)matrix_pending<=1;else matrix_countdown<=matrix_countdown-1;end if(matrix_pending&&mdr)begin matrix_pending<=0;matrix_model_busy<=0;end
   if(scv&&scr)begin sfu_model_busy<=1;sfu_task<=sct;sfu_countdown<=251+(scmerge?730:0);sfu_accepts<=sfu_accepts+1;end else if(sfu_model_busy&&!sfu_pending)begin if(sfu_countdown==0)sfu_pending<=1;else sfu_countdown<=sfu_countdown-1;end if(sfu_pending&&sdr)begin sfu_pending<=0;sfu_model_busy<=0;end
  end
 end
 initial begin clk=0;rst_n=0;start=0;repeat(6)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;while(!done&&cycles<20_000_000)@(posedge clk);if(!done)$fatal(1,"timeout");if(perr||qki!=12672||qkc!=12672||sfc!=12672||pvc!=12672||merges!=43008||matrix_accepts!=25344||sfu_accepts!=12672||sl||pl)$fatal(1,"accounting qki=%0d qkc=%0d sfc=%0d pvc=%0d merge=%0d ma=%0d sa=%0d",qki,qkc,sfc,pvc,merges,matrix_accepts,sfu_accepts);$display("L5_Q1024_8X8_PERFORMANCE_TRACE_PASS total_cycles=%0d matrix_active_cycles=%0d sfu_active_cycles=%0d matrix_queue_bubbles=%0d sfu_queue_bubbles=%0d tasks=%0d merge_rows=%0d score_DDR_bytes=0 probability_DDR_bytes=0",cycles,matrix_active,sfu_active,matrix_queue_bubbles,sfu_queue_bubbles,qki,merges);$finish;end
 initial begin repeat(21_000_000)@(posedge clk);$fatal(1,"global timeout");end
endmodule
