`timescale 1ns/1ps
module tb_l5_toy_bf16_block;logic clk;/* verilator lint_off SYNCASYNCNET */logic rst_n;/* verilator lint_on SYNCASYNCNET */always #5 clk=~clk;integer cycles,matrix_cycles,sfu_cycles;
 logic aiv,air,aov,aor;logic[255:0]aa;logic[511:0]ab;logic[16383:0]ai,ao;logic[4:0]af;logic[31:0]aac,acc;
 bf16_outer_product_array #(.ROWS(16),.COLS(32))array(.clk_i(clk),.rst_ni(rst_n),.in_valid_i(aiv),.in_ready_o(air),.a_i(aa),.b_i(ab),.acc_i(ai),.out_valid_o(aov),.out_ready_i(aor),.acc_o(ao),.exception_flags_o(af),.accepted_steps_o(aac),.completed_steps_o(acc));
 logic riv,rir,rov,ror;logic[511:0]rx,rw,ry;logic[31:0]reps;logic[4:0]rf;logic[31:0]rac,rcc;
 fp32_rmsnorm16 rms(.clk_i(clk),.rst_ni(rst_n),.in_valid_i(riv),.in_ready_o(rir),.x_i(rx),.weight_i(rw),.epsilon_i(reps),.out_valid_o(rov),.out_ready_i(ror),.y_o(ry),.exception_flags_o(rf),.accepted_o(rac),.completed_o(rcc));
 logic piv,pir,pov,por;logic[31:0]pe,po,pc,ps,pre,pro;logic[4:0]pf;logic[31:0]pac,pcc;
 fp32_rope_pair rope(.clk_i(clk),.rst_ni(rst_n),.in_valid_i(piv),.in_ready_o(pir),.even_i(pe),.odd_i(po),.cos_i(pc),.sin_i(ps),.out_valid_o(pov),.out_ready_i(por),.even_o(pre),.odd_o(pro),.exception_flags_o(pf),.accepted_pairs_o(pac),.completed_pairs_o(pcc));
 logic div,dir,dov,dor;logic[127:0]da,db;logic[31:0]ds,dr;logic[4:0]df;
 fp32_dot4_scaled dot(.clk_i(clk),.rst_ni(rst_n),.in_valid_i(div),.in_ready_o(dir),.a_i(da),.b_i(db),.scale_i(ds),.out_valid_o(dov),.out_ready_i(dor),.result_o(dr),.exception_flags_o(df));
 logic smclr,smiv,smir,smov,smor;logic[31:0]sms,smm,sml;logic[127:0]smv,smo;logic[4:0]smf;logic[31:0]smac,smcc;
 fp32_online_softmax #(.LANES(4))u_soft(.clk_i(clk),.rst_ni(rst_n),.clear_i(smclr),.in_valid_i(smiv),.in_ready_o(smir),.score_i(sms),.value_i(smv),.out_valid_o(smov),.out_ready_i(smor),.m_o(smm),.l_o(sml),.o_o(smo),.exception_flags_o(smf),.accepted_tokens_o(smac),.completed_tokens_o(smcc));
 logic siv,sir,sov,sor;logic[31:0]sx,sy;logic[4:0]sf;logic[31:0]sac,scc;
 fp32_silu silu(.clk_i(clk),.rst_ni(rst_n),.in_valid_i(siv),.in_ready_o(sir),.x_i(sx),.out_valid_o(sov),.out_ready_i(sor),.y_o(sy),.exception_flags_o(sf),.accepted_o(sac),.completed_o(scc));
 logic vop16;logic[511:0]va16,vb16,vo16;logic[4:0]vf16;fp32_vector_alu #(.LANES(16))valu16(.op_i(vop16),.a_i(va16),.b_i(vb16),.out_o(vo16),.exception_flags_o(vf16));
 logic vop32;logic[1023:0]va32,vb32,vo32;logic[4:0]vf32;fp32_vector_alu #(.LANES(32))valu32(.op_i(vop32),.a_i(va32),.b_i(vb32),.out_o(vo32),.exception_flags_o(vf32));
 logic[15:0]weights[0:2559];logic[31:0]nw1[0:15],nw2[0:15],rope_c[0:15];
 logic[31:0]ex_x[0:15],ex_n1[0:15],ex_q[0:15],ex_k[0:15],ex_v[0:15],ex_qr[0:15],ex_kr[0:15],ex_att[0:15],ex_op[0:15],ex_r1[0:15],ex_n2[0:15],ex_gate[0:31],ex_up[0:31],ex_silu[0:31],ex_prod[0:31],ex_down[0:15],ex_final[0:15],ex_scores[0:3];
 function automatic[15:0]to_bf16(input[31:0]u);logic[31:0]r;begin r=u+32'h7fff+u[16];to_bf16=r[31:16];end endfunction
 function automatic[63:0]hash16(input[511:0]d);reg[63:0]h;begin h=64'hcbf29ce484222325;for(int i=0;i<16;i++)h=(h^{32'd0,d[i*32+:32]})*64'h100000001b3;hash16=h;end endfunction
 task automatic load16(input logic[31:0]mem[0:15],output logic[511:0]bus);begin for(int i=0;i<16;i++)bus[i*32+:32]=mem[i];end endtask
 task automatic check16(input logic[511:0]bus,input logic[31:0]mem[0:15],input string name);begin for(int i=0;i<16;i++)if(bus[i*32+:32]!==mem[i])$fatal(1,"toy node %s lane=%0d got=%h exp=%h",name,i,bus[i*32+:32],mem[i]);end endtask
 task automatic check32(input logic[1023:0]bus,input logic[31:0]mem[0:31],input string name);begin for(int i=0;i<32;i++)if(bus[i*32+:32]!==mem[i])$fatal(1,"toy node %s lane=%0d",name,i);end endtask
 task automatic run_rms(input logic[511:0]x,input logic[511:0]w,output logic[511:0]y);integer st;begin st=cycles;@(negedge clk);rx=x;rw=w;reps=32'h3727c5ac;riv=1;do @(posedge clk);while(!rir);@(negedge clk);riv=0;do @(posedge clk);while(!(rov&&ror));@(negedge clk);y=ry;if(rf[4:1]!=0)$fatal(1,"toy rms flags");sfu_cycles+=cycles-st;end endtask
 task automatic run_gemv(input logic[1023:0]x,input integer kin,input integer nout,input integer woff,output logic[1023:0]y);logic[16383:0]cur;integer st;begin st=cycles;cur=0;y=0;
  for(int kidx=0;kidx<kin;kidx++)begin aa=0;ab=0;aa[15:0]=to_bf16(x[kidx*32+:32]);for(int j=0;j<nout;j++)ab[j*16+:16]=weights[woff+kidx*nout+j];ai=cur;
   @(negedge clk);aiv=1;do @(posedge clk);while(!air);@(negedge clk);aiv=0;do @(posedge clk);while(!(aov&&aor));@(negedge clk);cur=ao;if(af[4:1]!=0)$fatal(1,"toy gemv flags=%h",af);end
  for(int j=0;j<nout;j++)y[j*32+:32]=cur[j*32+:32];matrix_cycles+=cycles-st;end endtask
 task automatic run_rope(input logic[511:0]x,output logic[511:0]y);integer st;begin st=cycles;y=0;for(int p=0;p<8;p++)begin @(negedge clk);pe=x[(2*p)*32+:32];po=x[(2*p+1)*32+:32];pc=rope_c[2*p];ps=rope_c[2*p+1];piv=1;do @(posedge clk);while(!pir);@(negedge clk);piv=0;do @(posedge clk);while(!(pov&&por));@(negedge clk);y[(2*p)*32+:32]=pre;y[(2*p+1)*32+:32]=pro;end sfu_cycles+=cycles-st;end endtask
 task automatic run_dot(input logic[127:0]a,input logic[127:0]b,output logic[31:0]r);begin @(negedge clk);da=a;db=b;ds=32'h3f000000;div=1;do @(posedge clk);while(!dir);@(negedge clk);div=0;do @(posedge clk);while(!(dov&&dor));@(negedge clk);r=dr;end endtask
 task automatic run_soft(input logic[31:0]score,input logic[127:0]val,output logic[127:0]r);begin @(negedge clk);smclr=1;sms=score;smv=val;smiv=1;do @(posedge clk);while(!smir);@(negedge clk);smiv=0;smclr=0;do @(posedge clk);while(!(smov&&smor));@(negedge clk);r=smo;end endtask
 task automatic run_silu32(input logic[1023:0]x,output logic[1023:0]y);integer st;begin st=cycles;y=0;for(int i=0;i<32;i++)begin @(negedge clk);sx=x[i*32+:32];siv=1;do @(posedge clk);while(!sir);@(negedge clk);siv=0;do @(posedge clk);while(!(sov&&sor));@(negedge clk);y[i*32+:32]=sy;end sfu_cycles+=cycles-st;end endtask
 always @(posedge clk)if(!rst_n)cycles<=0;else cycles<=cycles+1;
 initial begin logic[511:0]x,n1,q,k,v,qr,kr,att,op,r1,n2,down,finalv,nw1b,nw2b;logic[1023:0]gate,up,act,prod,tmp;logic[31:0]score;clk=0;rst_n=0;matrix_cycles=0;sfu_cycles=0;
  aiv=0;aor=1;aa=0;ab=0;ai=0;riv=0;ror=1;piv=0;por=1;div=0;dor=1;smiv=0;smor=1;smclr=0;siv=0;sor=1;vop16=0;va16=0;vb16=0;vop32=0;va32=0;vb32=0;
  $readmemh("work/results/l5_toy_block/vectors/weights_bf16.memh",weights);$readmemh("work/results/l5_toy_block/vectors/norm_weight1.memh",nw1);$readmemh("work/results/l5_toy_block/vectors/norm_weight2.memh",nw2);$readmemh("work/results/l5_toy_block/vectors/rope_coeff.memh",rope_c);
  $readmemh("work/results/l5_toy_block/vectors/x.memh",ex_x);$readmemh("work/results/l5_toy_block/vectors/norm1.memh",ex_n1);$readmemh("work/results/l5_toy_block/vectors/q.memh",ex_q);$readmemh("work/results/l5_toy_block/vectors/k.memh",ex_k);$readmemh("work/results/l5_toy_block/vectors/v.memh",ex_v);$readmemh("work/results/l5_toy_block/vectors/q_rope.memh",ex_qr);$readmemh("work/results/l5_toy_block/vectors/k_rope.memh",ex_kr);$readmemh("work/results/l5_toy_block/vectors/attention.memh",ex_att);$readmemh("work/results/l5_toy_block/vectors/oproj.memh",ex_op);$readmemh("work/results/l5_toy_block/vectors/residual1.memh",ex_r1);$readmemh("work/results/l5_toy_block/vectors/norm2.memh",ex_n2);$readmemh("work/results/l5_toy_block/vectors/gate.memh",ex_gate);$readmemh("work/results/l5_toy_block/vectors/up.memh",ex_up);$readmemh("work/results/l5_toy_block/vectors/silu.memh",ex_silu);$readmemh("work/results/l5_toy_block/vectors/gate_mul_up.memh",ex_prod);$readmemh("work/results/l5_toy_block/vectors/down.memh",ex_down);$readmemh("work/results/l5_toy_block/vectors/final.memh",ex_final);$readmemh("work/results/l5_toy_block/vectors/scores.memh",ex_scores);
  repeat(3)@(posedge clk);rst_n=1;load16(ex_x,x);load16(nw1,nw1b);load16(nw2,nw2b);
  run_rms(x,nw1b,n1);check16(n1,ex_n1,"norm1");tmp=0;tmp[511:0]=n1;run_gemv(tmp,16,16,0,tmp);q=tmp[511:0];check16(q,ex_q,"q");run_gemv({512'd0,n1},16,16,256,tmp);k=tmp[511:0];check16(k,ex_k,"k");run_gemv({512'd0,n1},16,16,512,tmp);v=tmp[511:0];check16(v,ex_v,"v");
  run_rope(q,qr);check16(qr,ex_qr,"q_rope");run_rope(k,kr);check16(kr,ex_kr,"k_rope");att=0;for(int h=0;h<4;h++)begin run_dot(qr[h*128+:128],kr[h*128+:128],score);if(score!==ex_scores[h])$fatal(1,"toy score head=%0d",h);run_soft(score,v[h*128+:128],att[h*128+:128]);end check16(att,ex_att,"attention");
  run_gemv({512'd0,att},16,16,768,tmp);op=tmp[511:0];check16(op,ex_op,"oproj");va16=x;vb16=op;vop16=0;#1;r1=vo16;check16(r1,ex_r1,"residual1");run_rms(r1,nw2b,n2);check16(n2,ex_n2,"norm2");
  run_gemv({512'd0,n2},16,32,1024,gate);check32(gate,ex_gate,"gate");run_gemv({512'd0,n2},16,32,1536,up);check32(up,ex_up,"up");run_silu32(gate,act);check32(act,ex_silu,"silu");va32=act;vb32=up;vop32=1;#1;prod=vo32;check32(prod,ex_prod,"gate_mul_up");run_gemv(prod,32,16,2048,tmp);down=tmp[511:0];check16(down,ex_down,"down");va16=r1;vb16=down;vop16=0;#1;finalv=vo16;check16(finalv,ex_final,"final");
  $display("L5_TOY_BF16_BLOCK_PASS hidden=16 heads=4 mlp=32 total_cycles=%0d matrix_cycles=%0d sfu_cycles=%0d final_fnv64=%016h",cycles,matrix_cycles,sfu_cycles,hash16(finalv));$finish;end
 initial begin repeat(200000)@(posedge clk);$fatal(1,"toy block timeout");end
endmodule
