`timescale 1ns/1ps
module tb_l5_prefill_trace_controller;
 logic clk;/* verilator lint_off SYNCASYNCNET */logic rst_n;/* verilator lint_on SYNCASYNCNET */logic start,cr,ed,cv,lv,score,done,err;logic[10:0]seqin,seqout;logic[4:0]op;logic[2:0]eng;logic[31:0]work,steps,lat,cmds,mt,rope,dot,online,recip,norm,silu,prod,sc;logic[63:0]busy,h128,h384;integer cycles;
 always #5 clk=~clk;always@(posedge clk)if(!rst_n)cycles<=0;else cycles<=cycles+1;
 l5_prefill_trace_controller dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_ready_i(cr),.engine_done_i(ed),.sequence_length_i(seqin),.command_valid_o(cv),.measured_latency_valid_o(lv),.score_matrix_o(score),.done_o(done),.config_error_o(err),.sequence_length_o(seqout),.operation_o(op),.engine_o(eng),.work_items_o(work),.matrix_steps_o(steps),.measured_latency_o(lat),.commands_issued_o(cmds),.matrix_steps_total_o(mt),.rope_pairs_total_o(rope),.dot_operations_total_o(dot),.online_updates_total_o(online),.reciprocals_total_o(recip),.normalization_chunks_total_o(norm),.silu_scalars_total_o(silu),.product_chunks_total_o(prod),.score_matrix_commands_o(sc),.busy_cycles_o(busy));
 function automatic[63:0]hh(input[63:0]h,input[4:0]o,input[31:0]l);logic[63:0]x;begin x=(h^{59'd0,o})*64'h100000001b3;x=(x^{32'd0,l})*64'h100000001b3;hh=x;end endfunction
 task automatic run(input[10:0]seq,output[63:0]hash);longint expected_busy;integer this_lat;begin rst_n=0;start=0;cr=0;ed=0;seqin=seq;hash=64'hcbf29ce484222325;expected_busy=seq==128?61101824:202769664;repeat(3)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;for(int i=0;i<24;i++)begin do@(negedge clk);while(!cv);if(!lv||score||err||seqout!=seq||lat==0)$fatal(1,"prefill trace command seq=%0d cmd=%0d",seq,i);this_lat=lat;hash=hh(hash,op,this_lat);cr=1;@(posedge clk);@(negedge clk);cr=0;for(int c=0;c<this_lat;c++)begin ed=c==this_lat-1;@(posedge clk);@(negedge clk);end ed=0;end if(!done||cmds!=24||sc!=0||busy!=expected_busy)$fatal(1,"prefill trace total seq=%0d busy=%0d expected=%0d",seq,busy,expected_busy);if(seq==128&&mt!=11698176)$fatal(1,"trace q128 steps");if(seq==384&&mt!=35094528)$fatal(1,"trace q384 steps");$display("L5_PREFILL_TRACE_LENGTH_PASS sequence=%0d commands=24 matrix_steps=%0d busy_cycles=%0d wall_cycles=%0d score_matrix_commands=0 command_fnv64=%016h",seq,mt,busy,cycles,hash);end endtask
 initial begin clk=0;run(128,h128);run(384,h384);rst_n=0;seqin=256;repeat(3)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;@(posedge clk);if(!done||!err||cmds!=0||lv)$fatal(1,"trace invalid256");$display("L5_UNIFIED_PREFILL_TRACE_CONTROLLER_PASS same_binary=1 q128_busy=61101824 q384_busy=202769664 invalid256_rejected=1 hash128=%016h hash384=%016h",h128,h384);$finish;end
 initial begin repeat(265000000)@(posedge clk);$fatal(1,"unified trace timeout");end
endmodule
