`timescale 1ns/1ps
module tb_operator_matrix_owner_endpoint_v3;
 logic clk_i,rst_ni;initial begin clk_i=0;rst_ni=0;end always #1 clk_i=~clk_i;logic req_valid_i,req_ready_o;logic[7:0]req_opcode_i;logic[15:0]req_tag_i;logic[7:0]req_parent_phase_i,req_terminal_phase_i;logic[15:0]req_flags_i,req_rows_i,req_columns_i,req_depth_i;logic[23:0]req_src0_i,req_src1_i,req_dst_i;logic step_valid_i,step_ready_o;logic[2:0]step_context_i;logic step_clear_i,step_last_i;logic[255:0]step_a_i;logic[511:0]step_b_i;logic out_valid_o,out_ready_i;logic[2:0]out_context_o;logic out_last_o;logic[16383:0]out_acc_o;logic[4:0]exception_flags_o;logic conv_command_valid_o,conv_command_ready_i;logic[127:0]conv_command_data_o;logic conv_event_valid_i,conv_event_ready_o;logic[55:0]conv_event_data_i;logic completion_valid_o,completion_ready_i;logic[15:0]completion_tag_o;logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o;logic protocol_error_o;logic[7:0]ops[0:5];integer completed;
 operator_matrix_owner_endpoint_v3 dut(.*);
 task finish;begin wait(completion_valid_o);if(completion_status_o||completion_tag_o!=req_tag_i)$fatal(1,"completion");completion_ready_i=1;@(posedge clk_i);@(negedge clk_i);completion_ready_i=0;completed=completed+1;end endtask
 initial begin repeat(3000)@(posedge clk_i);$fatal(1,"timeout");end
 initial begin ops='{8'h20,8'h21,8'h22,8'h23,8'h24,8'h26};req_valid_i=0;req_opcode_i=0;req_tag_i=16'h2000;req_parent_phase_i=8'h12;req_terminal_phase_i=8'h34;req_flags_i=0;req_rows_i=16;req_columns_i=32;req_depth_i=1;req_src0_i=1;req_src1_i=2;req_dst_i=3;step_valid_i=0;step_context_i=0;step_clear_i=1;step_last_i=1;step_a_i=0;step_b_i=0;out_ready_i=1;conv_command_ready_i=0;conv_event_valid_i=0;conv_event_data_i=0;completion_ready_i=0;completed=0;repeat(4)@(posedge clk_i);rst_ni=1;for(int i=0;i<6;i++)begin @(negedge clk_i);req_opcode_i=ops[i];req_tag_i=16'h2000+i;req_valid_i=1;do @(posedge clk_i);while(!req_ready_o);@(negedge clk_i);req_valid_i=0;step_valid_i=1;do @(posedge clk_i);while(!step_ready_o);@(negedge clk_i);step_valid_i=0;wait(out_valid_o);if(!out_last_o)$fatal(1,"matrix result");finish();end
  @(negedge clk_i);req_opcode_i=8'h25;req_tag_i=16'h2500;req_valid_i=1;do @(posedge clk_i);while(!req_ready_o);@(negedge clk_i);req_valid_i=0;wait(conv_command_valid_o);if(conv_command_data_o[7:0]!=8'h22)$fatal(1,"conv command");conv_command_ready_i=1;@(posedge clk_i);@(negedge clk_i);conv_command_ready_i=0;repeat(3)@(posedge clk_i);if(completion_valid_o)$fatal(1,"early conv");conv_event_data_i={16'h2500,8'd0,3'd2,29'd1};conv_event_valid_i=1;@(posedge clk_i);@(negedge clk_i);conv_event_valid_i=0;finish();if(completed!=7||protocol_error_o)$fatal(1,"count");$display("OPERATOR_MATRIX_OWNER_ENDPOINT_V3_PASS opcodes=7 bf16=6 conv=1");$finish;end
endmodule
