`timescale 1ns/1ps
module tb_operator_kv_memory_endpoint_v3;
 logic clk_i,rst_ni;initial begin clk_i=0;rst_ni=0;end always #1 clk_i=~clk_i;
 logic req_valid_i,req_ready_o;logic[7:0]req_opcode_i;logic[15:0]req_tag_i;logic[7:0]req_parent_phase_i,req_terminal_phase_i;
 logic config_valid_i,config_ready_o;logic[31:0]sequence_id_i,token_start_i,token_count_i,generation_i,physical_page_limit_i,bytes_per_token_i;logic[11:0]layer_id_i,kv_head_id_i;logic[63:0]table_base_i,data_base_i,k_address_i,v_address_i,output_address_i;logic[7:0]format_i;
 logic ddr_req_valid_o,ddr_req_ready_i,ddr_req_write_o;logic[63:0]ddr_req_addr_o;logic[127:0]ddr_req_wdata_o;logic[15:0]ddr_req_wstrb_o;logic ddr_rsp_valid_i,ddr_rsp_ready_o;logic[127:0]ddr_rsp_rdata_i;logic ddr_rsp_error_i;
 logic page_req_valid_o,page_req_ready_i,page_req_free_o;logic[31:0]page_req_id_o;logic page_rsp_valid_i,page_rsp_ready_o;logic[31:0]page_rsp_id_i;logic page_rsp_error_i;
 logic idma_req_valid_o,idma_req_ready_i;logic[63:0]idma_src_addr_o,idma_dst_addr_o;logic[31:0]idma_length_o;logic idma_rsp_valid_i,idma_rsp_ready_o,idma_rsp_error_i;
 logic completion_valid_o,completion_ready_i;logic[15:0]completion_tag_o;logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o;logic[63:0]bytes_moved_o;
 logic[127:0]mem[0:4095];logic[31:0]next_page;integer ddr_reads,ddr_writes,page_allocs,page_frees,idma_requests,successful,error_cases;
 operator_kv_memory_endpoint_v3 dut(.*);
 assign ddr_req_ready_i=!ddr_rsp_valid_i;assign page_req_ready_i=!page_rsp_valid_i;assign idma_req_ready_i=!idma_rsp_valid_i;
 always_ff@(posedge clk_i)begin if(!rst_ni)begin ddr_rsp_valid_i<=0;ddr_rsp_rdata_i<=0;ddr_rsp_error_i<=0;ddr_reads<=0;ddr_writes<=0;for(int i=0;i<4096;i++)mem[i]<=0;end else begin if(ddr_rsp_valid_i&&ddr_rsp_ready_o)ddr_rsp_valid_i<=0;if(ddr_req_valid_o&&ddr_req_ready_i)begin if(ddr_req_addr_o[3:0]!=0||ddr_req_wstrb_o!=16'hffff)$fatal(1,"ddr alignment");ddr_rsp_valid_i<=1;ddr_rsp_error_i<=0;if(ddr_req_write_o)begin mem[ddr_req_addr_o[15:4]]<=ddr_req_wdata_o;ddr_writes<=ddr_writes+1;ddr_rsp_rdata_i<=0;end else begin ddr_rsp_rdata_i<=mem[ddr_req_addr_o[15:4]];ddr_reads<=ddr_reads+1;end end end end
 always_ff@(posedge clk_i)begin if(!rst_ni)begin page_rsp_valid_i<=0;page_rsp_id_i<=0;page_rsp_error_i<=0;next_page<=1;page_allocs<=0;page_frees<=0;end else begin if(page_rsp_valid_i&&page_rsp_ready_o)page_rsp_valid_i<=0;if(page_req_valid_o&&page_req_ready_i)begin page_rsp_valid_i<=1;page_rsp_error_i<=0;if(page_req_free_o)begin page_rsp_id_i<=page_req_id_o;page_frees<=page_frees+1;end else begin page_rsp_id_i<=next_page;next_page<=next_page+1;page_allocs<=page_allocs+1;end end end end
 always_ff@(posedge clk_i)begin if(!rst_ni)begin idma_rsp_valid_i<=0;idma_rsp_error_i<=0;idma_requests<=0;end else begin if(idma_rsp_valid_i&&idma_rsp_ready_o)idma_rsp_valid_i<=0;if(idma_req_valid_o&&idma_req_ready_i)begin if(idma_length_o==0||idma_length_o>8192)$fatal(1,"idma length");idma_rsp_valid_i<=1;idma_rsp_error_i<=0;idma_requests<=idma_requests+1;end end end
 task run_op(input[7:0]op,input[31:0]start,count,generation,input[7:0]expected_status,input[63:0]expected_bytes);begin @(negedge clk_i);req_opcode_i=op;token_start_i=start;token_count_i=count;generation_i=generation;req_valid_i=1;do @(posedge clk_i);while(!req_ready_o);@(negedge clk_i);req_valid_i=0;if(op inside{8'h50,8'h51,8'h52,8'h53})begin config_valid_i=1;do @(posedge clk_i);while(!config_ready_o);@(negedge clk_i);config_valid_i=0;end wait(completion_valid_o);if(completion_status_o!=expected_status||bytes_moved_o!=expected_bytes)$fatal(1,"op=%h status=%0d bytes=%0d",op,completion_status_o,bytes_moved_o);repeat(2)@(posedge clk_i);if(!completion_valid_o)$fatal(1,"completion stall");completion_ready_i=1;@(posedge clk_i);@(negedge clk_i);completion_ready_i=0;if(expected_status==0)successful=successful+1;else error_cases=error_cases+1;end endtask
 initial begin repeat(100000)@(posedge clk_i);$fatal(1,"timeout");end
 initial begin req_valid_i=0;req_opcode_i=0;req_tag_i=16'h1234;req_parent_phase_i=8'h56;req_terminal_phase_i=8'h78;config_valid_i=0;sequence_id_i=0;layer_id_i=0;kv_head_id_i=0;token_start_i=0;token_count_i=0;generation_i=1;physical_page_limit_i=4096;bytes_per_token_i=512;table_base_i=0;data_base_i=64'h0010_0000;k_address_i=64'h0020_0000;v_address_i=64'h0030_0000;output_address_i=64'h0040_0000;format_i=0;completion_ready_i=0;successful=0;error_cases=0;repeat(5)@(posedge clk_i);rst_ni=1;
  for(int i=0;i<20;i++)begin run_op(8'h50,0,16,1,0,16384);run_op(8'h51,0,16,1,0,16384);run_op(8'h52,16,16,1,0,0);run_op(8'h50,16,16,1,0,16384);run_op(8'h53,0,32,1,0,0);end
  run_op(8'h50,0,1024,1,0,1048576);run_op(8'h51,0,16,2,9,0);run_op(8'hff,0,16,1,4,0);
  if(successful!=101||error_cases!=2||idma_requests!=248||page_allocs!=105||page_frees!=40)$fatal(1,"counts ok=%0d err=%0d idma=%0d alloc=%0d free=%0d",successful,error_cases,idma_requests,page_allocs,page_frees);
  $display("OPERATOR_KV_MEMORY_ENDPOINT_V3_PASS successful=101 errors=2 q1024_pages=64 idma=248 alloc=105 free=40 ddr_reads=%0d ddr_writes=%0d",ddr_reads,ddr_writes);$finish;end
endmodule
