`timescale 1ns/1ps
module tb_operator_selection_endpoint_v3;
 logic clk_i,rst_ni;initial begin clk_i=0;rst_ni=0;end always #1 clk_i=~clk_i;logic req_valid_i,req_ready_o;logic[7:0]req_opcode_i;logic[15:0]req_tag_i;logic[7:0]req_parent_phase_i,req_terminal_phase_i;logic config_valid_i,config_ready_o;logic[19:0]topk_item_count_i;logic[8:0]topk_k_i;logic[63:0]expand_base_i,expand_stride_i;logic[31:0]route_token_i;logic[4:0]route_count_i;logic[18:0]pool_blocks_i;logic[4:0]pool_ratio_i;logic[8:0]pool_dimensions_i;logic[5:0]mtp_step_count_i;
 logic score_valid_i,score_ready_o;logic[31:0]score_i,score_index_i;logic ranked_valid_o,ranked_ready_i;logic[31:0]ranked_score_o,ranked_index_o;logic[8:0]ranked_rank_o;logic ranked_last_o;logic topk_sram_req_valid_o,topk_sram_req_ready_i,topk_sram_req_write_o;logic[8:0]topk_sram_req_addr_o;logic[64:0]topk_sram_req_wdata_o;logic topk_sram_rsp_valid_i,topk_sram_rsp_ready_o;logic[64:0]topk_sram_rsp_rdata_i;logic topk_sram_rsp_error_i;
 logic expand_valid_i,expand_ready_o;logic[31:0]expand_index_i;logic[8:0]expand_rank_i;logic expand_last_i,expand_out_valid_o,expand_out_ready_i;logic[63:0]expand_address_o;logic[8:0]expand_out_rank_o;logic expand_out_last_o;
 logic route_valid_i,route_ready_o;logic[9:0]route_expert_i;logic[31:0]route_weight_i;logic route_shared_i,dispatch_valid_o,dispatch_ready_i;logic[31:0]dispatch_token_o;logic[9:0]dispatch_expert_o;logic[31:0]dispatch_weight_o;logic[3:0]dispatch_tag_o;logic dispatch_shared_o,dispatch_last_o;logic merge_result_valid_i,merge_result_ready_o;logic[3:0]merge_result_tag_i;logic[511:0]merge_result_data_i;logic merge_valid_o,merge_ready_i;logic[3:0]merge_tag_o;logic[31:0]merge_weight_o;logic[511:0]merge_data_o;logic merge_first_o,merge_last_o;
 logic pool_valid_o,pool_ready_i;logic[17:0]pool_block_o;logic[21:0]pool_token_o;logic[7:0]pool_dimension_o;logic pool_first_token_o,pool_last_token_o,pool_last_dimension_o,pool_last_o;logic mtp_valid_i,mtp_ready_o;logic[31:0]mtp_draft_i,mtp_target_i;logic[5:0]mtp_step_i;logic mtp_last_i,mtp_result_valid_o,mtp_result_ready_i;logic[5:0]mtp_accepted_o,mtp_mismatch_step_o;logic mtp_all_match_o,mtp_rollback_o;logic completion_valid_o,completion_ready_i;logic[15:0]completion_tag_o;logic[7:0]completion_parent_phase_o,completion_terminal_phase_o,completion_status_o;logic[64:0]sram[0:511];integer completed;
 operator_selection_endpoint_v3 dut(.*);assign topk_sram_req_ready_i=!topk_sram_rsp_valid_i;
 always_ff@(posedge clk_i)begin if(!rst_ni)begin topk_sram_rsp_valid_i<=0;topk_sram_rsp_rdata_i<=0;topk_sram_rsp_error_i<=0;for(int i=0;i<512;i++)sram[i]<=0;end else begin if(topk_sram_rsp_valid_i&&topk_sram_rsp_ready_o)topk_sram_rsp_valid_i<=0;if(topk_sram_req_valid_o&&topk_sram_req_ready_i)begin if(topk_sram_req_write_o)sram[topk_sram_req_addr_o]<=topk_sram_req_wdata_o;else begin topk_sram_rsp_valid_i<=1;topk_sram_rsp_rdata_i<=sram[topk_sram_req_addr_o];end end end end
 task issue(input[7:0]op);begin @(negedge clk_i);req_opcode_i=op;req_valid_i=1;do @(posedge clk_i);while(!req_ready_o);@(negedge clk_i);req_valid_i=0;config_valid_i=1;do @(posedge clk_i);while(!config_ready_o);@(negedge clk_i);config_valid_i=0;end endtask
 task finish;begin wait(completion_valid_o);if(completion_status_o||completion_tag_o!=16'h1234||completion_parent_phase_o!=8'h56||completion_terminal_phase_o!=8'h78)$fatal(1,"completion op=%h status=%0d",req_opcode_i,completion_status_o);repeat(2)@(posedge clk_i);if(!completion_valid_o)$fatal(1,"completion stall");completion_ready_i=1;@(posedge clk_i);@(negedge clk_i);completion_ready_i=0;completed=completed+1;end endtask
 initial begin repeat(300000)@(posedge clk_i);$fatal(1,"timeout");end
 initial begin req_valid_i=0;req_opcode_i=0;req_tag_i=16'h1234;req_parent_phase_i=8'h56;req_terminal_phase_i=8'h78;config_valid_i=0;topk_item_count_i=4;topk_k_i=2;expand_base_i=64'h1000;expand_stride_i=64;route_token_i=9;route_count_i=2;pool_blocks_i=2;pool_ratio_i=2;pool_dimensions_i=2;mtp_step_count_i=3;score_valid_i=0;score_i=0;score_index_i=0;ranked_ready_i=0;expand_valid_i=0;expand_index_i=0;expand_rank_i=0;expand_last_i=0;expand_out_ready_i=0;route_valid_i=0;route_expert_i=0;route_weight_i=0;route_shared_i=0;dispatch_ready_i=0;merge_result_valid_i=0;merge_result_tag_i=0;merge_result_data_i=0;merge_ready_i=0;pool_ready_i=0;mtp_valid_i=0;mtp_draft_i=0;mtp_target_i=0;mtp_step_i=0;mtp_last_i=0;mtp_result_ready_i=0;completion_ready_i=0;completed=0;repeat(5)@(posedge clk_i);rst_ni=1;
  issue(8'h70);for(int i=0;i<4;i++)begin @(negedge clk_i);score_i=i==0?32'h3f800000:i==1?32'h40400000:i==2?32'h40000000:32'h40400000;score_index_i=i;score_valid_i=1;do @(posedge clk_i);while(!score_ready_o);end @(negedge clk_i);score_valid_i=0;for(int r=0;r<2;r++)begin wait(ranked_valid_o);if(ranked_index_o!=(r==0?1:3)||ranked_rank_o!=r||ranked_last_o!=(r==1))$fatal(1,"rank r=%0d idx=%0d",r,ranked_index_o);ranked_ready_i=1;@(posedge clk_i);@(negedge clk_i);ranked_ready_i=0;end finish();
  for(int n=0;n<95;n++)begin issue(8'h71);@(negedge clk_i);expand_index_i=n;expand_rank_i=n%8;expand_last_i=1;expand_valid_i=1;do @(posedge clk_i);while(!expand_ready_o);@(negedge clk_i);expand_valid_i=0;wait(expand_out_valid_o);if(expand_address_o!=64'h1000+n*64||!expand_out_last_o)$fatal(1,"expand");expand_out_ready_i=1;@(posedge clk_i);@(negedge clk_i);expand_out_ready_i=0;finish();end
  issue(8'h72);for(int r=0;r<2;r++)begin @(negedge clk_i);route_expert_i=r?7:4;route_weight_i=r?32'h40000000:32'h3f800000;route_shared_i=r;route_valid_i=1;do @(posedge clk_i);while(!route_ready_o);end @(negedge clk_i);route_valid_i=0;for(int r=0;r<2;r++)begin wait(dispatch_valid_o);if(dispatch_tag_o!=r||dispatch_expert_o!=(r?7:4)||dispatch_last_o!=(r==1))$fatal(1,"dispatch");dispatch_ready_i=1;@(posedge clk_i);@(negedge clk_i);dispatch_ready_i=0;end finish();
  issue(8'h73);for(int r=1;r>=0;r--)begin @(negedge clk_i);merge_result_tag_i=r;merge_result_data_i={16{r?32'h40000000:32'h3f800000}};merge_result_valid_i=1;do @(posedge clk_i);while(!merge_result_ready_o);end @(negedge clk_i);merge_result_valid_i=0;for(int r=0;r<2;r++)begin wait(merge_valid_o);if(merge_tag_o!=r||merge_first_o!=(r==0)||merge_last_o!=(r==1))$fatal(1,"merge");merge_ready_i=1;@(posedge clk_i);@(negedge clk_i);merge_ready_i=0;end finish();
  issue(8'h74);for(int i=0;i<8;i++)begin wait(pool_valid_o);if(pool_last_o!=(i==7))$fatal(1,"pool");pool_ready_i=1;@(posedge clk_i);@(negedge clk_i);pool_ready_i=0;end finish();
  issue(8'h75);for(int i=0;i<3;i++)begin @(negedge clk_i);mtp_draft_i=i;mtp_target_i=i==2?99:i;mtp_step_i=i;mtp_last_i=i==2;mtp_valid_i=1;do @(posedge clk_i);while(!mtp_ready_o);end @(negedge clk_i);mtp_valid_i=0;wait(mtp_result_valid_o);if(mtp_accepted_o!=2||mtp_mismatch_step_o!=2||!mtp_rollback_o||mtp_all_match_o)$fatal(1,"mtp");mtp_result_ready_i=1;@(posedge clk_i);@(negedge clk_i);mtp_result_ready_i=0;finish();
  if(completed!=100)$fatal(1,"completed=%0d",completed);$display("OPERATOR_SELECTION_ENDPOINT_V3_PASS successful=100 opcodes=6 topk_external_sram=1");$finish;end
endmodule
