`timescale 1ns/1ps
module tb_operator_bridge_sfu_scratch_v3;
 logic clk_i,rst_ni;initial begin clk_i=0;rst_ni=0;end always #1 clk_i=~clk_i;
 logic micro_valid,micro_ready;logic[7:0]kind,phase,mode;logic[15:0]flags,tag,m,n,k,index0,index1;logic[23:0]src0,src1,src2,dst;
 logic tv,tr;logic[3:0]to,ss0,ss1,ssd;logic[7:0]top,tpp,ttp,tmode,tvariant;logic[15:0]ttag,tflags,tm,tn,tk,tidx0,tidx1;logic[23:0]ts0,ts1,ts2,tdst;logic tsvalid,tfirst,tlast;
 logic owner_cv,owner_cr,root_predicate;logic[15:0]owner_ctag;logic[7:0]owner_cp,owner_ct,owner_cs;logic root_cv,root_cr;logic[15:0]root_tag;logic[7:0]root_phase,root_status;logic bridge_busy,unsupported,bridge_error;
 logic payload_valid,payload_ready;logic[511:0]pa,pb,pc,result;logic[15:0]pmask;logic[31:0]eps;logic plast,result_valid,result_ready,result_last;logic[12:0]eflags;logic domain_error;
 logic soft_score_ready,soft_merge_header_ready,soft_merge_beat_ready,soft_header_valid,soft_weight_valid,soft_beat_valid;logic[31:0]soft_m,soft_l,soft_weight;logic soft_weight_last,soft_beat_last;logic[127:0]soft_o;
 HeteroV3TerminalBridge bridge(.clock(clk_i),.reset(!rst_ni),.io_clear(1'b0),.io_in_ready(micro_ready),.io_in_valid(micro_valid),.io_in_bits_kind(kind),.io_in_bits_flags(flags),.io_in_bits_phase(phase),.io_in_bits_tag(tag),.io_in_bits_mode(mode),.io_in_bits_src0(src0),.io_in_bits_src1(src1),.io_in_bits_src2(src2),.io_in_bits_dst(dst),.io_in_bits_m(m),.io_in_bits_n(n),.io_in_bits_k(k),.io_in_bits_index0(index0),.io_in_bits_index1(index1),.io_terminal_ready(tr),.io_terminal_valid(tv),.io_terminal_bits_owner(to),.io_terminal_bits_opcode(top),.io_terminal_bits_tag(ttag),.io_terminal_bits_parentPhase(tpp),.io_terminal_bits_terminalPhase(ttp),.io_terminal_bits_flags(tflags),.io_terminal_bits_mode(tmode),.io_terminal_bits_src0(ts0),.io_terminal_bits_src1(ts1),.io_terminal_bits_src2(ts2),.io_terminal_bits_dst(tdst),.io_terminal_bits_rows(tm),.io_terminal_bits_columns(tn),.io_terminal_bits_depth(tk),.io_terminal_bits_index0(tidx0),.io_terminal_bits_index1(tidx1),.io_terminal_bits_scratchValid(tsvalid),.io_terminal_bits_scratchSrc0(ss0),.io_terminal_bits_scratchSrc1(ss1),.io_terminal_bits_scratchDst(ssd),.io_terminal_bits_variant(tvariant),.io_terminal_bits_first(tfirst),.io_terminal_bits_last(tlast),.io_terminalCompletion_ready(owner_cr),.io_terminalCompletion_valid(owner_cv),.io_terminalCompletion_bits_tag(owner_ctag),.io_terminalCompletion_bits_parentPhase(owner_cp),.io_terminalCompletion_bits_terminalPhase(owner_ct),.io_terminalCompletion_bits_status(owner_cs),.io_terminalCompletion_bits_predicate(1'b0),.io_completion_ready(root_cr),.io_completion_valid(root_cv),.io_completion_bits_tag(root_tag),.io_completion_bits_phase(root_phase),.io_completion_bits_status(root_status),.io_completion_bits_predicate(root_predicate),.io_busy(bridge_busy),.io_unsupported(unsupported),.io_protocolError(bridge_error));
 operator_sfu_owner_endpoint_v3 sfu(.clk_i,.rst_ni,.req_valid_i(tv),.req_ready_o(tr),.req_opcode_i(top),.req_variant_i(tvariant),.req_tag_i(ttag),.req_parent_phase_i(tpp),.req_terminal_phase_i(ttp),.req_scratch_valid_i(tsvalid),.req_scratch_src0_i(ss0),.req_scratch_src1_i(ss1),.req_scratch_dst_i(ssd),.req_first_i(tfirst),.req_last_i(tlast),.payload_valid_i(payload_valid),.payload_ready_o(payload_ready),.payload_a_i(pa),.payload_b_i(pb),.payload_c_i(pc),.payload_mask_i(pmask),.payload_epsilon_i(eps),.payload_last_i(plast),.result_valid_o(result_valid),.result_ready_i(result_ready),.result_data_o(result),.result_last_o(result_last),.exception_flags_o(eflags),.domain_error_o(domain_error),.soft_score_valid_i(1'b0),.soft_score_ready_o(soft_score_ready),.soft_score_i(0),.soft_score_mask_i(0),.soft_merge_header_valid_i(1'b0),.soft_merge_header_ready_o(soft_merge_header_ready),.soft_ma_i(0),.soft_la_i(0),.soft_mb_i(0),.soft_lb_i(0),.soft_merge_beat_valid_i(1'b0),.soft_merge_beat_ready_o(soft_merge_beat_ready),.soft_oa_i(0),.soft_ob_i(0),.soft_merge_beat_last_i(0),.soft_header_valid_o(soft_header_valid),.soft_header_ready_i(1'b0),.soft_m_o(soft_m),.soft_l_o(soft_l),.soft_weight_valid_o(soft_weight_valid),.soft_weight_ready_i(1'b0),.soft_weight_o(soft_weight),.soft_weight_last_o(soft_weight_last),.soft_beat_valid_o(soft_beat_valid),.soft_beat_ready_i(1'b0),.soft_o_o(soft_o),.soft_beat_last_o(soft_beat_last),.completion_valid_o(owner_cv),.completion_ready_i(owner_cr),.completion_tag_o(owner_ctag),.completion_parent_phase_o(owner_cp),.completion_terminal_phase_o(owner_ct),.completion_status_o(owner_cs));
 task run(input[7:0]fn,input[31:0]expected);begin @(negedge clk_i);kind=fn;tag=16'h1000+fn;micro_valid=1;do @(posedge clk_i);while(!micro_ready);@(negedge clk_i);micro_valid=0;payload_valid=1;do @(posedge clk_i);while(!payload_ready);@(negedge clk_i);payload_valid=0;wait(result_valid);if(result[31:0]!==expected||!result_last)$fatal(1,"fn=%h result=%h expected=%h",fn,result[31:0],expected);repeat(3)@(posedge clk_i);if(root_cv)$fatal(1,"early root completion");result_ready=1;@(posedge clk_i);@(negedge clk_i);result_ready=0;wait(root_cv);if(root_status||root_tag!=16'h1000+fn||bridge_error||unsupported)$fatal(1,"root status fn=%h",fn);root_cr=1;@(posedge clk_i);@(negedge clk_i);root_cr=0;end endtask
 initial begin repeat(20000)@(posedge clk_i);$fatal(1,"timeout");end
 initial begin micro_valid=0;kind=0;flags=0;phase=8'h12;tag=0;mode=0;src0=1;src1=2;src2=3;dst=4;m=16;n=16;k=16;index0=0;index1=0;root_cr=0;payload_valid=0;pa=0;pb=0;pc=0;pmask=16'hffff;eps=32'h358637bd;plast=1;result_ready=0;repeat(5)@(posedge clk_i);rst_ni=1;run(8'h55,32'h3f317218);run(8'h58,32'h00000000);run(8'h56,32'h3effffff);run(8'h57,32'h00000000);$display("OPERATOR_BRIDGE_SFU_SCRATCH_V3_PASS composites=4 leaf_counts=1_1_8_9");$finish;end
endmodule
