`timescale 1ns/1ps
module tb_qwen2_kv_append_ddr_stage_top;
 localparam integer RECORDS=6188,BASE=4096;logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[127:0]commands[0:0],records[0:RECORDS-1];logic qv,qr,sv,sr,cv,pv,pr,pl,pvalid,iv,ir,rv,rr,done;logic[23:0]qi;logic[127:0]sd;logic[9:0]pi;logic[31:0]pp,pg,pc,pu,reqs;logic[63:0]is,id,bytes,ta,da;logic[31:0]il;logic[7:0]status;logic[31:0]lfsr;logic dpending;logic[127:0]dpending_data;logic ipending;integer fetches,ptes,dmas;
 qwen2_kv_append_ddr_stage_top dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_i(commands[0]),.descriptor_req_valid_o(qv),.descriptor_req_ready_i(qr),.descriptor_req_index_o(qi),.descriptor_rsp_valid_i(sv),.descriptor_rsp_ready_o(sr),.descriptor_rsp_data_i(sd),.descriptor_rsp_error_i(1'b0),.pte_valid_o(pv),.pte_ready_i(pr),.pte_level_o(pl),.pte_index_o(pi),.pte_physical_page_o(pp),.pte_generation_o(pg),.pte_refcount_o(pc),.pte_entry_valid_o(pvalid),.idma_req_valid_o(iv),.idma_req_ready_i(ir),.idma_src_addr_o(is),.idma_dst_addr_o(id),.idma_length_o(il),.idma_rsp_valid_i(rv),.idma_rsp_ready_o(rr),.idma_rsp_error_i(1'b0),.done_o(done),.status_o(status),.pte_updates_o(pu),.idma_requests_o(reqs),.payload_bytes_o(bytes),.table_address_o(ta),.data_address_o(da));
 assign qr=!dpending&&(lfsr[0]||lfsr[4]);assign sv=dpending;assign sd=dpending_data;assign pr=lfsr[1]||lfsr[6];assign ir=!ipending&&(lfsr[2]||lfsr[8]);assign rv=ipending&&(lfsr[3]||lfsr[10]);
 always_ff@(posedge clk or negedge rst_n)begin if(!rst_n)begin lfsr<=32'hadd64100;dpending<=0;dpending_data<=0;ipending<=0;fetches<=0;ptes<=0;dmas<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(qv&&qr)begin dpending<=1;dpending_data<=records[qi-BASE];fetches<=fetches+1;end if(sv&&sr)dpending<=0;if(pv&&pr)begin if(ptes==0)begin if(pl||pi||pp)$fatal(1,"root");end else if(!pl||pi!=ptes-1||pp!=ptes-1)$fatal(1,"leaf");if(!pvalid||pg||pc!=1)$fatal(1,"pte fields");ptes<=ptes+1;end if(iv&&ir)begin if(il!=8192)$fatal(1,"len");if((dmas&1)==0)begin if(is!=64'h201000000+(dmas/2)*8192||id!=64'h500008000+(dmas/2)*16384)$fatal(1,"K");end else if(is!=64'h201100000+(dmas/2)*8192||id!=64'h500008000+(dmas/2)*16384+8192)$fatal(1,"V");ipending<=1;dmas<=dmas+1;end if(rv&&rr)ipending<=0;end end
 initial begin string cp,rp;start=0;if(!$value$plusargs("COMMAND=%s",cp)||!$value$plusargs("RECORDS=%s",rp))$fatal(1,"plusargs");$readmemh(cp,commands);$readmemh(rp,records);repeat(5)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(status||fetches!=13||ptes!=65||dmas!=128||pu!=65||reqs!=128||bytes!=1048576||ta!=64'h500000000||da!=64'h500008000||dpending||ipending)$fatal(1,"aggregate status=%0d fetch=%0d pte=%0d dma=%0d bytes=%0d",status,fetches,ptes,dmas,bytes);$display("QWEN2_KV_APPEND_DDR_STAGE_TOP_PASS commands=1 descriptor_fetches=13 pte_updates=65 idma_requests=128 payload_bytes=1048576 pages=64 table_base=0000000500000000 data_base=0000000500008000 random_backpressure=1");$finish;end
 initial begin repeat(12000)@(posedge clk);$fatal(1,"timeout");end
endmodule
