`timescale 1ns/1ps
module tb_qwen2_bias_tile16_controller;
 localparam integer RECORDS=6188,BASE=4096;logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[127:0]commands[0:2],records[0:RECORDS-1];logic dqv,dqr,dsv,dsr,av,ar,asv,asr,rv,rr,rsv,rsr,wv,wr,done;logic[23:0]dqi;logic[127:0]dsd;logic[1:0]ak;logic[63:0]as,ad;logic[31:0]ab,an,ass,ads;logic[14:0]ra,wa;logic[511:0]rd,wd;logic[63:0]be;logic[7:0]status;logic[17:0]elements;logic[31:0]values,lfsr;logic[63:0]dr,dw;logic dpending,apending,lpending;logic[127:0]dpending_data;logic[511:0]lpending_data,l2[0:16383],raw[0:767],bias[0:95],expected[0:767],out[0:767];integer projection,columns,beats,bias_beats,fetches,dmas,delay;
 qwen2_bias_tile16_controller dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_i(commands[projection]),.descriptor_req_valid_o(dqv),.descriptor_req_ready_i(dqr),.descriptor_req_index_o(dqi),.descriptor_rsp_valid_i(dsv),.descriptor_rsp_ready_o(dsr),.descriptor_rsp_data_i(dsd),.descriptor_rsp_error_i(1'b0),.dma_req_valid_o(av),.dma_req_ready_i(ar),.dma_req_kind_o(ak),.dma_src_addr_o(as),.dma_dst_addr_o(ad),.dma_row_bytes_o(ab),.dma_rows_o(an),.dma_src_stride_o(ass),.dma_dst_stride_o(ads),.dma_rsp_valid_i(asv),.dma_rsp_ready_o(asr),.dma_rsp_error_i(1'b0),.l2_rd_valid_o(rv),.l2_rd_ready_i(rr),.l2_rd_addr_o(ra),.l2_rsp_valid_i(rsv),.l2_rsp_ready_o(rsr),.l2_rsp_data_i(rd),.l2_wr_valid_o(wv),.l2_wr_ready_i(wr),.l2_wr_addr_o(wa),.l2_wr_data_o(wd),.l2_wr_be_o(be),.done_o(done),.status_o(status),.elements_o(elements),.values_o(values),.ddr_read_bytes_o(dr),.ddr_write_bytes_o(dw));
 assign dqr=!dpending&&(lfsr[0]||lfsr[5]);assign dsv=dpending;assign dsd=dpending_data;assign ar=!apending&&(lfsr[1]||lfsr[7]);assign asv=apending&&delay==0;assign rr=!lpending&&(lfsr[2]||lfsr[8]);assign rsv=lpending;assign rd=lpending_data;assign wr=lfsr[3]||lfsr[9];
 always@(posedge clk or negedge rst_n)if(!rst_n)begin lfsr<=32'hb1a51600;dpending<=0;apending<=0;lpending<=0;dpending_data<=0;lpending_data<=0;fetches<=0;dmas<=0;delay<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(dqv&&dqr)begin dpending<=1;dpending_data<=records[dqi-BASE];fetches<=fetches+1;end if(dsv&&dsr)dpending<=0;if(rv&&rr)begin lpending<=1;lpending_data<=l2[ra];end if(rsv&&rsr)lpending<=0;if(wv&&wr)l2[wa]<=wd;if(av&&ar)begin apending<=1;delay<=lfsr[12+:3];dmas<=dmas+1;case(ak)1:for(integer i=0;i<beats;i++)l2[8192+i]=raw[i];0:for(integer i=0;i<bias_beats;i++)l2[9216+i]=bias[i];3:for(integer i=0;i<beats;i++)out[i]=l2[10240+i];default:$fatal(1,"kind");endcase end if(apending)begin if(delay!=0)delay<=delay-1;else if(asv&&asr)apending<=0;end end
 initial begin string cp,rp,kind,rawp,biasp,expp;start=0;if(!$value$plusargs("COMMANDS=%s",cp)||!$value$plusargs("RECORDS=%s",rp)||!$value$plusargs("PROJECTION=%d",projection))$fatal(1,"plusargs");kind=projection==0?"q":(projection==1?"k":"v");columns=projection==0?1536:256;beats=16*columns/32;bias_beats=columns/16;rawp=$sformatf("work/results/qwen2_canonical_q_tile16_all/%s_expected_token_major.memh",kind);biasp=$sformatf("work/results/qwen2_canonical_q_tile16_all/%s_bias_fp32.memh",kind);expp=$sformatf("work/results/qwen2_canonical_q_tile16_all/%s_biased_token_major.memh",kind);$readmemh(cp,commands);$readmemh(rp,records);$readmemh(rawp,raw);$readmemh(biasp,bias);$readmemh(expp,expected);repeat(8)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(status||fetches!=6||dmas!=3||elements!=columns||values!=16*columns||dr!=64'(columns)*36||dw!=64'(columns)*32)$fatal(1,"aggregate status=%0d fetch=%0d dma=%0d elem=%0d values=%0d bytes=%0d/%0d",status,fetches,dmas,elements,values,dr,dw);for(integer i=0;i<beats;i++)if(out[i]!==expected[i])$fatal(1,"beat=%0d",i);$display("QWEN2_BIAS_TILE16_CONTROLLER_PASS command=%s rows=16 columns=%0d descriptor_fetches=6 dma_requests=3 bf16_bit_exact=%0d completion=1 random_backpressure=1",kind,columns,16*columns);$finish;end
 initial begin repeat(200000)@(posedge clk);$fatal(1,"timeout state=%0d",dut.st);end
endmodule
