`timescale 1ns/1ps
module tb_qwen2_real_command_submission;
 localparam integer N=252,ADDR_W=15,DATA_W=512;logic clk=0,rst_n=0,hv,hr;logic[127:0]hd;logic[5:0]ev,er,cv,cr;logic[767:0]ed;logic[335:0]cd;logic init;logic[4:0]cl,ql;logic[31:0]macro_err,grants,completion_err,promotions,read_grants,write_grants;logic illegal,lock;logic[3:0]rv,rr,rspv,rspr,rspe;logic[59:0]ra;logic[2047:0]rspd;logic[1:0]wv,wr,prv,prr,prspv,prspr,prspe;logic[29:0]wa,pra;logic[1023:0]wd,prspd;logic[127:0]wbe;logic pwv,pwr;logic[14:0]pwa;logic[511:0]pwd;logic[63:0]pwbe;logic[127:0]commands[0:N-1],held[0:5];logic[7:0]delay[0:5];logic[5:0]busy;logic[31:0]lfsr;integer cycles,sent,accepted,completed,matrix_cmds,sfu_cmds;
 always #0.5 clk=~clk;
 hetero_l3_command_fabric #(.WATCHDOG_CYCLES(256))dut(.clk_i(clk),.rst_ni(rst_n),.host_cmd_valid_i(hv),.host_cmd_ready_o(hr),.host_cmd_data_i(hd),.engine_cmd_valid_o(ev),.engine_cmd_ready_i(er),.engine_cmd_data_o(ed),.engine_completion_valid_i(cv),.engine_completion_ready_o(cr),.engine_completion_data_i(cd),.init_done_o(init),.command_level_o(cl),.completion_level_o(ql),.event_macro_error_count_o(macro_err),.illegal_engine_o(illegal),.watchdog_lock_o(lock),.completion_grants_o(grants),.completion_protocol_error_count_o(completion_err),.l2_rd_valid_i(rv),.l2_rd_ready_o(rr),.l2_rd_addr_i(ra),.l2_rd_rsp_valid_o(rspv),.l2_rd_rsp_ready_i(rspr),.l2_rd_rsp_data_o(rspd),.l2_rd_rsp_error_o(rspe),.l2_wr_valid_i(wv),.l2_wr_ready_o(wr),.l2_wr_addr_i(wa),.l2_wr_data_i(wd),.l2_wr_be_i(wbe),.phy_rd_valid_o(prv),.phy_rd_ready_i(prr),.phy_rd_addr_o(pra),.phy_rsp_valid_i(prspv),.phy_rsp_ready_o(prspr),.phy_rsp_data_i(prspd),.phy_rsp_error_i(prspe),.phy_wr_valid_o(pwv),.phy_wr_ready_i(pwr),.phy_wr_addr_o(pwa),.phy_wr_data_o(pwd),.phy_wr_be_o(pwbe),.descriptor_promotions_o(promotions),.l2_read_grants_o(read_grants),.l2_write_grants_o(write_grants));
 assign rv=0;assign ra=0;assign rspr='1;assign wv=0;assign wa=0;assign wd=0;assign wbe=0;assign prr='1;assign prspv=0;assign prspd=0;assign prspe=0;assign pwr=1;
 always_comb for(integer e=0;e<6;e++)begin er[e]=!busy[e]&&(lfsr[e]||lfsr[e+8]);cd[e*56+:56]={held[e][55:40],8'd0,3'(e),29'd0};end
 always_ff@(posedge clk)begin if(!rst_n)begin lfsr<=32'h5ad19e37;busy<=0;cv<=0;accepted<=0;completed<=0;matrix_cmds<=0;sfu_cmds<=0;cycles<=0;for(integer e=0;e<6;e++)begin held[e]<=0;delay[e]<=0;end end else begin cycles<=cycles+1;lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};for(integer e=0;e<6;e++)begin if(ev[e]&&er[e])begin busy[e]<=1;held[e]<=ed[e*128+:128];delay[e]<=2+(lfsr[e+4+:3]%7);accepted<=accepted+1;if(e==2)matrix_cmds<=matrix_cmds+1;if(e==3)sfu_cmds<=sfu_cmds+1;end else if(busy[e]&&!cv[e])begin if(delay[e]==0)cv[e]<=1;else delay[e]<=delay[e]-1'b1;end if(cv[e]&&cr[e])begin cv[e]<=0;busy[e]<=0;completed<=completed+1;end end end end
 initial begin hv=0;hd=0;$readmemh("work/results/llama_cpp_qwen2_baseline/commands.memh",commands);repeat(8)@(posedge clk);rst_n=1;wait(init);for(integer i=0;i<N;i++)begin @(negedge clk);hd=commands[i];hv=1;do@(posedge clk);while(!hr);@(negedge clk);hv=0;sent=i+1;end wait(completed==N);wait(cl==0&&ql==0);repeat(8)@(posedge clk);if(accepted!=N||grants!=N||matrix_cmds!=140||sfu_cmds!=112||macro_err||completion_err||illegal||lock||promotions||read_grants||write_grants)$fatal(1,"submission accepted=%0d completed=%0d grants=%0d matrix=%0d sfu=%0d errors=%0d/%0d",accepted,completed,grants,matrix_cmds,sfu_cmds,macro_err,completion_err);$display("QWEN2_REAL_COMMAND_SUBMISSION_PASS commands=252 completions=252 matrix=140 sfu=112 event_grants=252 random_backpressure=1 macro_errors=0 protocol_errors=0");$finish;end
 initial begin repeat(100000)@(posedge clk);$fatal(1,"timeout");end
endmodule
