`timescale 1ns/1ps
module tb_qwen2_real_payload_endpoint;
 localparam integer ADDR_W=15,DATA_W=512;logic clk=0,rst_n=0,hv,hr;logic[127:0]hd,commands[0:1];logic[5:0]ev,er,cv,cr;logic[767:0]ed;logic[335:0]cd;logic init;logic[4:0]cl,ql;logic[31:0]macro_err,grants,completion_err,promotions,read_grants,write_grants;logic illegal,lock;logic[3:0]rv,rr,rspv,rspr,rspe;logic[59:0]ra;logic[2047:0]rspd;logic[1:0]wv,wr,prv,prr,prspv,prspr,prspe;logic[29:0]wa,pra;logic[1023:0]wd,prspd;logic[127:0]wbe;logic pwv,pwr;logic[14:0]pwa;logic[511:0]pwd;logic[63:0]pwbe;logic[31:0]lfsr;
 logic spv,spr,sov,sor,scv,scr;logic[49151:0]sx,sw,sy;logic[55:0]scd;logic[4:0]sflags;
 logic mpv,mpr,mov,mor,mlast,mcv,mcr,merr;logic[2:0]mpctx,moctx;logic mpclear,mplast;logic[255:0]mpa;logic[511:0]mpb;logic[16383:0]macc;logic[55:0]mcd;
 logic[31:0]xmem[0:7679],wmem[0:7679],norm[0:1535];logic[15:0]mwmem[0:245759],erMS[0:1535],emat[0:31];integer sent,matrix_outputs;
 always #0.5 clk=~clk;always_ff@(posedge clk)if(!rst_n)lfsr<=32'h6d31a957;else lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};assign sor=lfsr[0]||lfsr[4];assign mor=lfsr[1]||lfsr[6];
 hetero_l3_command_fabric#(.WATCHDOG_CYCLES(20000))fabric(.clk_i(clk),.rst_ni(rst_n),.host_cmd_valid_i(hv),.host_cmd_ready_o(hr),.host_cmd_data_i(hd),.engine_cmd_valid_o(ev),.engine_cmd_ready_i(er),.engine_cmd_data_o(ed),.engine_completion_valid_i(cv),.engine_completion_ready_o(cr),.engine_completion_data_i(cd),.init_done_o(init),.command_level_o(cl),.completion_level_o(ql),.event_macro_error_count_o(macro_err),.illegal_engine_o(illegal),.watchdog_lock_o(lock),.completion_grants_o(grants),.completion_protocol_error_count_o(completion_err),.l2_rd_valid_i(rv),.l2_rd_ready_o(rr),.l2_rd_addr_i(ra),.l2_rd_rsp_valid_o(rspv),.l2_rd_rsp_ready_i(rspr),.l2_rd_rsp_data_o(rspd),.l2_rd_rsp_error_o(rspe),.l2_wr_valid_i(wv),.l2_wr_ready_o(wr),.l2_wr_addr_i(wa),.l2_wr_data_i(wd),.l2_wr_be_i(wbe),.phy_rd_valid_o(prv),.phy_rd_ready_i(prr),.phy_rd_addr_o(pra),.phy_rsp_valid_i(prspv),.phy_rsp_ready_o(prspr),.phy_rsp_data_i(prspd),.phy_rsp_error_i(prspe),.phy_wr_valid_o(pwv),.phy_wr_ready_i(pwr),.phy_wr_addr_o(pwa),.phy_wr_data_o(pwd),.phy_wr_be_o(pwbe),.descriptor_promotions_o(promotions),.l2_read_grants_o(read_grants),.l2_write_grants_o(write_grants));
 qwen2_sfu_command_endpoint sfu(.clk_i(clk),.rst_ni(rst_n),.cmd_valid_i(ev[3]),.cmd_ready_o(er[3]),.cmd_i(ed[3*128+:128]),.payload_valid_i(spv),.payload_ready_o(spr),.payload_x_i(sx),.payload_weight_i(sw),.out_valid_o(sov),.out_ready_i(sor),.out_y_o(sy),.completion_valid_o(scv),.completion_ready_i(scr),.completion_data_o(scd),.exception_flags_o(sflags));
 qwen2_matrix_command_endpoint matrix(.clk_i(clk),.rst_ni(rst_n),.cmd_valid_i(ev[2]),.cmd_ready_o(er[2]),.cmd_i(ed[2*128+:128]),.step_valid_i(mpv),.step_ready_o(mpr),.step_context_i(mpctx),.step_clear_i(mpclear),.step_last_i(mplast),.command_last_tile_i(1'b1),.step_a_i(mpa),.step_b_i(mpb),.out_valid_o(mov),.out_ready_i(mor),.out_context_o(moctx),.out_last_o(mlast),.out_acc_o(macc),.completion_valid_o(mcv),.completion_ready_i(mcr),.completion_data_o(mcd),.protocol_error_o(merr));
 always_comb begin er[0]=0;er[1]=0;er[4]=0;er[5]=0;cv=0;cd=0;cv[2]=mcv;cv[3]=scv;mcr=cr[2];scr=cr[3];cd[2*56+:56]=mcd;cd[3*56+:56]=scd;end
 assign rv=0;assign ra=0;assign rspr='1;assign wv=0;assign wa=0;assign wd=0;assign wbe=0;assign prr='1;assign prspv=0;assign prspd=0;assign prspe=0;assign pwr=1;
 function automatic[15:0]bf(input logic[31:0]v);logic[31:0]r;begin r=v+32'h7fff+v[16];bf=r[31:16];end endfunction
 always_ff@(posedge clk)if(rst_n)begin if(sov&&sor)for(integer i=0;i<1536;i++)begin if(bf(sy[i*32+:32])!==erMS[i])$fatal(1,"rms i=%0d",i);norm[i]<=sy[i*32+:32];end if(mov&&mor)begin matrix_outputs<=matrix_outputs+1;if(mlast)for(integer c=0;c<32;c++)if(bf(macc[c*32+:32])!==emat[c])$fatal(1,"matrix c=%0d",c);end end
 task automatic send(input[127:0]c);begin @(negedge clk);hd=c;hv=1;do@(posedge clk);while(!hr);@(negedge clk);hv=0;sent++;end endtask
 initial begin hv=0;spv=0;mpv=0;mpctx=0;mpclear=0;mplast=0;mpa=0;mpb=0;sx=0;sw=0;sent=0;matrix_outputs=0;$readmemh("work/results/qwen2_real_payload_endpoint/commands.memh",commands);$readmemh("work/results/l5_qwen2_four_layer_reference/cross_vectors/rms_x_fp32.memh",xmem);$readmemh("work/results/l5_qwen2_four_layer_reference/cross_vectors/rms_weight_fp32.memh",wmem);$readmemh("work/results/l5_qwen2_four_layer_reference/cross_vectors/matrix_weights_bf16.memh",mwmem);$readmemh("work/results/qwen2_real_payload_endpoint/rms_expected.memh",erMS);$readmemh("work/results/qwen2_real_payload_endpoint/matrix_expected.memh",emat);for(integer i=0;i<1536;i++)begin sx[i*32+:32]=xmem[i];sw[i*32+:32]=wmem[i];end repeat(8)@(posedge clk);rst_n=1;wait(init);send(commands[0]);send(commands[1]);wait(spr);@(negedge clk);spv=1;do@(posedge clk);while(!spr);@(negedge clk);spv=0;wait(grants>=1);for(integer k=0;k<1536;k++)begin mpa=0;mpa[15:0]=bf(norm[k]);for(integer c=0;c<32;c++)mpb[c*16+:16]=mwmem[k*160+c];mpclear=k==0;mplast=k==1535;mpv=1;do@(posedge clk);while(!mpr);@(negedge clk);mpv=0;end wait(grants==2);wait(cl==0&&ql==0);repeat(8)@(posedge clk);if(sent!=2||matrix_outputs!=1536||macro_err||completion_err||illegal||lock||merr||sflags[4:1])$fatal(1,"final sent=%0d outputs=%0d grants=%0d macro=%0d completion=%0d illegal=%0d lock=%0d merr=%0d sflags=%h",sent,matrix_outputs,grants,macro_err,completion_err,illegal,lock,merr,sflags);$display("QWEN2_REAL_PAYLOAD_ENDPOINT_PASS commands=2 completions=2 rms_values=1536 matrix_steps=1536 matrix_outputs=32 bf16_bit_exact=1568 event_order=1 random_backpressure=1");$finish;end
 initial begin repeat(200000)@(posedge clk);$fatal(1,"timeout");end
endmodule
