`timescale 1ns/1ps
module tb_qwen2_rope_token01_payload;
 logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[5:0]beats;logic[9:0]heads,dim;logic[3:0]lane;logic rv,rr,rsv,rsr,wv,wr,done,bad;logic[14:0]ra,wa;logic[511:0]rd,wd;logic[63:0]be;logic[31:0]reads,writes,pairs,pos,steps;logic[4:0]flags;logic[511:0]mem[0:255],qin[0:47],kin[0:7],qexp[0:47],kexp[0:7];logic[31:0]lfsr;logic pending;logic[511:0]pending_data;integer run_id;
 qwen2_shared_l2_rope_payload #(.ADDR_W(15))dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.data_beats_i(beats),.heads_i(heads),.head_dim_i(dim),.position_lane_i(lane),.data_local_i(64'd0),.position_local_i(64'h1000),.out_local_i(64'h2000),.l2_rd_valid_o(rv),.l2_rd_ready_i(rr),.l2_rd_addr_o(ra),.l2_rsp_valid_i(rsv),.l2_rsp_ready_o(rsr),.l2_rsp_data_i(rd),.l2_wr_valid_o(wv),.l2_wr_ready_i(wr),.l2_wr_addr_o(wa),.l2_wr_data_o(wd),.l2_wr_be_o(be),.done_o(done),.unsupported_position_o(bad),.read_beats_o(reads),.write_beats_o(writes),.pairs_o(pairs),.position_o(pos),.coefficient_steps_o(steps),.exception_flags_o(flags));
 assign rr=!pending&&(lfsr[0]||lfsr[4]);assign rsv=pending;assign rd=pending_data;assign wr=lfsr[1]||lfsr[7];
 always@(posedge clk or negedge rst_n)begin if(!rst_n)begin lfsr<=32'h701e0101;pending<=0;pending_data<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(rv&&rr)begin pending<=1;pending_data<=mem[ra];end if(rsv&&rsr)pending<=0;if(wv&&wr)mem[wa]<=wd;end end
 task automatic execute(input integer is_k,input integer position);begin beats=is_k?8:48;heads=is_k?2:12;dim=128;lane=position[3:0];for(integer i=0;i<beats;i++)mem[i]=is_k?kin[i]:qin[i];mem[64]=0;mem[64][31:0]=0;mem[64][63:32]=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(bad||pos!=position||pairs!=(is_k?128:768)||reads!=beats+1||writes!=beats||steps!=(position?64:0)||flags[4:1])$fatal(1,"run=%0d bad=%0d pos=%0d pairs=%0d reads=%0d writes=%0d steps=%0d flags=%h",run_id,bad,pos,pairs,reads,writes,steps,flags);for(integer i=0;i<beats;i++)if(mem[128+i]!==((position==0)?(is_k?kin[i]:qin[i]):(is_k?kexp[i]:qexp[i])))$fatal(1,"run=%0d beat=%0d",run_id,i);run_id=run_id+1;@(posedge clk);@(negedge clk);end endtask
 initial begin start=0;beats=0;heads=0;dim=0;lane=0;run_id=0;$readmemh("work/results/qwen2_rope_token01_vectors/q_input.memh",qin);$readmemh("work/results/qwen2_rope_token01_vectors/k_input.memh",kin);$readmemh("work/results/qwen2_rope_token01_vectors/q_position1_expected.memh",qexp);$readmemh("work/results/qwen2_rope_token01_vectors/k_position1_expected.memh",kexp);repeat(6)@(posedge clk);rst_n=1;execute(0,0);execute(0,1);execute(1,0);execute(1,1);$display("QWEN2_ROPE_TOKEN01_PAYLOAD_PASS runs=4 Q_pairs=1536 K_pairs=256 coefficient_steps=128 bf16_bit_exact=3584 theta=1000000 split_half=1 Q_K_state_independent=1 random_backpressure=1");$finish;end
 initial begin repeat(30000)@(posedge clk);$fatal(1,"timeout run=%0d state=%0d",run_id,dut.st);end
endmodule
