`timescale 1ns/1ps
module tb_qwen2_kv_bias_add;
 logic clk=0,rst_n=0,iv,ir,ov,orr;always #0.5 clk=~clk;logic[511:0]d,y;logic[1023:0]b;logic[4:0]flags;logic[31:0]acc,done,lfsr;
 logic[511:0]qr[0:47],qb[0:95],qe[0:47],kr[0:7],kb[0:15],ke[0:7],vr[0:7],vb[0:15],ve[0:7];integer sent,received;
 bf16_bias_add_tile32 dut(.clk_i(clk),.rst_ni(rst_n),.in_valid_i(iv),.in_ready_o(ir),.data_i(d),.bias_i(b),.out_valid_o(ov),.out_ready_i(orr),.data_o(y),.exception_flags_o(flags),.accepted_o(acc),.completed_o(done));
 always_ff@(posedge clk or negedge rst_n)if(!rst_n)lfsr<=32'h63a9d71f;else lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};assign orr=lfsr[0]||lfsr[6];
 task automatic send(input[511:0]x,input[1023:0]bias);begin @(negedge clk);d=x;b=bias;iv=1;do@(posedge clk);while(!ir);@(negedge clk);iv=0;sent++;end endtask
 always_ff@(posedge clk)if(rst_n&&ov&&orr)begin if(received<48)begin if(y!==qe[received])$fatal(1,"Q bias beat=%0d",received);end else if(received<56)begin if(y!==ke[received-48])$fatal(1,"K bias beat=%0d",received-48);end else if(y!==ve[received-56])$fatal(1,"V bias beat=%0d",received-56);received<=received+1;end
 initial begin iv=0;d=0;b=0;sent=0;received=0;$readmemh("work/results/qwen2_shared_l2_tile_payload/q_expected_all_beats.memh",qr);$readmemh("work/results/qwen2_shared_l2_tile_payload/q_bias_fp32_beats.memh",qb);$readmemh("work/results/qwen2_shared_l2_tile_payload/q_biased_expected_all_beats.memh",qe);$readmemh("work/results/qwen2_kv_projection_vectors/k_raw_expected_beats.memh",kr);$readmemh("work/results/qwen2_kv_projection_vectors/k_bias_fp32_beats.memh",kb);$readmemh("work/results/qwen2_kv_projection_vectors/k_biased_expected_beats.memh",ke);$readmemh("work/results/qwen2_kv_projection_vectors/v_raw_expected_beats.memh",vr);$readmemh("work/results/qwen2_kv_projection_vectors/v_bias_fp32_beats.memh",vb);$readmemh("work/results/qwen2_kv_projection_vectors/v_biased_expected_beats.memh",ve);repeat(6)@(posedge clk);rst_n=1;for(integer i=0;i<48;i++)send(qr[i],{qb[2*i+1],qb[2*i]});for(integer i=0;i<8;i++)send(kr[i],{kb[2*i+1],kb[2*i]});for(integer i=0;i<8;i++)send(vr[i],{vb[2*i+1],vb[2*i]});wait(received==64);repeat(5)@(posedge clk);if(acc!=64||done!=64||flags[4:1])$fatal(1,"bias counters/flags");$display("QWEN2_QKV_BIAS_ADD_PASS Q_values=1536 K_values=256 V_values=256 beats=64 bias_format=FP32 bf16_bit_exact=2048 random_backpressure=1 accepted=64 completed=64");$finish;end
 initial begin repeat(10000)@(posedge clk);$fatal(1,"timeout sent=%0d received=%0d",sent,received);end
endmodule
