`timescale 1ns/1ps
module tb_qwen2_matrix_tile16_payload;
 logic clk=0,rst_n=0,start,rv,rr,rsv,rsr,wv,wr,mpv,mpr,mc,ml,mov,mor,mol,done,mcv,merr;always #0.5 clk=~clk;logic[14:0]ra,wa;logic[511:0]rd,wd,mb;logic[63:0]be;logic[2:0]mctx,moctx;logic[255:0]ma;logic[16383:0]macc;logic[55:0]mcd;logic[31:0]reads,writes,steps,lfsr;logic pending;logic[511:0]pending_data,mem[0:4095],avec[0:1535],wvec[0:1535],expected[0:15];logic[127:0]command;integer completions;
 qwen2_shared_l2_matrix_tile16_payload payload(.depth_i(16'd1536),.rows_i(16'd16),.columns_i(16'd32),.status_o(),.clk_i(clk),.rst_ni(rst_n),.start_i(start),.activation_local_i(0),.weight_local_i(64'h18000),.output_local_i(64'h30000),.l2_rd_valid_o(rv),.l2_rd_ready_i(rr),.l2_rd_addr_o(ra),.l2_rsp_valid_i(rsv),.l2_rsp_ready_o(rsr),.l2_rsp_data_i(rd),.l2_wr_valid_o(wv),.l2_wr_ready_i(wr),.l2_wr_addr_o(wa),.l2_wr_data_o(wd),.l2_wr_be_o(be),.matrix_step_valid_o(mpv),.matrix_step_ready_i(mpr),.matrix_context_o(mctx),.matrix_clear_o(mc),.matrix_last_o(ml),.matrix_a_o(ma),.matrix_b_o(mb),.matrix_out_valid_i(mov),.matrix_out_ready_o(mor),.matrix_out_last_i(mol),.matrix_acc_i(macc),.done_o(done),.read_beats_o(reads),.write_beats_o(writes),.matrix_steps_o(steps));
 qwen2_matrix_command_endpoint matrix(.clk_i(clk),.rst_ni(rst_n),.cmd_valid_i(start),.cmd_ready_o(),.cmd_i(command),.step_valid_i(mpv),.step_ready_o(mpr),.step_context_i(mctx),.step_clear_i(mc),.step_last_i(ml),.command_last_tile_i(1'b1),.step_a_i(ma),.step_b_i(mb),.out_valid_o(mov),.out_ready_i(mor),.out_context_o(moctx),.out_last_o(mol),.out_acc_o(macc),.completion_valid_o(mcv),.completion_ready_i(1'b1),.completion_data_o(mcd),.protocol_error_o(merr));
 assign rr=!pending&&(lfsr[0]||lfsr[4]);assign rsv=pending;assign rd=pending_data;assign wr=lfsr[1]||lfsr[7];always@(posedge clk or negedge rst_n)if(!rst_n)begin lfsr<=32'h16a32c01;pending<=0;pending_data<=0;completions<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(rv&&rr)begin pending<=1;pending_data<=mem[ra];end if(rsv&&rsr)pending<=0;if(wv&&wr)mem[wa]<=wd;if(mcv)completions<=completions+1;end
 initial begin start=0;command=128'h00100800100700100600020001000220;$readmemh("work/results/qwen2_canonical_tile16_vectors/activation_kmajor.memh",avec);$readmemh("work/results/qwen2_canonical_tile16_vectors/q_weight_tile0.memh",wvec);$readmemh("work/results/qwen2_canonical_tile16_vectors/expected_rows.memh",expected);for(integer i=0;i<1536;i++)begin mem[i]=avec[i];mem[1536+i]=wvec[i];end repeat(8)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(reads!=3072||writes!=16||steps!=1536||completions!=1||merr||mcd[39:32])$fatal(1,"aggregate r=%0d w=%0d s=%0d c=%0d err=%0d",reads,writes,steps,completions,merr);for(integer r=0;r<16;r++)if(mem[3072+r]!==expected[r])$fatal(1,"row=%0d",r);$display("QWEN2_MATRIX_TILE16_PAYLOAD_PASS rows=16 columns=32 k=1536 matrix_steps=1536 effective_macs=786432 reads=3072 writes=16 bf16_bit_exact=512 completion=1 random_backpressure=1");$finish;end
 initial begin repeat(50000)@(posedge clk);$fatal(1,"timeout state=%0d k=%0d",payload.st,payload.k_q);end
endmodule
