`timescale 1ns/1ps
module tb_qwen2_bias_stage_vcs;
 import hetero_idma_512_pkg::*;localparam integer AW=15,DBEATS=1547;logic clk=0,rst_n=0,start,done;always #0.5 clk=~clk;logic[127:0]cmd[0:2],current;logic[55:0]a[0:8];
 logic dqv,dqr,dsv,dsr,dse;logic[23:0]dqi;logic[127:0]dsd;logic fqv,fqr,frv,frr;logic[AW-1:0]fqa;logic[511:0]frd;logic av,ar;logic[1:0]ak;logic[63:0]as,ad;logic[31:0]ab,an,ass,ads;logic asv,asr,ase;
 logic iv,ir,ior,iordy,ioe,local_source;logic[63:0]isrc,idst;logic[31:0]ilen,flat;logic[7:0]ibusy;axi_req_t iread,iwrite,local_req,ddr_req;axi_rsp_t iread_rsp,iwrite_rsp,local_rsp,ddr_rsp;logic brv,brr,brsv,brsr,bwv,bwr,bbusy;logic[AW-1:0]bra,bwa;logic[511:0]brd,bwd;logic[63:0]bbe;
 logic trv,trr,trsv,trsr,twv,twr;logic[AW-1:0]tra,twa;logic[511:0]trd,twd;logic[63:0]tbe;logic[7:0]status;logic[17:0]elements;logic[63:0]dr,dw;logic[31:0]lr,lw;logic[1:0]mrv,mrr,mrsv,mrsr;logic[2*AW-1:0]mra;logic[1023:0]mrd;logic mwv,mwr;logic[AW-1:0]mwa;logic[511:0]mwd;logic[63:0]mbe;logic[63:0]cy,lreads,lwrites,conflicts,rstalls,wstalls;logic[1:0]owner;logic[31:0]lfsr;logic host,hwv;logic[AW-1:0]hwa;logic[511:0]hwd;
 logic[511:0]db[0:DBEATS-1],qr[0:47],qb[0:95],qe[0:47],kr[0:7],kb[0:15],ke[0:7],vr[0:7],vb[0:15],ve[0:7];integer desc,flat_seen,rbeats,wbeats;logic[63:0]sumr,sumw;logic[31:0]sumlr,sumlw;
 qwen2_bias_stage_top #(.ADDR_W(AW))top(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_i(current),.descriptor_req_valid_o(dqv),.descriptor_req_ready_i(dqr),.descriptor_req_index_o(dqi),.descriptor_rsp_valid_i(dsv),.descriptor_rsp_ready_o(dsr),.descriptor_rsp_data_i(dsd),.descriptor_rsp_error_i(dse),.dma_req_valid_o(av),.dma_req_ready_i(ar),.dma_req_kind_o(ak),.dma_src_addr_o(as),.dma_dst_addr_o(ad),.dma_row_bytes_o(ab),.dma_rows_o(an),.dma_src_stride_o(ass),.dma_dst_stride_o(ads),.dma_rsp_valid_i(asv),.dma_rsp_ready_o(asr),.dma_rsp_error_i(ase),.l2_rd_valid_o(trv),.l2_rd_ready_i(trr),.l2_rd_addr_o(tra),.l2_rsp_valid_i(trsv),.l2_rsp_ready_o(trsr),.l2_rsp_data_i(trd),.l2_wr_valid_o(twv),.l2_wr_ready_i(twr),.l2_wr_addr_o(twa),.l2_wr_data_o(twd),.l2_wr_be_o(tbe),.done_o(done),.status_o(status),.elements_o(elements),.ddr_read_bytes_o(dr),.ddr_write_bytes_o(dw),.l2_read_beats_o(lr),.l2_write_beats_o(lw));
 qwen2_tile_idma_expand expand(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(av),.req_ready_o(ar),.req_kind_i(ak),.src_addr_i(as),.dst_addr_i(ad),.row_bytes_i(ab),.rows_i(an),.src_stride_i(ass),.dst_stride_i(ads),.rsp_valid_o(asv),.rsp_ready_i(asr),.rsp_error_o(ase),.idma_req_valid_o(iv),.idma_req_ready_i(ir),.idma_src_addr_o(isrc),.idma_dst_addr_o(idst),.idma_length_o(ilen),.idma_rsp_valid_i(ior),.idma_rsp_ready_o(iordy),.idma_rsp_error_i(ioe),.flat_requests_o(flat),.local_source_o(local_source));idma_backend_rw_axi_flat_wrap idma(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(iv),.req_ready_o(ir),.src_addr_i(isrc),.dst_addr_i(idst),.length_i(ilen),.rsp_valid_o(ior),.rsp_ready_i(iordy),.rsp_error_o(ioe),.axi_read_req_o(iread),.axi_read_rsp_i(iread_rsp),.axi_write_req_o(iwrite),.axi_write_rsp_i(iwrite_rsp),.busy_o(ibusy));always_comb begin local_req=0;ddr_req=0;iread_rsp=0;iwrite_rsp=0;if(local_source)begin local_req=iread;ddr_req=iwrite;iread_rsp=local_rsp;iwrite_rsp=ddr_rsp;end else begin ddr_req=iread;local_req=iwrite;iread_rsp=ddr_rsp;iwrite_rsp=local_rsp;end end
 qwen2_axi_shared_l2_bridge #(.ADDR_W(AW))bridge(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(local_req),.axi_rsp_o(local_rsp),.l2_rd_valid_o(brv),.l2_rd_ready_i(brr),.l2_rd_addr_o(bra),.l2_rsp_valid_i(brsv),.l2_rsp_ready_o(brsr),.l2_rsp_data_i(brd),.l2_wr_valid_o(bwv),.l2_wr_ready_i(bwr),.l2_wr_addr_o(bwa),.l2_wr_data_o(bwd),.l2_wr_be_o(bbe),.busy_o(bbusy));axi_sim_mem#(.AddrWidth(64),.DataWidth(512),.IdWidth(4),.UserWidth(1),.axi_req_t(axi_req_t),.axi_rsp_t(axi_rsp_t),.WarnUninitialized(1'b0),.ClearErrOnAccess(1'b1),.ApplDelay(0ns),.AcqDelay(0ns))ddr(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(ddr_req),.axi_rsp_o(ddr_rsp),.mon_r_last_o(),.mon_r_beat_count_o(),.mon_r_user_o(),.mon_r_id_o(),.mon_r_data_o(),.mon_r_addr_o(),.mon_r_valid_o(),.mon_w_last_o(),.mon_w_beat_count_o(),.mon_w_user_o(),.mon_w_id_o(),.mon_w_data_o(),.mon_w_addr_o(),.mon_w_valid_o());
 shared_l2_descriptor_port #(.ADDR_W(AW),.SRAM_BYTES(64'd1572864))port(.clk_i(clk),.rst_ni(rst_n),.descriptor_base_i(0),.descriptor_req_valid_i(dqv),.descriptor_req_ready_o(dqr),.descriptor_req_index_i(dqi),.descriptor_rsp_valid_o(dsv),.descriptor_rsp_ready_i(dsr),.descriptor_rsp_data_o(dsd),.descriptor_rsp_error_o(dse),.fabric_req_valid_o(fqv),.fabric_req_ready_i(fqr),.fabric_req_addr_o(fqa),.fabric_rsp_valid_i(frv),.fabric_rsp_ready_o(frr),.fabric_rsp_data_i(frd),.fabric_rsp_error_i(0));shared_l2_fabric #(.ADDR_W(AW),.ROWS_PER_BANK(6144))l2(.clk_i(clk),.rst_ni(rst_n),.rd_valid_i(mrv),.rd_ready_o(mrr),.rd_addr_i(mra),.rd_resp_valid_o(mrsv),.rd_resp_ready_i(mrsr),.rd_data_o(mrd),.wr_valid_i(mwv),.wr_ready_o(mwr),.wr_addr_i(mwa),.wr_data_i(mwd),.wr_be_i(mbe),.cycle_count_o(cy),.read_count_o(lreads),.write_count_o(lwrites),.bank_conflict_count_o(conflicts),.read_stall_count_o(rstalls),.write_stall_count_o(wstalls));
 always_comb begin mrv[0]=trv&&(lfsr[0]||lfsr[4]);mra[0+:AW]=tra;trr=mrr[0]&&(lfsr[0]||lfsr[4]);trsv=mrsv[0]&&(lfsr[1]||lfsr[6]);trd=mrd[0+:512];mrsr[0]=trsr&&(lfsr[1]||lfsr[6]);mrv[1]=fqv||brv;mra[AW+:AW]=fqv?fqa:bra;fqr=mrr[1]&&fqv;brr=mrr[1]&&!fqv&&brv;frv=mrsv[1]&&owner==0;frd=mrd[512+:512];brsv=mrsv[1]&&owner==1;brd=mrd[512+:512];mrsr[1]=owner==0?frr:brsr;mwv=host?hwv:(bwv?1:(twv&&(lfsr[2]||lfsr[7])));mwa=host?hwa:(bwv?bwa:twa);mwd=host?hwd:(bwv?bwd:twd);mbe=host?'1:(bwv?bbe:tbe);bwr=!host&&bwv&&mwr;twr=!host&&!bwv&&mwr&&(lfsr[2]||lfsr[7]);end
 always_ff@(posedge clk or negedge rst_n)if(!rst_n)begin owner<=0;lfsr<=32'h71a5c93d;desc<=0;flat_seen<=0;rbeats<=0;wbeats<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(mrv[1]&&mrr[1])owner<=fqv?0:1;if(dqv&&dqr)desc<=desc+1;if(iv&&ir)flat_seen<=flat_seen+1;if(iread_rsp.r_valid&&iread.r_ready)rbeats<=rbeats+1;if(iwrite.w_valid&&iwrite_rsp.w_ready)wbeats<=wbeats+1;end
 task automatic hwrite(input[AW-1:0]x,input[511:0]y);begin @(negedge clk);hwa=x;hwd=y;hwv=1;do@(posedge clk);while(!mwr);@(negedge clk);hwv=0;end endtask
 initial begin string bp,cp,ap,qrp,qbp,qep,krp,kbp,kep,vrp,vbp,vep;start=0;host=1;hwv=0;hwa=0;hwd=0;sumr=0;sumw=0;sumlr=0;sumlw=0;if(!$value$plusargs("BEATS=%s",bp)||!$value$plusargs("COMMANDS=%s",cp)||!$value$plusargs("ADDR=%s",ap)||!$value$plusargs("Q_RAW=%s",qrp)||!$value$plusargs("Q_BIAS=%s",qbp)||!$value$plusargs("Q_EXPECT=%s",qep)||!$value$plusargs("K_RAW=%s",krp)||!$value$plusargs("K_BIAS=%s",kbp)||!$value$plusargs("K_EXPECT=%s",kep)||!$value$plusargs("V_RAW=%s",vrp)||!$value$plusargs("V_BIAS=%s",vbp)||!$value$plusargs("V_EXPECT=%s",vep))$fatal(1,"args");$readmemh(bp,db);$readmemh(cp,cmd);$readmemh(ap,a);$readmemh(qrp,qr);$readmemh(qbp,qb);$readmemh(qep,qe);$readmemh(krp,kr);$readmemh(kbp,kb);$readmemh(kep,ke);$readmemh(vrp,vr);$readmemh(vbp,vb);$readmemh(vep,ve);
  for(integer i=0;i<48;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,a[0]}+i*64+b]=qr[i][b*8+:8];for(integer i=0;i<96;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,a[1]}+i*64+b]=qb[i][b*8+:8];for(integer i=0;i<8;i++)for(integer b=0;b<64;b++)begin ddr.mem[{8'd0,a[3]}+i*64+b]=kr[i][b*8+:8];ddr.mem[{8'd0,a[6]}+i*64+b]=vr[i][b*8+:8];end for(integer i=0;i<16;i++)for(integer b=0;b<64;b++)begin ddr.mem[{8'd0,a[4]}+i*64+b]=kb[i][b*8+:8];ddr.mem[{8'd0,a[7]}+i*64+b]=vb[i][b*8+:8];end
  repeat(8)@(posedge clk);rst_n=1;for(integer i=0;i<DBEATS;i++)hwrite(1024+i,db[i]);@(negedge clk);host=0;for(integer p=0;p<3;p++)begin current=cmd[p];start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(status)$fatal(1,"bias stage %0d",p);sumr+=dr;sumw+=dw;sumlr+=lr;sumlw+=lw;@(posedge clk);@(negedge clk);end
  for(integer i=0;i<48;i++)for(integer b=0;b<64;b++)if(ddr.mem[{8'd0,a[2]}+i*64+b]!==qe[i][b*8+:8])$fatal(1,"Q bias");for(integer i=0;i<8;i++)for(integer b=0;b<64;b++)begin if(ddr.mem[{8'd0,a[5]}+i*64+b]!==ke[i][b*8+:8])$fatal(1,"K bias");if(ddr.mem[{8'd0,a[8]}+i*64+b]!==ve[i][b*8+:8])$fatal(1,"V bias");end
  if(desc!=18||flat_seen!=70||flat!=70||rbeats!=256||wbeats!=256||sumr!=12288||sumw!=4096||sumlr!=192||sumlw!=64)$fatal(1,"counts desc=%0d flat=%0d beats=%0d/%0d bytes=%0d/%0d l2=%0d/%0d",desc,flat_seen,rbeats,wbeats,sumr,sumw,sumlr,sumlw);$display("QWEN2_BIAS_STAGE_VCS_PASS commands=3 descriptor_fetches=18 flat_idma=70 axi_beats=256 ddr_read_bytes=12288 ddr_write_bytes=4096 l2_read_beats=192 l2_write_beats=64 Q_values=1536 K_values=256 V_values=256 bf16_bit_exact=2048 bias_format=FP32 no_reference_inside_stage=1");$finish;end
 initial begin repeat(200000)@(posedge clk);$fatal(1,"timeout flat=%0d",flat_seen);end
endmodule
