`timescale 1ns/1ps
module tb_qwen2_projection_group8_trace64;
 integer runtime_batches,selected_batches;
 localparam integer RECORDS=6188,BASE=4096;logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[127:0]commands[0:2],records[0:RECORDS-1];logic dqv,dqr,dsv,dsr,done;logic[23:0]dqi;logic[127:0]dsd;logic[7:0]status;logic[31:0]steps,values,wloads,nloads,lfsr;logic[63:0]dr,dw;logic dpending;logic[127:0]dpending_data;integer projection,columns,tiles,groups,expected_steps,expected_values,expected_nloads,fetches;
 qwen2_projection_q1024_group8_controller dut(.batch_count_i(runtime_batches),.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_i(commands[projection]),.trace_only_i(1'b1),.descriptor_req_valid_o(dqv),.descriptor_req_ready_i(dqr),.descriptor_req_index_o(dqi),.descriptor_rsp_valid_i(dsv),.descriptor_rsp_ready_o(dsr),.descriptor_rsp_data_i(dsd),.descriptor_rsp_error_i(1'b0),.dma_req_valid_o(),.dma_req_ready_i(1'b0),.dma_req_kind_o(),.dma_src_addr_o(),.dma_dst_addr_o(),.dma_row_bytes_o(),.dma_rows_o(),.dma_src_stride_o(),.dma_dst_stride_o(),.dma_rsp_valid_i(1'b0),.dma_rsp_ready_o(),.dma_rsp_error_i(1'b0),.l2_rd_valid_o(),.l2_rd_ready_i(1'b0),.l2_rd_addr_o(),.l2_rsp_valid_i(1'b0),.l2_rsp_ready_o(),.l2_rsp_data_i('0),.l2_wr_valid_o(),.l2_wr_ready_i(1'b0),.l2_wr_addr_o(),.l2_wr_data_o(),.l2_wr_be_o(),.done_o(done),.status_o(status),.matrix_steps_o(steps),.values_o(values),.weight_tile_loads_o(wloads),.norm_batch_loads_o(nloads),.ddr_read_bytes_o(dr),.ddr_write_bytes_o(dw));
 assign dqr=!dpending&&(lfsr[0]||lfsr[4]);assign dsv=dpending;assign dsd=dpending_data;always@(posedge clk or negedge rst_n)if(!rst_n)begin lfsr<=32'h64081632;dpending<=0;fetches<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(dqv&&dqr)begin dpending<=1;dpending_data<=records[dqi-BASE];fetches<=fetches+1;end if(dsv&&dsr)dpending<=0;end
 initial begin string cp,rp;if(!$value$plusargs("COMMANDS=%s",cp)||!$value$plusargs("RECORDS=%s",rp)||!$value$plusargs("PROJECTION=%d",projection))$fatal(1,"plusargs");$readmemh(cp,commands);$readmemh(rp,records);if(!$value$plusargs("BATCHES=%d",runtime_batches))runtime_batches=64;selected_batches=runtime_batches;columns=projection==0?1536:256;tiles=columns/32;groups=(tiles+7)/8;expected_steps=tiles*selected_batches*1536;expected_values=selected_batches*16*columns;expected_nloads=groups*selected_batches;start=0;repeat(6)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;runtime_batches=0;wait(done);if(selected_batches==0||selected_batches>64)begin if(status!=5||fetches!=0||steps||values)$fatal(1,"bad runtime admission");$display("QWEN2_GROUP8_RUNTIME_REJECT_PASS batches=%0d",selected_batches);$finish;end if(status||fetches!=6||wloads!=tiles||nloads!=expected_nloads||steps!=expected_steps||values!=expected_values||dr!=64'(tiles)*98304+64'(expected_nloads)*49152||dw!=64'(expected_values)*2)$fatal(1,"aggregate p=%0d fetch=%0d w=%0d n=%0d steps=%0d values=%0d bytes=%0d/%0d",projection,fetches,wloads,nloads,steps,values,dr,dw);if(selected_batches==64)$display("QWEN2_PROJECTION_GROUP8_TRACE64_PASS projection=%0d batches=64 tiles=%0d groups=%0d weight_loads=%0d norm_loads=%0d matrix_steps=%0d values=%0d weight_refetch=0 trace_only=1",projection,tiles,groups,wloads,nloads,steps,values);else $display("QWEN2_GROUP8_RUNTIME_TRACE_PASS batches=%0d trace_only=1",selected_batches);$finish;end
 initial begin repeat(20000)@(posedge clk);$fatal(1,"timeout");end
endmodule
