`timescale 1ns/1ps
module tb_qwen2_kv_append_descriptor_v3_context;
 localparam integer RECORDS=6188,BASE=4096;logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[127:0]commands[0:0],records[0:RECORDS-1],command;logic qv,qr,sv,sr,se,cv,cr,cl;logic[23:0]qi,pending_index;logic[127:0]sd,pending_data;logic pending;logic[7:0]status;logic[63:0]ka,va,ta,da;logic[31:0]seq,ts,tc,gen,lp;logic[11:0]layer;logic[9:0]heads,dim;logic[23:0]limit;logic[5:0]idbits;logic[4:0]ptlog;logic[3:0]ptelog;logic[31:0]lfsr;integer fetches;
 qwen2_kv_append_descriptor_v3_context dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_i(command),.descriptor_req_valid_o(qv),.descriptor_req_ready_i(qr),.descriptor_req_index_o(qi),.descriptor_rsp_valid_i(sv),.descriptor_rsp_ready_o(sr),.descriptor_rsp_data_i(sd),.descriptor_rsp_error_i(se),.context_valid_o(cv),.context_ready_i(cr),.context_legal_o(cl),.context_status_o(status),.k_address_o(ka),.v_address_o(va),.table_address_o(ta),.data_address_o(da),.sequence_id_o(seq),.token_start_o(ts),.token_count_o(tc),.generation_o(gen),.logical_page_count_o(lp),.layer_id_o(layer),.kv_heads_o(heads),.head_dim_o(dim),.physical_page_limit_o(limit),.page_id_bits_o(idbits),.page_tokens_log2_o(ptlog),.pte_bytes_log2_o(ptelog));
 assign qr=!pending&&(lfsr[0]||lfsr[5]);assign sv=pending;assign sd=pending_data;assign se=0;assign cr=lfsr[1]||lfsr[7];
 always_ff@(posedge clk or negedge rst_n)begin if(!rst_n)begin pending<=0;pending_index<=0;pending_data<=0;lfsr<=32'h41c0ffee;fetches<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(qv&&qr)begin pending<=1;pending_index<=qi;pending_data<=records[qi-BASE];fetches<=fetches+1;end if(sv&&sr)pending<=0;end end
 task automatic launch(input[127:0]c);begin @(negedge clk);command=c;start=1;@(posedge clk);@(negedge clk);start=0;end endtask
 initial begin string cp,rp;start=0;command=0;if(!$value$plusargs("COMMAND=%s",cp)||!$value$plusargs("RECORDS=%s",rp))$fatal(1,"plusargs");$readmemh(cp,commands);$readmemh(rp,records);repeat(5)@(posedge clk);rst_n=1;launch(commands[0]);wait(cv);if(!cl||status!=0||ka!=64'h0000000201000000||va!=64'h0000000201100000||ta!=64'h0000000500000000||da!=64'h0000000500008000||seq!=0||layer!=0||ts!=0||tc!=1024||gen!=0||lp!=64||heads!=2||dim!=128||limit!=4096||idbits!=32||ptlog!=4||ptelog!=4||fetches!=13)$fatal(1,"valid status=%0d fetch=%0d ka=%h va=%h ta=%h da=%h heads=%0d dim=%0d",status,fetches,ka,va,ta,da,heads,dim);wait(!cv);launch(commands[0]^{117'd0,3'd1,8'd0});wait(cv);if(cl||status!=2||fetches!=13)$fatal(1,"illegal command");wait(!cv);records[5927-BASE][127]=1;launch(commands[0]);wait(cv);if(cl||status!=4||fetches!=26)$fatal(1,"table flags status=%0d fetch=%0d",status,fetches);$display("QWEN2_KV_APPEND_DESCRIPTOR_V3_CONTEXT_PASS valid_fetches=13 malformed_preissue=1 table_flag_reject=1 table_base=0000000500000000 data_base=0000000500008000 tokens=1024 pages=64 page_bytes=16384 random_backpressure=1");$finish;end
 initial begin repeat(2000)@(posedge clk);$fatal(1,"timeout fetches=%0d",fetches);end
endmodule
