`timescale 1ns/1ps
module tb_qwen2_idma_descriptor_compute_top #(parameter integer FULL_Q=0,parameter integer OVERLAP=0);
 import hetero_idma_512_pkg::*;localparam integer AW=15,DBEATS=1547;logic clk=0,rst_n=0,start,done;logic[5:0]tile;always #0.5 clk=~clk;
 logic[127:0]cmd[0:1];logic dqv,dqr,dsv,dsr,dse;logic[23:0]dqi;logic[127:0]dsd;logic fqv,fqr,frv,frr;logic[AW-1:0]fqa;logic[511:0]frd;
 logic av,ar;logic[1:0]ak;logic[63:0]asrc,adst;logic[31:0]arb,arows,ass,ads;logic asv,asr,ase;
 logic iv,ir,ior,iordy,ioe,local_source;logic[63:0]isrc,idst;logic[31:0]ilen,flat;logic[7:0]ibusy;
 axi_req_t iread,iwrite,local_req,ddr_req;axi_rsp_t iread_rsp,iwrite_rsp,local_rsp,ddr_rsp;
 logic brv,brr,brsv,brsr,bwv,bwr,bbusy;logic[AW-1:0]bra,bwa;logic[511:0]brd,bwd;logic[63:0]bbe;
 logic trv,trr,trsv,trsr,twv,twr;logic[AW-1:0]tra,twa;logic[511:0]trd,twd;logic[63:0]tbe;logic[7:0]status;logic[63:0]ddrr,ddrw;logic[31:0]tl2r,tl2w;
 logic[1:0]mrv,mrr,mrsv,mrsr;logic[2*AW-1:0]mra;logic[1023:0]mrd;logic mwv,mwr;logic[AW-1:0]mwa;logic[511:0]mwd;logic[63:0]mbe;logic[63:0]cy,lreads,lwrites,conflicts,rstalls,wstalls;
 logic host_write,hwv,hrv,hrr,hrsv,hrsr;logic[AW-1:0]hwa,hra;logic[511:0]hwd,hrd;logic[1:0]owner1_q;logic[31:0]lfsr;
 logic[511:0]db[0:DBEATS-1],hidden[0:47],nw[0:95],qw[0:1535],qwall[0:73727],enorm[0:47],eq[0:0],eqall[0:47];logic[55:0]eaddr[0:5];integer flat_seen,rbeats,wbeats,descriptor_fetches,iterations,cycles,start_cycle,device_cycles;logic[63:0]sum_ddrr,sum_ddrw,sum_l2r,sum_l2w;logic[31:0]overlap_cycles;
 generate if(FULL_Q&&OVERLAP)begin:g_overlap
  qwen2_full_q_pingpong_top #(.ADDR_W(AW))top(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.rms_command_i(cmd[0]),.matrix_command_i(cmd[1]),.descriptor_req_valid_o(dqv),.descriptor_req_ready_i(dqr),.descriptor_req_index_o(dqi),.descriptor_rsp_valid_i(dsv),.descriptor_rsp_ready_o(dsr),.descriptor_rsp_data_i(dsd),.descriptor_rsp_error_i(dse),.dma_req_valid_o(av),.dma_req_ready_i(ar),.dma_req_kind_o(ak),.dma_src_addr_o(asrc),.dma_dst_addr_o(adst),.dma_row_bytes_o(arb),.dma_rows_o(arows),.dma_src_stride_o(ass),.dma_dst_stride_o(ads),.dma_rsp_valid_i(asv),.dma_rsp_ready_o(asr),.dma_rsp_error_i(ase),.l2_rd_valid_o(trv),.l2_rd_ready_i(trr),.l2_rd_addr_o(tra),.l2_rsp_valid_i(trsv),.l2_rsp_ready_o(trsr),.l2_rsp_data_i(trd),.l2_wr_valid_o(twv),.l2_wr_ready_i(twr),.l2_wr_addr_o(twa),.l2_wr_data_o(twd),.l2_wr_be_o(tbe),.done_o(done),.status_o(status),.ddr_read_bytes_o(ddrr),.ddr_write_bytes_o(ddrw),.l2_read_beats_o(tl2r),.l2_write_beats_o(tl2w),.overlap_cycles_o(overlap_cycles));
 end else begin:g_serial
  qwen2_descriptor_shared_l2_tile_top #(.ADDR_W(AW))top(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.rms_command_i(cmd[0]),.matrix_command_i(cmd[1]),.q_column_tile_i(tile),.full_q_i(FULL_Q!=0),.descriptor_req_valid_o(dqv),.descriptor_req_ready_i(dqr),.descriptor_req_index_o(dqi),.descriptor_rsp_valid_i(dsv),.descriptor_rsp_ready_o(dsr),.descriptor_rsp_data_i(dsd),.descriptor_rsp_error_i(dse),.dma_req_valid_o(av),.dma_req_ready_i(ar),.dma_req_kind_o(ak),.dma_src_addr_o(asrc),.dma_dst_addr_o(adst),.dma_row_bytes_o(arb),.dma_rows_o(arows),.dma_src_stride_o(ass),.dma_dst_stride_o(ads),.dma_rsp_valid_i(asv),.dma_rsp_ready_o(asr),.dma_rsp_error_i(ase),.l2_rd_valid_o(trv),.l2_rd_ready_i(trr),.l2_rd_addr_o(tra),.l2_rsp_valid_i(trsv),.l2_rsp_ready_o(trsr),.l2_rsp_data_i(trd),.l2_wr_valid_o(twv),.l2_wr_ready_i(twr),.l2_wr_addr_o(twa),.l2_wr_data_o(twd),.l2_wr_be_o(tbe),.done_o(done),.status_o(status),.ddr_read_bytes_o(ddrr),.ddr_write_bytes_o(ddrw),.l2_read_beats_o(tl2r),.l2_write_beats_o(tl2w));
  assign overlap_cycles=0;
 end endgenerate
 qwen2_tile_idma_expand expand(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(av),.req_ready_o(ar),.req_kind_i(ak),.src_addr_i(asrc),.dst_addr_i(adst),.row_bytes_i(arb),.rows_i(arows),.src_stride_i(ass),.dst_stride_i(ads),.rsp_valid_o(asv),.rsp_ready_i(asr),.rsp_error_o(ase),.idma_req_valid_o(iv),.idma_req_ready_i(ir),.idma_src_addr_o(isrc),.idma_dst_addr_o(idst),.idma_length_o(ilen),.idma_rsp_valid_i(ior),.idma_rsp_ready_o(iordy),.idma_rsp_error_i(ioe),.flat_requests_o(flat),.local_source_o(local_source));
 idma_backend_rw_axi_flat_wrap idma(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(iv),.req_ready_o(ir),.src_addr_i(isrc),.dst_addr_i(idst),.length_i(ilen),.rsp_valid_o(ior),.rsp_ready_i(iordy),.rsp_error_o(ioe),.axi_read_req_o(iread),.axi_read_rsp_i(iread_rsp),.axi_write_req_o(iwrite),.axi_write_rsp_i(iwrite_rsp),.busy_o(ibusy));
 always_comb begin local_req='0;ddr_req='0;iread_rsp='0;iwrite_rsp='0;if(local_source)begin local_req=iread;ddr_req=iwrite;iread_rsp=local_rsp;iwrite_rsp=ddr_rsp;end else begin ddr_req=iread;local_req=iwrite;iread_rsp=ddr_rsp;iwrite_rsp=local_rsp;end end
 qwen2_axi_shared_l2_bridge #(.ADDR_W(AW))bridge(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(local_req),.axi_rsp_o(local_rsp),.l2_rd_valid_o(brv),.l2_rd_ready_i(brr),.l2_rd_addr_o(bra),.l2_rsp_valid_i(brsv),.l2_rsp_ready_o(brsr),.l2_rsp_data_i(brd),.l2_wr_valid_o(bwv),.l2_wr_ready_i(bwr),.l2_wr_addr_o(bwa),.l2_wr_data_o(bwd),.l2_wr_be_o(bbe),.busy_o(bbusy));
 axi_sim_mem#(.AddrWidth(64),.DataWidth(512),.IdWidth(4),.UserWidth(1),.axi_req_t(axi_req_t),.axi_rsp_t(axi_rsp_t),.WarnUninitialized(1'b0),.ClearErrOnAccess(1'b1),.ApplDelay(0ns),.AcqDelay(0ns))ddr(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(ddr_req),.axi_rsp_o(ddr_rsp),.mon_r_last_o(),.mon_r_beat_count_o(),.mon_r_user_o(),.mon_r_id_o(),.mon_r_data_o(),.mon_r_addr_o(),.mon_r_valid_o(),.mon_w_last_o(),.mon_w_beat_count_o(),.mon_w_user_o(),.mon_w_id_o(),.mon_w_data_o(),.mon_w_addr_o(),.mon_w_valid_o());
 shared_l2_descriptor_port #(.ADDR_W(AW),.SRAM_BYTES(64'd1572864))port(.clk_i(clk),.rst_ni(rst_n),.descriptor_base_i(0),.descriptor_req_valid_i(dqv),.descriptor_req_ready_o(dqr),.descriptor_req_index_i(dqi),.descriptor_rsp_valid_o(dsv),.descriptor_rsp_ready_i(dsr),.descriptor_rsp_data_o(dsd),.descriptor_rsp_error_o(dse),.fabric_req_valid_o(fqv),.fabric_req_ready_i(fqr),.fabric_req_addr_o(fqa),.fabric_rsp_valid_i(frv),.fabric_rsp_ready_o(frr),.fabric_rsp_data_i(frd),.fabric_rsp_error_i(1'b0));
 shared_l2_fabric #(.ADDR_W(AW),.ROWS_PER_BANK(6144))l2(.clk_i(clk),.rst_ni(rst_n),.rd_valid_i(mrv),.rd_ready_o(mrr),.rd_addr_i(mra),.rd_resp_valid_o(mrsv),.rd_resp_ready_i(mrsr),.rd_data_o(mrd),.wr_valid_i(mwv),.wr_ready_o(mwr),.wr_addr_i(mwa),.wr_data_i(mwd),.wr_be_i(mbe),.cycle_count_o(cy),.read_count_o(lreads),.write_count_o(lwrites),.bank_conflict_count_o(conflicts),.read_stall_count_o(rstalls),.write_stall_count_o(wstalls));
 always_comb begin
  mrv[0]=trv&&(lfsr[0]||lfsr[4]);mra[0+:AW]=tra;trr=mrr[0]&&(lfsr[0]||lfsr[4]);trsv=mrsv[0]&&(lfsr[1]||lfsr[6]);trd=mrd[0+:512];mrsr[0]=trsr&&(lfsr[1]||lfsr[6]);
  mrv[1]=hrv||fqv||brv;mra[AW+:AW]=hrv?hra:(fqv?fqa:bra);hrr=mrr[1]&&hrv;fqr=mrr[1]&&!hrv&&fqv;brr=mrr[1]&&!hrv&&!fqv&&brv;
  hrsv=mrsv[1]&&owner1_q==2;hrd=mrd[512+:512];frv=mrsv[1]&&owner1_q==0;frd=mrd[512+:512];brsv=mrsv[1]&&owner1_q==1;brd=mrd[512+:512];
  case(owner1_q)0:mrsr[1]=frr;1:mrsr[1]=brsr;default:mrsr[1]=hrsr;endcase
  mwv=host_write?hwv:(bwv?1'b1:(twv&&(lfsr[2]||lfsr[7])));mwa=host_write?hwa:(bwv?bwa:twa);mwd=host_write?hwd:(bwv?bwd:twd);mbe=host_write?'1:(bwv?bbe:tbe);bwr=!host_write&&bwv&&mwr;twr=!host_write&&!bwv&&mwr&&(lfsr[2]||lfsr[7]);
 end
 always_ff@(posedge clk or negedge rst_n)begin if(!rst_n)begin owner1_q<=0;lfsr<=32'h7ac319d5;flat_seen<=0;rbeats<=0;wbeats<=0;descriptor_fetches<=0;cycles<=0;end else begin cycles<=cycles+1;lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(mrv[1]&&mrr[1])owner1_q<=hrv?2:(fqv?0:1);if(dqv&&dqr)descriptor_fetches<=descriptor_fetches+1;if(iv&&ir)flat_seen<=flat_seen+1;if(iread_rsp.r_valid&&iread.r_ready)rbeats<=rbeats+1;if(iwrite.w_valid&&iwrite_rsp.w_ready)wbeats<=wbeats+1;end end
 task automatic hwrite(input[AW-1:0]ad,input[511:0]data);begin @(negedge clk);hwa=ad;hwd=data;hwv=1;do@(posedge clk);while(!mwr);@(negedge clk);hwv=0;end endtask
 task automatic hread(input[AW-1:0]ad,input[511:0]exp);begin @(negedge clk);hrv=1;hra=ad;hrsr=0;do@(posedge clk);while(!hrr);@(negedge clk);hrv=0;wait(hrsv);if(hrd!==exp)$fatal(1,"norm readback %0d",ad);@(negedge clk);hrsr=1;@(posedge clk);@(negedge clk);hrsr=0;end endtask
 initial begin string ap,hp,np,qp,ep,bp,cp,op,qap,qoap;start=0;tile=0;host_write=1;hwv=0;hrv=0;hrsr=0;hwa=0;hra=0;hwd=0;sum_ddrr=0;sum_ddrw=0;sum_l2r=0;sum_l2w=0;
  if(!$value$plusargs("ADDR_MEM=%s",ap)||!$value$plusargs("HIDDEN=%s",hp)||!$value$plusargs("NORM_WEIGHT=%s",np)||!$value$plusargs("Q_WEIGHT=%s",qp)||!$value$plusargs("EXPECTED=%s",ep)||!$value$plusargs("DESCRIPTOR_BEATS=%s",bp)||!$value$plusargs("COMMANDS=%s",cp)||!$value$plusargs("Q_OUT=%s",op))$fatal(1,"plusargs");$readmemh(ap,eaddr);$readmemh(hp,hidden);$readmemh(np,nw);$readmemh(ep,enorm);$readmemh(bp,db);$readmemh(cp,cmd);$readmemh(op,eq);
  if(FULL_Q)begin if(!$value$plusargs("Q_WEIGHT_ALL=%s",qap)||!$value$plusargs("Q_OUT_ALL=%s",qoap))$fatal(1,"full Q plusargs");$readmemh(qap,qwall);$readmemh(qoap,eqall);end else $readmemh(qp,qw);
  for(integer i=0;i<48;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,eaddr[0]}+i*64+b]=hidden[i][b*8+:8];for(integer i=0;i<96;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,eaddr[1]}+i*64+b]=nw[i][b*8+:8];
  if(FULL_Q)for(integer t=0;t<48;t++)for(integer i=0;i<1536;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,eaddr[4]}+i*3072+t*64+b]=qwall[t*1536+i][b*8+:8];else for(integer i=0;i<1536;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,eaddr[4]}+i*3072+b]=qw[i][b*8+:8];
  repeat(8)@(posedge clk);rst_n=1;for(integer i=0;i<DBEATS;i++)hwrite(1024+i,db[i]);@(negedge clk);host_write=0;tile=0;start_cycle=cycles;start=1;@(posedge clk);@(negedge clk);start=0;wait(done);device_cycles=cycles-start_cycle;
  if(FULL_Q)begin
    if(status||flat_seen!=73778||flat!=73778||rbeats!=73920||wbeats!=73920||descriptor_fetches!=12||ddrr!=4727808||ddrw!=3072||tl2r!=73872||tl2w!=96)$fatal(1,"full Q counts status=%0d flat=%0d/%0d beats=%0d/%0d desc=%0d ddr=%0d/%0d l2=%0d/%0d",status,flat_seen,flat,rbeats,wbeats,descriptor_fetches,ddrr,ddrw,tl2r,tl2w);
  end else if(status||flat_seen!=1539||flat!=1539||rbeats!=1681||wbeats!=1681||descriptor_fetches!=12||ddrr!=107520||ddrw!=64||tl2r!=1680||tl2w!=49)$fatal(1,"single counts");
  for(integer i=0;i<48;i++)hread(4288+i,enorm[i]);if(FULL_Q)begin for(integer t=0;t<48;t++)for(integer b=0;b<64;b++)if(ddr.mem[{8'd0,eaddr[5]}+t*64+b]!==eqall[t][b*8+:8])$fatal(1,"full Q tile=%0d byte=%0d",t,b);if(OVERLAP)$display("QWEN2_FULL_Q_TOKEN_PINGPONG_PASS physical_columns=1536 column_tiles=48 descriptor_fetches=12 abstract_dma=98 flat_idma=73778 axi_beats=73920 ddr_read_bytes=4727808 ddr_write_bytes=3072 l2_read_beats=73872 l2_write_beats=96 rms_executions=1 matrix_completion=1 bf16_bit_exact=3072 pingpong_buffers=2 device_cycles=%0d overlap_cycles=%0d",device_cycles,overlap_cycles);else $display("QWEN2_FULL_Q_TOKEN_SINGLE_COMMAND_PASS physical_columns=1536 column_tiles=48 descriptor_fetches=12 abstract_dma=98 flat_idma=73778 axi_beats=73920 ddr_read_bytes=4727808 ddr_write_bytes=3072 l2_read_beats=73872 l2_write_beats=96 rms_executions=1 matrix_completion=1 bf16_bit_exact=3072 pingpong_buffers=2 device_cycles=%0d overlap_cycles=0",device_cycles);end else begin for(integer b=0;b<64;b++)if(ddr.mem[{8'd0,eaddr[5]}+b]!==eq[0][b*8+:8])$fatal(1,"DDR output %0d",b);$display("QWEN2_IDMA_DESCRIPTOR_COMPUTE_TOP_PASS commands=2 descriptor_fetches=12 abstract_dma=4 flat_idma=1539 axi_beats=1681 ddr_read_bytes=107520 ddr_write_bytes=64 l2_read_beats=1680 l2_write_beats=49 rms_values=1536 matrix_steps=1536 matrix_outputs=32 bf16_bit_exact=1568 byte_exact_dma=1 engine_completions=2");end $finish;end
 generate if(OVERLAP)begin:g_overlap_timeout
  initial begin repeat(4000000)@(posedge clk);$fatal(1,"timeout status=%0d flat=%0d tile=%0d owner=%0d pstate=%0d/%0d load=%b done=%b rearm=%b dma=%0d/%0d payload=%0d pldstate=%0d k=%0d seen=%0d mactive=%0d maccept=%0d mcomplete=%0d final=%0d",status,flat_seen,g_overlap.top.tile_q,g_overlap.top.owner_q,g_overlap.top.g_plan[0].plan.state_q,g_overlap.top.g_plan[1].plan.state_q,g_overlap.top.pload,g_overlap.top.pdone,g_overlap.top.prearm_q,g_overlap.top.dma_active_q,g_overlap.top.dma_owner_q,g_overlap.top.payload_active_q,g_overlap.top.payload.state_q,g_overlap.top.payload.k_q,g_overlap.top.payload.final_seen_q,g_overlap.top.matrix.active_q,g_overlap.top.matrix.maccept,g_overlap.top.matrix.mcomplete,g_overlap.top.final_pending_q);end
 end else begin:g_serial_timeout
  initial begin repeat(4000000)@(posedge clk);$fatal(1,"timeout status=%0d flat=%0d",status,flat_seen);end
 end endgenerate
endmodule
