`timescale 1ns/1ps
module tb_qwen2_rms_matrix_tile16_chain;
 logic clk=0,rst_n=0,rs,rdone,ms,mdone,phase;always #0.5 clk=~clk;logic rrv,rrr,rrsv,rrsr,rwv,rwr,mrv,mrr,mrsv,mrsr,mwv,mwr;logic[14:0]rra,rwa,mra,mwa,ra,wa;logic[511:0]rrd,rwd,mrd,mwd,data;logic[63:0]rbe,mbe,be;logic rv,ready,rsv,rsr,wv,wr;logic[31:0]rreads,rwrites,rvectors,rvalues,mreads,mwrites,msteps,lfsr;logic[4:0]rflags;logic pending;logic[511:0]pending_data,wdata,mem[0:8191],hidden[0:767],rweight[0:95],qweight[0:1535],expected[0:15];logic mpv,mpr,mc,ml,mov,mor,mol,mcv,merr;logic[2:0]mctx,moctx;logic[255:0]ma;logic[511:0]mb;logic[16383:0]macc;logic[55:0]mcd;logic[127:0]command;integer completions;
 qwen2_shared_l2_rms_tile16_stager rms(.clk_i(clk),.rst_ni(rst_n),.start_i(rs),.hidden_local_i(0),.weight_local_i(64'h10000),.norm_token_local_i(64'h20000),.norm_kmajor_local_i(64'h40000),.l2_rd_valid_o(rrv),.l2_rd_ready_i(rrr),.l2_rd_addr_o(rra),.l2_rsp_valid_i(rrsv),.l2_rsp_ready_o(rrsr),.l2_rsp_data_i(rrd),.l2_wr_valid_o(rwv),.l2_wr_ready_i(rwr),.l2_wr_addr_o(rwa),.l2_wr_data_o(rwd),.l2_wr_be_o(rbe),.done_o(rdone),.read_beats_o(rreads),.write_beats_o(rwrites),.rms_vectors_o(rvectors),.transpose_values_o(rvalues),.exception_flags_o(rflags));
 qwen2_shared_l2_matrix_tile16_payload matrix_payload(.depth_i(16'd1536),.rows_i(16'd16),.columns_i(16'd32),.status_o(),.clk_i(clk),.rst_ni(rst_n),.start_i(ms),.activation_local_i(64'h40000),.weight_local_i(64'h60000),.output_local_i(64'h78000),.l2_rd_valid_o(mrv),.l2_rd_ready_i(mrr),.l2_rd_addr_o(mra),.l2_rsp_valid_i(mrsv),.l2_rsp_ready_o(mrsr),.l2_rsp_data_i(mrd),.l2_wr_valid_o(mwv),.l2_wr_ready_i(mwr),.l2_wr_addr_o(mwa),.l2_wr_data_o(mwd),.l2_wr_be_o(mbe),.matrix_step_valid_o(mpv),.matrix_step_ready_i(mpr),.matrix_context_o(mctx),.matrix_clear_o(mc),.matrix_last_o(ml),.matrix_a_o(ma),.matrix_b_o(mb),.matrix_out_valid_i(mov),.matrix_out_ready_o(mor),.matrix_out_last_i(mol),.matrix_acc_i(macc),.done_o(mdone),.read_beats_o(mreads),.write_beats_o(mwrites),.matrix_steps_o(msteps));
 qwen2_matrix_command_endpoint matrix(.clk_i(clk),.rst_ni(rst_n),.cmd_valid_i(ms),.cmd_ready_o(),.cmd_i(command),.step_valid_i(mpv),.step_ready_o(mpr),.step_context_i(mctx),.step_clear_i(mc),.step_last_i(ml),.command_last_tile_i(1'b1),.step_a_i(ma),.step_b_i(mb),.out_valid_o(mov),.out_ready_i(mor),.out_context_o(moctx),.out_last_o(mol),.out_acc_o(macc),.completion_valid_o(mcv),.completion_ready_i(1'b1),.completion_data_o(mcd),.protocol_error_o(merr));
 assign rv=phase?mrv:rrv;assign ra=phase?mra:rra;assign mrr=phase?ready:0;assign rrr=phase?0:ready;assign mrsv=phase?rsv:0;assign rrsv=phase?0:rsv;assign mrd=pending_data;assign rrd=pending_data;assign rsr=phase?mrsr:rrsr;assign wv=phase?mwv:rwv;assign wa=phase?mwa:rwa;assign wdata=phase?mwd:rwd;assign be=phase?mbe:rbe;assign mwr=phase?wr:0;assign rwr=phase?0:wr;
 assign ready=!pending&&(lfsr[0]||lfsr[4]);assign rsv=pending;assign wr=lfsr[1]||lfsr[7];always@(posedge clk or negedge rst_n)if(!rst_n)begin lfsr<=32'h16c0ffee;pending<=0;pending_data<=0;completions<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(rv&&ready)begin pending<=1;pending_data<=mem[ra];end if(rsv&&rsr)pending<=0;if(wv&&wr)mem[wa]<=wdata;if(mcv)completions<=completions+1;end
 initial begin rs=0;ms=0;phase=0;command=128'h00100800100700100600020001000220;$readmemh("work/results/qwen2_canonical_tile16_vectors/hidden_token_major.memh",hidden);$readmemh("work/results/qwen2_canonical_tile16_vectors/rms_weight_fp32.memh",rweight);$readmemh("work/results/qwen2_canonical_tile16_vectors/q_weight_tile0.memh",qweight);$readmemh("work/results/qwen2_canonical_tile16_vectors/expected_rows.memh",expected);for(integer i=0;i<768;i++)mem[i]=hidden[i];for(integer i=0;i<96;i++)mem[1024+i]=rweight[i];for(integer i=0;i<1536;i++)mem[6144+i]=qweight[i];repeat(8)@(posedge clk);rst_n=1;@(negedge clk);rs=1;@(posedge clk);@(negedge clk);rs=0;wait(rdone);@(posedge clk);@(negedge clk);phase=1;ms=1;@(posedge clk);@(negedge clk);ms=0;wait(mdone);if(rreads!=25440||rwrites!=2304||rvectors!=16||rvalues!=24576||mreads!=3072||mwrites!=16||msteps!=1536||completions!=1||rflags[4:1]||merr)$fatal(1,"aggregate");for(integer r=0;r<16;r++)if(mem[7680+r]!==expected[r])$fatal(1,"row=%0d",r);$display("QWEN2_RMS_MATRIX_TILE16_CHAIN_PASS rows=16 rms_values=24576 matrix_values=512 matrix_steps=1536 effective_macs=786432 bf16_bit_exact=25088 completion=1 activation_reference_injection=0 random_backpressure=1");$finish;end
 initial begin repeat(250000)@(posedge clk);$fatal(1,"timeout phase=%0d",phase);end
endmodule
