`timescale 1ns/1ps
module tb_qwen2_kv_append_pinned_idma_vcs;
 import hetero_idma_512_pkg::*;localparam integer RECORDS=6188,BASE=4096;logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[127:0]commands[0:0],records[0:RECORDS-1];logic qv,qr,sv,sr;logic[23:0]qi;logic[127:0]sd;logic pv,pr,pl,pvalid,iv,ir,ior,iordy,ioe,done;logic[9:0]pi;logic[31:0]pp,pg,pc,pu,reqs;logic[63:0]is,id,bytes,ta,da;logic[31:0]il;logic[7:0]status,ibusy;axi_req_t read_req,write_req,joined_req;axi_rsp_t read_rsp,write_rsp,joined_rsp;logic[31:0]lfsr;logic dpending;logic[127:0]dpending_data;integer fetches,ptes,idmas,rbeats,wbeats;
 qwen2_kv_append_ddr_stage_top stage(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_i(commands[0]),.descriptor_req_valid_o(qv),.descriptor_req_ready_i(qr),.descriptor_req_index_o(qi),.descriptor_rsp_valid_i(sv),.descriptor_rsp_ready_o(sr),.descriptor_rsp_data_i(sd),.descriptor_rsp_error_i(1'b0),.pte_valid_o(pv),.pte_ready_i(pr),.pte_level_o(pl),.pte_index_o(pi),.pte_physical_page_o(pp),.pte_generation_o(pg),.pte_refcount_o(pc),.pte_entry_valid_o(pvalid),.idma_req_valid_o(iv),.idma_req_ready_i(ir),.idma_src_addr_o(is),.idma_dst_addr_o(id),.idma_length_o(il),.idma_rsp_valid_i(ior),.idma_rsp_ready_o(iordy),.idma_rsp_error_i(ioe),.done_o(done),.status_o(status),.pte_updates_o(pu),.idma_requests_o(reqs),.payload_bytes_o(bytes),.table_address_o(ta),.data_address_o(da));
 idma_backend_rw_axi_flat_wrap idma(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(iv),.req_ready_o(ir),.src_addr_i(is),.dst_addr_i(id),.length_i(il),.rsp_valid_o(ior),.rsp_ready_i(iordy),.rsp_error_o(ioe),.axi_read_req_o(read_req),.axi_read_rsp_i(read_rsp),.axi_write_req_o(write_req),.axi_write_rsp_i(write_rsp),.busy_o(ibusy));
 axi_rw_join#(.axi_req_t(axi_req_t),.axi_resp_t(axi_rsp_t))i_join(.clk_i(clk),.rst_ni(rst_n),.slv_read_req_i(read_req),.slv_read_resp_o(read_rsp),.slv_write_req_i(write_req),.slv_write_resp_o(write_rsp),.mst_req_o(joined_req),.mst_resp_i(joined_rsp));
 axi_sim_mem#(.AddrWidth(64),.DataWidth(512),.IdWidth(4),.UserWidth(1),.axi_req_t(axi_req_t),.axi_rsp_t(axi_rsp_t),.WarnUninitialized(1'b0),.ClearErrOnAccess(1'b1),.ApplDelay(0ns),.AcqDelay(0ns))mem(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(joined_req),.axi_rsp_o(joined_rsp),.mon_r_last_o(),.mon_r_beat_count_o(),.mon_r_user_o(),.mon_r_id_o(),.mon_r_data_o(),.mon_r_addr_o(),.mon_r_valid_o(),.mon_w_last_o(),.mon_w_beat_count_o(),.mon_w_user_o(),.mon_w_id_o(),.mon_w_data_o(),.mon_w_addr_o(),.mon_w_valid_o());
 assign qr=!dpending&&(lfsr[0]||lfsr[5]);assign sv=dpending;assign sd=dpending_data;assign pr=lfsr[1]||lfsr[7];
 function automatic[7:0]kp(input integer i);kp=8'((i^(i>>8)^32'h5a)&255);endfunction function automatic[7:0]vp(input integer i);vp=8'((i^(i>>7)^32'ha5)&255);endfunction
 always_ff@(posedge clk or negedge rst_n)begin if(!rst_n)begin lfsr<=32'h1d4a600d;dpending<=0;dpending_data<=0;fetches<=0;ptes<=0;idmas<=0;rbeats<=0;wbeats<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(qv&&qr)begin dpending<=1;dpending_data<=records[qi-BASE];fetches<=fetches+1;end if(sv&&sr)dpending<=0;if(pv&&pr)ptes<=ptes+1;if(iv&&ir)idmas<=idmas+1;if(joined_rsp.r_valid&&joined_req.r_ready)rbeats<=rbeats+1;if(joined_req.w_valid&&joined_rsp.w_ready)wbeats<=wbeats+1;end end
 initial begin string cp,rp;start=0;if(!$value$plusargs("COMMAND=%s",cp)||!$value$plusargs("RECORDS=%s",rp))$fatal(1,"plusargs");$readmemh(cp,commands);$readmemh(rp,records);for(integer i=0;i<524288;i++)begin mem.mem[{8'd0,64'h201000000}+i]=kp(i);mem.mem[{8'd0,64'h201100000}+i]=vp(i);end repeat(8)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(status||fetches!=13||ptes!=65||idmas!=128||pu!=65||reqs!=128||bytes!=1048576||rbeats!=16384||wbeats!=16384||ibusy!=0)$fatal(1,"aggregate status=%0d fetch=%0d pte=%0d idma=%0d beats=%0d/%0d busy=%h",status,fetches,ptes,idmas,rbeats,wbeats,ibusy);for(integer p=0;p<64;p++)for(integer i=0;i<8192;i++)begin if(mem.mem[{8'd0,64'h500008000}+p*16384+i]!==kp(p*8192+i))$fatal(1,"K page=%0d byte=%0d",p,i);if(mem.mem[{8'd0,64'h500008000}+p*16384+8192+i]!==vp(p*8192+i))$fatal(1,"V page=%0d byte=%0d",p,i);end $display("QWEN2_KV_APPEND_PINNED_IDMA_VCS_PASS commands=1 descriptor_fetches=13 pte_updates=65 idma_requests=128 axi_read_beats=16384 axi_write_beats=16384 payload_bytes=1048576 byte_exact=1048576 pages=64 upstream_clean=1 source_injection=synthetic_preload");$finish;end
 initial begin repeat(200000)@(posedge clk);$fatal(1,"timeout fetch=%0d idma=%0d beats=%0d/%0d",fetches,idmas,rbeats,wbeats);end
endmodule
