`timescale 1ns/1ps
module tb_qwen2_first9_tile16_controller;
 localparam integer RECORDS=6188,BASE=4096;logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[127:0]rmscmd[0:1],pcmd[0:2],bcmd[0:2],ocmd[0:1],records[0:RECORDS-1];logic dqv,dqr,dsv,dsr,av,ar,asv,asr,rv,rr,rsv,rsr,wv,wr,done;logic[23:0]dqi;logic[127:0]dsd;logic[1:0]ak;logic[63:0]as,ad;logic[31:0]ab,an,ass,ads;logic[14:0]ra,wa;logic[511:0]rd,wd;logic[63:0]be;logic[7:0]status;logic[3:0]op;logic[31:0]completions,msteps,rsteps,values,lfsr;logic[63:0]dr,dw;logic dpending,apending,lpending;logic[127:0]dpending_data;logic[511:0]lpending_data,l2[0:24575],hidden[0:767],rweight[0:95],qweights[0:73727],kweights[0:12287],vweights[0:12287],qbias[0:95],kbias[0:15],vbias[0:15],positions[0:0],qexp[0:767],kexp[0:127],vexp[0:127],qbexp[0:767],kbexp[0:127],vbexp[0:127],qrexp[0:767],krexp[0:127],qraw[0:767],kraw[0:127],vraw[0:127],qbout[0:767],kbout[0:127],vbout[0:127],qrout[0:767],krout[0:127];integer fetches,dmas,delay,qload,kload,vload,qstore,kstore,vstore;
 qwen2_first9_tile16_controller dut(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.rms_command_i(rmscmd[0]),.q_command_i(pcmd[0]),.q_bias_command_i(bcmd[0]),.q_rope_command_i(ocmd[0]),.k_command_i(pcmd[1]),.k_bias_command_i(bcmd[1]),.k_rope_command_i(ocmd[1]),.v_command_i(pcmd[2]),.v_bias_command_i(bcmd[2]),.descriptor_req_valid_o(dqv),.descriptor_req_ready_i(dqr),.descriptor_req_index_o(dqi),.descriptor_rsp_valid_i(dsv),.descriptor_rsp_ready_o(dsr),.descriptor_rsp_data_i(dsd),.descriptor_rsp_error_i(1'b0),.dma_req_valid_o(av),.dma_req_ready_i(ar),.dma_req_kind_o(ak),.dma_src_addr_o(as),.dma_dst_addr_o(ad),.dma_row_bytes_o(ab),.dma_rows_o(an),.dma_src_stride_o(ass),.dma_dst_stride_o(ads),.dma_rsp_valid_i(asv),.dma_rsp_ready_o(asr),.dma_rsp_error_i(1'b0),.l2_rd_valid_o(rv),.l2_rd_ready_i(rr),.l2_rd_addr_o(ra),.l2_rsp_valid_i(rsv),.l2_rsp_ready_o(rsr),.l2_rsp_data_i(rd),.l2_wr_valid_o(wv),.l2_wr_ready_i(wr),.l2_wr_addr_o(wa),.l2_wr_data_o(wd),.l2_wr_be_o(be),.done_o(done),.status_o(status),.operation_index_o(op),.completions_o(completions),.matrix_steps_o(msteps),.rope_steps_o(rsteps),.values_o(values),.ddr_read_bytes_o(dr),.ddr_write_bytes_o(dw));
 assign dqr=!dpending&&(lfsr[0]||lfsr[5]);assign dsv=dpending;assign dsd=dpending_data;assign ar=!apending&&(lfsr[1]||lfsr[7]);assign asv=apending&&delay==0;assign rr=!lpending&&(lfsr[2]||lfsr[8]);assign rsv=lpending;assign rd=lpending_data;assign wr=lfsr[3]||lfsr[9];
 always@(posedge clk or negedge rst_n)if(!rst_n)begin lfsr<=32'h916f00d5;dpending<=0;apending<=0;lpending<=0;fetches<=0;dmas<=0;delay<=0;qload<=0;kload<=0;vload<=0;qstore<=0;kstore<=0;vstore<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(dqv&&dqr)begin dpending<=1;dpending_data<=records[dqi-BASE];fetches<=fetches+1;end if(dsv&&dsr)dpending<=0;if(rv&&rr)begin lpending<=1;lpending_data<=l2[ra];end if(rsv&&rsr)lpending<=0;if(wv&&wr)l2[wa]<=wd;if(av&&ar)begin apending<=1;delay<=lfsr[12+:3];dmas<=dmas+1;case(op)
  0:if(ak==1)for(integer i=0;i<768;i++)l2[i]=hidden[i];else for(integer i=0;i<96;i++)l2[1024+i]=rweight[i];
  1:if(ak==1)begin for(integer k=0;k<1536;k++)l2[6144+k]=qweights[k*48+qload];qload<=qload+1;end else begin for(integer t=0;t<16;t++)qraw[t*48+qstore]=l2[7680+t];qstore<=qstore+1;end
  2:case(ak)1:for(integer i=0;i<768;i++)l2[8192+i]=qraw[i];0:for(integer i=0;i<96;i++)l2[9216+i]=qbias[i];3:for(integer i=0;i<768;i++)qbout[i]=l2[10240+i];endcase
  3:case(ak)1:for(integer i=0;i<768;i++)l2[12288+i]=qbout[i];0:l2[13312]=positions[0];3:for(integer i=0;i<768;i++)qrout[i]=l2[14336+i];endcase
  4:if(ak==1)begin for(integer k=0;k<1536;k++)l2[6144+k]=kweights[k*8+kload];kload<=kload+1;end else begin for(integer t=0;t<16;t++)kraw[t*8+kstore]=l2[7680+t];kstore<=kstore+1;end
  5:case(ak)1:for(integer i=0;i<128;i++)l2[8192+i]=kraw[i];0:for(integer i=0;i<16;i++)l2[9216+i]=kbias[i];3:for(integer i=0;i<128;i++)kbout[i]=l2[10240+i];endcase
  6:case(ak)1:for(integer i=0;i<128;i++)l2[12288+i]=kbout[i];0:l2[13312]=positions[0];3:for(integer i=0;i<128;i++)krout[i]=l2[14336+i];endcase
  7:if(ak==1)begin for(integer k=0;k<1536;k++)l2[6144+k]=vweights[k*8+vload];vload<=vload+1;end else begin for(integer t=0;t<16;t++)vraw[t*8+vstore]=l2[7680+t];vstore<=vstore+1;end
  8:case(ak)1:for(integer i=0;i<128;i++)l2[8192+i]=vraw[i];0:for(integer i=0;i<16;i++)l2[9216+i]=vbias[i];3:for(integer i=0;i<128;i++)vbout[i]=l2[10240+i];endcase default:$fatal(1,"op");endcase end if(apending)begin if(delay!=0)delay<=delay-1;else if(asv&&asr)apending<=0;end end
 task automatic check(input[511:0]a,input[511:0]e,input integer kind,input integer index);if(a!==e)$fatal(1,"kind=%0d index=%0d",kind,index);endtask
 initial begin string rp,rc,pc,bc,oc;start=0;if(!$value$plusargs("RECORDS=%s",rp)||!$value$plusargs("RMS=%s",rc)||!$value$plusargs("PROJ=%s",pc)||!$value$plusargs("BIAS=%s",bc)||!$value$plusargs("ROPE=%s",oc))$fatal(1,"plusargs");$readmemh(rp,records);$readmemh(rc,rmscmd);$readmemh(pc,pcmd);$readmemh(bc,bcmd);$readmemh(oc,ocmd);$readmemh("work/results/qwen2_canonical_tile16_vectors/hidden_token_major.memh",hidden);$readmemh("work/results/qwen2_canonical_tile16_vectors/rms_weight_fp32.memh",rweight);$readmemh("work/results/qwen2_canonical_q_tile16_all/q_weight_ddr_beats.memh",qweights);$readmemh("work/results/qwen2_canonical_q_tile16_all/k_weight_ddr_beats.memh",kweights);$readmemh("work/results/qwen2_canonical_q_tile16_all/v_weight_ddr_beats.memh",vweights);$readmemh("work/results/qwen2_canonical_q_tile16_all/q_bias_fp32.memh",qbias);$readmemh("work/results/qwen2_canonical_q_tile16_all/k_bias_fp32.memh",kbias);$readmemh("work/results/qwen2_canonical_q_tile16_all/v_bias_fp32.memh",vbias);$readmemh("work/results/qwen2_canonical_token01_vectors/positions_0_15.memh",positions);$readmemh("work/results/qwen2_canonical_q_tile16_all/q_expected_token_major.memh",qexp);$readmemh("work/results/qwen2_canonical_q_tile16_all/k_expected_token_major.memh",kexp);$readmemh("work/results/qwen2_canonical_q_tile16_all/v_expected_token_major.memh",vexp);$readmemh("work/results/qwen2_canonical_q_tile16_all/q_biased_token_major.memh",qbexp);$readmemh("work/results/qwen2_canonical_q_tile16_all/k_biased_token_major.memh",kbexp);$readmemh("work/results/qwen2_canonical_q_tile16_all/v_biased_token_major.memh",vbexp);$readmemh("work/results/qwen2_canonical_q_tile16_all/q_rope_token_major.memh",qrexp);$readmemh("work/results/qwen2_canonical_q_tile16_all/k_rope_token_major.memh",krexp);repeat(8)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(status||op!=8||completions!=9||fetches!=62||dmas!=145||msteps!=98304||rsteps!=1920||values!=118784||dr!=6477952||dw!=188416)$fatal(1,"aggregate status=%0d op=%0d comp=%0d fetch=%0d dma=%0d steps=%0d/%0d values=%0d bytes=%0d/%0d",status,op,completions,fetches,dmas,msteps,rsteps,values,dr,dw);for(integer i=0;i<768;i++)begin check(qraw[i],qexp[i],0,i);check(qbout[i],qbexp[i],3,i);check(qrout[i],qrexp[i],6,i);end for(integer i=0;i<128;i++)begin check(kraw[i],kexp[i],1,i);check(vraw[i],vexp[i],2,i);check(kbout[i],kbexp[i],4,i);check(vbout[i],vbexp[i],5,i);check(krout[i],krexp[i],7,i);end $display("QWEN2_FIRST9_TILE16_CONTROLLER_PASS commands=9 rows=16 positions=0_15 descriptor_fetches=62 dma_requests=145 completions=9 rms_values=24576 qkv_values=32768 bias_values=32768 rope_values=28672 bf16_bit_exact=118784 matrix_steps=98304 effective_macs=50331648 rope_steps=1920 no_intermediate_injection=1 random_backpressure=1");$finish;end
 initial begin repeat(1800000)@(posedge clk);$fatal(1,"timeout op=%0d",op);end
endmodule
