`timescale 1ns/1ps
module tb_qwen2_kv_append_repeated_payload_vcs;
 import hetero_idma_512_pkg::*;localparam integer RECORDS=6188,BASE=4096;logic clk=0,rst_n=0,start;always #0.5 clk=~clk;logic[127:0]commands[0:0],records[0:RECORDS-1];logic qv,qr,sv,sr,pv,pr,pl,pvalid,iv,ir,ior,iordy,ioe,done;logic[23:0]qi;logic[127:0]sd;logic[9:0]pi;logic[31:0]pp,pg,pc,pu,reqs;logic[63:0]is,id,bytes,ta,da;logic[31:0]il;logic[7:0]status,ibusy;axi_req_t read_req,write_req,joined_req;axi_rsp_t read_rsp,write_rsp,joined_rsp;logic[31:0]lfsr;logic dpending;logic[127:0]dpending_data;integer fetches,ptes,idmas,rbeats,wbeats,model_source;logic[511:0]kbeats[0:8191],vbeats[0:8191];
 qwen2_kv_append_ddr_stage_top stage(.clk_i(clk),.rst_ni(rst_n),.start_i(start),.command_i(commands[0]),.descriptor_req_valid_o(qv),.descriptor_req_ready_i(qr),.descriptor_req_index_o(qi),.descriptor_rsp_valid_i(sv),.descriptor_rsp_ready_o(sr),.descriptor_rsp_data_i(sd),.descriptor_rsp_error_i(1'b0),.pte_valid_o(pv),.pte_ready_i(pr),.pte_level_o(pl),.pte_index_o(pi),.pte_physical_page_o(pp),.pte_generation_o(pg),.pte_refcount_o(pc),.pte_entry_valid_o(pvalid),.idma_req_valid_o(iv),.idma_req_ready_i(ir),.idma_src_addr_o(is),.idma_dst_addr_o(id),.idma_length_o(il),.idma_rsp_valid_i(ior),.idma_rsp_ready_o(iordy),.idma_rsp_error_i(ioe),.done_o(done),.status_o(status),.pte_updates_o(pu),.idma_requests_o(reqs),.payload_bytes_o(bytes),.table_address_o(ta),.data_address_o(da));
 idma_backend_rw_axi_flat_wrap idma(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(iv),.req_ready_o(ir),.src_addr_i(is),.dst_addr_i(id),.length_i(il),.rsp_valid_o(ior),.rsp_ready_i(iordy),.rsp_error_o(ioe),.axi_read_req_o(read_req),.axi_read_rsp_i(read_rsp),.axi_write_req_o(write_req),.axi_write_rsp_i(write_rsp),.busy_o(ibusy));axi_rw_join#(.axi_req_t(axi_req_t),.axi_resp_t(axi_rsp_t))i_join(.clk_i(clk),.rst_ni(rst_n),.slv_read_req_i(read_req),.slv_read_resp_o(read_rsp),.slv_write_req_i(write_req),.slv_write_resp_o(write_rsp),.mst_req_o(joined_req),.mst_resp_i(joined_rsp));axi_sim_mem#(.AddrWidth(64),.DataWidth(512),.IdWidth(4),.UserWidth(1),.axi_req_t(axi_req_t),.axi_rsp_t(axi_rsp_t),.WarnUninitialized(1'b0),.ClearErrOnAccess(1'b1),.ApplDelay(0ns),.AcqDelay(0ns))mem(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(joined_req),.axi_rsp_o(joined_rsp),.mon_r_last_o(),.mon_r_beat_count_o(),.mon_r_user_o(),.mon_r_id_o(),.mon_r_data_o(),.mon_r_addr_o(),.mon_r_valid_o(),.mon_w_last_o(),.mon_w_beat_count_o(),.mon_w_user_o(),.mon_w_id_o(),.mon_w_data_o(),.mon_w_addr_o(),.mon_w_valid_o());
 assign qr=!dpending&&(lfsr[0]||lfsr[4]);assign sv=dpending;assign sd=dpending_data;assign pr=lfsr[1]||lfsr[6];always_ff@(posedge clk or negedge rst_n)if(!rst_n)begin lfsr<=32'h4b561024;dpending<=0;fetches<=0;ptes<=0;idmas<=0;rbeats<=0;wbeats<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(qv&&qr)begin dpending<=1;dpending_data<=records[qi-BASE];fetches<=fetches+1;end if(sv&&sr)dpending<=0;if(pv&&pr)ptes<=ptes+1;if(iv&&ir)idmas<=idmas+1;if(joined_rsp.r_valid&&joined_req.r_ready)rbeats<=rbeats+1;if(joined_req.w_valid&&joined_rsp.w_ready)wbeats<=wbeats+1;end
 task automatic put(input[63:0]addr,input[511:0]beat);for(integer b=0;b<64;b++)mem.mem[{8'd0,addr}+b]=beat[b*8+:8];endtask task automatic check(input[63:0]addr,input[511:0]beat,input integer kind,input integer index);for(integer b=0;b<64;b++)if(mem.mem[{8'd0,addr}+b]!==beat[b*8+:8])$fatal(1,"kind=%0d beat=%0d byte=%0d",kind,index,b);endtask
 initial begin string cp,rp,kp,vp,source_name;start=0;if(!$value$plusargs("MODEL_SOURCE=%d",model_source))model_source=0;source_name=model_source?"exact_model_backend":"Q2p46_repeated";if(!$value$plusargs("COMMAND=%s",cp)||!$value$plusargs("RECORDS=%s",rp)||!$value$plusargs("K=%s",kp)||!$value$plusargs("V=%s",vp))$fatal(1,"plusargs");$readmemh(cp,commands);$readmemh(rp,records);$readmemh(kp,kbeats);$readmemh(vp,vbeats);for(integer i=0;i<8192;i++)begin put(64'h201000000+i*64,kbeats[i]);put(64'h201100000+i*64,vbeats[i]);end repeat(8)@(posedge clk);rst_n=1;@(negedge clk);start=1;@(posedge clk);@(negedge clk);start=0;wait(done);if(status||fetches!=13||ptes!=65||idmas!=128||pu!=65||reqs!=128||bytes!=1048576||rbeats!=16384||wbeats!=16384||ibusy!=0)$fatal(1,"aggregate");for(integer p=0;p<64;p++)for(integer b=0;b<128;b++)begin check(64'h500008000+p*16384+b*64,kbeats[p*128+b],0,p*128+b);check(64'h500008000+p*16384+8192+b*64,vbeats[p*128+b],1,p*128+b);end $display("QWEN2_KV_APPEND_PAYLOAD_PASS command=1 tokens=1024 pages=64 descriptor_fetches=13 pte_updates=65 idma_requests=128 axi_beats=16384 payload_bytes=1048576 byte_exact=1048576 source=%s repeated_payload=%0d",source_name,!model_source);$finish;end
 initial begin repeat(200000)@(posedge clk);$fatal(1,"timeout");end
endmodule
