`timescale 1ns/1ps
module tb_qwen2_raw_qkv_chain;
 import hetero_idma_512_pkg::*;localparam integer AW=15,DBEATS=1547;logic clk=0,rst_n=0;always #0.5 clk=~clk;logic[3:0]stage;logic rstart,rfinish,pstart,pfinish,xstart,xfinish;
 logic[127:0]rcommands[0:1],pcommands[0:2],pcommand,xcommands[0:2],xcommand;logic[55:0]raexp[0:5],pa[0:8],xa[0:8];
 logic rdqv,rdqr,rdsv,rdsr,rdse;logic[23:0]rdqi;logic[127:0]rdsd;logic pdqv,pdqr,pdsv,pdsr,pdse;logic[23:0]pdqi;logic[127:0]pdsd;
 logic rav,rar;logic[1:0]rak;logic[63:0]ras,rad;logic[31:0]rarb,rarows,rass,rads;logic rasv,rasr,rase;logic pav,par;logic[1:0]pak;logic[63:0]pas,pad;logic[31:0]parb,parows,pass,pads;logic pasv,pasr,pase;
 logic rrv,rrr,rrsv,rrsr,rwv,rwr;logic[AW-1:0]rra,rwa;logic[511:0]rrd,rwd;logic[63:0]rbe;logic[7:0]rstatus;logic[63:0]rddr;logic[31:0]rl2r,rl2w;
 logic prv,prr,prsv,prsr,pwv,pwr;logic[AW-1:0]pra,pwa;logic[511:0]prd,pwd;logic[63:0]pbe;logic[7:0]pstatus;logic[17:0]pcols;logic[5:0]ptiles;logic[63:0]pddrr,pddrw;logic[31:0]pl2r,pl2w,poverlap;
 logic xdqv,xdqr,xdsv,xdsr,xdse;logic[23:0]xdqi;logic[127:0]xdsd;logic xav,xar;logic[1:0]xak;logic[63:0]xas,xad;logic[31:0]xarb,xarows,xass,xads;logic xasv,xasr,xase;logic xrv,xrr,xrsv,xrsr,xwv,xwr;logic[AW-1:0]xra,xwa;logic[511:0]xrd,xwd;logic[63:0]xbe;logic[7:0]xstatus;logic[17:0]xelements;logic[63:0]xddrr,xddrw;logic[31:0]xl2r,xl2w;
 logic dqv,dqr,dsv,dsr,dse;logic[23:0]dqi;logic[127:0]dsd;logic[511:0]fdata;logic fqv,fqr,frv,frr;logic[AW-1:0]fqa;
 logic av,ar;logic[1:0]ak;logic[63:0]asrc,adst;logic[31:0]arb,arows,ass,ads;logic asv,asr,ase;logic iv,ir,ior,iordy,ioe,local_source;logic[63:0]isrc,idst;logic[31:0]ilen,flat;logic[7:0]ibusy;
 axi_req_t iread,iwrite,local_req,ddr_req;axi_rsp_t iread_rsp,iwrite_rsp,local_rsp,ddr_rsp;logic brv,brr,brsv,brsr,bwv,bwr,bbusy;logic[AW-1:0]bra,bwa;logic[511:0]brd,bwd;logic[63:0]bbe;
 logic trv,trr,trsv,trsr,twv,twr;logic[AW-1:0]tra,twa;logic[511:0]trd,twd;logic[63:0]tbe;logic[1:0]mrv,mrr,mrsv,mrsr;logic[2*AW-1:0]mra;logic[1023:0]mrd;logic mwv,mwr;logic[AW-1:0]mwa;logic[511:0]mwd;logic[63:0]mbe;logic[63:0]cy,lreads,lwrites,conflicts,rstalls,wstalls;
 logic host,hwv;logic[AW-1:0]hwa;logic[511:0]hwd;logic[1:0]owner1;logic[31:0]lfsr;logic[511:0]db[0:DBEATS-1],hidden[0:47],nw[0:95],qw[0:73727],kw[0:12287],vw[0:12287],qe[0:47],ke[0:7],ve[0:7],qb[0:95],kb[0:15],vb[0:15],qbe[0:47],kbe[0:7],vbe[0:7];integer desc,flat_seen,rbeats,wbeats,abstract_stores;logic[63:0]sumread,sumwrite;logic[31:0]suml2r,suml2w;
 qwen2_rms_stage_top #(.ADDR_W(AW))rms(.clk_i(clk),.rst_ni(rst_n),.start_i(rstart),.command_i(rcommands[0]),.descriptor_req_valid_o(rdqv),.descriptor_req_ready_i(rdqr),.descriptor_req_index_o(rdqi),.descriptor_rsp_valid_i(rdsv),.descriptor_rsp_ready_o(rdsr),.descriptor_rsp_data_i(rdsd),.descriptor_rsp_error_i(rdse),.dma_req_valid_o(rav),.dma_req_ready_i(rar),.dma_req_kind_o(rak),.dma_src_addr_o(ras),.dma_dst_addr_o(rad),.dma_row_bytes_o(rarb),.dma_rows_o(rarows),.dma_src_stride_o(rass),.dma_dst_stride_o(rads),.dma_rsp_valid_i(rasv),.dma_rsp_ready_o(rasr),.dma_rsp_error_i(rase),.l2_rd_valid_o(rrv),.l2_rd_ready_i(rrr),.l2_rd_addr_o(rra),.l2_rsp_valid_i(rrsv),.l2_rsp_ready_o(rrsr),.l2_rsp_data_i(rrd),.l2_wr_valid_o(rwv),.l2_wr_ready_i(rwr),.l2_wr_addr_o(rwa),.l2_wr_data_o(rwd),.l2_wr_be_o(rbe),.done_o(rfinish),.status_o(rstatus),.ddr_read_bytes_o(rddr),.l2_read_beats_o(rl2r),.l2_write_beats_o(rl2w));
 qwen2_projection_pingpong_top #(.ADDR_W(AW))proj(.clk_i(clk),.rst_ni(rst_n),.start_i(pstart),.matrix_command_i(pcommand),.descriptor_req_valid_o(pdqv),.descriptor_req_ready_i(pdqr),.descriptor_req_index_o(pdqi),.descriptor_rsp_valid_i(pdsv),.descriptor_rsp_ready_o(pdsr),.descriptor_rsp_data_i(pdsd),.descriptor_rsp_error_i(pdse),.dma_req_valid_o(pav),.dma_req_ready_i(par),.dma_req_kind_o(pak),.dma_src_addr_o(pas),.dma_dst_addr_o(pad),.dma_row_bytes_o(parb),.dma_rows_o(parows),.dma_src_stride_o(pass),.dma_dst_stride_o(pads),.dma_rsp_valid_i(pasv),.dma_rsp_ready_o(pasr),.dma_rsp_error_i(pase),.l2_rd_valid_o(prv),.l2_rd_ready_i(prr),.l2_rd_addr_o(pra),.l2_rsp_valid_i(prsv),.l2_rsp_ready_o(prsr),.l2_rsp_data_i(prd),.l2_wr_valid_o(pwv),.l2_wr_ready_i(pwr),.l2_wr_addr_o(pwa),.l2_wr_data_o(pwd),.l2_wr_be_o(pbe),.done_o(pfinish),.status_o(pstatus),.output_columns_o(pcols),.column_tiles_o(ptiles),.ddr_read_bytes_o(pddrr),.ddr_write_bytes_o(pddrw),.l2_read_beats_o(pl2r),.l2_write_beats_o(pl2w),.overlap_cycles_o(poverlap));
 qwen2_bias_stage_top #(.ADDR_W(AW))bias(.clk_i(clk),.rst_ni(rst_n),.start_i(xstart),.command_i(xcommand),.descriptor_req_valid_o(xdqv),.descriptor_req_ready_i(xdqr),.descriptor_req_index_o(xdqi),.descriptor_rsp_valid_i(xdsv),.descriptor_rsp_ready_o(xdsr),.descriptor_rsp_data_i(xdsd),.descriptor_rsp_error_i(xdse),.dma_req_valid_o(xav),.dma_req_ready_i(xar),.dma_req_kind_o(xak),.dma_src_addr_o(xas),.dma_dst_addr_o(xad),.dma_row_bytes_o(xarb),.dma_rows_o(xarows),.dma_src_stride_o(xass),.dma_dst_stride_o(xads),.dma_rsp_valid_i(xasv),.dma_rsp_ready_o(xasr),.dma_rsp_error_i(xase),.l2_rd_valid_o(xrv),.l2_rd_ready_i(xrr),.l2_rd_addr_o(xra),.l2_rsp_valid_i(xrsv),.l2_rsp_ready_o(xrsr),.l2_rsp_data_i(xrd),.l2_wr_valid_o(xwv),.l2_wr_ready_i(xwr),.l2_wr_addr_o(xwa),.l2_wr_data_o(xwd),.l2_wr_be_o(xbe),.done_o(xfinish),.status_o(xstatus),.elements_o(xelements),.ddr_read_bytes_o(xddrr),.ddr_write_bytes_o(xddrw),.l2_read_beats_o(xl2r),.l2_write_beats_o(xl2w));
 assign dqv=stage==0?rdqv:((stage==2||stage==5||stage==8)?xdqv:pdqv);assign dqi=stage==0?rdqi:((stage==2||stage==5||stage==8)?xdqi:pdqi);assign rdqr=stage==0?dqr:0;assign xdqr=(stage==2||stage==5||stage==8)?dqr:0;assign pdqr=(stage!=0&&stage!=2&&stage!=5&&stage!=8)?dqr:0;assign rdsv=stage==0?dsv:0;assign xdsv=(stage==2||stage==5||stage==8)?dsv:0;assign pdsv=(stage!=0&&stage!=2&&stage!=5&&stage!=8)?dsv:0;assign rdsd=dsd;assign xdsd=dsd;assign pdsd=dsd;assign dsr=stage==0?rdsr:((stage==2||stage==5||stage==8)?xdsr:pdsr);assign rdse=dse;assign xdse=dse;assign pdse=dse;
 assign av=stage==0?rav:((stage==2||stage==5||stage==8)?xav:pav);assign ak=stage==0?rak:((stage==2||stage==5||stage==8)?xak:pak);assign asrc=stage==0?ras:((stage==2||stage==5||stage==8)?xas:pas);assign adst=stage==0?rad:((stage==2||stage==5||stage==8)?xad:pad);assign arb=stage==0?rarb:((stage==2||stage==5||stage==8)?xarb:parb);assign arows=stage==0?rarows:((stage==2||stage==5||stage==8)?xarows:parows);assign ass=stage==0?rass:((stage==2||stage==5||stage==8)?xass:pass);assign ads=stage==0?rads:((stage==2||stage==5||stage==8)?xads:pads);assign rar=stage==0?ar:0;assign xar=(stage==2||stage==5||stage==8)?ar:0;assign par=(stage!=0&&stage!=2&&stage!=5&&stage!=8)?ar:0;assign rasv=stage==0?asv:0;assign xasv=(stage==2||stage==5||stage==8)?asv:0;assign pasv=(stage!=0&&stage!=2&&stage!=5&&stage!=8)?asv:0;assign asr=stage==0?rasr:((stage==2||stage==5||stage==8)?xasr:pasr);assign rase=ase;assign xase=ase;assign pase=ase;
 assign trv=stage==0?rrv:((stage==2||stage==5||stage==8)?xrv:prv);assign tra=stage==0?rra:((stage==2||stage==5||stage==8)?xra:pra);assign rrr=stage==0?trr:0;assign xrr=(stage==2||stage==5||stage==8)?trr:0;assign prr=(stage!=0&&stage!=2&&stage!=5&&stage!=8)?trr:0;assign rrsv=stage==0?trsv:0;assign xrsv=(stage==2||stage==5||stage==8)?trsv:0;assign prsv=(stage!=0&&stage!=2&&stage!=5&&stage!=8)?trsv:0;assign rrd=trd;assign xrd=trd;assign prd=trd;assign trsr=stage==0?rrsr:((stage==2||stage==5||stage==8)?xrsr:prsr);assign twv=stage==0?rwv:((stage==2||stage==5||stage==8)?xwv:pwv);assign twa=stage==0?rwa:((stage==2||stage==5||stage==8)?xwa:pwa);assign twd=stage==0?rwd:((stage==2||stage==5||stage==8)?xwd:pwd);assign tbe=stage==0?rbe:((stage==2||stage==5||stage==8)?xbe:pbe);assign rwr=stage==0?twr:0;assign xwr=(stage==2||stage==5||stage==8)?twr:0;assign pwr=(stage!=0&&stage!=2&&stage!=5&&stage!=8)?twr:0;
 qwen2_tile_idma_expand expand(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(av),.req_ready_o(ar),.req_kind_i(ak),.src_addr_i(asrc),.dst_addr_i(adst),.row_bytes_i(arb),.rows_i(arows),.src_stride_i(ass),.dst_stride_i(ads),.rsp_valid_o(asv),.rsp_ready_i(asr),.rsp_error_o(ase),.idma_req_valid_o(iv),.idma_req_ready_i(ir),.idma_src_addr_o(isrc),.idma_dst_addr_o(idst),.idma_length_o(ilen),.idma_rsp_valid_i(ior),.idma_rsp_ready_o(iordy),.idma_rsp_error_i(ioe),.flat_requests_o(flat),.local_source_o(local_source));
 idma_backend_rw_axi_flat_wrap idma(.clk_i(clk),.rst_ni(rst_n),.req_valid_i(iv),.req_ready_o(ir),.src_addr_i(isrc),.dst_addr_i(idst),.length_i(ilen),.rsp_valid_o(ior),.rsp_ready_i(iordy),.rsp_error_o(ioe),.axi_read_req_o(iread),.axi_read_rsp_i(iread_rsp),.axi_write_req_o(iwrite),.axi_write_rsp_i(iwrite_rsp),.busy_o(ibusy));always_comb begin local_req='0;ddr_req='0;iread_rsp='0;iwrite_rsp='0;if(local_source)begin local_req=iread;ddr_req=iwrite;iread_rsp=local_rsp;iwrite_rsp=ddr_rsp;end else begin ddr_req=iread;local_req=iwrite;iread_rsp=ddr_rsp;iwrite_rsp=local_rsp;end end
 qwen2_axi_shared_l2_bridge #(.ADDR_W(AW))bridge(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(local_req),.axi_rsp_o(local_rsp),.l2_rd_valid_o(brv),.l2_rd_ready_i(brr),.l2_rd_addr_o(bra),.l2_rsp_valid_i(brsv),.l2_rsp_ready_o(brsr),.l2_rsp_data_i(brd),.l2_wr_valid_o(bwv),.l2_wr_ready_i(bwr),.l2_wr_addr_o(bwa),.l2_wr_data_o(bwd),.l2_wr_be_o(bbe),.busy_o(bbusy));
 axi_sim_mem#(.AddrWidth(64),.DataWidth(512),.IdWidth(4),.UserWidth(1),.axi_req_t(axi_req_t),.axi_rsp_t(axi_rsp_t),.WarnUninitialized(1'b0),.ClearErrOnAccess(1'b1),.ApplDelay(0ns),.AcqDelay(0ns))ddr(.clk_i(clk),.rst_ni(rst_n),.axi_req_i(ddr_req),.axi_rsp_o(ddr_rsp),.mon_r_last_o(),.mon_r_beat_count_o(),.mon_r_user_o(),.mon_r_id_o(),.mon_r_data_o(),.mon_r_addr_o(),.mon_r_valid_o(),.mon_w_last_o(),.mon_w_beat_count_o(),.mon_w_user_o(),.mon_w_id_o(),.mon_w_data_o(),.mon_w_addr_o(),.mon_w_valid_o());
 shared_l2_descriptor_port #(.ADDR_W(AW),.SRAM_BYTES(64'd1572864))port(.clk_i(clk),.rst_ni(rst_n),.descriptor_base_i(0),.descriptor_req_valid_i(dqv),.descriptor_req_ready_o(dqr),.descriptor_req_index_i(dqi),.descriptor_rsp_valid_o(dsv),.descriptor_rsp_ready_i(dsr),.descriptor_rsp_data_o(dsd),.descriptor_rsp_error_o(dse),.fabric_req_valid_o(fqv),.fabric_req_ready_i(fqr),.fabric_req_addr_o(fqa),.fabric_rsp_valid_i(frv),.fabric_rsp_ready_o(frr),.fabric_rsp_data_i(fdata),.fabric_rsp_error_i(1'b0));
 shared_l2_fabric #(.ADDR_W(AW),.ROWS_PER_BANK(6144))l2(.clk_i(clk),.rst_ni(rst_n),.rd_valid_i(mrv),.rd_ready_o(mrr),.rd_addr_i(mra),.rd_resp_valid_o(mrsv),.rd_resp_ready_i(mrsr),.rd_data_o(mrd),.wr_valid_i(mwv),.wr_ready_o(mwr),.wr_addr_i(mwa),.wr_data_i(mwd),.wr_be_i(mbe),.cycle_count_o(cy),.read_count_o(lreads),.write_count_o(lwrites),.bank_conflict_count_o(conflicts),.read_stall_count_o(rstalls),.write_stall_count_o(wstalls));
 always_comb begin mrv[0]=trv&&(lfsr[0]||lfsr[4]);mra[0+:AW]=tra;trr=mrr[0]&&(lfsr[0]||lfsr[4]);trsv=mrsv[0]&&(lfsr[1]||lfsr[6]);trd=mrd[0+:512];mrsr[0]=trsr&&(lfsr[1]||lfsr[6]);mrv[1]=fqv||brv;mra[AW+:AW]=fqv?fqa:bra;fqr=mrr[1]&&fqv;brr=mrr[1]&&!fqv&&brv;frv=mrsv[1]&&owner1==0;fdata=mrd[512+:512];brsv=mrsv[1]&&owner1==1;brd=mrd[512+:512];mrsr[1]=owner1==0?frr:brsr;mwv=host?hwv:(bwv?1'b1:(twv&&(lfsr[2]||lfsr[7])));mwa=host?hwa:(bwv?bwa:twa);mwd=host?hwd:(bwv?bwd:twd);mbe=host?'1:(bwv?bbe:tbe);bwr=!host&&bwv&&mwr;twr=!host&&!bwv&&mwr&&(lfsr[2]||lfsr[7]);end
 always_ff@(posedge clk or negedge rst_n)begin if(!rst_n)begin owner1<=0;lfsr<=32'h517ac93d;desc<=0;flat_seen<=0;rbeats<=0;wbeats<=0;abstract_stores<=0;end else begin lfsr<={lfsr[30:0],lfsr[31]^lfsr[21]^lfsr[1]^lfsr[0]};if(mrv[1]&&mrr[1])owner1<=fqv?0:1;if(dqv&&dqr)desc<=desc+1;if(av&&ar&&ak==2)abstract_stores<=abstract_stores+1;if(iv&&ir)flat_seen<=flat_seen+1;if(iread_rsp.r_valid&&iread.r_ready)rbeats<=rbeats+1;if(iwrite.w_valid&&iwrite_rsp.w_ready)wbeats<=wbeats+1;end end
 task automatic hwrite(input[AW-1:0]a,input[511:0]d);begin @(negedge clk);hwa=a;hwd=d;hwv=1;do@(posedge clk);while(!mwr);@(negedge clk);hwv=0;end endtask
 initial begin string bp,rc,ra,pc,pa_path,xc,xa_path,hp,np,qp,kp,vp,qep,kep,vep,qbp,kbp,vbp,qbep,kbep,vbep;stage=0;rstart=0;pstart=0;xstart=0;host=1;hwv=0;hwa=0;hwd=0;sumread=0;sumwrite=0;suml2r=0;suml2w=0;if(!$value$plusargs("BEATS=%s",bp)||!$value$plusargs("RMS_COMMANDS=%s",rc)||!$value$plusargs("RMS_ADDR=%s",ra)||!$value$plusargs("PROJ_COMMANDS=%s",pc)||!$value$plusargs("PROJ_ADDR=%s",pa_path)||!$value$plusargs("BIAS_COMMANDS=%s",xc)||!$value$plusargs("BIAS_ADDR=%s",xa_path)||!$value$plusargs("HIDDEN=%s",hp)||!$value$plusargs("NORM_WEIGHT=%s",np)||!$value$plusargs("Q_WEIGHT=%s",qp)||!$value$plusargs("K_WEIGHT=%s",kp)||!$value$plusargs("V_WEIGHT=%s",vp)||!$value$plusargs("Q_EXPECT=%s",qep)||!$value$plusargs("K_EXPECT=%s",kep)||!$value$plusargs("V_EXPECT=%s",vep)||!$value$plusargs("Q_BIAS=%s",qbp)||!$value$plusargs("K_BIAS=%s",kbp)||!$value$plusargs("V_BIAS=%s",vbp)||!$value$plusargs("Q_BIASED=%s",qbep)||!$value$plusargs("K_BIASED=%s",kbep)||!$value$plusargs("V_BIASED=%s",vbep))$fatal(1,"plusargs");$readmemh(bp,db);$readmemh(rc,rcommands);$readmemh(ra,raexp);$readmemh(pc,pcommands);$readmemh(pa_path,pa);$readmemh(xc,xcommands);$readmemh(xa_path,xa);$readmemh(hp,hidden);$readmemh(np,nw);$readmemh(qp,qw);$readmemh(kp,kw);$readmemh(vp,vw);$readmemh(qep,qe);$readmemh(kep,ke);$readmemh(vep,ve);$readmemh(qbp,qb);$readmemh(kbp,kb);$readmemh(vbp,vb);$readmemh(qbep,qbe);$readmemh(kbep,kbe);$readmemh(vbep,vbe);
  for(integer i=0;i<48;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,raexp[0]}+i*64+b]=hidden[i][b*8+:8];for(integer i=0;i<96;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,raexp[1]}+i*64+b]=nw[i][b*8+:8];for(integer t=0;t<48;t++)for(integer i=0;i<1536;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,pa[1]}+i*3072+t*64+b]=qw[t*1536+i][b*8+:8];for(integer t=0;t<8;t++)for(integer i=0;i<1536;i++)for(integer b=0;b<64;b++)begin ddr.mem[{8'd0,pa[4]}+i*512+t*64+b]=kw[t*1536+i][b*8+:8];ddr.mem[{8'd0,pa[7]}+i*512+t*64+b]=vw[t*1536+i][b*8+:8];end for(integer i=0;i<96;i++)for(integer b=0;b<64;b++)ddr.mem[{8'd0,xa[1]}+i*64+b]=qb[i][b*8+:8];for(integer i=0;i<16;i++)for(integer b=0;b<64;b++)begin ddr.mem[{8'd0,xa[4]}+i*64+b]=kb[i][b*8+:8];ddr.mem[{8'd0,xa[7]}+i*64+b]=vb[i][b*8+:8];end
  repeat(8)@(posedge clk);rst_n=1;for(integer i=0;i<DBEATS;i++)hwrite(1024+i,db[i]);@(negedge clk);host=0;rstart=1;@(posedge clk);@(negedge clk);rstart=0;wait(rfinish);if(rstatus||rddr!=9216||rl2r!=144||rl2w!=48)$fatal(1,"RMS");sumread+=rddr;suml2r+=rl2r;suml2w+=rl2w;
  for(integer p=0;p<3;p++)begin stage=1+p*3;pcommand=pcommands[p];pstart=1;@(posedge clk);@(negedge clk);pstart=0;wait(!pfinish);wait(pfinish);if(pstatus)$fatal(1,"projection %0d",p);sumread+=pddrr;sumwrite+=pddrw;suml2r+=pl2r;suml2w+=pl2w;@(posedge clk);@(negedge clk);stage=2+p*3;xcommand=xcommands[p];xstart=1;@(posedge clk);@(negedge clk);xstart=0;wait(xfinish);if(xstatus)$fatal(1,"bias %0d",p);sumread+=xddrr;sumwrite+=xddrw;suml2r+=xl2r;suml2w+=xl2w;@(posedge clk);@(negedge clk);end
  for(integer t=0;t<48;t++)for(integer b=0;b<64;b++)begin if(ddr.mem[{8'd0,pa[2]}+t*64+b]!==qe[t][b*8+:8])$fatal(1,"Q raw tile=%0d byte=%0d",t,b);if(ddr.mem[{8'd0,xa[2]}+t*64+b]!==qbe[t][b*8+:8])$fatal(1,"Q biased tile=%0d byte=%0d",t,b);end for(integer t=0;t<8;t++)for(integer b=0;b<64;b++)begin if(ddr.mem[{8'd0,pa[5]}+t*64+b]!==ke[t][b*8+:8])$fatal(1,"K raw tile=%0d byte=%0d got=%02h exp=%02h",t,b,ddr.mem[{8'd0,pa[5]}+t*64+b],ke[t][b*8+:8]);if(ddr.mem[{8'd0,pa[8]}+t*64+b]!==ve[t][b*8+:8])$fatal(1,"V raw tile=%0d byte=%0d got=%02h exp=%02h",t,b,ddr.mem[{8'd0,pa[8]}+t*64+b],ve[t][b*8+:8]);if(ddr.mem[{8'd0,xa[5]}+t*64+b]!==kbe[t][b*8+:8])$fatal(1,"K biased tile=%0d byte=%0d",t,b);if(ddr.mem[{8'd0,xa[8]}+t*64+b]!==vbe[t][b*8+:8])$fatal(1,"V biased tile=%0d byte=%0d",t,b);end
  if(desc!=42||flat_seen!=98440||flat!=98440||rbeats!=98768||wbeats!=98768||sumread!=6312960||sumwrite!=8192||suml2r!=98784||suml2w!=176)$fatal(1,"aggregate desc=%0d flat=%0d/%0d beats=%0d/%0d bytes=%0d/%0d l2=%0d/%0d",desc,flat_seen,flat,rbeats,wbeats,sumread,sumwrite,suml2r,suml2w);
  $display("QWEN2_QKV_BIAS_CHAIN_PASS commands=7 descriptor_fetches=42 flat_idma=98440 axi_beats=98768 ddr_read_bytes=6312960 ddr_write_bytes=8192 l2_read_beats=98784 l2_write_beats=176 raw_values=3584 biased_values=2048 bf16_bit_exact=5632 matrix_completions=3 sfu_completions=4 no_reference_injection=1");$finish;end
 initial begin repeat(3000000)@(posedge clk);$fatal(1,"timeout stage=%0d flat=%0d pfinish=%0d pstatus=%0d tile=%0d final=%0d mseen=%0d owner=%0d pstate=%0d/%0d payload=%0d",stage,flat_seen,pfinish,pstatus,proj.tile_q,proj.final_pending_q,proj.mseen_q,proj.owner_q,proj.g_plan[0].plan.state_q,proj.g_plan[1].plan.state_q,proj.payload.state_q);end
endmodule
